- packages/core-api/package.json
- packages/core-api/src/handlers/node/controller.ts
- packages/core-database-postgres/src/queries/index.ts
- packages/core-database-postgres/src/queries/transactions/fee-statistics.sql
- packages/core-database-postgres/src/repositories/transactions.ts
> refactor(core-database-postgres): use sql to calculate fee statistics

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/peer-verifier.ts
- yarn.lock
Increase the number of requests/second to accommodate for larger networks like mainnet.
> fix(core-p2p): increase rate limit to handle bigger networks

- packages/crypto/src/utils/index.ts
Originally they were already cached, but it must have gotten lost when all utility functions were moved into the same file.
Since the mainnet genesis block contains over 1k transactions things become awfully slow:
```
7818    5.5%  Builtin: ObjectAssign
4309   55.1%    LazyCompile: *managers_1.configManager.get.reduce /home/supaiku/git/ark-core/packages/crypto/dist/utils/index.js:54:21
3963   92.0%      LazyCompile: *<anonymous> /home/supaiku/git/ark-core/packages/crypto/dist/validation/keywords.js:60:20
1516   38.3%        LazyCompile: *validate :3:321
397   26.2%          LazyCompile: *validate :3:297
397  100.0%            LazyCompile: *processBlocks.blockList.blocks.map.b /home/supaiku/git/ark-core/packages/core-blockchain/dist/blockchain.js:65:64
395   26.1%          LazyCompile: …
```
> perf(crypto): cache genesis transaction ids

- __tests__/integration/core-api/handlers/blocks.test.ts
- __tests__/integration/core-api/handlers/delegates.test.ts
- __tests__/unit/core-blockchain/mocks/database.ts
- __tests__/unit/core-blockchain/state-machine.test.ts
- __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
- __tests__/unit/core-state/__fixtures__/database-connection-stub.ts
- __tests__/unit/core-state/mocks/database.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/state-machine.ts
- packages/core-database-postgres/src/postgres-connection.ts
- packages/core-database-postgres/src/queries/blocks/delete.sql
- packages/core-database-postgres/src/queries/transactions/delete-by-block.sql
- packages/core-database-postgres/src/repositories/blocks.ts
- packages/core-database-postgres/src/repositories/repository.ts
- packages/core-database-postgres/src/repositories/rounds.ts
- packages/core-database-postgres/src/repositories/transactions.ts
- packages/core-database/src/database-service.ts
- packages/core-interfaces/src/core-database/database-connection.ts
- packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
- packages/core-interfaces/src/core-database/database-repository/repository.ts
- packages/core-interfaces/src/core-database/database-repository/rounds-repository.ts
- packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
- packages/core-interfaces/src/core-database/database-service.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-verifier.ts
`saveBlocks` did not correctly wrap the statements in a `BEGIN ... COMMIT` block and could therefore lead to a database corruption. Same when blocks were deleted (e.g. rollback).
Before:
```
LOG:  statement: INSERT INTO "public"."blocks" (...) VALUES(...)
LOG:  statement: INSERT INTO "public"."transactions" (...) VALUES(...)
LOG:  statement: INSERT INTO "public"."transactions" (...) VALUES(...)
LOG:  statement: INSERT INTO "public"."transactions" (...) VALUES(...)
LOG:  statement: BEGIN
LOG:  statement: COMMIT
```
After:
```
LOG:  statement: BEGIN
LOG:  statement: INSERT INTO "public"."blocks" (...) VALUES(...)
LOG:  statement: INSERT INTO "public"."transactions" (...) VALUES(...)
LOG:  statement: COMMIT
```
I bodged my node to fail during `saveBlocks`. Without this PR the database gets …
> fix(core-database-postgres): possible database corruption when writing and deleting blocks

- packages/core-api/src/defaults.ts
- packages/core-wallet-api/package.json
- packages/core-wallet-api/src/server/index.ts
- yarn.lock
> feat(core-wallet-api): impose the same rate limit as the public API

- packages/core-wallet-api/src/defaults.ts
- packages/core-wallet-api/src/plugin.ts
The port can be customisable but the API should always be on if the plugin is registered.
> refactor(core-wallet-api): always keep the Wallet API enabled

- packages/crypto/src/transactions/builders/index.ts
Export the abstract transaction builder so that a plugin can use it when writing custom transactions.
> chore: export abstract builder for use by plugins

- packages/core-p2p/src/peer-verifier.ts
Prevents that the peer verifier runs into the rate limiter.
> fix(core-p2p): off-by-one error when fetching blocks from peer

- packages/core/src/helpers/snapshot.ts
Resolves https://github.com/ArkEcosystem/core/issues/2732
> fix(core): check for user confirmation in snapshot commands

- packages/core-api/src/defaults.ts
- packages/core-container/src/registrars/plugin.ts
- packages/core-http-utils/src/plugins/whitelist.ts
- packages/core-interfaces/src/core-container/container.ts
- packages/core-utils/package.json
- packages/core-utils/src/index.ts
- packages/core-utils/src/is-whitelisted.ts
- packages/core-wallet-api/package.json
- packages/core-wallet-api/src/plugin.ts
- packages/core-wallet-api/src/server/index.ts
- packages/core/bin/config/devnet/plugins.js
- packages/core/bin/config/mainnet/plugins.js
- packages/core/bin/config/testnet/plugins.js
Check if the whitelist of `core-api` allows access, if not we won't mount the Wallet API.
> refactor(core-wallet-api): respect the whitelist of the public API

- __tests__/integration/core-api/handlers/blockchain.test.ts
- __tests__/integration/core-api/handlers/blocks.test.ts
- __tests__/integration/core-api/handlers/peers.test.ts
- __tests__/integration/core-api/handlers/transactions.test.ts
>  test(core-api): test /transactions/fees and /blockchain endpoints

- __tests__/integration/core-api/handlers/node.test.ts
> test(core-api): /node/configuration/crypto endpoint

- __tests__/integration/core-api/handlers/node.test.ts
- packages/core-database-postgres/src/repositories/transactions.ts
> test(core-api): /node/fees endpoint

- docker/production/README.md
> docs(docker): Updated README

- __tests__/unit/core-utils/is-whitelisted.test.ts
- packages/core-api/src/defaults.ts
- packages/core-container/src/registrars/plugin.ts
- packages/core-utils/src/is-whitelisted.ts
- packages/core/bin/config/devnet/plugins.js
- packages/core/bin/config/mainnet/plugins.js
- packages/core/bin/config/testnet/plugins.js
Grant access if the whitelist is empty as no one is explicitly listed.
> fix(core-utils): grant access if the whitelist is empty

- __tests__/unit/core-blockchain/mocks/transactionPool.ts
- __tests__/unit/core-state/mocks/transactionPool.ts
- __tests__/unit/core-transaction-pool/__stubs__/connection.ts
- __tests__/unit/core-transaction-pool/connection.test.ts
- packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
- packages/core-blockchain/src/processor/handlers/verification-failed-handler.ts
- packages/core-interfaces/src/core-transaction-pool/connection.ts
- packages/core-transaction-pool/src/connection.ts
> fix: do not purge transactions when a block is not accepted

- packages/core-database-postgres/src/postgres-connection.ts
> refactor(core-database-postgres): check error code instead of exiting blindly

- __tests__/integration/core-api/handlers/node.test.ts
- packages/core-api/src/handlers/node/controller.ts
> feat(core-api): return timestamp from /node/status

- __tests__/integration/core-p2p/mocks/core-container.ts
- __tests__/integration/core-transaction-pool/processor.test.ts
- __tests__/unit/core-transaction-pool/__stubs__/connection.ts
- __tests__/unit/core-transaction-pool/connection.test.ts
- packages/core-interfaces/src/core-transaction-pool/connection.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transaction-pool/src/processor.ts
Removes `blockSender` and everything related to it since it is unnecessary.
> refactor(core-transaction-pool): remove blockSender

- __tests__/integration/core-api/utils.ts
- packages/core-api/src/handlers/wallets/transformer.ts
> feat(core-api): add nonce to wallet transformer

- docker/production/README.md
- docker/production/devnet/devnet.env
- docker/production/devnet/docker-compose-build.yml
- docker/production/devnet/docker-compose.yml
- docker/production/mainnet/docker-compose-build.yml
- docker/production/mainnet/docker-compose.yml
- install.sh
> fix: install.sh and docker

- __tests__/unit/core-transaction-pool/connection.forging.test.ts
- packages/core-transaction-pool/src/connection.ts
> fix(core-transaction-pool): try harder to return the requested number of transactions

- __tests__/integration/core-database-postgres/connection.test.ts
- packages/core-database/src/database-service.ts
If the `DatabaseService` fails to deserialize the last block during `init` for whatever reason manual intervention is required. This PR adds a safeguard to help Core recover on it's own.
> refactor(core-database): delete last block if deserialization fails during init

- packages/core-p2p/src/network-monitor.ts
> fix(core-p2p): TypeError: Reduce of empty array with no initial value

- __tests__/unit/crypto/blocks/block.test.ts
- packages/crypto/src/blocks/block.ts
Accept transactions that are up to 3600 + blocktime seconds in the future to prevent unintended block rejection due to discrepancies between system time and slot time.
> fix(crypto): allow future timestamps up to 3600 + blocktime seconds

- install.sh
> revert: let the user choose if they want to use @next release

- packages/core-api/src/server.ts
- packages/core-elasticsearch/src/server.ts
- packages/core-http-utils/package.json
- packages/core-http-utils/src/server/create.ts
- packages/core-webhooks/src/server/index.ts
Under certain circumstances the url can be null and invalid JSON payloads can trigger an exception which clutters the log with a nice stacktrace.
> fix(core-api): handle null url and malformed JSON payloads

- packages/core-exchange-json-rpc/package.json
- yarn.lock
Bumps the exchange RPC as it has a new version constraint.
> chore(deps): bump @arkecosystem/exchange-json-rpc to 1.0.1

- packages/core-container/src/registrars/plugin.ts
- packages/core-http-utils/src/server/create.ts
> fix(core-http-utils): loading of ssl certificate

- packages/core-p2p/src/defaults.ts
Got lost during the merge into master.
> fix(core-p2p): accepted versions

- .circleci/config.yml
- __tests__/e2e/tests/scenarios/scenario1/chained-tx/0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/chained-tx/3.resend-BtoC.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/utils.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/0.0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/1.0.doubletransfer.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/1.1.doubletransfer2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/1.2.doublevote.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/1.3.doubledelreg.action.js
- __tests__/e2e/tests/scenarios/scenario1/doublespend/1.4.double2ndsigreg.action.js
- __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.1.transfer2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/pool-restart/0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/pool-restart/1.create-transactions.action.js
- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/utils.js
- __tests__/e2e/tsconfig.json
- __tests__/functional/transaction-forging/multi-payment.test.ts
- packages/core-transaction-pool/src/connection.ts
> fix: e2e tests 

- packages/core-snapshots/src/transport/index.ts
> fix(core-snapshots): also fix the genesis block id during verify (#2809)

- docker/production/Dockerfile
> build(docker): add ntp and google servers for ntpd

- __tests__/e2e/lib/generate-files.js
- __tests__/e2e/lib/test-runner.js
- __tests__/e2e/lib/utils/test-utils.js
- __tests__/integration/core-blockchain/__support__/setup.ts
- __tests__/integration/core-transaction-pool/processor.test.ts
- __tests__/integration/core-transaction-pool/wallet-manager.test.ts
- packages/core-blockchain/src/processor/handlers/unchained-handler.ts
- packages/core-blockchain/src/utils/validate-generator.ts
- packages/core-container/src/config/index.ts
- packages/core-database-postgres/src/repositories/blocks.ts
- packages/core-database-postgres/src/repositories/repository.ts
- packages/core-database/src/database-service.ts
- packages/core-snapshots/src/db/index.ts
- packages/core-snapshots/src/transport/index.ts
- packages/core-state/src/wallets/wallet-manager.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transaction-pool/src/memory.ts
- packages/core-transactions/src/handlers/transaction.ts
- packages/core-webhooks/src/listener.ts
- packages/crypto/src/managers/config.ts
> style: apply tslint and prettier formatting

- .codacy.yml
Setup a configuration to exclude some files from https://www.codacy.com/ analysis.
> chore: setup codacy configuration

- packages/core-database/src/repositories/delegates-business-repository.ts
> perf(core-database): lookup delegates by key

- packages/core-utils/src/httpie.ts
> fix(core-utils): add content-type header

- packages/core-database-postgres/src/repositories/repository.ts
> fix(core-api): internal server error caused by invalid orderBy field

- __tests__/integration/core-transactions/__support__/setup.ts
- __tests__/integration/core-transactions/handlers/delegate-registration.test.ts
- __tests__/integration/core-transactions/handlers/delegate-resignation.test.ts
- __tests__/integration/core-transactions/handlers/ipfs.test.ts
- __tests__/integration/core-transactions/handlers/multi-payment.test.ts
- __tests__/integration/core-transactions/handlers/multi-signature.test.ts
- __tests__/integration/core-transactions/handlers/second-signature.test.ts
- __tests__/integration/core-transactions/handlers/transfer.test.ts
- __tests__/integration/core-transactions/handlers/vote.test.ts
- packages/core-database-postgres/src/queries/state-builder/assets-by-type.sql
- packages/core-database-postgres/src/state-builder.ts
- packages/core-transactions/src/handlers/multi-signature.ts
- packages/core-transactions/src/handlers/vote.ts
Initial tests for transactions handlers bootstrap method.
+ fixed multisignature bootstrap method (apply to multisig wallet for v2 instead of sender wallet)
+ refactored vote bootstrap method
+ state-builder "assets by type" query to return rows by timestamp ASC (seems better to me in order to then bootstrap starting with the first transactions to the last)
> test(core-transactions): initial tests for transactions handlers bootstrap methods

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/package.json
- packages/core-p2p/src/socket-server/index.ts
- packages/core-p2p/src/socket-server/payload-processor.ts
> perf(core-p2p): improve transactions endpoint

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/network-monitor.ts
> fix(core-p2p): peer discovery limit

- CHANGELOG.md
> release: 2.5.14

- __tests__/integration/core-api/handlers/delegates.test.ts
- packages/core-database/src/repositories/delegates-business-repository.ts
- packages/core-interfaces/src/core-state/wallets.ts
- packages/core-state/src/wallets/wallet-manager.ts
The recent changes to the wallet-manager cause the delegates api endpoints to return non-delegate wallets, e.g. [api/delegates/021d03bace0687a1a5e797f884b13fb46f817ec32de1374a7f223f24404401d220](https://explorer.ark.io/api/delegates/021d03bace0687a1a5e797f884b13fb46f817ec32de1374a7f223f24404401d220)
```
{
"data": {
"address": "AUDud8tvyVZa67p3QY7XPRUTjRGnWQQ9Xv",
"blocks": {
"produced": 0
},
"forged": {
"fees": "0",
"rewards": "0",
"total": "0"
},
"production": {
"approval": 0
},
"publicKey": "021d03bace0687a1a5e797f884b13fb46f817ec32de1374a7f223f24404401d220",
"votes": "0"
}
}
```
> fix(core-state): differentiate between wallets and delegates

- packages/core-p2p/src/socket-server/payload-processor.ts
> fix(core-p2p): delete existing db

- __tests__/integration/core-api/handlers/transactions.test.ts
- packages/core-api/package.json
- packages/core-api/src/handlers/transactions/controller.ts
```
{
"data": {
"Core": {
"Transfer": 0,
"SecondSignature": 1,
"DelegateRegistration": 2,
"Vote": 3,
"MultiSignature": 4,
"Ipfs": 5,
"MultiPayment": 6,
"DelegateResignation": 7,
"HtlcLock": 8,
"HtlcClaim": 9,
"HtlcRefund": 10
}
}
}
```
> refactor(core-api): return all types from the `/transactions/types` endpoint

- __tests__/unit/core-database/database-service.test.ts
- __tests__/unit/core-forger/manager.test.ts
- packages/core-blockchain/src/state-machine.ts
- packages/core-database/src/database-service.ts
- packages/core-event-emitter/src/index.ts
- packages/core-forger/src/client.ts
- packages/core-forger/src/manager.ts
> refactor(core-database): emit missing `transaction.reverted` event and remove obsolete ones

- packages/core-blockchain/src/blockchain.ts
Clear queue on the first invalid block since the queued blocks will get discarded anyway, but doing it early prevents the logs from getting cluttered with nonsense.
> fix(core-blockchain): clear queue on invalid block

- __tests__/integration/core-transaction-pool/processor.test.ts
- __tests__/unit/core-transactions/handler-registry.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-blockchain/src/processor/block-processor.ts
- packages/core-interfaces/src/core-state/wallets.ts
- packages/core-transactions/src/errors.ts
- packages/core-transactions/src/handlers/multi-signature.ts
- packages/core-transactions/src/handlers/transaction.ts
- packages/crypto/src/transactions/types/multi-signature.ts
- packages/crypto/src/transactions/verifier.ts
Fixes sync from 0, by accepting whitelisted legacy multisig transactions again. A previous refactor broke it.
> fix(crypto): legacy multi signature verification

- packages/core-api/src/handlers/transactions/transformer.ts
> fix(core-api): return block timestamp for v2 transactions

- __tests__/helpers/peers.ts
- __tests__/integration/core-p2p/network-monitor.test.ts
- __tests__/unit/core-p2p/mocks/core-container.ts
- __tests__/unit/core-p2p/mocks/event-emitter.ts
- __tests__/unit/core-p2p/socket-server/versions/internal/handlers/utils.test.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-processor.ts
> fix(core-p2p): disconnect if api reports different network

- __tests__/e2e/tests/scenarios/scenario1/config.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/1.create-multisig-registration.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/2.check-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/3.transfer-multisig-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/4.create-lock-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/5.create-claim-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/6.check-multisig.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/config.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/shared.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/utils.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/0.transfer-new-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/1.create-multisig-registration.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/2.check-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/3.transfer-multisig-wallet.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/4.create-lock-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/5.create-refund-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/6.check-multisig.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/config.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/shared.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/utils.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/4.create-valid-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/5.create-invalid-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/6.check-multisig.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/config.js
Add e2e tests for multisignature :
- not enough signatures : only 2 participants signing
- wrong signature : signed with 3 participants but 1 is wrong
- htlc lock / claim workflow with multisignature wallet
- htlc lock / refund workflow with multisignature wallet
> test: add e2e tests for more multisignature cases including htlc

- __tests__/unit/core-utils/mocks/core-container-calculator.ts
- packages/core-utils/src/delegate-calculator.ts
> fix(core-utils): use supply calculator in delegate approval calculation

- packages/core-database-postgres/src/state-builder.ts
- packages/core-transactions/src/handlers/vote.ts
> fix(core-state): `buildVoteBalances` called too early

- packages/core-database-postgres/src/state-builder.ts
- packages/core-transactions/src/handlers/delegate-registration.ts
> fix(core-state): `buildDelegateRanking` called too early

- packages/core-api/src/handlers/node/controller.ts
- packages/core-api/src/handlers/node/routes.ts
- packages/core-api/src/handlers/node/schema.ts
Adds an `/node/debug` endpoint (only on testnets) which can be used to view the current log.
> feat(core-api): add `/node/debug` endpoint

- packages/core-database-postgres/src/migrations/20190905000000-change-set_row_nonce-to-use-max-nonce.sql
> fix(core-database-postgres): use postgresql-9.5 compatible syntax

- __tests__/unit/crypto/transactions/deserializer.test.ts
- __tests__/unit/crypto/transactions/factory.test.ts
- __tests__/unit/crypto/transactions/utils.test.ts
- packages/crypto/src/errors.ts
- packages/crypto/src/transactions/deserializer.ts
- packages/crypto/src/transactions/factory.ts
> refactor(crypto): make error more verbose

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- __tests__/unit/core-p2p/socket-server/worker.test.ts
- packages/core-p2p/src/enums.ts
- packages/core-p2p/src/socket-server/worker.ts
> fix(core-p2p): terminate connection when not authorized

- packages/core-transactions/src/errors.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core-transactions/src/handlers/transaction.ts
Also mention the sender public key in the unexpected nonce error
message.
> chore(core-transactions): elaborate the unexpected nonce error

- .circleci/config.yml
- .github/workflows/benchmark.yml
- .github/workflows/test.yml
Create workflow files for unit tests and benchmarking so that they can run through GitHub Actions instead of CircleCI.
> ci: setup github action workflows for testing and benchmarking

- .github/workflows/functional.yml
- .github/workflows/test.yml
Functional tests simulate real world behaviours which are coupled to block times so they almost 50 minutes to finish for all types. This PR splits that job into 1 job per type to reduce the overall time spent on jobs running by having them run in parallel.
> ci: split functional job into 1 job per type

- __tests__/unit/core-container/__stubs__/config/milestones.json
- __tests__/unit/crypto/transactions/schemas.test.ts
- packages/crypto/src/networks/devnet/milestones.json
- packages/crypto/src/networks/mainnet/milestones.json
- packages/crypto/src/networks/testnet/milestones.json
- packages/crypto/src/networks/unitnet/milestones.json
- packages/crypto/src/transactions/types/schemas.ts
- packages/crypto/src/validation/keywords.ts
Allows changing the maximum recipients of a multipayment via milestone.
> refactor(crypto): change maximum recipients of multipayment via milestone

- __tests__/e2e/README.md
> test(e2e): No need to run as root the chmod command when modifying own's files

- .github/workflows/functional.yml
- .github/workflows/test.yml
> ci: temporarily disable pull_request.synchronize event

- __tests__/e2e/lib/config/nginx/docker-compose.yml
- __tests__/e2e/lib/config/nginx/nginx.conf
- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/2.check-lock.test.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/4.check-claim.test.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-refund/2.check-lock.test.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-refund/4.check-refund.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/2.check-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/4.create-lock-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/5.create-claim-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/6.check-multisig.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/2.check-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/4.create-lock-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/5.create-refund-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/6.check-multisig.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/2.check-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/4.create-valid-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/5.create-invalid-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisignature/6.check-multisig.test.js
- docker/production/devnet/docker-compose-build.yml
- docker/production/devnet/docker-compose.yml
- docker/production/mainnet/docker-compose-build.yml
- docker/production/mainnet/docker-compose.yml
- docker/production/purge_all.sh
- packages/core-database-postgres/src/queries/transactions/fee-statistics.sql
- packages/crypto/rollup.config.js
- scripts/docker/templates/testnet/purge_all.sh
sed -E -I '' 's/[[:space:]]+$//' `git grep -Il '[[:space:]]$'`
> chore: remove trailing whitespace

- packages/core-snapshots/src/db/index.ts
- packages/core-snapshots/src/db/queries/transactions/timestamp-range.sql
> fix(core-snapshots): export/import transactions' type_group

- packages/core-new-relic/package.json
- yarn.lock
The node.js package from new relic now supports node 12/13.
> chore(new-relic): update dependencies to support node.js 12

- packages/core-transaction-pool/src/wallet-manager.ts
- packages/core-transactions/src/handlers/delegate-resignation.ts
- yarn.lock
Ensure it always checks against the database wallet manager.
> fix(core-transactions): delegate resignation

- packages/core-database-postgres/src/migrations/index.ts
> chore(core-database-postgres): load migration file names automatically

- packages/core-exchange-json-rpc/package.json
- yarn.lock
Update the `@arkecosystem/exchange-json-rpc` dependency so that it can use the `next` release of the `@arkecosystem/crypto` package while on devnet. Without this there is the potential for node module resolution issues.
> chore(core-exchange-json-rpc): bump @arkecosystem/exchange-json-rpc to 1.0.6

- packages/crypto/src/networks/devnet/milestones.json
Let the `minimumVersions` milestone kick in a bit earlier on thursday afternoon.
> chore(crypto): updat milestone height

- packages/core-p2p/src/peer-processor.ts
- packages/core-p2p/src/utils/build-rate-limiter.ts
The peer verifier ends up calling `getCommonBlocks` more often than the rate limit allows. This is because the amount of calls depends on the input of the prober - which basically runs `log8(someHeight)` times and it often happens to be more than 5 times. Raising the rate limit from 5 to 9 makes it so that the number of calls are even at height 100M within the rate limit.
This can be observed in the logs:
```
3|ark-relay  | nAray: low 1 - high 3943291
3|ark-relay  | [2019-10-16 01:36:35.145] DEBUG: 54.36.118.0/p2p.peer.getCommonBlocks (timeout 59944ms)
3|ark-relay  | [2019-10-16 01:36:35.183] DEBUG: 54.36.118.0/p2p.peer.getCommonBlocks (timeout 59901ms)
3|ark-relay  | [2019-10-16 01:36:35.264] DEBUG: 54.36.118.0/p2p.peer.getCommonBlocks (timeout 59858ms)
3|ark-relay  | [2019-10-16 …
```
> fix(core-p2p): raise `getCommonBlocks` rate limit

- packages/crypto/src/networks/devnet/milestones.json
> chore(crypto): 2.6 prereleases after milestone

- __tests__/unit/core-state/stores/state.test.ts
- packages/core-state/src/stores/state.ts
> refactor: make block ping log less confusing

- __tests__/unit/core-blockchain/state-machine.test.ts
- packages/core-blockchain/src/state-machine.ts
- packages/core-p2p/src/peer-communicator.ts
> chore: print more details in log messages

- docker/production/Dockerfile
- scripts/docker/templates/devnet/Dockerfile
- scripts/docker/templates/testnet/Dockerfile
> chore: update docker to node.js 12

- packages/core-database-postgres/src/queries/state-builder/assets-by-type.sql
- packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
> feat: expose transaction height, blockId and generatorPublicKey during bootstrap

- packages/core-p2p/src/socket-server/worker.ts
> fix(core-p2p): properly terminate bad connections

- packages/core-magistrate-transactions/package.json
- packages/core-magistrate-transactions/src/wallet-manager.ts
> refactor(core-magistrate): use type from core-interfaces

- __tests__/integration/core-api/handlers/transactions.test.ts
- packages/core-api/src/handlers/transactions/controller.ts
Resolves: https://github.com/ArkEcosystem/core/issues/3104
> fix(core-api): use numerics for typeGroups in /transactions/types

- packages/core-magistrate-transactions/src/events.ts
> fix(core-magistrate-transactions): emit correct event

- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-update.ts
> fix(core-magistrate): get connection from databaseservice

- __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
- __tests__/functional/transaction-forging/bridgechain-update.test.ts
- __tests__/helpers/transaction-factory.ts
- __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
- __tests__/unit/core-magistrate/handlers/business-registration.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/wallet.test.ts
- packages/core-magistrate-crypto/src/builders/bridgechain-resignation.ts
- packages/core-magistrate-crypto/src/interfaces.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/interfaces.ts
- packages/core-magistrate-transactions/src/wallet-manager.ts
Changes the type of `businessId` and `bridgechainId` to `number`. Closes #3113.
> refactor(core-magistrate): business and bridgechain ids as numbers

- packages/core-api/src/handlers/businesses/controller.ts
- packages/core-api/src/handlers/businesses/methods.ts
- packages/core-api/src/handlers/businesses/routes.ts
- packages/core-api/src/handlers/businesses/schema.ts
Implements the `businesses/{id}/bridgechains` endpoint. Closes #3115.
> feat(core-api): implement businesses/bridgechains endpoint

- packages/crypto/src/errors.ts
- packages/crypto/src/transactions/builders/transactions/multi-payment.ts
> refactor(crypto): use multiPaymentLimit from milestone if available

- packages/core-magistrate-transactions/src/errors.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
Closes #3123 and corrects a small styling anomaly.
> refactor(core-magistrate-transactions): BridgechainUpdate errors

- packages/core-p2p/src/socket-server/worker.ts
> fix(core-p2p): uncaught IPC timeout

- packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
> polish(core-magistrate-crypto): remove redundant bridgechain schema properties

- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
> refactor(core-magistrate-crypto): use 4 bytes instead of 8 bytes for bridgechainId

- packages/core-database/src/repositories/wallets-business-repository.ts
> fix(core-database): correctly reduce indexed bridgechain entries

- __tests__/unit/core-blockchain/mocks/blockchain.ts
- __tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
- __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
- __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/processor/block-processor.ts
- packages/core-blockchain/src/processor/handlers/unchained-handler.ts
- packages/core-blockchain/src/state-machine.ts
The `AcceptBlockHandler` already alters `blocksInCurrentRound` while blocks
aren't written to database until the current batch finished processing.
In the case of a fork, we'd stop while blocks have been accepted, but not
written to database yet. This led to inconsistencies and resulted
in an assert being hit which then wrecked the state machine
effectively stopping the node.
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert_1.default(this.blocksInCurrentRound.pop().data.id === block.data.id)
at DatabaseService.revertBlock (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-database/dist/database-service.js:312:25)
at async revertLastBlock (/home/ark/.config/yarn/global/node_modules/@arkecosystem/core-blockchain/dist/blockchain.js:236:13)
at …
```
> fix(core-blockchain): write accepted blocks to database before rolling back

- __tests__/functional/transaction-forging/multi-payment.test.ts
- __tests__/unit/core-container/__stubs__/config/milestones.json
- __tests__/unit/crypto/transactions/deserializer.test.ts
- packages/crypto/src/networks/devnet/milestones.json
- packages/crypto/src/networks/mainnet/milestones.json
- packages/crypto/src/networks/testnet/milestones.json
- packages/crypto/src/networks/unitnet/milestones.json
> refactor(crypto): update multipayment limits

- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
> feat(core-api): add additional fields to businesses search schema

- packages/core-p2p/src/network-monitor.ts
> chore(core-p2p): improve log message

- __tests__/functional/transaction-forging/bridgechain-registration.test.ts
- __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
- __tests__/functional/transaction-forging/bridgechain-update.test.ts
- __tests__/functional/transaction-forging/business-registration.test.ts
- __tests__/functional/transaction-forging/business-resignation.test.ts
- __tests__/functional/transaction-forging/business-update.test.ts
- __tests__/unit/core-magistrate/builders/business-registration.test.ts
- __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
- __tests__/unit/core-magistrate/helper.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate/transactions/business-registration.test.ts
- __tests__/unit/core-magistrate/wallet.test.ts
- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
- packages/core-magistrate-crypto/src/transactions/utils/business-schema.ts
- packages/crypto/src/validation/schemas.ts
This Pull Request changes the following:
- Adds the URI schema
- Refactors `website`, `repository` and `bridgechainRepository` validation to use URI schema
- Updates all unit tests to comply with new URI schema (a lot of tests used 'ark.io' or similar, making the tests fail after this change)
- Adds new unit tests
- Adds new functional tests
Closes #3106 
This PR took a bit longer to make due to being forced of refactoring (and re-testing) all those tests.
> refactor(core-magistrate-crypto): use URI schema for website and repository validation

- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-verifier.ts
> refactor(core-p2p): pluralize logs

- __tests__/integration/core-api/handlers/wallets.test.ts
- __tests__/unit/core-database/__fixtures__/wallets.json
- __tests__/unit/core-state/__fixtures__/wallets.json
- packages/core-api/src/handlers/shared/schemas/wallet-id.ts
- packages/core-api/src/handlers/wallets/schema.ts
This PR adds a schema for the three possible wallet ids formats that are accepted:
- delegate name
- address
- public key
> refactor(core-api): more restrictive wallet id schema

- packages/core-container/package.json
- packages/core-container/src/container.ts
- yarn.lock
The container can now optionally enable [log-process-errors](https://github.com/ehmicky/log-process-errors) for better diagnostics (controlled by `CORE_LOG_PROCESS_ERRORS_ENABLED`).
> feat(core-container): log-process-errors

- packages/core-transactions/src/handlers/delegate-registration.ts
> fix(core-transactions): add `delegate.producedBlocks` attribute

- __tests__/unit/core-database/repositories/utils/filter-rows.test.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-database/src/repositories/utils/filter-rows.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
> feat(core-api): add additional fields to bridgechains search schema

- packages/core-forger/src/client.ts
- packages/core-forger/src/manager.ts
- packages/core-p2p/src/socket-server/worker.ts
> fix(core-p2p): return error when app is not ready

- __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
- __tests__/unit/core-magistrate/handlers/business-handlers.test.ts
- __tests__/unit/core-magistrate/handlers/business-registration.test.ts
- __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
- __tests__/unit/core-state/wallets/wallet-manager-multipayment.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-magistrate-transactions/src/handlers/business-update.ts
- packages/core-transactions/src/handlers/delegate-registration.ts
- packages/core-transactions/src/handlers/delegate-resignation.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core-transactions/src/handlers/ipfs.ts
- packages/core-transactions/src/handlers/multi-payment.ts
- packages/core-transactions/src/handlers/multi-signature.ts
- packages/core-transactions/src/handlers/second-signature.ts
- packages/core-transactions/src/handlers/transaction.ts
- packages/core-transactions/src/handlers/transfer.ts
- packages/core-transactions/src/handlers/vote.ts
- packages/core-transactions/src/interfaces.ts
Renames `databaseWalletManager` to `walletManager` since the former is no longer guaranteed as initially the case.
> refactor(core-transactions): rename handler parameter, check against correct walletManager

- packages/core-transactions/src/handlers/delegate-resignation.ts
> fix(core-transactions): reindex wallet when applying delegate resignation

- __tests__/e2e/README.md
- __tests__/e2e/bin/e2e
- __tests__/e2e/lib/docker.js
- __tests__/e2e/lib/generate.js
- __tests__/e2e/lib/run.js
- simpler to use (3 steps for launching the e2e steps)
- added "launch" cli command to just launch a local network (no tests)
- some more refactor here and there
> test(e2e): update framework

- packages/core-state/src/wallets/wallet-manager.ts
Fixes https://github.com/ArkEcosystem/core/issues/3186
> fix(core-state): remove delegate.rank for resigned delegates

- __tests__/functional/transaction-forging/vote.test.ts
- packages/core-transactions/src/handlers/vote.ts
> fix(core-transactions): allow unvoting a resigned delegate

- .github/workflows/benchmark.yml
- .github/workflows/functional.yml
- .github/workflows/test.yml
https://github.blog/changelog/2019-11-04-github-actions-adds-dependency-caching/
> ci: add dependency caching

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-interfaces/src/core-p2p/peer-connector.ts
- packages/core-p2p/src/constants.ts
- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/schemas.ts
- packages/core-p2p/src/socket-server/index.ts
- packages/core-p2p/src/socket-server/versions/internal.ts
- packages/core-p2p/src/socket-server/worker.ts
- Handle unwanted control frames
- Stricter WS/SC events/messages handling
- Prepare for upcoming 2.6 release
> fix(core-p2p): stricter WS/SC events/messages handling

- __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
- __tests__/functional/transaction-forging/ipfs.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-interfaces/src/core-state/wallets.ts
- packages/core-state/src/wallets/wallet-manager.ts
- packages/core-transactions/src/errors.ts
- packages/core-transactions/src/handlers/ipfs.ts
> refactor(core-transactions): unique ipfs hashes

- __tests__/integration/core-api/utils.ts
- __tests__/unit/core-utils/lock-expiration-calculator.test.ts
- packages/core-api/src/handlers/locks/transformer.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core-utils/src/index.ts
- packages/core-utils/src/lock-expiration-calculator.ts
> feat(core-api): add `isExpired` property to locks response

- package.json
- yarn.lock
https://devblogs.microsoft.com/typescript/announcing-typescript-3-7/
> chore: update to TypeScript 3.7

- __tests__/functional/transaction-forging/bridgechain-registration.test.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
> fix(core-magistrate-transactions): case insensitive bridgechain comparison

- packages/core-api/src/handlers/wallets/methods.ts
> fix(core-api): include query in wallets/{id}/locks cache

- packages/crypto/src/transactions/types/schemas.ts
- packages/crypto/src/validation/schemas.ts
> refactor(crypto): use transactionId ref in lockTransactionId schema definition

- __tests__/functional/transaction-forging/business-registration.test.ts
- packages/crypto/src/validation/schemas.ts
Fixes the `genericName` regex, see https://github.com/ArkEcosystem/core/pull/3229#issuecomment-552685635 for reference.
> fix(crypto): adjust genericName regex and add tests

- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
> fix(core-transactions): do not attempt to convert vendorfield

- install.sh
> chore: handle Debian/Ubuntu derivate NodeJS install

- packages/core-api/src/handlers/bridgechains/methods.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
> fix(core-api): search by genesisHash in show method

- __tests__/integration/core-api/handlers/bridgechains.test.ts
- __tests__/integration/core-api/handlers/businesses.test.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-api/src/handlers/delegates/transformer.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
> feat(core-api): allow searching businesses and bridgechains by isResigned

- packages/crypto/src/utils/base58.ts
- packages/crypto/src/utils/index.ts
Caching of exception transactions and genesis block had invalidation bug.
> refactor(crypto): fix genesis and exception transactions cache

- packages/core-transactions/src/handlers/delegate-registration.ts
Two attributes were missing in the delegate registration handler, that were being set in that same handler's bootstrap and applyToSender methods: `forgedRewards` and `forgedFees`. This fixes that.
> fix(core-transactions): add missing delegate attributes to walletAttributes

- packages/core/src/commands/network/generate.ts
Returns the correct file path in the network generate command error.
> fix(core): fix "file path exists" error

- packages/core-api/src/handlers/delegates/schema.ts
- packages/core-api/src/handlers/shared/schemas/index.ts
- packages/core-api/src/handlers/shared/schemas/username.ts
- packages/core-api/src/handlers/shared/schemas/wallet-id.ts
- packages/core-api/src/handlers/wallets/schema.ts
Fixes #3343 by adding a shared username schema. Also refactors the wallet id schema to use the shared address, username and public key schemata.
> refactor(core-api): add shared username schema

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/src/socket-server/worker.ts
Handle socketcluster disconnect packets.
> fix(core-p2p): handle disconnect packets

- __tests__/integration/core-api/handlers/businesses.test.ts
- packages/core-api/src/handlers/businesses/methods.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
> feat(core-api): retrieve business by username, address or public key

- packages/crypto/src/transactions/deserializer.ts
- packages/crypto/src/transactions/serializer.ts
- packages/crypto/src/utils/index.ts
Change `isSupportedTansactionVersion` to `isSupportedTransactionVersion`
> chore(crypto): fix typo in `isSupportedTansactionVersion` method name

- packages/core-p2p/src/peer-communicator.ts
Define default timeouts for peer socket messages, and use them when no specific timeout is asked.
> refactor(core-p2p): timeouts for peer socket messages

- packages/core-p2p/src/defaults.ts
- packages/crypto/src/networks/mainnet/milestones.json
> chore: update aip11 milestone + update p2p minver defaults

- packages/core-exchange-json-rpc/package.json
- yarn.lock
This PR will fail until tomorrow when the RPC is tagged.
> chore(exchange-json-rpc): use @arkecosystem/exchange-json-rpc@2.0.0

- wallaby.js
[Wallaby.js] configuration. Only couple of tests that are known to be working are whitelisted. Screenshot below illustrates coverage, green lines covered, white lines not covered. It's updated immediately as tests are written.
It's will help with #3482.
[wallaby.js]: https://wallabyjs.com/
> chore: setup Wallaby.js configuration

- __tests__/functional/transaction-forging/bridgechain-registration.test.ts
- __tests__/functional/transaction-forging/business-resignation.test.ts
- __tests__/unit/core-magistrate/handlers/business-resignation.test.ts
- packages/core-magistrate-transactions/src/errors.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
> refactor(magistrate): allow to resign business only when bridgechains are resigned

- packages/core-transaction-pool/src/defaults.ts
> refactor(core-transaction-pool): no default addonBytes for magistrate transactions

- __tests__/functional/multipayment-applyToRecipient/__support__/index.ts
- __tests__/functional/multipayment-applyToRecipient/multipayment.test.ts
- __tests__/integration/core-transaction-pool/processor.test.ts
- packages/core-transaction-pool/src/connection.ts
> fix(core-transaction-pool): always call applyToRecipient

- packages/core-blockchain/package.json
- yarn.lock
> chore(deps): update xstate to v4.8.0

- .gitignore
Remove app.js from .gitignore as we now have app.js files that must be checked in source control.
> chore: remove app.js from .gitignore

- .github/workflows/test.yml
Environment variables were not correctly set up for github test workflow.
> test: fix github environment variable setup

- .github/workflows/benchmark.yml
- .github/workflows/functional.yml
- .github/workflows/test.yml
> ci: use v2 for github actions checkout

- __tests__/unit/core-magistrate/handlers/business-resignation.test.ts
- packages/core-magistrate-transactions/src/errors.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
> chore(core-magistrate-transactions): fix bride -> bridge typo

- .github/sync-script/sync-script.sh
- .github/workflows/devnet-sync.yml
Set up nightly devnet sync with github actions.
> ci: set up nightly devnet sync on github

- packages/core-test-framework/src/utils/mapper.ts
- packages/core-test-framework/src/utils/transaction-factory.ts
What changes are being made?
- Changed import scope to arkecosystem
- Made some properties protected
Why are these changes necessary?
- Import scope: changed it because it throws an error
- Made some protected properties so they can be extended when creating new custom-transactions
> fix(core-tester-framework): import scope

- packages/core-api/src/index.ts
- packages/core-cli/src/index.ts
- packages/core-database/src/index.ts
- packages/core-kernel/src/bootstrap/index.ts
- packages/core-kernel/src/contracts/index.ts
- packages/core-kernel/src/exceptions/index.ts
- packages/core-kernel/src/index.ts
- packages/core-kernel/src/ioc/index.ts
- packages/core-kernel/src/services/index.ts
- packages/core-kernel/src/utils/index.ts
- packages/core-magistrate-crypto/src/index.ts
- packages/core-magistrate-transactions/src/index.ts
- packages/core-state/src/index.ts
- packages/core-test-framework/src/factories/index.ts
- packages/core-test-framework/src/index.ts
- packages/core-test-framework/src/mocks/index.ts
- packages/core-test-framework/src/utils/index.ts
- packages/core-transactions/src/handlers/index.ts
- packages/core-transactions/src/index.ts
- packages/crypto/src/crypto/index.ts
- packages/crypto/src/index.ts
- packages/crypto/src/transactions/types/index.ts
Resolves https://github.com/ArkEcosystem/core/issues/3616
> refactor: use `export * as ns` syntax

- tsconfig.json
Resolves https://github.com/ArkEcosystem/core/issues/3618
> chore: enable assumeChangesOnlyAffectDirectDependencies for TypeScript

- __tests__/e2e/lib/config/docker-compose.yml
- __tests__/unit/core-database/database-service.test.ts
- packages/core-database/src/database-service.ts
- packages/core-kernel/src/bootstrap/app/register-base-bindings.ts
- packages/core-p2p/src/defaults.ts
Get app version from package.json.
Also fixed issue in core-database where detectMissedBlocks was called twice.
> fix(core-kernel): get app version from package.json

- __tests__/unit/core-manager/server/server-boot-dispose.test.ts
- __tests__/unit/core-manager/server/server.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/defaults.ts
- packages/core-manager/src/server/plugins/plugin-factory.ts
- packages/core-manager/src/server/validators/index.ts
- packages/core-manager/src/server/validators/token.ts
- packages/core-manager/src/service-provider.ts
- yarn.lock
This PR implements token authentication. Token can be set in defaults file and is checked on every request, if plugin is enabled. 
External plugin used:
- [hapi-auth-bearer-token](https://github.com/johnbrett/hapi-auth-bearer-token)
> feat(core-manager) implement token authentication

- packages/core-p2p/src/socket-server/worker.ts
For `p2p.peer.postBlock` do a custom validation on the worker as validating with AJV and Buffer keyword is not strict enough.
> refactor(core-p2p): custom validation for postBlock in worker

- __tests__/unit/core-manager/actions/info-blockchain-height.test.ts
- __tests__/unit/core-manager/utils/__mocks__/axios.ts
- __tests__/unit/core-manager/utils/http-client.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/action-reader.ts
- packages/core-manager/src/actions/info-blockchain-height.ts
- packages/core-manager/src/actions/info-core-status.ts
- packages/core-manager/src/actions/info-core-version.ts
- packages/core-manager/src/actions/support-argon2id.ts
- packages/core-manager/src/contracts/action.ts
- packages/core-manager/src/contracts/authentication.ts
- packages/core-manager/src/contracts/http-client.ts
- packages/core-manager/src/contracts/index.ts
- packages/core-manager/src/contracts/plugins.ts
- packages/core-manager/src/defaults.ts
- packages/core-manager/src/ioc/index.ts
- packages/core-manager/src/server/plugins/index.ts
- packages/core-manager/src/server/plugins/plugin-factory.ts
- packages/core-manager/src/server/plugins/rpc-response-handler.ts
- packages/core-manager/src/server/server.ts
- packages/core-manager/src/server/validators/argon2id.ts
- packages/core-manager/src/server/validators/index.ts
- packages/core-manager/src/server/validators/token.ts
- packages/core-manager/src/service-provider.ts
- packages/core-manager/src/utils/api-connection.ts
- packages/core-manager/src/utils/http-client.ts
- packages/core-manager/src/utils/index.ts
- yarn.lock
This PR add new action for getting current height and height of the random node.
---
**Name:** info.blockchainHeight
**Response:**
|-|-|-|
|height|Number|Current height.|
|randomNodeHeight|Number|(Optional) Height of the random node. Returned only on successful response from node. |
|randomNodeIp|String|(Optional) IP of the random node. Returned only on successful response from node. |
> feat(core-manager): implement `info.blockchainHeight` action 

- __tests__/unit/core-manager/actions/info-disk-space.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/info-disk-space.ts
- yarn.lock
This PR add new action for getting disk space related information. It uses [@sindresorhus/df](https://www.npmjs.com/package/@sindresorhus/df) package to get disk info from the system. 
---
**Name:** info.diskSpace
**Params:**
|-|-|-|
|showAllDisks|Boolean|Show information for all available disks.|
**Response:** Array or disk info objects.
|-|-|-|
|filesystem|String|Name of the filesystem|
|size|Number|Size of disk in kilobytes.|
|used|Number|Used space in kilobytes.|
|available|Number|Available space in kilobytes.|
|capacity|Number|Usage ratio in percents.|
|mountpoint|String|Mountpoint.|
> feat(core-manager): implement `info.diskSpace` action

- __tests__/functional/core-database/repositories/block-repository.test.ts
- __tests__/functional/core-database/repositories/transaction-repository.test.ts
- __tests__/unit/core-database/block-history-service.test.ts
- __tests__/unit/core-database/transaction-history-service.test.ts
- packages/core-database/src/block-history-service.ts
- packages/core-database/src/repositories/abstract-repository.ts
- packages/core-database/src/transaction-history-service.ts
- packages/core-kernel/src/contracts/search/index.ts
- packages/core-kernel/src/contracts/shared/block-history-service.ts
- packages/core-kernel/src/contracts/shared/transaction-history-service.ts
Count estimation by parsing `EXPLAIN ${query}` output.
> feat(core-database): count estimation

- packages/crypto/package.json
- packages/crypto/src/identities/public-key.ts
Update bcrypto package from 4.2.9 to 5.1.0 version. Version update fixes problem with crashing node workers, when this dependency is included in worker script.
> chore(deps): update bcrypto dependency

- __tests__/unit/core-database/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
> fix(core-database): handle multipayment recipientId during search

- __tests__/unit/core-manager/database-logger.test.ts
- packages/core-database/src/service-provider.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-manager/src/database-logger.ts
- packages/core-manager/src/service-provider.ts
This PR implements DatabaseLogger, which is TypeOrm logger with ability to save all logs to watcher DatabaseService.
> feat(core-manager): implements DatabaseLogger

- packages/core-kernel/package.json
- packages/core-kernel/src/services/config/watcher.ts
- yarn.lock
> chore: update nsfw 2.0.0 to support node.js 14

- __tests__/unit/core-kernel/services/queue/drivers/memory.test.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-kernel/src/services/queue/drivers/memory.ts
This PR adds functionality into queue memory driver, that will emit driver name and execution time on every successful or failed job.
> feat(core-kernel): dispatch queue events

- packages/core-api/src/server.ts
Currently API is missing error logging. Unhandled exceptions raise 503 without logging anything. This simple server extensions logs any unexpected error to console.
> fix(core-api): log all unexpected errors

- __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
- packages/core-p2p/src/socket-server/controllers/peer.ts
> fix(core-p2p): return last common block

- __tests__/functional/transaction-forging/entity-register.test.ts
- __tests__/functional/transaction-forging/entity-resign.test.ts
- __tests__/functional/transaction-forging/entity-update.test.ts
- __tests__/integration/core-api/handlers/transactions.test.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
- packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
- packages/crypto/src/networks/testnet/milestones.json
Set up aip36 milestone to enable entity transactions.
> feat(core-magistrate): set up aip36 milestone to enable entity transactions

- packages/crypto/src/networks/devnet/milestones.json
> chore(crypto): add aip36 milestone for devnet

- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/1.1.check-business-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/2.1.check-business-update.test.js
- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.1.check-bridgechain-registration.test.js
- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.1.check-bridgechain-update.test.js
- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/5.1.check-bridgechain-resignation.test.js
- __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/6.1.check-business-resignation.test.js
Fix failing e2e tests (due to old magistrate api endpoints removed)
> test(e2e): fix magistrate tests

- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/resign.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
Fix the entity bootstrap methods that were not called at all because of their implementation.
> fix(core-magistrate): fix entity bootstrap methods

- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
Fix the entity register bootstrap method that was buggy and set wallet entity based on transaction data
> fix(core-magistrate): fix entity register bootstrap method

- packages/core-api/src/defaults.ts
> fix(core-api): respect CORE_API_RATE_LIMIT_DISABLED env variable

- packages/core-kernel/src/contracts/transaction-pool/query.ts
- packages/core-transaction-pool/src/query.ts
> fix(core-transaction-pool): union type with number in pool query

- __tests__/integration/core-api/handlers/entities.test.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
Remove duplicates entity resigned/isResigned properties.
> fix(core-database): remove duplicates entity resigned/isResigned

- __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
- packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Allow dynamic fees with `core-magistrate-transactions`. 
This resolves an issue syncing with dev net (otherwise we hit `ERROR: StaticFeeMismatchError` issue at height 4159741).
> fix(core-magistrate-transactions): allow dynamic fees

- __tests__/functional/transaction-forging/entity-register.test.ts
- __tests__/unit/core-magistrate/handlers/entity.test.ts
- packages/core-magistrate-crypto/src/enums.ts
- packages/core-magistrate-crypto/src/transactions/entity.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/errors.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/index.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/register.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/resign.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/update.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
Implement aip36 delegate entity.
> feat(core-magistrate): aip36 delegate entity

- __tests__/functional/pool/pool.test.ts
- __tests__/unit/core-p2p/network-monitor.test.ts
- __tests__/unit/crypto/blocks/block.test.ts
- __tests__/unit/crypto/crypto/hash.test.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/utils/build-rate-limiter.ts
- packages/core-transaction-pool/src/connection.ts
- packages/crypto/src/crypto/hash.ts
> fix: pool, p2p and crypto fixes

- __tests__/unit/core-manager/actions/info-current-delegate.test.ts
- __tests__/unit/core-manager/actions/info-last-forged-block.test.ts
- __tests__/unit/core-manager/actions/info-next-forging-slot.test.ts
- __tests__/unit/core-manager/utils/process.test.ts
- packages/core-manager/src/actions/info-current-delegate.ts
- packages/core-manager/src/actions/info-last-forged-block.ts
- packages/core-manager/src/actions/info-next-forging-slot.ts
- packages/core-manager/src/utils/index.ts
- packages/core-manager/src/utils/process.ts
- packages/core/src/commands/core-run.ts
- packages/core/src/commands/forger-run.ts
Get data from ark-forger if setup is using combination of core-relay and core-forger or from ark-core otherwise.
> chore(core-manager): trigger processes from ark-core or ark-forger

- CHANGELOG.md
- __tests__/functional/transaction-forging/htlc-lock.test.ts
- __tests__/unit/core-blockchain/blockchain.test.ts
- __tests__/unit/core-p2p/network-monitor.test.ts
- __tests__/unit/core-p2p/peer-communicator.test.ts
- __tests__/unit/crypto/blocks/block.test.ts
- __tests__/unit/crypto/crypto/hash.test.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/utils/build-rate-limiter.ts
- packages/core-state/src/block-state.ts
- packages/core-test-framework/src/matchers/functional/unconfirmed.ts
- packages/core-test-framework/src/matchers/functional/vote-balance.ts
- packages/crypto/package.json
- packages/crypto/rollup.config.js
- packages/crypto/src/crypto/hash.ts
- yarn.lock
Merge latest changes from 2.6 (master) to develop.
> merge: 2.6

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/defaults.ts
> chore(core-p2p): add 3.0.0 alpha channel to valid peer versions

- __tests__/unit/core-magistrate-crypto/fixtures/entity/assets/generate.ts
- __tests__/unit/core-magistrate-crypto/transactions/entity.test.ts
> test(core-magistrate-crypto): additional test cases

- packages/core-api/package.json
- packages/core-database-postgres/package.json
- packages/core-database/package.json
- packages/core-jest-matchers/package.json
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/crypto/package.json
- yarn.lock
> fix(core-p2p): peer verifier check claimed state + peer communicator use head from utils

- __tests__/functional/transaction-forging/htlc-lock.test.ts
- packages/core-test-framework/src/utils/api.ts
Fixes #4001
Fix htlc-lock integration tests. Consider increment of delegate vote balance due collected fees, because delegate is voting for himself.
> test(core-transactions): consider delegate collected fees

- CHANGELOG.md
- packages/core-api/package.json
- packages/core-database-postgres/package.json
- packages/core-database/package.json
- packages/core-jest-matchers/package.json
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/crypto/package.json
- yarn.lock
Merge latest changes from master into 2.7.
> merge: master

- packages/core-state/src/wallets/index.ts
> chore(core-state): add indexers export

- __tests__/functional/transaction-forging/entity-register.test.ts
- __tests__/functional/transaction-forging/entity-resign.test.ts
- __tests__/functional/transaction-forging/entity-update.test.ts
- __tests__/integration/core-api/handlers/entities.test.ts
- __tests__/unit/core-magistrate/fixtures/entity/assets/generate.ts
- __tests__/unit/core-magistrate/fixtures/entity/schemas/register.ts
- __tests__/unit/core-magistrate/fixtures/entity/schemas/resign.ts
- __tests__/unit/core-magistrate/fixtures/entity/schemas/update.ts
- packages/core-magistrate-crypto/src/enums.ts
- packages/core-magistrate-transactions/src/errors.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
Bridgechain entity type was deactivated, but it is unnecessary as entities are not yet on mainnet.
Instead, activate all entity types and re-allocate based on our needs.
> chore(magistrate): activate all entity types + re-allocate entity type enum

- __tests__/integration/core-api/handlers/transactions.test.ts
- packages/core-api/src/handlers/node/controller.ts
- packages/core-api/src/handlers/transactions/controller.ts
> chore(core-api): custom entity fees for register/update/resign

- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/core-p2p/src/socket-server/utils/validate.ts
> fix(core-p2p): peer-verifier, peer-connector and tx validation

- CHANGELOG.md
- packages/core-forger/package.json
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/core-p2p/src/socket-server/utils/validate.ts
> merge: master into 2.7

- packages/core-magistrate-api/src/service-provider.ts
Resolves #4043 .
Extend /node/fees and /transactions/fees with entities static fees for register / update / resign.
> chore(magistrate-api): extend /node/fees and /transactions/fees with entities static fees

- packages/crypto/package.json
- yarn.lock
Update [bcrypto](https://www.npmjs.com/package/bcrypto) package.
> deps(crypto): update bcrypto

- packages/crypto/src/networks/mainnet/milestones.json
> chore(crypto): aip36 milestone for mainnet

- __tests__/integration/core-p2p/peer-communicator.test.ts
- packages/core-interfaces/src/core-p2p/peer.ts
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/peer.ts
- packages/core-p2p/src/socket-server/versions/peer.ts
> fix(core-p2p): rate limit and peer broadcast

- packages/core-p2p/src/peer-connector.ts
> fix(core-p2p): destroy connection after terminate

- __tests__/unit/core-api/plugins/comma-array-query.test.ts
- packages/core-api/src/plugins/comma-array-query.ts
- packages/core-api/src/plugins/index.ts
> feat(core-api): transform comma query into array to allow OR

- packages/core-blockchain/src/actions/process-block.ts
- packages/core-forger/src/actions/forge-new-block.ts
- packages/core-forger/src/actions/is-forging-allowed.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
- packages/core-p2p/src/actions/validate-and-accept-peer.ts
- packages/core-p2p/src/index.ts
- packages/core-snapshots/src/contracts/database.ts
- packages/core-snapshots/src/contracts/stream.ts
- packages/core-snapshots/src/workers/actions/test-worker-action.ts
- packages/core-state/src/actions/build-delegate-ranking.ts
- packages/core-state/src/actions/get-active-delegates.ts
- packages/core-test-framework/src/matchers/functional/entity.ts
- packages/core-test-framework/src/mocks/block-repository.ts
- packages/core-test-framework/src/mocks/blockchain.ts
- packages/core-test-framework/src/mocks/network-monitor.ts
- packages/core-test-framework/src/mocks/peer-storage.ts
- packages/core-test-framework/src/mocks/query.ts
- packages/core-test-framework/src/mocks/round-repository.ts
- packages/core-test-framework/src/mocks/state-store.ts
- packages/core-test-framework/src/mocks/transaction-repository.ts
- packages/core-test-framework/src/mocks/wallet-respository.ts
- packages/core-test-framework/src/utils/api.ts
- packages/core-transaction-pool/src/actions/apply-transaction.ts
- packages/core-transaction-pool/src/actions/revert-transaction.ts
- packages/core-transaction-pool/src/actions/throw-if-cannot-enter-pool.ts
- packages/core-transaction-pool/src/actions/verify-transaction.ts
> refactor: remove import from dist or src

- packages/core-cli/src/services/updater.ts
Output `Installing <latest version>` instead of current version.
> syntax(core-cli): latest version instead of current in updater output

- packages/core-state/src/block-state.ts
Update vote balance for each vote in asset﻿
> fix(core-state): update vote balance for each asset vote

- packages/core-p2p/src/peer-connector.ts
Resolves #4092 
Define default timeouts for requests and connection.
> chore(core-p2p): define default p2p timeouts

- __tests__/unit/core-p2p/socket-server/plugins/is-app-ready.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-kernel/src/contracts/blockchain/blockchain.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/socket-server/plugins/is-app-ready.ts
- packages/core-p2p/src/socket-server/server.ts
Do not accept request and respond with error when blockchain is not ready.
> fix(core-p2p): respond with error when blockchain is not ready

- __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
- packages/core-blockchain/src/state-machine/actions/initialize.ts
- packages/core-kernel/src/contracts/state/index.ts
- packages/core-kernel/src/contracts/state/state-builder.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-state/src/service-provider.ts
> fix(core-blockchain): run state builder after database integrity

- install.sh
> chore: update install script for setting env

- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-state/src/database-interactions.ts
- packages/core-state/src/service-provider.ts
> fix(core-blockchain): fork recovery

- packages/core-api/src/defaults.ts
- packages/core-p2p/src/socket-server/versions/peer.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/crypto/src/transactions/builders/transactions/htlc-lock.ts
- packages/crypto/src/transactions/types/schemas.ts
> fix: p2p and schema

- packages/core-p2p/src/socket-server/versions/peer.ts
> fix(core-p2p): strict greater than

- __tests__/unit/core-transaction-pool/processor.test.ts
- packages/core-transaction-pool/src/processor.ts
> fix(core-transaction-pool): do not await tx broadcast in processor

- __tests__/unit/core-kernel/services/triggers/triggers.test.ts
- packages/core-kernel/src/services/triggers/triggers.ts
Fix issue #4112.
Implements **unbind** and **rebind** method on Triggers.
> chore(core-kernel): implement trigger unbind and rebind methods

- packages/core-state/src/defaults.ts
Enable wallet sync (#4038 #4108) through environment variable.
> feat(core-state): enable wallet sync though environment variable

- packages/core-forger/src/client.ts
- packages/core-forger/src/forger-service.ts
> fix(core-forger): log only once when app is not ready

- packages/core-database/src/repositories/abstract-repository.ts
Manually building count query to avoid slow `COUNT(DISTINCT primary_key_column)` built by typeorm. Should help with #4095.
> fix(core-database): count performance

- packages/core-database/src/migrations/20201102000000-add-asset-payments-index-to-transactions-table.ts
Add index: 
CREATE INDEX transactions_asset_payments ON transactions USING GIN ((asset->'payments'));
> chore(core-database): migration: add asset.payments index to transactions

- __tests__/functional/core-database/repositories/round-repository.test.ts
- __tests__/unit/core-database/database-service.test.ts
- __tests__/unit/core-state/database-interactions.test.ts
- packages/core-database/src/database-service.ts
- packages/core-database/src/repositories/round-repository.ts
> fix(core-database): delete all rounds starting from `round`

- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-transaction-pool/src/service.ts
> fix(core-transaction-pool): re-add transactions after state builder finished

- __tests__/unit/core/commands/core-run.test.ts
- __tests__/unit/core/commands/forger-run.test.ts
- __tests__/unit/core/commands/network-generate.test.ts
- __tests__/unit/core/commands/relay-run.test.ts
- packages/core/bin/run
- packages/core/src/commands/core-run.ts
- packages/core/src/commands/forger-run.ts
- packages/core/src/commands/network-generate.ts
- packages/core/src/commands/relay-run.ts
Network:generate
- Save generated files to default location. 
- Ignore prompts when all flags are passed
Don't resolve execute method on :run commands to prevent exiting the process.
> fix(core): network:generate save to default location

- packages/core-database/src/migrations/20201102000000-add-asset-payments-index-to-transactions-table.ts
> chore(core-database): create asset.payments index if not exists

- __tests__/unit/core/commands/network-generate.test.ts
- packages/core/src/commands/network-generate.ts
Add additional flags into network:generate command. 
- dynamic fees
- htlcEnabled
- peer (add peer ports)
> feat(core): set dynamic fees in network:generate

- __tests__/unit/core-p2p/socket-server/plugins/accept-peer.test.ts
- __tests__/unit/core-p2p/socket-server/server.test.ts
- packages/core-p2p/src/socket-server/plugins/accept-peer.ts
- packages/core-p2p/src/socket-server/server.ts
> fix(core-p2p): restore accept peer plugin

- __tests__/unit/core-forger/forger-service.test.ts
- packages/core-forger/src/forger-service.ts
> Resolves https://github.com/ArkEcosystem/core/issues/4156
> chore: remove fork 6 mention

- install-next.sh
> Resolves https://github.com/ArkEcosystem/core/issues/4096
Differences to the `install.sh` file
`yarn global add @arkecosystem/core` => `yarn global add @arkecosystem/core@next`
`ark config:publish` => `ark config:publish --network=devnet`
`ark config:cli` => `ark config:cli --channel=next`
> chore: add `install-next.sh` script for devnet installations

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- __tests__/unit/core-p2p/mocks/request.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-database-postgres/src/migrations/20201117000000-add-generator_public_key_height-index-to-blocks-table.sql
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/core-p2p/src/utils/sc-codec.ts
> fix: fixes on p2p, blockchain and database

- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-kernel/package.json
- packages/core-manager/package.json
- packages/core-state/package.json
- packages/core/package.json
- packages/crypto/package.json
- yarn.lock
> chore: update @arkecosystem/utils version to 1.2.1

- packages/core/src/commands/network-generate.ts
Extracted a single commit so prettier formatting doesn't clutter #4179.
> refactor(core-cli): prettier network-generate formatting

- __tests__/unit/core-cli/services/config.test.ts
- packages/core-cli/src/services/config.ts
Remove deprecated versioning channels.
> chore(core-cli): remove deprecated versioning channels

- __tests__/unit/core-manager/actions/configuration-get-env.test.ts
- __tests__/unit/core-manager/actions/configuration-set-plugins.test.ts
Increase test coverage for configuration.getEnv and configuration.setPlugin.
> test(core-manager): increase test coverage

- __tests__/unit/core-manager/actions/log-search.test.ts
- packages/core-manager/src/actions/log-search.ts
Rename log.log action to log.search.
> refactor(core-manager): rename log.log to log.search

- __tests__/unit/core-manager/actions/info-core-update.test.ts
- packages/core-manager/src/actions/info-core-update.ts
This PR add new action which calls core update command. 
**Name:** info.coreUpdate
**Response:** {}
> feat(core-manager): implement info.coreUpdate action

- __tests__/unit/core-p2p/hapi-nes/client.test.ts
- __tests__/unit/core-p2p/hapi-nes/socket.test.ts
- packages/core-p2p/src/hapi-nes/client.ts
- packages/core-p2p/src/hapi-nes/socket.ts
> chore(core-p2p): terminate on ws.ping() ws.pong()

- __tests__/unit/core-kernel/utils/ip-address.test.ts
- packages/core-kernel/package.json
- packages/core-kernel/src/utils/index.ts
- packages/core-kernel/src/utils/ip-address.ts
Required for issue #4058
Implements IP address utils module required for handling IPv6 addresses.
> feat(core-kernel): ip address utils

- __tests__/unit/core-manager/actions/info-resources.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/info-resources.ts
- yarn.lock
This PR add new action which is used for monitoring system status like CPU, memory and filesystem consumption. Used package for gathering system info is [systeminformation](https://www.npmjs.com/package/systeminformation).
**Name:** info.resources
**Params:**: none
**Response:** 
|-|-|-|
|cpu.total|Number|Total CPU resources (100%).|
|cpu.used|Number|Used CPU resources.|
|cpu.available|Number|Available resources.|
|ram.total|Number|Total memory (KB).|
|ram.used|Number|Used memory (KB).|
|ram.available|Number|Available memory (KB).|
|disk.total|Number|Total space (KB).|
|disk.used|Number|Used space (KB).|
|disk.available|Number|Availble space (KB).|
> feat(core-manager): implements info.resources action

- __tests__/unit/core-manager/database/database.test.ts
- packages/core-manager/src/database/database.ts
- packages/core-manager/src/database/events-database-service.ts
Add support for indexed columns on sqlite database.  Add indexes on EventsDatabaseService.
> feat(core-manager): implement database indexing support

- __tests__/unit/core-manager/database/database.test.ts
- packages/core-manager/src/database/database.ts
Implements sqlite database delete support.
> feat(core-manger): implement database delete support

- __tests__/unit/core-cli/services/process-manager.test.ts
- packages/core-cli/src/services/process-manager.ts
- packages/core-manager/src/actions/info-current-delegate.ts
- packages/core-manager/src/actions/info-last-forged-block.ts
- packages/core-manager/src/actions/info-next-forging-slot.ts
Support async PM2 triggers using execa async mode. Update core-manager actions to call trigger async.
> refactor(core-cli): support async PM2 triggers

- __tests__/unit/core-magistrate-crypto/fixtures/entity/schemas/register.ts
- packages/core-magistrate-crypto/src/transactions/utils/entity-schemas.ts
> chore(crypto): match entity schema name with delegate username

- __tests__/unit/core-magistrate/fixtures/entity/schemas/register.ts
- packages/core-magistrate-crypto/src/transactions/utils/entity-schemas.ts
Same as #4209 but needed on master branch too (2.7).
> refactor(crypto): match entity schema name with delegate username (2.7)

- packages/core/package.json
Run full:testnet with --env=test to skip network reach check.
> fix(core): append --env=test to full:testnet script

- __tests__/unit/core-p2p/peer-communicator.test.ts
- __tests__/unit/core-p2p/socket-server/plugins/validate.test.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/socket-server/codecs/blocks.ts
- packages/core-p2p/src/socket-server/codecs/peer.ts
- packages/core-p2p/src/socket-server/codecs/proto/blocks.proto
- packages/core-p2p/src/socket-server/codecs/proto/peer.proto
- packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
- packages/core-p2p/src/socket-server/codecs/proto/protos.js
- packages/core-p2p/src/socket-server/codecs/proto/shared.proto
- packages/core-p2p/src/socket-server/codecs/proto/transactions.proto
- packages/core-p2p/src/socket-server/codecs/transactions.ts
- packages/core-p2p/src/socket-server/plugins/validate.ts
- packages/core-p2p/src/socket-server/schemas/blocks.ts
- packages/core-p2p/src/socket-server/schemas/peer.ts
- packages/core-p2p/src/socket-server/schemas/shared.ts
- packages/core-p2p/src/socket-server/schemas/transactions.ts
Resolves #3997 
Validate version on all incoming endpoints (except internal).
> chore(core-p2p): validate version on all p2p endpoints

- packages/core/bin/config/testnet/app.json
Remove core-manager plugin from app.json. Package installation it optional.
> chore(core): remove core-manager plugin from app.json

- __tests__/unit/crypto/blocks/block.test.ts
- packages/core-api/src/defaults.ts
- packages/core-p2p/package.json
- packages/core-p2p/src/constants.ts
- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/schemas.ts
- packages/core-p2p/src/socket-server/utils/validate.ts
- packages/core-p2p/src/socket-server/versions/peer.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/crypto/src/crypto/hash.ts
- yarn.lock
> fix: api / p2p / crypto

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/log-download.test.ts
- __tests__/unit/core-manager/database/database.test.ts
- __tests__/unit/core-manager/worker/actions/generate-log.test.ts
- __tests__/unit/core-manager/worker/worker-manager.test.ts
- __tests__/unit/core-manager/worker/worker.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/log-download.ts
- packages/core-manager/src/database/database.ts
- packages/core-manager/src/database/logs-database-service.ts
- packages/core-manager/src/ioc/identifiers.ts
- packages/core-manager/src/service-provider.ts
- packages/core-manager/src/workers/actions/generate-log.ts
- packages/core-manager/src/workers/worker-manager.ts
- packages/core-manager/src/workers/worker.ts
This PR add new action to generate log files from log sqlite database. Log generation is handled inside new Worker process. Running multiple workers is permitted. File is saved to temp location during generation and is moved to CORE_PATH_DATA/log-archive after successful generation. 
**Name:** log.download
**Params:**:
|-|-|-|
|dateFrom|Number|Date from in unix timestamp (s).|
|dateTo|Number|Date to in unix timestamp (s).|
|levels|String[ ]|Filter by log levels.|
|processes|String[ ]|Filter by process names. (Optional) |
**Response:** 
String containing log name.
> feat(core-manager): implements `log.download` action

- packages/core-blockchain/src/blockchain.ts
> chore(core-blockchain): remove :chains: from logs

- packages/core-blockchain/src/process-blocks-job.ts
> fix(core-blockchain): import fix

- packages/core-database-postgres/src/migrations/20201117000000-add-generator_public_key_height-index-to-blocks-table.sql
- packages/core-database/src/migrations/20201117000000-add-generator_public_key_height-index-to-blocks-table.ts
> fix(core-database): move migration to correct location

- packages/core-p2p/src/socket-server/plugins/codec.ts
Explicit check against undefined, as response could be `false` and still valid.
> fix(core-p2p): explicit check against undefined

- __tests__/unit/core-manager/server/server-boot-dispose.test.ts
- packages/core-manager/src/actions/log-download.ts
- packages/core-manager/src/server/server.ts
Await log generation on `log.download` action. 
**Caution!** Action may take several minutes to complete, depending on log size.
> chore(core-manager): await log generation on `log.download`

- __tests__/unit/core-api/service-provider.test.ts
- packages/core-api/package.json
- packages/core-api/src/defaults.ts
- packages/core-api/src/service-provider.ts
- yarn.lock
Implement core-api service provider schema.
Cache plugin is disabled by default.
> chore(core-api): implements service provider schema

- __tests__/unit/core-database/service-provider.test.ts
- packages/core-database/package.json
- packages/core-database/src/service-provider.ts
Implement core-database service provider schema.
> chore(core-database): implements service provider schema

- .github/sync-script/sync-script.sh
- .github/workflows/devnet-sync.yml
Apply changes from PR #4267  to master as it is the master branch setup that is used in github actions nightly devnet sync.
> ci: re-enable devnet sync (master)

- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/defaults.ts
- packages/core-manager/src/service-provider.ts
Implement core-manager service provider schema.
> core(core-manager): implements service provider schema

- __tests__/unit/core-state/service-provider.test.ts
- packages/core-state/package.json
- packages/core-state/src/service-provider.ts
Implement core-state service provider schema.
> chore(core-state): implements service provider schema

- __tests__/unit/core-p2p/service-provider.test.ts
- packages/core-p2p/src/service-provider.ts
Implement core-p2p service provider schema.
> chore(core-p2p): implements service provider schema

- __tests__/unit/core-webhooks/service-provider.test.ts
- packages/core-webhooks/src/defaults.ts
- packages/core-webhooks/src/service-provider.ts
Implement core-webhooks service provider schema.
> chore(core-webhooks): implements service provider schema

- __tests__/unit/core-snapshots/service-provider.test.ts
- packages/core-snapshots/src/service-provider.ts
Implement core-snapshots service provider schema.
> chore(core-snapshots): implements service provider schema

- __tests__/unit/core-logger-pino/service-provider.test.ts
- packages/core-logger-pino/package.json
- packages/core-logger-pino/src/service-provider.ts
Implement core-logger-pino service provider schema.
> chore(core-logger-pino): implements service provider schema

- __tests__/unit/core-api/service-provider.test.ts
- __tests__/unit/core-blockchain/service-provider.test.ts
- __tests__/unit/core-database/service-provider.test.ts
- __tests__/unit/core-forger/service-provider.test.ts
- __tests__/unit/core-logger-pino/service-provider.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- __tests__/unit/core-p2p/service-provider.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core-state/service-provider.test.ts
- __tests__/unit/core-transaction-pool/service-provider.test.ts
- __tests__/unit/core-webhooks/service-provider.test.ts
> test: fix joi imports

- __tests__/unit/core-api/service-provider.test.ts
- packages/core-api/src/service-provider.ts
Improve service provider schema. Add required objects and check negative values. Add restrictions check tests.
> chore(core-api): improve service provider schema

- __tests__/unit/core-magistrate-api/service-provider.test.ts
- packages/core-magistrate-api/src/service-provider.ts
Return entity fees when aip36 is set.
> fix(core-magistrate-api): respect aip36 milestone in handlers

- packages/core-p2p/src/socket-server/codecs/blocks.ts
- packages/core-p2p/src/socket-server/codecs/proto/blocks.proto
- packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
- packages/core-p2p/src/socket-server/codecs/proto/protos.js
Replace repeated fields in getBlocks with custom ser/deser to be able to set a limit on max number of items.
> chore(core-p2p): replace repeated fields in getBlocks with custom ser/deser

- packages/core-p2p/src/hapi-nes/client.ts
> fix(core-p2p): syntax in setMaxPayload

- __tests__/unit/core-api/service-provider.test.ts
- __tests__/unit/core-blockchain/service-provider.test.ts
- __tests__/unit/core-database/service-provider.test.ts
- __tests__/unit/core-forger/service-provider.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- __tests__/unit/core-p2p/service-provider.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core-state/service-provider.test.ts
- __tests__/unit/core-transaction-pool/service-provider.test.ts
- __tests__/unit/core-webhooks/service-provider.test.ts
- packages/core-api/src/service-provider.ts
- packages/core-blockchain/src/service-provider.ts
- packages/core-database/src/service-provider.ts
- packages/core-forger/src/service-provider.ts
- packages/core-manager/src/service-provider.ts
- packages/core-p2p/src/service-provider.ts
- packages/core-snapshots/src/defaults.ts
- packages/core-snapshots/src/service-provider.ts
- packages/core-state/src/service-provider.ts
- packages/core-transaction-pool/src/service-provider.ts
- packages/core-webhooks/src/service-provider.ts
Add integer checks to service provider schemas.
> chore: add integer checks to service provider schemas

- __tests__/unit/core-snapshots/database-service.test.ts
- __tests__/unit/core-snapshots/repositories/block-repository.test.ts
- __tests__/unit/core-snapshots/repositories/round-repository.test.ts
- __tests__/unit/core-snapshots/repositories/transaction-repository.test.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/repositories/abstract-repository.ts
- packages/core-snapshots/src/repositories/block-repository.ts
- packages/core-snapshots/src/repositories/round-repository.ts
- packages/core-snapshots/src/repositories/transaction-repository.ts
Improve `count`,`countInRange` and `trucnate` performance.
> refactor(core-snapshots): improve database query performance

- __tests__/unit/core-snapshots/database-service.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core-snapshots/workers/worker-thread.test.ts
- __tests__/unit/core-snapshots/workers/worker.test.ts
- packages/core-snapshots/src/contracts/worker.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/defaults.ts
- packages/core-snapshots/src/service-provider.ts
- packages/core-snapshots/src/workers/worker.ts
Add support for custom crypo packages in core-snapshots. Custom packages can be added in app.json file.
> feat(core-snapshots): support custom crypto packages

- __tests__/unit/core-snapshots/database-service.test.ts
- __tests__/unit/core-snapshots/filesystem/filesystem.test.ts
- __tests__/unit/core-snapshots/filesystem/stream-reader-writer.test.ts
- __tests__/unit/core-snapshots/workers/actions/worker-action.test.ts
- packages/core-snapshots/src/contracts/repository.ts
- packages/core-snapshots/src/contracts/stream.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/filesystem/filesystem.ts
- packages/core-snapshots/src/filesystem/stream-reader.ts
- packages/core-snapshots/src/filesystem/stream-writer.ts
- packages/core-snapshots/src/repositories/block-repository.ts
- packages/core-snapshots/src/repositories/round-repository.ts
- packages/core-snapshots/src/repositories/transaction-repository.ts
- packages/core-snapshots/src/workers/actions/abstract-worker-action.ts
- packages/core-snapshots/src/workers/worker.ts
- Handle stream errors
- Close streams on worker terminate
- Delete snapshot files on dump error
> fix(core-snapshot): handle stream errors

- packages/core/src/commands/snapshot-dump.ts
Verify codec on snapshot:dump command
> chore(core): verify codec on snapshot:dump command

- __tests__/unit/core/commands/manager-log.test.ts
- __tests__/unit/core/commands/manager-restart.test.ts
- __tests__/unit/core/commands/manager-status.test.ts
- packages/core/src/commands/manager-log.ts
- packages/core/src/commands/manager-restart.ts
- packages/core/src/commands/manager-status.ts
Implement `manager:status`, `manager:log` & `manager:restart` CLI commands.
> feat(core): implement `manager:status`, `manager:log` & `manager:restart` cli commands

- packages/core-manager/src/actions/process-restart.ts
- packages/core-manager/src/actions/snapshots-restore.ts
Set required fields in action schemas.
> chore(core-manager): set required fields in action schemas

- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/process-blocks-job.ts
- packages/core-blockchain/src/processor/handlers/unchained-handler.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/snapshot-service.ts
Use correct pluralization form in logs.
> chore: use correct pluralization form in logs 

- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-kernel/package.json
- packages/core-manager/package.json
- packages/core-state/package.json
- packages/core/package.json
- packages/crypto/package.json
- yarn.lock
Update @arkecosystem/utils to 1.3.0.
> deps: update @arkecosystem/utils to 1.3.0

- __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
- packages/core-api/src/handlers/node/schema.ts
- packages/core-database-postgres/src/queries/index.ts
- packages/core-database-postgres/src/queries/transactions/fee-statistics-by-type.sql
- packages/core-database-postgres/src/repositories/transactions.ts
- packages/core-database/src/repositories/transactions-business-repository.ts
- packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
- packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
When no `days` parameter is provided, return fee statistics for each tx type according to the last 20 txs for this type.
> feat(core-api): improve fee statistics when no `days` parameter is provided

- __tests__/functional/core-database/repositories/transaction-repository.test.ts
- __tests__/unit/core-api/controllers/node.test.ts
- __tests__/unit/core-test-framework/mocks/transaction-repository.test.ts
- packages/core-api/src/controllers/node.ts
- packages/core-api/src/routes/node.ts
- packages/core-database/src/repositories/transaction-repository.ts
- packages/core-test-framework/src/mocks/transaction-repository.ts
See #4328 ; this is the same but based on develop branch.
> feat(core-api): fee stats from last 20 tx when no days param is provided

- __tests__/unit/core-state/stores/state.test.ts
- packages/core-kernel/src/contracts/state/state-store.ts
- packages/core-state/src/stores/state.ts
Remove unused clear method on StateStore
> chore(core-state): remove unused clear method on stateStore

- __tests__/unit/core-forger/service-provider.test.ts
- packages/core-forger/src/service-provider.ts
Register ForgerService on boot.
> chore(core-forger): register ForgerService on boot

- packages/core-blockchain/src/blockchain.ts
PushPingBlock after slot check, to limit the options for unwanted changing of pingBlock.
> chore(core-blockchain): pushPingBlock after slot check

- __tests__/unit/core-p2p/peer-connector.test.ts
- packages/core-p2p/src/peer-connector.ts
Remove connection form connections list on connection error.
> fix(core-p2p): remove connection from list onError

- __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
- __tests__/unit/core-blockchain/state-machine/actions/rollback-database.test.ts
- __tests__/unit/core-state/stores/state.test.ts
- packages/core-blockchain/src/state-machine/actions/initialize.ts
- packages/core-blockchain/src/state-machine/actions/rollback-database.ts
- packages/core-database/src/database-service.ts
- packages/core-kernel/src/contracts/state/state-store.ts
- packages/core-state/src/stores/state.ts
Implement get and set for restoredDatabaseIntegrity.
> reafactor(core-state): implement get and set for restoredDatabaseIntegrity

- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-transaction-pool/src/service.ts
Join duplicated logs on service.
> refactor(core-forger): join duplicated logs

- __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Remove double multiSignature set in MultiSignatureRegistration.
> chore(core-transactions): remove double multiSignature set in MultiSignatureRegistration

- packages/core-kernel/src/enums/events.ts
- packages/core-transactions/src/handlers/two/htlc-refund.ts
> refactor(core-transactions): cleanup htlcRefund

- __tests__/unit/core-transactions/handlers/two/vote.test.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-transactions/src/handlers/one/vote.ts
Support event dispatching for vote transactions with multiple vote/unvote entries.
> fix(core-tranasctions): vote dispatchEvents for all changes

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/devnet-sync.yml
- .github/workflows/functional.yml
- .github/workflows/mainnet-sync.yml
- .github/workflows/publish-master.yml
- .github/workflows/test.yml
- __tests__/e2e/lib/config/nodes/Dockerfile
> ci: devnet/mainnet sync

- __tests__/unit/core-p2p/socket-server/utils/get-peer-config.test.ts
- packages/core-p2p/src/socket-server/utils/get-peer-config.ts
Resolve plugin enabled value from configuration in case enabled value exists.
> chore(core-p2p): resolve plugin enabled value

- packages/core-manager/package.json
- packages/core-manager/src/actions/info-resources.ts
- yarn.lock
Update [systeminformation](https://www.npmjs.com/package/systeminformation) package.
> deps(core-manager): update systeminformation

- __tests__/unit/core-test-framework/app/generators/__fixtures__/assets.ts
- __tests__/unit/core-test-framework/app/generators/core.test.ts
- packages/core-test-framework/src/app/generators/core.ts
Generate .env file content based on json data. 
Fixes failing test.
> fix(core-test-framework): save .env content in valid format

- packages/core-webhooks/src/listener.ts
Broadcast event to all targets at once.
> chore(core-webhooks): broadcast to all targets at once

- packages/crypto/package.json
- yarn.lock
Update @arkecosystem/crypto-identities to version 1.2.0.
> deps(crypto): update @arkecosystem/crypto-identities

- __tests__/unit/core-state/__utils__/build-delegate-and-vote-balances.ts
- packages/core-state/src/dpos/dpos.ts
Take `WalletRepository` clone to calculate previous delegates and `WalletRepository` blockchain for active delegates.
> fix(core-state): calculate previous round

- __tests__/unit/core-kernel/bootstrap/service-providers/register-service-providers.test.ts
- packages/core-kernel/src/exceptions/plugins.ts
> fix(core-kernel): missing dependency logs

- __tests__/unit/core-blockchain/blockchain.test.ts
- __tests__/unit/core-blockchain/process-blocks-job.test.ts
- __tests__/unit/core-state/stores/state.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/process-blocks-job.ts
- packages/core-kernel/src/contracts/state/state-store.ts
- packages/core-state/src/stores/state.ts
Keep record of database height in `StateStore`.
> chore(core-blockchain): keep record of last stored block height

- __tests__/unit/core-blockchain/processor/block-processor.test.ts
- __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
- packages/core-blockchain/src/processor/handlers/exception-handler.ts
Search for forged block in database as well in StateStore. Downloaded blocks are processed in chunks and are saved to database at the end of processing of chunk.
Implements additional check for block height, which should be last block height + 1, to prevent accepting block on random position.
> fix(core-blockchain): improve ExceptionHandler

- __tests__/unit/core-blockchain/processor/block-processor.test.ts
- packages/core-blockchain/src/processor/block-processor.ts
Check if `StateStore` contains forged transactions.
> chore(core-blockchain): check forged transactions in StateStore

- CODEOWNERS
Add @rainydio and @sebastijankuzner to codeowners.
> chore: add @rainydio and @sebastijankuzner to codeowners

- install-next.sh
- install.sh
Use node 14 in install.sh & install-next.sh scripts.
> chore: update node version to 14.x in install.sh scripts

- packages/core/package.json
- Fix package.json debug scripts. 
- Replace `debug:start` with `debug:core`
> fix(core): debug scripts

- packages/core/src/commands/snapshot-restore.ts
- packages/core/src/commands/snapshot-truncate.ts
> chore(core): remove excess flags on snapshot:* commands

- __tests__/unit/core-magistrate-crypto/builders/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate-crypto/builders/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate-crypto/builders/bridgechain-update.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-registration.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-resignation.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-update.test.ts
- __tests__/unit/core-magistrate-crypto/builders/enity.test.ts
Fixed imports in tests, changed from `dist` to `src` .
> test(core-magistrate-crypto): fix imports in tests

- __tests__/unit/core-cli/plugins/suggest.test.ts
- __tests__/unit/core/cli.test.ts
- packages/core-cli/src/plugins/suggest.ts
- packages/core/bin/run
- packages/core/src/cli.ts
Exit CLI gracefully. Suggest `ark help` instead `ark --help`.
> chore(core): exit cli gracefully

- __tests__/unit/core-cli/services/updater.test.ts
- __tests__/unit/core/commands/update.test.ts
- packages/core-cli/src/contracts.ts
- packages/core-cli/src/services/updater.ts
- packages/core/src/commands/update.ts
Add optional updateProcessManager flag. If flag is used, PM2 is going to be update during process.
> chore(core): add updateProcessManager flag in `update` command

- packages/core-transaction-pool/src/processor.ts
Extract `entryId` variable when handling `POST /api/transactions` request.
> refactor(core-transaction-pool): extract entryId variable

- __tests__/unit/core-manager/actions/process-delete.test.ts
- packages/core-manager/src/actions/process-delete.ts
Implements `process.delete` action.
> chore(core-manager): implements `process.delete` action

- packages/core-blockchain/package.json
- packages/core-jest-matchers/package.json
- yarn.lock
Fix xstate to version 4.23.1. This fixes issue #4480.
> deps: fix xstate to 4.23.1

- docker/production/Dockerfile
> docker: switch to node 14

- packages/crypto/package.json
- yarn.lock
Update `@arkecosystem/crypto-networks` to version **1.2.0**.
> deps(crypto): update `@arkecosystem/crypto-networks` to 1.2.0

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/devnet-sync.yml
- .github/workflows/functional.yml
- .github/workflows/mainnet-sync.yml
- .github/workflows/publish-master.yml
- lerna.json
Merged `master` into `develop`. Once PR is merged `develop` will merge into `master` without conflicts. They all are resolved here.
> chore: merge master into develop

- package.json
- packages/core-cli/__tests__/services/updater.test.ts
- packages/core/__tests__/commands/config-database.test.ts
- yarn.lock
Update **lerna** from 3.22.1 to 4.0.0
> deps: update lerna from 3.22.1 to 4.0.0

- packages/core-kernel/__tests__/bootstrap/app/load-service-providers.test.ts
- packages/core-kernel/__tests__/providers/plugin-discoverer.test.ts
- packages/core-kernel/src/application.ts
- packages/core-kernel/src/bootstrap/app/load-service-providers.ts
- packages/core-kernel/src/contracts/kernel/application.ts
- packages/core-kernel/src/exceptions/plugins.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-kernel/src/providers/index.ts
- packages/core-kernel/src/providers/plugin-discoverer.ts
- packages/core-snapshots/__tests__/database-service.test.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-transaction-pool/__tests__/worker-pool.test.ts
- packages/core-transaction-pool/src/worker-pool.ts
- yarn.lock
Implements PluginDiscoverer that loads plugins form project packages and plugins, installed plugins and from the node_modules.
> feat: implements PluginDiscoverer

- __tests__/unit/core-api/plugins/log.test.ts
- __tests__/unit/core-api/service-provider.test.ts
- packages/core-api/src/defaults.ts
- packages/core-api/src/plugins/index.ts
- packages/core-api/src/plugins/log.ts
- packages/core-api/src/service-provider.ts
Implements log plugin which logs request with debug log level. 
Logging can be enabled with `CORE_API_LOG` env variable.
> feat(core-api): implements log plugin

- packages/core-forger/package.json
- yarn.lock
Update [node-forge](https://www.npmjs.com/package/node-forge) to 1.2.1. 
Related to: #4568
> deps(core-forger): update node-forge to 1.2.1

- packages/core-api/src/resources/transaction.ts
> fix(core-api): skip transaction nonce for V1 on /transactions/unconfirmed endpoint

- __tests__/unit/core-logger-pino/driver.test.ts
- __tests__/unit/core-logger-pino/service-provider.test.ts
- packages/core-kernel/src/contracts/kernel/log.ts
- packages/core-kernel/src/services/log/drivers/memory.ts
- packages/core-kernel/src/services/log/drivers/null.ts
- packages/core-logger-pino/package.json
- packages/core-logger-pino/src/driver.ts
- packages/core-logger-pino/src/service-provider.ts
- yarn.lock
> feat(core-logger-pino): close file streams on dipose (#4536)

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.2

- packages/crypto/package.json
Fix the publish script in package.json..
> fix(crypto): publish

- packages/core/src/index.ts
Export core exceptions as Exceptions
> refactor(core): export exceptions as Exceptions

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.3

- packages/core-snapshots/package.json
- packages/core/package.json
- pnpm-lock.yaml
Include **pg** in core-snapshots and increase **pm2** version in core package.
> deps: add pg8 and increase pm2 version

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.4

- __mocks__/better-sqlite3.js
- __mocks__/execa.js
- packages/core-cli/__tests__/__mocks__/execa.js
- packages/core-cli/__tests__/services/installer.test.ts
- packages/core-cli/__tests__/services/source-providers/git.test.ts
- packages/core-cli/__tests__/services/updater.test.ts
- packages/core/__tests__/commands/config-cli.test.ts
- packages/core/__tests__/commands/reinstall.test.ts
- packages/core/__tests__/commands/update.test.ts
> test: move root mocks under packages tests (#4588)

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.5

- docker/production/Dockerfile
> chore: use `python3` in docker

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.6

- .github/workflows/devnet-sync.yml
- .github/workflows/mainnet-sync.yml
Devnet-sync.yml was overwritten in #4502. Reverting back to change from #4373.
> ci: adjust devnet-sync.yml

- packages/core-cli/__tests__/services/source-providers/npm.test.ts
- packages/core-cli/src/services/source-providers/abstract-source.ts
- packages/core-cli/src/services/source-providers/errors.ts
- packages/core-cli/src/services/source-providers/npm.ts
Update package to latest version on channel.
> fix(core-cli): update package to latest version on channel

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.7

- packages/core-kernel/src/services/search/pagination-service.ts
Fixes invalid pagination order. Additionally compare indexes when items in pagination are equal by given sorting.
> fix(core-kernel): fix pagination results order 

- packages/core-p2p/src/network-monitor.ts
> fix(core-p2p): use Promise.allSettled on block download

- __tests__/integration/core-api/services/__support__/setup.ts
- packages/core-api/__tests__/services/delegate-search-service.test.ts
- packages/core-api/src/services/delegate-search-service.ts
Merge master to develop
- release: 3.1.1 (#4598)
- chore: use `python3` in docker (#4603)
- chore(deps): bump simple-get from 3.1.0 to 3.1.1 (#4599)
- chore(deps): bump follow-redirects from 1.14.7 to 1.14.8 (#4606)
- fix(core-cli): delete better_sqlite3.node before installing (#4605)
- fix(core-api): use current supply to calculate delegates approval (#4615)
> merge: master to develop

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.8

- packages/core-api/src/resources-new/block.ts
- packages/core-api/src/resources-new/transaction.ts
- packages/core-api/src/routes/blocks.ts
- packages/core-api/src/routes/delegates.ts
- packages/core-api/src/routes/transactions.ts
- packages/core-api/src/routes/votes.ts
- packages/core-api/src/routes/wallets.ts
- packages/core-api/src/schemas.ts
Fixes:  #4621
Cherry pick:  https://github.com/Solar-network/core/pull/34
> fix(core-api): create block and transaction sorting schemas

- packages/core-p2p/src/network-monitor.ts
> fix(core-p2p): use Promise.allSettled on block download (#4618)

- packages/core-kernel/src/services/search/pagination-service.ts
> fix(core-kernel): fix pagination results order (#4617)

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.9

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/devnet-sync.yml
- .github/workflows/e2e.yml
- .github/workflows/functional.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/publish-develop.yml
- .github/workflows/publish-master.yml
- .github/workflows/unit.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> ci: set explicit permissions for actions/workflows

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.10

- __tests__/unit/core-p2p/actions/validate-and-accept-peer.test.ts
- __tests__/unit/core-p2p/peer-processor.test.ts
- __tests__/unit/core-p2p/socket-server/controllers/internal.test.ts
- __tests__/unit/core-p2p/socket-server/plugins/accept-peer.test.ts
- packages/core-kernel/src/contracts/p2p/peer-processor.ts
- packages/core-p2p/src/actions/validate-and-accept-peer.ts
- packages/core-p2p/src/peer-processor.ts
- packages/core-p2p/src/socket-server/controllers/internal.ts
- packages/core-p2p/src/socket-server/plugins/accept-peer.ts
> fix(core-p2p): update peer version on request (#4644)

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.11

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.12

- packages/core-api/src/plugins/pagination/ext.ts
Return unencoded query in meta response.
> fix(core-api): undencoded query

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.13

- __tests__/unit/core-cli/services/installer.test.ts
- __tests__/unit/core/commands/reinstall.test.ts
- __tests__/unit/core/commands/update.test.ts
- packages/core-cli/src/services/installer.ts
- split remove and yarn add command
- ignore errors on rm
> reafactor(core-cli): split remove and yarn add command

- packages/crypto/src/validation/schemas.ts
> fix(crypto): walletVote schema is public key

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.15

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.16

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0 next.18

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.19

- __tests__/unit/core-blockchain/processor/block-processor.test.ts
- __tests__/unit/core-database/transaction-filter.test.ts
- __tests__/unit/core-kernel/services/search/pagination-service.test.ts
- __tests__/unit/core-p2p/utils/is-valid-version.test.ts
- __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
- packages/core-api/src/controllers/blocks.ts
- packages/core-api/src/services/delegate-search-service.ts
- packages/core-blockchain/src/processor/block-processor.ts
- packages/core-database/src/transaction-filter.ts
- packages/core-kernel/src/services/search/pagination-service.ts
- packages/core-p2p/src/utils/is-valid-version.ts
- packages/core-state/src/block-state.ts
- packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
- packages/crypto/package.json
- yarn.lock
- fix(core-api): use ITransactionData in argument with BlockWithTransactionsResource (#4688) 
- fix: prevent new wallet creation in API requests (#4689) 
- fix(core-kernel): fix item ordering for undefined and null values in pagination service (#4691)
- refactor(core-api): order resigned delegates by publicKey (#4692) 
- fix(core-state): create new wallet instance in WalletRepositoryCopyOnWrite (#4694)
- fix(core-p2p): node version should pass min version defined in configuration and milestones (#4695)
> merge: cherry pick from `develop`

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.20

- __tests__/unit/core/commands/pool-clear.test.ts
- packages/core-api/src/controllers/delegates.ts
- packages/core/src/commands/pool-clear.ts
Cherry pick:
- fix(core-api): use block query criteria on delegates route (#4703)
- fix(core): remove all sqlite files with (#4704)
> merge: cherry pick from develop

- install.sh
Update install.sh script. Skip installation of python and libcairo2-dev packages.
> chore: update install.sh

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.21

- __tests__/integration/package.json
- packages/core-api/__tests__/server.test.ts
- packages/core-api/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-api/src/service-provider.ts
- packages/core-p2p/package.json
- packages/core-webhooks/package.json
- pnpm-lock.yaml
> deps: update @hapi packages

- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
> release: 4.0.0-next.22

- packages/core-database/src/repositories/abstract-repository.ts
> merge: cherry-pick query optimizer workaround (#4726)

- packages/core-p2p/src/defaults.ts
- packages/crypto/package.json
- yarn.lock
Add support for @arkecosystem/core rc channel.
> feat: add support for `rc` channel

- .github/workflows/publish-develop.yml
Update github CI for develop branch. Relase develop under `rc` tag.
> chore: update github CI for `develop` branch

- packages/core-p2p/src/defaults.ts
- packages/crypto/package.json
- yarn.lock
Remove: 3.0.0 prereleases, becaue they are included in ^3.0.0 with includePrerelease: true option.
> refactor(core-p2p): remove 3.0.0 prereleases

- packages/core-p2p/src/defaults.ts
- packages/crypto/package.json
- pnpm-lock.yaml
Cherry pick: 
[refactor: remove 3.0.0 pre-releases](https://github.com/ArkEcosystem/core/commit/6b6fd24db796264e1a659c6fe0b4f47fecdb8a40)
> merge: cherry-pick refactor: remove 3.0.0 pre-releases 

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/functional.yml
- .github/workflows/publish-master.yml
Remove setup python actions from Gitlab workflows.
> chore: remove setup python actions from Gitlab workflows

- packages/core/src/commands/config-cli.ts
> fix(core): support `rc` channel

- __tests__/unit/core-database/database-service.test.ts
- packages/core-database/src/database-service.ts
Run ANALYZE SQL statement on database initialization. This analyzes the database and collects statistics for more optimized queries by PostgreSQL Query Planner.
> feat(core-database): run `ANALYZE` on database initialization

- packages/core-api/src/server.ts
Destroy socket on response to prevent reusing connection. Each connection is started with new package status, which makes it suitable for iptables rate limiter.
> feat(core-api): destroy socket on response

- scripts/api-iptables.sh
Add script for rate limiter implementation using iptables.
> feat: api iptables rate limiter

- .github/workflows/benchmark.yml
- .github/workflows/e2e.yml
- .github/workflows/functional.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/publish-develop.yml
- .github/workflows/publish-master.yml
- .github/workflows/unit.yml
> chore: use node 16.x in Github CI

- docker/production/Dockerfile
- docker/production/entrypoint.sh
> docker - use node 18

- install-rc.sh
- install.sh
Use node 16 in install scripts
> chore: use node 16 in install scripts

- .github/workflows/benchmark.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/functional.yml
- .github/workflows/publish-master.yml
- README.md
Cherry pick readme updates from develop
> chore: merge cherry pick from develop

- packages/core-p2p/package.json
- packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
- packages/core-p2p/src/socket-server/codecs/proto/protos.js
- yarn.lock
Update [protobufjs](https://www.npmjs.com/package/protobufjs), due possible security vulnerability.
> deps(p2p): update protobufjs

- install.sh
Update **install.sh** script. Use officail PostrgreSql source to install latest PG15 version.
> refactor: update `install.sh`

- packages/core-p2p/package.json
- yarn.lock
[chore: update deps (](https://github.com/ArkEcosystem/core/commit/0a7922878f0fc63fe4997eefe4b7877713cd1a3f)https://github.com/ArkEcosystem/core/pull/4811[)](https://github.com/ArkEcosystem/core/commit/0a7922878f0fc63fe4997eefe4b7877713cd1a3f)
> merge: cherry pick from develop 
