ArkEcosystem/core

- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/socket-server/index.ts
* Traffic volume is reduced 21 times (!)
* As expected, only small messages appear in clear text (uncompressed)
now in tcpdump(1) output. Messages smaller than 1024 bytes are not
compressed
* Compression is used according to the following:
server perMessageDeflate=true,    client perMessageDeflate=true:    yes
server perMessageDeflate=true,    client perMessageDeflate not set: yes
server perMessageDeflate not set, client perMessageDeflate=true:    no
server perMessageDeflate not set, client perMessageDeflate not set: no
> feat(core-p2p): use compression on the p2p level

- __tests__/unit/core-webhooks/conditions.test.ts
- packages/core-webhooks/src/conditions.ts
> fix(core-webhooks): cast params in condition checks

- __tests__/helpers/transaction-factory.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-state/src/wallets/wallet.ts
- packages/crypto/src/errors.ts
- packages/crypto/src/transactions/deserializer.ts
- packages/crypto/src/transactions/factory.ts
- packages/crypto/src/transactions/types/schemas.ts
Ensure a participant does not provide multiple valid signatures by himself.
> fix(crypto): ensure only one signature per participant

- packages/crypto/src/validation/index.ts
`anyOf` looks for the first matching schema and exits early. `oneOf` always matches against each schema and will error when there's more than 1 match. This is not only slower but also sporadically causing issues when a transaction payload matches against multiple schemas.
Resolves #2888 
> fix(crypto): use `anyOf` for transactions schema

- packages/core-blockchain/src/blockchain.ts
The previous code would remove entires from milestoneHeights[] even if
no milestone is hit (due to e.g. "currentTransactionsCount >= 150" being
true).
> fix(core-blockchain): only shift milestoneHeights[] if at that height

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- __tests__/unit/core-webhooks/conditions.test.ts
- packages/core-p2p/src/enums.ts
- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/socket-server/index.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/core-webhooks/src/conditions.ts
- packages/crypto/src/validation/index.ts
> Backport bug fixes to master

- packages/core-p2p/src/utils/is-valid-version.ts
Removes the need to mess with `minimumVersions` on devnet.
> misc(core-p2p): accept prerelease version

- packages/core-database-postgres/src/migrations/20190905000000-change-set_row_nonce-to-use-max-nonce.sql
- packages/core-database-postgres/src/migrations/index.ts
Use `SELECT COALESCE(MAX(nonce), 0)` instead of `SELECT COUNT(*)` - they
produce the same result, but the former is much faster.
With this change a full block insert (with 500 transactions, so 1 + 500
INSERT queries) drops from about 4 seconds to about 0.4 seconds - the
same time it takes without the check constraint and the trigger on the
transactions table.
> perf(core-database-postgres): speed up nonce checks at DB level

- __tests__/integration/core-p2p/mocks/core-container.ts
- __tests__/unit/core-blockchain/stubs/state-storage.ts
- __tests__/unit/core-database/__fixtures__/state-storage-stub.ts
- __tests__/unit/core-state/__fixtures__/state-storage-stub.ts
- __tests__/unit/core-state/stores/state.test.ts
- __tests__/unit/core-transaction-pool/mocks/state.ts
- packages/core-interfaces/src/core-state/state-store.ts
- packages/core-state/src/stores/state.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transaction-pool/src/processor.ts
Because of nonces, #2879 changed how the transaction pool processor removes cached transaction ids. They are now removed too early which effectively renders the cache useless. But with nonces it is not trivially possible to generate a different id anymore (without changing the payload) and thus if rejected once (e.g. sent too early or whatever) it will likely be rejected again for quite some time.
The only purpose of the id caching is to "debounce" the transaction broadcasts that happen between peers in the network. Without it, the processor would end up processing the same transactions multiple times, because the endpoint is hit multiple times with the same payload in a short timeframe.
This PR changes it so that the cache is cleared whenever a block is accepted instead. While that …
> refactor(core-transaction-pool): clear cached transaction ids after accepting block

- packages/core-blockchain/src/processor/block-processor.ts
We already call `blockContainsIncompatibleTransactions` which ensures that a block cannot contain mixed versions. So it is safe to assume that all following transactions are the same.
> refactor(core-blockchain): break loop if block contains v1 transaction

- __tests__/functional/transaction-forging/multi-payment.test.ts
- __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- __tests__/unit/crypto/transactions/schemas.test.ts
- packages/crypto/src/errors.ts
- packages/crypto/src/transactions/builders/transactions/multi-payment.ts
- packages/crypto/src/transactions/types/multi-payment.ts
We don't need 4 bytes to store the number of payments of a multipayment transaction.
> fix(crypto): use 2 bytes to store number of payments

- __tests__/functional/transaction-forging/delegate-resignation.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-transaction-pool/src/wallet-manager.ts
- packages/core-transactions/src/errors.ts
- packages/core-transactions/src/handlers/delegate-resignation.ts
Core assumes to always have at least `activeDelegates` (i.e. 51) delegates so we mustn't allow dropping below that number if there are no other delegates to fill that spot.
> fix(core-transactions): reject delegate resignation if not enough inactive delegates

- packages/crypto/src/transactions/types/htlc-lock.ts
Changing the size of bytebuffer in htlc serialization, because is larger then needed
> fix(crypto): htlc lock buffer allocation

- __tests__/unit/core-transaction-pool/connection.test.ts
- packages/core-transaction-pool/src/memory.ts
The merge 3923c3755 wrongly removed the method sortAll() from memory.ts.
This method was sorting transactions in the pool by fee, nonce (sorted
by highest fee first, but transactions from the same sender must be
sorted lowest nonce first).
Restore the sortAll() method as of before the merge and adapt it to use
the calculateTransactionExpiration() method for expiration sorting.
> fix(core-transaction-pool): sort by fee, nonce

- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-refund/1.create-lock-txs.action.js
- packages/core-transactions/src/handlers/htlc-refund.ts
HTLC refund handler needs to use performGenericWalletChecks just like claim handler.
Also fixed e2e tests (needed to give a bit more expiration time for htlc lock txs).
> fix: htlc refund handler to use performGenericWalletChecks (+ fix e2e tests)

- packages/core-transaction-pool/package.json
- packages/core-transaction-pool/src/connection.ts
transactions.filter(t => !forgedIds.includes(t.id)) has
complexity O(transactions.length * forgedIds.length). Use the efficient
lodash.differencewith instead (which has O(transactions.length +
forgedIds.length), maybe).
A comparison between .filter(... .includes()) and differencewith() ran
over two arrays with 50k elements (integers and strings):
int lodash:        15ms
int poor man's:  1969ms
str lodash:        21ms
str poor man's: 35102ms
> perf: use lodash to efficiently remove forged transactions

- packages/core-transaction-pool/src/connection.ts
validateTransactions() would take an array of transaction objects and
return a subset of it, but just the serialized property, not the entire
transaction object.
The two callers of validateTransactions() would then filter the array
they provided to validateTransactions() so that it contains only the
returned valid transactions. But, given that the returned array is a
subset of the provided array that means that the returned array is
the same as the filtered input. On top of this the unnecessary filtering
was done using an ineffective O(m*n) algorithm.
So, change validateTransactions() to return the transaction objects
instead of just the serialized property and use the returned array
directly (avoid the unnecessary filtering altogether).
A summary of what changes this PR introduces and …
> perf: Avoid O(m*n) when filtering pool txs and simplify the code

- .github/workflows/test.yml
Coverage reporting seems to be acting out after the move to GitHub Actions, using different directories for each type of test should force codecov to merge them.
> ci: use different test coverage directories for each type

- packages/core-p2p/src/peer-communicator.ts
Don't flood the log with reply schema errors and make it opt-in.
```
3|ark-relay      | [2019-09-24 02:20:27.075] INFO : Broadcasting block 3,709,770 to 129 peers
3|ark-relay      | [2019-09-24 02:20:28.182] ERROR: Got unexpected reply from http://134.209.94.193:4002/p2p.peer.getStatus: data.config should have required property 'plugins'
3|ark-relay      | [2019-09-24 02:20:28.554] ERROR: Got unexpected reply from http://134.209.94.193:4002/p2p.peer.getStatus: data.config should have required property 'plugins'
3|ark-relay      | [2019-09-24 02:20:28.869] ERROR: Got unexpected reply from http://134.209.94.193:4002/p2p.peer.getStatus: data.config should have required property 'plugins'
3|ark-relay      | [2019-09-24 02:20:34.417] INFO : 134.209.94.193 has downloaded 400 blocks from height …
```
> refactor(core-p2p): make peer reply errors less verbose

- __tests__/unit/core-blockchain/state-machine.test.ts
- __tests__/unit/core-blockchain/stubs/state-storage.ts
- packages/core-blockchain/src/state-machine.ts
- packages/core-state/src/stores/state.ts
Otherwise it is possible that the chain gets stuck, as it would never attempt to check for forks. Instead, reset inside `setLastBlock`.
> fix(core-blofix(core-blockchain): do not reset `noBlockCounter` when `downloadBlocks` succeeds

- packages/core-snapshots/src/db/index.ts
- packages/core-snapshots/src/db/queries/rounds/round-range.sql
- packages/core-snapshots/src/utils.ts
skipRoundRows was only set to something else than 0 when appending to an
existent snapshot and then it was set to the number of rows in the
rounds table in the appended-to snapshot. Then it would translate to an
OFFSET in the SQL query:
SELECT round, balance, public_key
FROM rounds
WHERE round BETWEEN 9804 AND 9902
ORDER BY round, balance DESC, public_key
OFFSET 500004
but the proper rows to be selected are already defined by the BETWEEN
clause.
So, the usage of OFFSET is wrong and leads to bogus results - when
appending to a snapshot the result would be a snapshot with missing rows
from the rounds table, and subsequently when that snapshot is restored -
gaps (missing rows) in the rounds table in the database.
> fix(core-snapshots): remove bogus skipRoundRows

- __tests__/integration/core-api/handlers/locks.test.ts
- __tests__/integration/core-api/handlers/wallets.test.ts
- packages/core-api/src/handlers/locks/transformer.ts
- packages/core-api/src/handlers/wallets/methods.ts
- packages/core-api/src/handlers/wallets/schema.ts
- packages/core-api/src/handlers/wallets/transformer.ts
- packages/core-database/src/repositories/utils/sort-entries.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
Accept `orderBy` on `/locks` and `/wallet/{id}/locks`.
> fix(core-api): missing orderBy

- __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
- packages/crypto/src/transactions/builders/transactions/transaction.ts
Complements `signWif` and `secondSignWif` by adding `multiSignWif` to the transaction builder.
> feat(crypto): add multiSignWif to transaction builder

- __tests__/unit/core-magistrate/builders/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/builders/business-registration.test.ts
- __tests__/unit/core-magistrate/builders/business-resignation.test.ts
- __tests__/unit/core-magistrate/builders/business-update.test.ts
- __tests__/unit/core-magistrate/handlers/business-registration.test.ts
- __tests__/unit/core-magistrate/handlers/handlers.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/transactions/business-registration.test.ts
- __tests__/unit/core-magistrate/transactions/business-resgination.test.ts
- __tests__/unit/core-magistrate/transactions/business-update.test.ts
- packages/core-api/src/handlers/bridgechains/transformer.ts
- packages/core-api/src/handlers/businesses/transformer.ts
- packages/core-magistrate-crypto/src/index.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-magistrate-transactions/src/handlers/business-update.ts
- packages/core-snapshots/src/db/index.ts
Export top level namespaces for `Transactions`  and `Enums`.
> refactor(core-magistrate-crypto): export only namespaces

- packages/core/src/shared/start.ts
This was added to trigger the GC sooner on nodes with low memory, as they tend to run out of memory during a long running sync. However, all this did was to just work around a symptom and not the actual issue (*cough* Socketcluster timeouts something *cough*). Now it is causing issues during bootstrap, because V8 hits the allocation limit and just kills itself. Since the former is the latter evil, rather take the risk to run out of memory during a long running sync than during bootstrap.
> refactor(core): use default heap size regardless of available memory

- packages/core-database-postgres/src/postgres-connection.ts
It was added back when the `asset` column was introduced to keep
support for old snapshots without an `asset` column. But this is now
obsolete since all snapshots nowadays contain assets. It also stopped
working reliably, as there are now multiple transactions types which
falsely trigger a migration.
> refactor: remove asset migration heuristic

- __tests__/unit/crypto/managers/config.test.ts
- packages/crypto/src/managers/config.ts
Before one had to call `setHeight` before to check an explicit height, but now the height can be passed in directly.
> feat(crypto): allow passing height to `configManager.isNewMilestone`

- __tests__/unit/crypto/blocks/factory.test.ts
- __tests__/unit/crypto/fixtures/block.ts
- packages/crypto/src/blocks/block.ts
- packages/crypto/src/validation/index.ts
- packages/crypto/src/validation/keywords.ts
If the block validation fails and there are any exceptions, instead of continuing right away, rerun the schema validation without bailing out on the first encountered error. This ensures all bignumber 
properties are properly converted.
Fixes #3003
> fix(crypto): run ajv validator again when encountering exceptions

- __tests__/integration/core-api/handlers/locks.test.ts
- __tests__/integration/core-api/utils.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- packages/core-api/src/handlers/locks/schema.ts
- packages/core-database/src/repositories/utils/search-entries.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
- packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/crypto/src/interfaces/transactions.ts
- packages/crypto/src/transactions/builders/transactions/htlc-lock.ts
- packages/crypto/src/transactions/builders/transactions/multi-payment.ts
- packages/crypto/src/transactions/types/htlc-lock.ts
- packages/crypto/src/transactions/types/multi-payment.ts
- packages/crypto/src/transactions/types/schemas.ts
Adds `vendorField` and `timestamp` to the `/locks` endpoint.
> refactor(core-api): add `vendorField` and `timestamp` to `/locks` endpoint

- packages/core-database/src/database-service.ts
- packages/core-event-emitter/src/index.ts
Emit `round.missed` at the end of a round for each active delegate that didn't forge a block.
> feat(core-database): emit `round.missed` for each active delegate that didn't forge

- packages/crypto/package.json
- packages/crypto/src/crypto/bip38.ts
- packages/crypto/src/identities/address.ts
- packages/crypto/src/transactions/serializer.ts
- packages/crypto/src/utils/base58.ts
- yarn.lock
Memoize Base58 functions to speed up multipayment processing by up to 50%.
```
Before:
✓  Block.fromData (Multipayments 500 recipients) x 10.46 ops/sec ±1.14% (29 runs sampled)
After:
✓  Block.fromData (Multipayments 500 recipients) x 15.92 ops/sec ±3.32% (43 runs sampled)
```
> perf(crypto): memoize base58 de/encoding

- __tests__/integration/core-transactions/handlers/htlc-claim.test.ts
- __tests__/integration/core-transactions/handlers/htlc-refund.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- packages/core-database-postgres/src/queries/index.ts
- packages/core-database-postgres/src/queries/state-builder/claimed-locks.sql
- packages/core-database-postgres/src/queries/state-builder/open-locks.sql
- packages/core-database-postgres/src/queries/state-builder/refunded-locks.sql
- packages/core-database-postgres/src/repositories/transactions.ts
- packages/core-database/src/repositories/transactions-business-repository.ts
- packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
- packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core-transactions/src/transaction-reader.ts
Optimizes the HTLC bootstrap by excluding claimed/refunded locks and ensuring that each wallet is only indexed once.
Before:
```
[2019-10-05 01:13:50.419] INFO : State Generation - Step 10 of 20: DelegateResignation
[2019-10-05 01:13:50.458] INFO : State Generation - Step 11 of 20: HtlcLock
[2019-10-05 01:14:30.826] INFO : State Generation - Step 12 of 20: HtlcClaim
[2019-10-05 01:14:41.115] INFO : State Generation - Step 13 of 20: HtlcRefund
[2019-10-05 01:14:41.217] INFO : State Generation - Step 14 of 20: BusinessRegistration
```
After:
```
[2019-10-05 01:15:06.293] INFO : State Generation - Step 10 of 20: DelegateResignation
[2019-10-05 01:15:06.326] INFO : State Generation - Step 11 of 20: HtlcLock
[2019-10-05 01:15:06.611] INFO : State Generation - Step 12 of 20: HtlcClaim …
```
> perf(core-transactions): htlc bootstrap

- packages/core-database-postgres/src/migrations/20191008000000-add-type-index-to-transactions-table.sql
On mainnet database (9912558 blocks, 3171992 transactions):
SELECT * FROM transactions WHERE type = 6;
no index: 700ms, with index: 1ms
SELECT * FROM transactions WHERE type = 1;
no index: 650ms, with index: 14ms
SELECT * FROM transactions WHERE type = 3;
no index: 1280ms, with index: 480ms
SELECT * FROM transactions WHERE type = 0;
no index: 11500ms, with index: 11500ms (the index is not used)
bootstrap
no index: 22sec, with index: 20sec
> perf(core-database-postgres): add index on transactions.type

- packages/core-transactions/src/transaction-reader.ts
Disable the TransactionReader because it inflicts a minor performance
regression. However, do not completely delete it from the source code
because we may revisit it later when the database queries start
returning way too many rows to the nodejs app at once. The proper
solution is to execute the database query once and serve the results to
the app on portions using cursors, rather than executing the same query
multiple times and chopping the portions using OFFSET,LIMIT.
> perf(core-transactions): disable TransactionReader

- packages/core-database/src/repositories/transactions-business-repository.ts
Attach a block to the transaction model so the transformer can calculate the confirmations.
> fix(core-api): missing confirmations for lock transactions

- packages/core-p2p/src/socket-server/versions/utils.ts
- packages/core-p2p/src/socket-server/worker.ts
Fixes #3047 by returning an object rather than a primitive.
> fix(core-p2p): convert isAppReady response to object

- packages/core-database-postgres/src/migrations/20191003000000-migrate-vendor-field-hex.sql
* We support utf8 strings for vendor field
* \u0000 (nul byte) is a valid utf8 string
* PostgreSQL cannot store \u0000 in VARCHAR
It follows that we cannot use VARCHAR for storing vendor field.
So use bytea for that.
> fix(core-database-postgres): store vendor field in bytea

- CHANGELOG.md
Changelog for 2.6 with all notable changes.
> docs: 2.6.0 changelog

- __tests__/unit/crypto/blocks/factory.test.ts
- packages/crypto/src/blocks/block.ts
- packages/crypto/src/validation/index.ts
fix(crypto): strengthen schema validation checks
Check each schema error:
* if it originated from the block, then the block must be an exception
* if it originated from a transaction, then the transaction must be an
exception
Also print the value should validation fail to make it easier to
diagnose problems.
> Block schema validation

- packages/core-p2p/src/defaults.ts
- packages/crypto/src/networks/devnet/milestones.json
Two new devnet milestones:
- Height `3967000`:
The `p2p.minimumVersions` milestone is used to switch to a `2.6` only network after a few days. All <2.6 nodes should get dropped  then.
- Height `4006000`:
The `aip11` milestone which is scheduled to happen next week. That's when the network will switch from V1 to V2 transactions including the new types
> misc(crypto): add devnet milestones

- packages/core-api/src/handlers/peers/controller.ts
Resolves https://github.com/ArkEcosystem/core/issues/3074
Resolves https://github.com/ArkEcosystem/core/issues/3080
> fix(core-api): add missing offset handling to /api/peers

- packages/core-tester-cli/package.json
- packages/core-tester-cli/src/commands/command.ts
- packages/core-tester-cli/src/commands/make/block.ts
- packages/core-tester-cli/src/signer.ts
> fix(core-tester-cli): support nonces and chunk transactions before broadcast

- packages/core-api/src/handlers/transactions/controller.ts
- packages/core-api/src/handlers/transactions/routes.ts
> feat(core-api): add `/transactions/schemas` endpoint

- __tests__/unit/core-transaction-pool/connection.test.ts
- packages/core-database-postgres/package.json
- packages/core-database-postgres/src/state-builder.ts
- packages/core-event-emitter/src/index.ts
- packages/core-transaction-pool/src/connection.ts
> refactor(core-event-emitter): add `stateBuilder.finished` to ApplicationEvents

- packages/core-database/src/database-service.ts
- packages/core-state/src/wallets/temp-wallet-manager.ts
If the database wallet manager doesn't know the wallet we have to create a new one.
> fix(core-transaction-pool): create new wallet if not found

- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-magistrate-transactions/src/handlers/business-update.ts
- packages/core-transactions/src/handlers/delegate-resignation.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core-transactions/src/handlers/ipfs.ts
- packages/core-transactions/src/handlers/multi-payment.ts
Use strict comparison to decide if AIP11 is active or not. Using `!!` means any [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) value would indicate that AIP11 is active.
> fix: use strict comparison to decide if a transaction should be enabled

- __tests__/unit/core-transactions/handler-registry.test.ts
- packages/crypto/src/errors.ts
- packages/crypto/src/transactions/registry.ts
> fix(core-transactions): throw if transaction key is already taken

- packages/core-database/src/database-service.ts
> fix(core-database): set last height before initializing last block to use correct milestones

- __tests__/unit/crypto/managers/config.test.ts
- packages/crypto/src/managers/config.ts
Instead of concatenating arrays, overwrite them with the `source` array. In the particular case of `minimumVersions` we don't want to keep older values around, this PR is a solution targeted at this case and is not intended as a general solution for merging arrays - although as of now the `minimumVersions` array is the only array used in milestones.
Possibly closes #3105.
> refactor(crypto): overwrite arrays when merging milestones

- __tests__/functional/transaction-forging/bridgechain-registration.test.ts
- __tests__/unit/core-blockchain/state-machine.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/state-machine.ts
- packages/core-database/src/database-service.ts
- packages/core-interfaces/src/core-transaction-pool/connection.ts
- packages/core-transaction-pool/src/connection.ts
Replay all transactions on the pool in the correct order for sender and recipient after a rollback finished. Otherwise they cannot be applied due to nonce conflicts.
I.e.
```
[2019-10-24 02:26:16.101] ERROR: Cannot apply a transaction with nonce 32: the sender 03395ce74f7d696edee6e34bc68b7c41348f558ee99766389adcf93e6291d8c37b has nonce 32.
[2019-10-24 02:26:16.104] ERROR: Cannot apply a transaction with nonce 50: the sender 02afe630a4feaacdb12162a0107ac395189548246a0c148ebfdb79641a25778a16 has nonce 51.
[2019-10-24 02:26:16.106] ERROR: Cannot apply a transaction with nonce 51: the sender 02afe630a4feaacdb12162a0107ac395189548246a0c148ebfdb79641a25778a16 has nonce 51.
[2019-10-24 02:26:16.107] ERROR: Cannot apply a transaction with nonce 58: the sender …
```
> fix(core-blockchain): add transactions back to pool only after reverting all blocks

- __tests__/unit/core-transaction-pool/__stubs__/connection.ts
- packages/core/src/commands/chain/replay.ts
- packages/core/src/commands/core/run.ts
- packages/core/src/commands/forger/run.ts
- packages/core/src/commands/relay/run.ts
- packages/core/src/commands/snapshot/dump.ts
- packages/core/src/commands/snapshot/restore.ts
- packages/core/src/commands/snapshot/rollback.ts
- packages/core/src/commands/snapshot/truncate.ts
- packages/core/src/commands/snapshot/verify.ts
- packages/core/src/helpers/replay.ts
- packages/core/src/helpers/snapshot.ts
- packages/core/src/utils.ts
Fixes the config lookup. Additionally, `packages/core/bin/config/{network}/app.js` needs to be manually copied to `~/.config/ark-core/{network}` or `ark config:reset`.
Resolves:
```
10|ark-forger  | [2019-10-26 11:44:26.760] ERROR: InvalidTransactionBytesError: Failed to deserialize transaction, encountered invalid bytes: Unknown transaction type: 2/2
10|ark-forger  |     at Function.fromBytesUnsafe (/home/ark/core/packages/crypto/dist/transactions/factory.js:34:19)
10|ark-forger  |     at response.transactions.map (/home/ark/core/packages/core-forger/dist/manager.js:147:106)
10|ark-forger  |     at Array.map (<anonymous>)
10|ark-forger  |     at ForgerManager.getTransactionsForForging 
```
> fix(core): read `paths.config` instead of env variable

- packages/core-transactions/src/handlers/htlc-lock.ts
Closes #3134.
Judging by the current state of the dexplorer node (https://dexplorer.ark.io/api/locks) the vendorfield of bootstrapped lock transactions isn't converted to strings. New transactions applied to senders however show the vendorfield as expected.
> refactor(core-database): convert htlc lock vendorfield to string during bootstrap

- __tests__/functional/transaction-forging/bridgechain-registration.test.ts
- __tests__/functional/transaction-forging/business-registration.test.ts
- __tests__/functional/transaction-forging/business-update.test.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
- packages/core-magistrate-crypto/src/transactions/utils/business-schema.ts
- packages/crypto/src/validation/schemas.ts
Closes #3125.
The chosen validation for Business and Bridgechain names is a RegEx that validates for alphanumeric characters, with the addition of a lowercase and dash. This validation has been saved as the 'genericName' schema.
Addtional schemas and validation on the `website` and `repository` fields has intentionally not been created as it's out of scope of this PR (+ ongoing discussion in #3106 ).
> fix(core-magistrate-crypto): improve 'name' field validation to avoid illegal characters

- __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
- packages/core-database/src/repositories/transactions-business-repository.ts
> refactor(core-api): fallback to core typegroup if querying by type

- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/socket-server/index.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/core-p2p/src/utils/socket.ts
>  fix(core-p2p): timeout promise race

- packages/core-p2p/src/socket-server/worker.ts
Call `next()` in emit middleware so that the request can proceed. Not calling `next()` and not terminating socket result in timeout for the sender. (and in this case problems when trying to accept a new peer that just started and is in "application not ready" state).
> fix(core-p2p): call next() so that the request can proceed

- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/utils/index.ts
Use the rate limiter in reverse to stop ourselves from sending too
many requests to a given peer that could possibly trigger their
protection and result in banning us.
We use the default configuration for rate limits. So this will work as
long as the peer is using the same software and has not changed his
config or has made it more liberal. If the peer has made his limits
more restricted, then we could still trigger their protection.
A more robust solution would be to negotiate the rate limits at peer
handshake and then obey different limits for each peer.
> feat(core-p2p): implement throttling on outgoing p2p communication

- packages/core-database/src/repositories/wallets-business-repository.ts
expirationValue could be either "height of the blockchain" or "seconds
since the genesis block", so sorting by it gives some misleading
impression that the returned results are sorted by expiration when they
are in fact not.
It is not possible to reliably convert from height to seconds, thus
ditch the ordering by expirationValue and order by lockId which will at
least deterministically return the results in the same order every time.
Closes https://github.com/ArkEcosystem/core/issues/3088
> chore(core-database): remove misleading order by expirationValue

- packages/core/src/commands/snapshot/dump.ts
- packages/core/src/commands/snapshot/restore.ts
- packages/core/src/commands/snapshot/rollback.ts
- packages/core/src/commands/snapshot/truncate.ts
- packages/core/src/commands/snapshot/verify.ts
Abort the execution of snapshots command if any core process is active to avoid unexpected side-effects.
> fix(core): prevent snapshot commands from running if core is running

- packages/core-api/src/handlers/wallets/transformer.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
```
{
"data": {
"address": "DMT1PcHdwv5Uh4Wj51iY9GtWnumhzVX6DG",
"publicKey": "02e0dce173cd011d7caaf9f847e4354ee9394d8d3f8acddbaffcbb79dfe78aea52",
"nonce": "3",
"balance": "5000000004",
"isDelegate": false,
"isResigned": false,
"business": {
"name": "Lemii-Inc-7c0b1653",
"website": "https://www.lemii-inc-7c0b1653.com",
"repository": "https://www.lemii-inc-7c0b1653.com/repository",
"businessId": 80
}
}
}
```
Bridgechains are deliberately omitted and should be looked up via the dedicated endpoint.
> feat(core-api): include business asset in wallet transformer

- packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Exceptions for https://github.com/ArkEcosystem/core/commit/312abcfe70d1c8055ef82380c00a8a8acd284225 won't work because the invalid fees are checked before exceptions are checked.
Needed for https://github.com/ArkEcosystem/core/pull/3214
> fix(core-magistrate-transactions): check for an exception before checking for invalid fees

- __tests__/integration/core-p2p/peer-communicator.test.ts
In "real life", common block response only has a few properties.
We mocked it in integration tests with a full block, the genesis block, which was causing the integration tests to fail as we were sending too large data to the p2p endpoint.
This fixes the test by mocking with a "valid" common block object.
> test(core-p2p): fix mock common block

- __tests__/integration/core-api/handlers/locks.test.ts
- __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
- packages/core-api/src/handlers/locks/schema.ts
- packages/core-api/src/handlers/locks/transformer.ts
- packages/core-api/src/handlers/wallets/schema.ts
- packages/core-database/src/repositories/utils/filter-rows.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
Closes #3224. The calculation of the expiration status needed to be moved out of the transformer, as the respective field is needed earlier when the filter is applied to the rows.
> feat(core-api): filter locks by expiration status

- __tests__/unit/crypto/identities/address.test.ts
- packages/crypto/src/identities/address.ts
Shortcut for `Identities.Address.fromPublicKey(Identities.PublicKey.fromWIF(...))`.
> feat(crypto): implement Address.fromWIF method

- packages/core-api/src/handlers/locks/schema.ts
Changes the schema for `expirationType` to be based on the `HtlcLockExpirationType` enum instead of using hardcoded values.
> refactor(core-api): validate expiration type based on enum

- __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/transactions/business-registration.test.ts
- __tests__/unit/core-magistrate/transactions/business-resgination.test.ts
- __tests__/unit/core-magistrate/transactions/business-update.test.ts
- __tests__/unit/crypto/blocks/deserializer.test.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- benchmark/transaction/deserialize/methods.js
- packages/crypto/src/blocks/block.ts
- packages/crypto/src/blocks/deserializer.ts
- packages/crypto/src/blocks/factory.ts
- packages/crypto/src/transactions/deserializer.ts
- packages/crypto/src/transactions/factory.ts
Now it's consistent with the block/transaction `Serializer` classes.
> refactor(crypro): make deserializers static

- __tests__/integration/core-api/handlers/blocks.test.ts
- packages/core-api/src/handlers/blocks/schema.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-api/src/handlers/delegates/schema.ts
- packages/core-api/src/handlers/locks/schema.ts
- packages/core-api/src/handlers/peers/schema.ts
- packages/core-api/src/handlers/shared/schemas/index.ts
- packages/core-api/src/handlers/shared/schemas/order-by.ts
- packages/core-api/src/handlers/transactions/schema.ts
- packages/core-api/src/handlers/votes/schema.ts
- packages/core-api/src/handlers/wallets/schema.ts
Closes #3237 by adding a basic schema to validate against `<iteratee>:<direction`, where `iteratee` is a string between 1 and 40 characters, `direction` is either `asc` or `desc`.
Using an invalid `orderBy` param will result in a 422 error:
```
{
"statusCode": 422,
"error": "Unprocessable Entity",
"message": "child \"orderBy\" fails because [\"orderBy\" with value \"foo:bar\" fails to match the orderBy query parameter (<iteratee>:<direction>) pattern]"
}
```
> refactor(core-api): add schema for orderBy query param

- packages/core-database-postgres/src/repositories/repository.ts
Fixes #3236.
The following conditional will cause the `findManyWithCount` method to return early:
https://github.com/ArkEcosystem/core/blob/0257c3c442aa18b27aa4b0d787bc99737b3ebd52/packages/core-database-postgres/src/repositories/repository.ts#L77-L79
This works as intended as long as `rows.length > 0`. When there are no rows however, the offset (which is calculated based on the page param) is returned as count, resulting in the faulty meta data described in #3236.
> fix(core-database-postgres): return early only if there are rows

- __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
- packages/core-magistrate-transactions/src/errors.ts
- packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Increase verbosity of error that appears when not using the required static fee on core-magistrate transactions. Closes #3249.
> refactor(core-magistrate-transactions): more verbose static fee mismatch error

- packages/core/src/commands/pool/clear.ts
Adds a CLI command to delete the files belonging to the transaction pool as an easy to remember alternative to manually deleting the files.
Usage: `ark pool:clear`
> feat(core): add command to clear transaction pool

- __tests__/integration/core-transaction-pool/wallet-manager.test.ts
- packages/core-transaction-pool/src/wallet-manager.ts
Resolves #3242 
Transaction pool wallet manager : try database wallet manager findByIndex() when local findByIndex() doesn't return a match.
We might not have all existing wallets indexes on transaction pool wallet manager : so in case we get no match we should try with database wallet manager.
> fix(core-transaction-pool): wallet-manager fallback to database wallet manager findByIndex() when no "local" match

- __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
- __tests__/functional/transaction-forging/bridgechain-update.test.ts
- __tests__/helpers/transaction-factory.ts
- __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
- __tests__/unit/core-magistrate/wallet.test.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
- packages/core-magistrate-crypto/src/builders/bridgechain-resignation.ts
- packages/core-magistrate-crypto/src/interfaces.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
- packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/interfaces.ts
Resolves #3257 
Use bridgechain genesisHash as id instead of using some index based on current bridgechains registered.
The current bridgechain id logic is causing the #3257 issue , relying on wallet current registered bridgechains is a bit "weak" in my opinion (and as we have database vs tx pool wallet manager which can hold different states, it is dangerous).
Using genesisHash makes sense as it is enforced as unique and defines the bridgechain.
Also, in my opinion **business id should be updated too** as it uses the same mecanism and can be bug-prone. (will open an issue for it)
**Important** : current devnet nodes cannot just update with this and be fine, as their database contains "old" ids and will mess up a lot, 2 options : 
- roll back to before the 1st typeGroup 2 transaction
- …
> fix(core-magistrate): use genesisHash for bridgechainId

- packages/core-forger/src/delegate.ts
If anything with the provided bip38 or password was wrong it was just assumed that no delegate will be used. Now the exception will be thrown and nothing is assumed.
> fix(core-forger): don't swallow BIP38 errors

- packages/core/src/commands/command.ts
Removes the `bip38` constraint from the `--password` flag so that it can be used as documented on docs.ark.io. This makes it possible to run the `core:forger` command directly instead of the underlying commands.
> fix(core): remove password flag constraint for core:forger command

- __tests__/integration/core-api/handlers/businesses.test.ts
- __tests__/unit/core-magistrate/handlers/business-registration.test.ts
- __tests__/unit/core-magistrate/wallet.test.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-api/src/handlers/businesses/methods.ts
- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-api/src/handlers/wallets/transformer.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/interfaces.ts
- packages/core-magistrate-transactions/src/wallet-manager.ts
Resolves #3259 
Use wallet publicKey for business id index, as a business is unique to a wallet.
Before we were using a wallet manager based index which can lead to bugs (database wallet manager does not hold the same state as tx pool wallet manager, so we can easily choose a wrong id).
> fix(core-magistrate): use wallet publicKey for business id index

- packages/crypto/src/transactions/types/schemas.ts
Since ARK mainnet and bridgechains are introducing transactions that require zero fees, it might be a good idea to have the minimum fee in `transactionBaseSchema` as `0`.
> refactor(crypto): Set transactionBaseSchema fee minimum to 0

- __tests__/unit/crypto/transactions/schemas.test.ts
- packages/crypto/src/transactions/types/schemas.ts
Overwrites the new minimum fee of zero introduced in #3275 to be positive again on certain transaction types:
- transfer
- second signature
- delegate registration
- delegate resignation
- vote
- multi signature
- ipfs
- htlc lock
- multi payment
Alternatively the unit tests for these transaction types can be adjusted to check for negative fees instead of zero fees.
> refactor(crypto): set minimum fee on transaction types

- packages/core-transactions/src/handlers/transaction.ts
While applying and reverting transactions update sender's state only after everything is validated, otherwise wallet may end up in inconsistent state.
> fix(core-transactions): update sender's wallet after validation

- .gitignore
`tmp-shm` and `tmp-wal` are generated by integration tests. These files should be added to project root gitignore.
> chore: add tmp-shm and tmp-wal to .gitignore

- __tests__/integration/core-api/handlers/businesses.test.ts
- packages/core-api/src/handlers/businesses/methods.ts
- packages/core-api/src/handlers/businesses/schema.ts
With these changes it will be possible to retrieve a business and its bridgechains by using the associated wallets address, publicKey or delegate name.
Fixes #3308 and fixes #3309.
> refactor(core-api): accept address, publicKey, delegate name as business id

- packages/core-database/src/repositories/utils/search-entries.ts
- packages/core-database/src/repositories/utils/sort-entries.ts
- packages/core-database/src/repositories/wallets-business-repository.ts
Adds cases to properly order by `voteBalance` and `forgedTotal`.
~https://github.com/ArkEcosystem/core/blob/develop/packages/core-database/src/repositories/wallets-business-repository.ts#L157-L172~
~These lines were removed as I don't see the reason for the delegate attributes to be set. The `searchEntries` method manipulates each of these iteratees to be a method, which is then used for the actual sorting - the attributes aren't accessed, which makes the mapping superfluous imho.~
The above seems to be necessary for the _filtering_, not _sorting_.
Fixes the specific issue described in #3315.
> fix(core-database): handle forgedTotal and voteBalance in orderBy query param

- packages/core-transactions/src/handlers/delegate-resignation.ts
- packages/core-transactions/src/handlers/multi-signature.ts
- packages/core-transactions/src/handlers/second-signature.ts
- packages/core-transactions/src/handlers/vote.ts
- packages/core-transactions/src/interfaces.ts
Explain that if canEnterTransactionPool() returns false it would have
called processor.pushError().
In addition:
Simplify some code that did "if (A) { return false } return true"
to "return !A".
Remove redundant processor.pushError() from
DelegateResignationTransactionHandler() because
typeFromSenderAlreadyInPool() would have already pushed a very similar
error message.
Closes https://github.com/ArkEcosystem/core/issues/3322
> chore: document canEnterTransactionPool()

- packages/core-api/src/handlers/blocks/schema.ts
- packages/core-api/src/handlers/bridgechains/schema.ts
- packages/core-api/src/handlers/businesses/schema.ts
- packages/core-api/src/handlers/delegates/schema.ts
- packages/core-api/src/handlers/locks/schema.ts
- packages/core-api/src/handlers/shared/schemas/address.ts
- packages/core-api/src/handlers/shared/schemas/generic-name.ts
- packages/core-api/src/handlers/shared/schemas/index.ts
- packages/core-api/src/handlers/shared/schemas/public-key.ts
- packages/core-api/src/handlers/transactions/schema.ts
- packages/core-api/src/handlers/votes/schema.ts
- packages/core-api/src/handlers/wallets/schema.ts
- packages/crypto/src/validation/schemas.ts
Fixes the validation of the name param on the businesses and bridgechains search endpoints.
This PR also:
- adjusts the `genericName` to allow dashes surrounded by spaces (` - `) between words, to allow names such as `ARK - Just Forge It`
- replaces the `schemaIdentifier` schema on the delegate endpoints with the stricter shared `walletId` schema
- adds `address` to the businesses and bridgechains search schema (#3312)
- adds shared schemas for `address` and `publicKey` which are used almost everywhere
- fixes a bug in the `blocks/{id}/transactions` endpoint where the transaction id param is required to be 66 characters long
> fix(core-api): businesses/bridgechains search by name

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/src/socket-server/worker.ts
Improve incoming WS message check by discarding too small messages (no need to even try to JSON parse those).
IP banning on worker for errors at WS level (no need to call master, we shut down socket and ban the IP for 1 minute).
Use `prependListener` for our WS message listeners so that our listeners are called before SC ones.
> feat(core-p2p): improve incoming WS message check + IP banning on worker

- packages/core-database/src/database-service.ts
When resetting this.blocksInCurrentRound to an empty array assign [] to
it which also works if it is undefined.
Fixes https://github.com/ArkEcosystem/core/issues/3329
> fix(core-database): don't assume blocksInCurrentRound is defined

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/src/utils/build-rate-limiter.ts
This allows two blocks to be sent/received shortly one after another, in
case we have late blocks.
Will maybe fix https://github.com/ArkEcosystem/core/issues/3349
> core-p2p: relax postBlock rate limit

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/network-monitor.ts
A fork recovery's success depends on the number of available peers, so we should ensure enough peers are available.
> refactor(core-p2p): discover peers when checking network health

- __tests__/helpers/transaction-factory.ts
- __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- packages/core-database/src/database-service.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/core-transactions/src/handlers/htlc-lock.ts
- packages/core-transactions/src/handlers/htlc-refund.ts
- packages/core/bin/config/devnet/peers.json
- packages/crypto/src/networks/devnet/milestones.json
- packages/crypto/src/networks/testnet/milestones.json
- packages/crypto/src/networks/unitnet/milestones.json
- packages/crypto/src/transactions/types/htlc-claim.ts
- packages/crypto/src/transactions/types/htlc-lock.ts
- packages/crypto/src/transactions/types/htlc-refund.ts
Introduces a new milestone `htlcEnabled` to en-/disable HTLC transaction types independently of the other transaction types.
It is mostly duplicating the existing `aip11` milestone, which will be cleaned up properly in V3.
> refactor: enable htlc types via dedicated milestone

- packages/core-blockchain/src/blockchain.ts
- packages/core-state/src/stores/state.ts
Currently, Core only detects forks and eventually attempts to rollback when `checkNetworkHealth` is called after consecutively failing to download blocks. However, this does not work so reliable when there are not enough missed blocks (e.g network split evenly) which constantly causes the `noBlockCounter` to reset.
So now we also listen to missed blocks events and call `checkNetworkHealth` when the number of missed blocks in a round is > 51/3. This should prevent situations where nodes aren't aware of other forks and therefore never attempt a fork recovery.
> refactor: call `checkNetworkHealth` more deterministically

- __tests__/unit/crypto/blocks/factory.test.ts
- packages/core-database/src/database-service.ts
Resolves #3370 
Allowing legacy transactions in getBlocksForRound, disabling checks with deserializeTransactionsUnchecked as we get the transactions from our own database. (that was previously verified)
> fix(core-database): allow legacy transaction in getBlocksForRound

- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-claim/3.create-claim-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/htlc-refund/1.create-lock-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/4.create-lock-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/5.create-claim-multisig-txs.action.js
- __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/4.create-lock-multisig-txs.action.js
- __tests__/functional/transaction-forging/htlc-claim.test.ts
- __tests__/integration/core-tester-cli/commands/send/htlc-claim.test.ts
- __tests__/integration/core-tester-cli/commands/send/htlc-lock.test.ts
- __tests__/integration/core-transactions/handlers/htlc-claim.test.ts
- __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
- __tests__/unit/core-transactions/handler.test.ts
- __tests__/unit/crypto/transactions/builders/transactions/htlc-claim.test.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- __tests__/unit/crypto/transactions/schemas.test.ts
- packages/core-tester-cli/src/commands/send/htlc-claim.ts
- packages/core-tester-cli/src/commands/send/htlc-lock.ts
- packages/core-tester-cli/src/shared/htlc-secret.ts
- packages/core-transactions/src/handlers/htlc-claim.ts
- packages/crypto/src/transactions/types/htlc-claim.ts
- packages/crypto/src/transactions/types/schemas.ts
Previously the HTLC unlock secret (preimage) would be required to be 32
printable ASCII characters.
Fix this so that it can be any 32 bytes. To accommodate this we print it
in hex (64 chars) in the HTLC claim transaction JSON.
> fix(core-transactions): HTLC unlock secret format

- __tests__/unit/crypto/utils/is-valid-peer.test.ts
- packages/crypto/src/utils/is-valid-peer.ts
- packages/crypto/src/validation/formats.ts
The schema used to validate seednodes uses `isValidPeer` which in addition to checking for localhost will refuse any ip that comes `os.networkInterfaces()`. But in this case the additional network interface restriction is not desired and therefore lifted.
> fix: relax network interface check for seednode ips

- packages/core-p2p/src/socket-server/worker.ts
Remove banning when peer opens multiple sockets.
> fix(core-p2p): remove banning when peer opens multiple sockets

- __tests__/integration/core-api/handlers/transactions.test.ts
- __tests__/integration/core-p2p/mocks/core-container.ts
- __tests__/integration/core-p2p/socket-server/peer-with-remote-access.test.ts
- __tests__/integration/core-p2p/socket-server/peer.test.ts
- __tests__/unit/core-blockchain/blockchain.test.ts
- __tests__/unit/core-blockchain/mocks/p2p/network-monitor.ts
- __tests__/unit/core-p2p/mocks/request.ts
- __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rate-limiter.test.ts
- __tests__/unit/core-p2p/socket-server/worker.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-interfaces/src/core-blockchain/blockchain.ts
- packages/core-interfaces/src/core-p2p/network-monitor.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/rate-limiter.ts
- packages/core-p2p/src/socket-server/errors.ts
- packages/core-p2p/src/socket-server/utils/validate.ts
- packages/core-p2p/src/socket-server/versions/internal.ts
- packages/core-p2p/src/socket-server/versions/peer.ts
- packages/core-p2p/src/socket-server/versions/utils.ts
- packages/core-p2p/src/socket-server/worker.ts
- packages/crypto/src/networks/unitnet/milestones.json
-   Discard blocks containing too many transactions
-   Disconnect when multiple sockets are opened from same IP
-   Handle invalid WS opcodes
-   Disconnect for p2p SocketCluster events that do not have a handler
-   Handle payload with additional properties
-   Use shared rate limiter for defined endpoints only
-   call `checkNetworkHealth` less deterministically
> fix(core-p2p): handle p2p edge cases

- __tests__/integration/core-blockchain/blockchain.test.ts
- __tests__/integration/core-transaction-pool/processor.test.ts
- __tests__/integration/core-transaction-pool/wallet-manager.test.ts
- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/replay/replay-blockchain.ts
- packages/core-interfaces/src/core-blockchain/blockchain.ts
Pass IBlockData to processBlocks instead of IBlock, to only create instance of IBlock when actually processing the block : this fixes an issue when reaching a new milestone in the middle of the downloaded blocks, as creating instance of IBlock verifies the transactions within it according to the current milestone.
> fix(core-blockchain): pass IBlockData to processBlocks instead of IBlock

- packages/core-database-postgres/src/repositories/transactions.ts
Query by type to use type index when querying multipayments to improve performance.
> perf(core-database-postgres): use type index when querying multipayments

- __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
- __tests__/integration/core-tester-cli/commands/send/fixtures.ts
- __tests__/integration/core-tester-cli/commands/send/htlc-claim.test.ts
- __tests__/integration/core-tester-cli/commands/send/htlc-lock.test.ts
- __tests__/integration/core-tester-cli/commands/send/htlc-refund.test.ts
- __tests__/integration/core-tester-cli/commands/send/ipfs.test.ts
- __tests__/integration/core-tester-cli/commands/send/multi-payment.test.ts
- __tests__/integration/core-tester-cli/commands/send/multi-signature-registration.test.ts
- __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts
- __tests__/integration/core-tester-cli/commands/send/transfer.test.ts
- __tests__/integration/core-tester-cli/commands/send/vote.test.ts
- packages/core-tester-cli/src/commands/command.ts
For core-tester-cli, set the network height on configManager in order to have it correctly configured (milestones depend on height).
> fix(core-tester-cli): set network height on configManager

- __tests__/integration/core-api/handlers/wallets.test.ts
- packages/core-api/src/handlers/wallets/transformer.ts
> refactor(core-api): re-enable username and 2nd public key as top api attributes

- packages/core-transactions/src/handlers/delegate-registration.ts
Fix "genesis wallet" case that was correctly handled for `forgedBlocks` but not for `lastForgedBlocks`.
> fix(core-transactions): apply genesis wallet exception to lastForgedBlocks

- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-transactions/src/handlers/handler-registry.ts
- packages/core-transactions/src/service-provider.ts
Added symbol for TransactionHandlerProvider to provide support for test core-transactions package.
> refactor(core-kernel): add symbol for TransactionHandlerProvider

- __tests__/integration/core-api/handlers/peers.test.ts
- packages/core-api/src/handlers/peers/controller.ts
Changes the peers API endpoint so that it can also accept a version range for retrieval of multiple versions at once.
> feat(core-api): filter peers by version range

- packages/core-snapshots/src/manager.ts
- packages/core/src/commands/snapshot/rollback.ts
This PR adds an additional flag (`--export` / `--no-export`) to the `snapshot:rollback` command which allows to skip the export of rolled back transactions.
> feat(core): add flag to skip export of rolled back transactions

- __tests__/integration/core-transactions/handlers/multi-signature.test.ts
- packages/core-transactions/src/handlers/multi-signature.ts
Set the public key on the wallet when applying multisignature registration transaction. Before using findByAddress, it would only set the address, now using findByPublicKey it sets both address and public key.
> refactor(core-transactions): use findByPublicKey to set both publickey and address on the multisig wallet

- __tests__/unit/crypto/transactions/schemas.test.ts
- packages/crypto/src/transactions/registry.ts
- packages/crypto/src/transactions/types/schemas.ts
Resolves #3444 by allowing in json schema validation legacy multisig to have the "signatures" property (which is handled fine by core then).
> fix(crypto): multisig legacy allow signatures property

- packages/core-database/src/database-service.ts
Fixes #3491 by detecting missed blocks before applying the round, since applying the round will repopulate `forgingDelegates` with the order of the new round, but we need to check against the current (old) round to detect the correct delegate if the last delegate in a round misses its block. Otherwise it incorrectly fires for a different delegate in the new round.
> fix(core-database): check for missed blocks before applying round

- __tests__/unit/core-transaction-pool/connection.forging.test.ts
- __tests__/unit/core-transactions/handler-registry.test.ts
- __tests__/unit/crypto/transactions/deserializer.test.ts
- packages/crypto/package.json
- packages/crypto/src/blocks/serializer.ts
- packages/crypto/src/transactions/serializer.ts
- packages/crypto/src/transactions/types/htlc-lock.ts
- packages/crypto/src/transactions/types/multi-payment.ts
- packages/crypto/src/transactions/types/transfer.ts
The `long@3` dependency can cause problems if people also have `long@4` installed because node.js will think it should use `long@4` even though we don't have it as a dependency. This will cause the `value instanceof Long` check in the `bytebuffer` dependency to fail because its own dependency is `long@3` but node.js will force it to use `long@4` if it is installed, which will throw an exception because the instance signatures will differ.
The `bytebuffer` types have been removed because they don't reflect their JavaScript code. The types state that you can only pass in a `number` or `Long` but their code will actually perform assertions and use `Long` internally to create an instance. This means that whatever long version is installed will be used.
```js
ByteBufferPrototype.writeUint64 = …
```
> refactor(crypto): remove long dependency

- packages/core/bin/config/testnet/app.js
- packages/core/src/utils.ts
Adds the `app.js` file to testnet and fixes the wrongly behaviour that the `app.js` file is required to be published. It was intended to be optional and fallback to the default `app.js` that core ships if it doesn't exist in the published configuration folder.
Can be tested with `yarn global add @arkecosystem/core@2.6.0-alpha.1`.
> fix(core): make app.js optional as initially intended

- packages/core-p2p/src/peer-connector.ts
- packages/core-p2p/src/socket-server/index.ts
There is memory leak in `core-p2p` which also leads to workers not responding after a while. This is caused by enabling `permessage-deflate` (PMD) in the websockets. PMD was introduced in 2.5 but the problem only became apparent in 2.6 because PMD uses heuristics to determine whether to compress the data or send it uncompressed, for example, small packets are not compressed because the overhead would not be worth it. AIP11 introduced things like multipayments, which result in larger transaction payloads, triggering PMD compression whereas the smaller transaction payloads in Core 2.5 were below the threshold for PMD compression. This is why the problem only became apparent in 2.6 and also likely explains why 2.6 uses more CPU cycles as PMD is happening much more often, which requires more …
> fix(core-p2p): disable permessage-deflate

- install.sh
- packages/core/bin/run
This PR replaces the native memory allocator with jemalloc in Core to reduce memory fragmentation and results in a smaller memory footprint as confirmed by multiple Core nodes using the native memory allocator (glibc) vs jemalloc, where in all cases the jemalloc nodes consistently used less RAM. Furthermore, results from a sync from 0 test (using the same hardware with 2GB physical RAM to eliminate variability due to different specifications) demonstrate that jemalloc is more performant and uses far less memory by the end:
native memory allocator (glibc): Completed in 14h 54m 14s using 1.3GB RAM 30 minutes after completion.
jemalloc: Completed in 13h 37m 56s using 314.5MB RAM 30 minutes after completion.
Therefore a sync from 0 using jemalloc completed 1h 16m 18s faster than glibc on the …
> perf(core): use jemalloc as the memory allocator

- packages/core-blockchain/src/replay/replay-blockchain.ts
Resolves #3554 
Set height=1 on config manager for processing genesis block + initialize memoryDatabase activeDelegates with restoreCurrentRound.
> fix(core-blockchain): set height 1 on config manager for processing genesis block (blockchain replay)

- packages/core/bin/run
This handles an edge case if there are multiple installations of jemalloc (e.g. a system-wide installation via a package manager in `/usr/lib` and also another version built from source in `/usr/local/lib`).
Previously it would fail because the `jemallocPath` would contain a concatenation of both installation paths separated by a newline. Now we just take the first path that we find.
> fix(core): handle multiple installations of jemalloc

- packages/core/bin/run
@geopsllc reported that Core couldn't find libjemalloc on Ubuntu 16.04.
I reproduced this and it seems `whereis` in Ubuntu 16.04 doesn't traverse `/usr/lib/{architecture}/` to find binaries, whereas 18.04's version does. Since the package manager installs libjemalloc to that directory, Core doesn't find it on 16.04 even when it is properly installed.
Replaced `whereis` with output from `gcc --print-search-dirs` which now also works on 16.04 as well as the others (since `gcc` is always installed as part of the Core installation).
> fix(core): jemalloc compatibility for ubuntu 16.04

- packages/core-container/package.json
- packages/core-container/src/container.ts
- packages/core-event-emitter/src/index.ts
- packages/core-p2p/src/peer-processor.ts
- packages/core-snapshots/package.json
- packages/core-snapshots/src/transport/index.ts
- packages/core-state/package.json
- packages/core-state/src/stores/state.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transactions/src/handlers/vote.ts
- packages/core/src/commands/snapshot/restore.ts
> refactor: use application events from core-event-emitter

- .github/workflows/publish-master.yml
Commands are hardcoded because they are published in a specific order.
> ci: setup auto publishing for master releases

- packages/core-kernel/src/utils/expiration-calculator.ts
- packages/core-utils/src/lock-expiration-calculator.ts
Must've slipped in during the merge of 2.6
> chore: remove core-utils package

- __tests__/unit/core-logger-pino/service-provider.test.ts
- __tests__/unit/core-transactions/service-provider.test.ts
- jest.config.js
- packages/core-logger-pino/src/driver.ts
Resolves https://github.com/ArkEcosystem/core/issues/3475
> test(core-logger-pino): increase coverage to 100%

- __tests__/integration/core-transaction-pool/processor.test.ts
- packages/core-transaction-pool/src/connection.ts
Currently, when a node syncs from genesis, not all transactions are applied to the relevant sender wallets in the transaction pool's `acceptChainedBlock`.
This causes issues where the pool wallet state becomes inconsistent with the database wallet state.
By guaranteeing that the sender wallet is always set, the transactions are always properly applied to the relevant wallets on `acceptChainedBlock`, and the state & db wallets remain in sync.
> fix(core-transaction-pool): always apply to sender wallet on acceptChainedBlock

- __tests__/integration/core-p2p/socket-server/peer.test.ts
- packages/core-p2p/src/socket-server/worker.ts
> fix(core-p2p): block incomplete sockets

- packages/core-blockchain/src/blockchain.ts
Reset missedBlocks before await call in checkMissingBlocks.
Reason for that is the await call takes a bit of time, during which checkMissingBlocks can be called various times. If missedBlocks is not reset before it, we can end up calling this await checkNetworkHealth() a lot of times for nothing.
> refactor(core-blockchain): reset missedBlocks before await call

- __tests__/unit/core-forger/delegate-tracker.test.ts
- __tests__/unit/core-forger/setup.ts
- packages/core-forger/src/delegate-tracker.ts
Log a warning in the `DelegateTracker`'s `handle` method when the number of active delegates is below the required delegate count.
Without the total number of required delegates we are not able to accurately compute the next forgers.
> fix(core-forger): log warning when active delegates are under the required delegate count

- packages/core-test-framework/src/factories/factories/wallet.ts
What changes are being made?
Changed 
` import { Services } from "@packages/core-kernel";`
to
`import { Services } from "@arkecosystem/core-kernel";`
Why are these changes necessary?
When writing tests for custom-transaction in plugins folder I received the following error:
```bash
● Test suite failed to run
Cannot find module '@packages/core-kernel' from 'wallet.ts'
```
> fix(core-test-framework): change import scope from @package to @arkecosystem

- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/machines/blockchain.ts
Allow transition to fork from idle state, as the ForgerMissing event can be triggered while being idle.
Also implement a 10min delay between each potential checkNetworkHealth as when downloading blocks we can trigger a lot of ForgerMissing events.
> fix(core-blockchain): allow transition to fork from idle

- README.md
Current 'Build Status' badge is still using CircleCI, it expectedly fails to load.
This change uses the current build status of 'master'.
> chore(readme): fix build status badge

- packages/core-api/package.json
- packages/core-database-postgres/package.json
- packages/core-database/package.json
- packages/core-jest-matchers/package.json
- packages/crypto/package.json
- yarn.lock
A missing dependency in an older release of `@arkecosystem/utils` causes issues when used with `yarn berry`.
```
@arkecosystem/utils tried to access deepmerge, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: deepmerge (via "deepmerge")
Required by: @arkecosystem/utils@npm:0.8.3 (via /Users/brian/Code/platform-sdk/.yarn/cache/@arkecosystem-utils-npm-0.8.3-595b56811a-2.zip/node_modules/@arkecosystem/utils/dist/)
```
> chore: update @arkecosystem/utils dependency

- __tests__/unit/core-utils/tree.test.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transaction-pool/src/memory.ts
- packages/core-utils/src/index.ts
- packages/core-utils/src/tree.ts
Plus other perf improvements.
Now inserting txs is slower (expect around 10k per second, still okay).
But fetching is way faster, which is important when getting transactions for forging, considering default tx pool limit is 100k.
> perf(core-transaction-pool): use tree memory structure to sort by fee and by sender nonce

- __tests__/functional/transaction-forging/htlc-lock.test.ts
- packages/core-jest-matchers/src/functional/index.ts
- packages/core-jest-matchers/src/functional/vote-balance.ts
- packages/core-state/src/wallets/wallet-manager.ts
When updating the vote balance on a vote/unvote transaction, we were not taking the potential sender locked balance.
This fixes it.
> fix(core-state): update vote balance with htlc locked balance on vote transactions

- __tests__/unit/core-transaction-pool/connection.test.ts
- __tests__/unit/core-transaction-pool/memory.test.ts
- __tests__/unit/core-utils/sorted-array.test.ts
- __tests__/unit/core-utils/tree.test.ts
- packages/core-transaction-pool/src/connection.ts
- packages/core-transaction-pool/src/defaults.ts
- packages/core-transaction-pool/src/memory.ts
- packages/core-utils/src/index.ts
- packages/core-utils/src/sorted-array.ts
- packages/core-utils/src/tree.ts
Use sorted array instead of tree for storing transaction by fee and nonce, because tree has some issues like with recursion and max call stack. Sorted array is simpler and does the job for a lower max size of the transaction pool (now reduced to 15k transactions by default instead of 100k).
(tree memory structure is still available in core-utils and might be improved and used in the future : needs re-balancing while inserting to be usable)
> fix(core-transaction-pool): use sorted array (instead of tree) for storing transactions by fee and nonce

- __tests__/unit/core-manager/actions/info-core-status.test.ts
- __tests__/unit/core-manager/utils/__mocks__/axios.ts
- __tests__/unit/core-manager/utils/http-client.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/info-core-status.ts
- packages/core-manager/src/ioc/identifiers.ts
- packages/core-manager/src/service-provider.ts
- packages/core-manager/src/utils/http-client.ts
- packages/core-manager/src/utils/index.ts
- yarn.lock
This PR add new action for getting current application process status and syncing status if available.
---
**Name:** info.coreStatus
**Params:**
|-|-|-|
|token|String|(Optional). Name of the token. Used for getting process by token name|
**Response:**
|-|-|-|
|processStatus|String|Proces status|
|syncing|Boolean|(Optional) Is node in syncing mode? Returned only if running node returned successful response.|
**Possible process statuses:**
- undefined
- online
- stopped
- stopping
- waiting restart
- launching
- errored
- one-launch-status
> feat(core-manager): implement `info.coreStatus` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/info-database-size.test.ts
- __tests__/unit/core-manager/actions/info-disk-space.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/info-database-size.ts
- packages/core-manager/src/defaults.ts
This PR add new action for getting database space using pg_database_size SQL method. 
**Name:** info.databaseSize
**Response:**
|-|-|-|
|size|Number|Size of the database in KB.|
> feat(core-manager): implement `info.databaseSize` action

- __tests__/unit/core-manager/actions/process-restart.test.ts
- packages/core-manager/src/actions/process-restart.ts
This PR add new action which restarts named pm2 process. 
**Name:** process.restart
**Params:**
|-|-|-|
|name|String|Pm2 process name.|
**Response:**
|-|-|-|
|name|String|Pm2 process name.|
|status|String|Process status.|
**Possible process statuses:**
- undefined
- online
- stopped
- stopping
- waiting restart
- launching
- errored
- one-launch-status
> feat(core-manager): implement `process.restart` action 

- __tests__/unit/core-manager/actions/process-start.test.ts
- packages/core-manager/src/actions/process-start.ts
This PR add new action which starts named process via CLI command with passed arguments.
**Name:** process.start
**Params:**
|-|-|-|
|name|String|Cli command name without :start. Examples: core, forger, manager, relay|
|args|String|Additional command arguments: Example: --network=devnet --token=dark|
**Response:** none
> feat(core-manager): implement `process.start` action

- __tests__/unit/core-manager/actions/process.stop.test.ts
- packages/core-manager/src/actions/process.stop.ts
This PR add new action which stop the named process and return stopped process status.
**Name:** process.stop
**Params:**
|-|-|-|
|name|String|Process name.|
**Response:**
|-|-|-|
|name|String|Process name.|
|status|String|Process status.|
> feat(core-manager): implement `process.stop` action 

- __tests__/unit/core-manager/actions/info-core-status.test.ts
- __tests__/unit/core-manager/actions/process-list.test.ts
- __tests__/unit/core/commands/manager-start.test.ts
- __tests__/unit/core/commands/manager-stop.test.ts
- packages/core-manager/src/actions/process-list.ts
- packages/core/src/commands/manager-start.ts
- packages/core/src/commands/manager-stop.ts
This PR add new action which returns list of all pm2 processes. PR also implements additional CLI commands:
- manager:start
- manager:stop
**Name:** process.list
**Response:**: Array of process informations.
|-|-|-|
|pid|Number|Process ID.|
|name|String|Process name.|
|pm_id|Number|PM2 process id.|
|status|String|Process status.|
|monit.memory|Number|Process memory consumption in KB|
|monit.cpu|Number|Process cpu consumption in percent.|
**Possible process statuses:**
- undefined
- online
- stopped
- stopping
- waiting restart
- launching
- errored
- one-launch-status
> feat(core-manager): implement `process.list` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/configuration-env-get.test.ts
- packages/core-manager/src/actions/configuration-env-get.ts
This PR add new action which returns content of the .env file for current network (selected on core-manager start).
**Name:** configuration.getEnv
**Params:**: none
**Response:** .env file content
> feat(core-manager): implement `configuration.getEnv` action 

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/configuration-get-plugins.test.ts
- packages/core-manager/src/actions/configuration-get-plugins.ts
`
This PR add new action which returns content of the plugins.js file for current network (selected on core-manager start).
**Name:** configuration.getPlugins
**Params:**: none
**Response:** plugins.js file content
> feat(core-manager): implement `configuration.getPlugins` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/configuration-update-env.test.ts
- packages/core-manager/src/actions/configuration-update-env.ts
This PR add new action which validate and save .env file for current network (selected on core-manager start) if validation pass.
**Name:** configuration.updateEnv
**Params:**: 
|-|-|-|
|content|String|.env file content.|
**Response:** Empty if action executed without errors.
> feat(core-manager): implement `configuration.updateEnv` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/configuration-update-plugins.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/configuration-update-plugins.ts
This PR add new action which validate and save plugins.js file for current network (selected on core-manager start) if validation pass.
**Name:** configuration.updatePlugins
**Params:**: 
|-|-|-|
|content|String|plugins.js file content.|
**Response:** Empty if action executed without errors.
> feat(core-manager): implement `configuration.updatePlugins` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/log-archived.test.ts
- __tests__/unit/core-manager/server/routes/log-achived.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/actions/log-archived.ts
- packages/core-manager/src/server/controllers/log-archived.ts
- packages/core-manager/src/server/handlers.ts
- packages/core-manager/src/server/routes/log-archived.ts
- packages/core-manager/src/server/server.ts
- packages/core-manager/src/service-provider.ts
This PR add new action which return list of available logs with size and download link. PR also implements new server route for downloading log files.
**Name:** log.archived
**Params:**: none
**Response:** List of log infos
|-|-|-|
|name|String|Log file name.|
|size|Number|Log file size.|
|downloadLink|String|Link for downloading log.|
> feat(core-manager): implement `log.archived` action

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/log-log.test.ts
- packages/core-manager/src/actions/log-log.ts
This PR add new action which return total count of log file lines and return those lines in selected range. 
**Name:** log.log
**Params:**
|-|-|-|
|name|String|Process name. Example: "ark-core", "ark-forger".|
|fromLine|Number|(Optional; Default: 1) Starting line of returned range.|
|range|Number|(Optional; Default: 100) Range size.|
|showError|Boolean|(Optional; Default: false) Show logs from error file.|
**Response:**
|-|-|-|
|totalLines|Number|Number of lines in log file.|
|lines|String|Content of the file within given range.|
> feat(core-manager): implement `log.log` action 

- packages/core-kernel/src/contracts/snapshot/snapshot-service.ts
- packages/core-snapshots/src/contracts/options.ts
- packages/core-snapshots/src/snapshot-service.ts
- packages/core/src/commands/snapshot-dump.ts
- packages/core/src/commands/snapshot-restore.ts
- packages/core/src/commands/snapshot-verify.ts
This PR changes core-snapshost snapshot interface and include strict type definitions instead any type.
> refactor(core-snapshot) improve snapshotService interface

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/snapshots-create.test.ts
- __tests__/unit/core-manager/snapshots/snapshot-manager.test.ts
- packages/core-manager/src/actions/snapshots-create.ts
- packages/core-manager/src/ioc/identifiers.ts
- packages/core-manager/src/service-provider.ts
- packages/core-manager/src/snapshots/snapshots-manager.ts
- packages/core/bin/config/devnet/app.json
- packages/core/bin/config/mainnet/app.json
- packages/core/bin/config/testnet/app.json
This PR add new action which creates snapshot with given parameters. PR also implements snapshot-manager which prevents snapshot action to run in parallel and can be later extended to keep record of the process status (eg: percentage of restored blocks). 
**Name:** snapshots.create
**Params:** 
|-|-|-|
|codec|String|(Optional; Default: default) Codec name eg: default, json|
|skipCompression|Boolean|(Optional: Default: false) Skip zlib snapshot compression?|
|start|Number|(Optional) Number of first block included in snaphsot * |
|start|Number|(Optional) Number of last block included in snaphsot * |
**Response:**: Empty response if snapshot process is started successfully. It doesn't guarantee that snapshot process completed successfully. 
(*) Block height is later …
> feat(core-manager): implement `snapshots.create` action 

- __tests__/unit/core-manager/actions/snapshots-delete.test.ts
- packages/core-manager/src/actions/snaphsots-delete.ts
- packages/core/src/commands/core-run.ts
This PR add new action which delete snapshot folder with given name.
**Name:** snapshots.delete
**Params:** 
|-|-|-|
|name|String|Snapshot name.|
**Response:**: Empty response if action is completed successfully.
> feat(core-manager): implement `snapshots.delete` action 

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/snapshots-list.test.ts
- packages/core-manager/src/actions/snapshots-list.ts
This PR add new action which returns list of all snapshots.
**Name:** snapshots.list
**Response:**: Array of snapshot information.
|-|-|-|
|name|String|Snapshot name.|
|size|Number|Snapshot size in KB.|
> feat(core-manager): implement `snapshots.list` action

- __tests__/unit/core-cli/services/process-manager.test.ts
- packages/core-cli/src/services/process-manager.ts
This PR adds support for triggering pm2 trigger actions from ProcessManager. Functionality is added to trigger Process Actions directly from core via shell.
> feat(core-cli): implement trigger method in ProcessManager

- __tests__/unit/core-forger/forger-service.test.ts
- __tests__/unit/core-forger/process-actions/last-forged-block.test.ts
- packages/core-forger/src/forger-service.ts
- packages/core-forger/src/process-actions/index.ts
- packages/core-forger/src/process-actions/last-forged-block.ts
- packages/core-forger/src/service-provider.ts
This PR implements new `forger.lastForgedBlock` process action in core-forger package. Action returns last forged block, forged by local forger.
**Name:** forger.lastForgedBlock
**Description:** Returns last block created from local forger.
**Params:** None
**Result:** Last forged block.
> feat(core-forger): implements `forger.lastForgedBlock` process actions 

- __tests__/unit/core-manager/actions/snapshots-restore.test.ts
- __tests__/unit/core-manager/snapshots/snapshot-manager.test.ts
- packages/core-manager/src/actions/snapshots-restore.ts
- packages/core-manager/src/snapshots/snapshots-manager.ts
This PR add new action which restores snapshot with given parameters. Action returns error if snapshot cannot be found. 
**Name:** snapshots.restore
**Params:** 
|-|-|-|
|name|String|Snapshot name.|
|truncate|Boolean|(Optional; Default: false) Truncate database before restore?|
|verify|Booelan|(Optional; Deafault: false) Verify data during restore. |
**Response:**: Empty response if snapshot process is started successfully. It doesn't guarantee that snapshot process completed successfully.
> feat(core-manager): implement `snapshots.restore` action 

- install.sh
- Added jemalloc library.
- RedHat derivatives installs update:
- Added missing flag to `yum clean`.
- Switched NTP to Chrony (due to CentOS 8 `ntpd` deprecation).
- Additional record to `pg_hba.conf` (thanks to @rainydio).
> chore: CentOS install fixes

- __tests__/unit/core-transaction-pool/dynamic-fee-matcher.test.ts
- __tests__/unit/core-transaction-pool/processor.test.ts
- packages/core-kernel/src/contracts/transaction-pool/dynamic-fee-matcher.ts
- packages/core-transaction-pool/src/dynamic-fee-matcher.ts
- packages/core-transaction-pool/src/errors.ts
- packages/core-transaction-pool/src/processor.ts
This PR fixes #3712 bug. Additional fee checks are added and DynamicFeeMatcher is now reponsible for throwing error if fee is too high or too low.
> fix(core-transaction-pool): throw ERR_HIGH_FEE when fee is too high

- __tests__/unit/core-manager/__fixtures__/index.ts
- __tests__/unit/core-manager/__fixtures__/trigger-responses.ts
- __tests__/unit/core-manager/actions/info-current-delegate.test.ts
- __tests__/unit/core-manager/utils/process-actions.test.ts
- packages/core-manager/src/actions/info-current-delegate.ts
- packages/core-manager/src/utils/index.ts
- packages/core-manager/src/utils/process-actions.ts
This PR add new action which return current delegate username and rank if forger process is running. 
**Name:** info.currentDelegate
**Response:** 
|-|-|-|
|username|String|Delegate username.|
|rank|Number|Delegate rank.|
> feat(core-manager): implement `info.currentDelegate` action

- __tests__/unit/core-forger/forger-service.test.ts
- __tests__/unit/core-forger/process-actions/next-slot.test.ts
- packages/core-forger/src/forger-service.ts
- packages/core-forger/src/process-actions/index.ts
- packages/core-forger/src/process-actions/next-slot.ts
- packages/core-forger/src/service-provider.ts
This PR implements new forger.nextSlot process action in core-forger package. Action returns time till next slot.
**Name:** forger.nextSlot
**Description:** Returns remaining time till next slot in ms. 
**Params:** None
**Result:**
|Field|Type|Description|
|-|-|-|
|remainingTime|Number|Remaining time in ms.|
> feat(core-forger): implements `forger.nextSlot` process actions

- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-p2p/src/socket-server/worker.ts
Discard late forged blocks from forger (same check that is done already in forger) as late blocks won't be accepted by other peers.
Also added : 1ms delay on p2p processing to help handle loads.
> fix(core-p2p): discard late-forged blocks from forger

- __tests__/unit/core-manager/__fixtures__/trigger-responses.ts
- __tests__/unit/core-manager/actions/info-next-forging-slot.test.ts
- packages/core-manager/src/actions/info-next-forging-slot.ts
This PR add new action which return time till the next forging slot if forger process is running.
**Name:** info.nextForgingSlot
**Response:**
|-|-|-|
|remainingTime|Number|Time till next forging slot in ms.|
> feat(core-manager): implement `info.nextForgingSlot` action

- install.sh
Following on from #3738 I wanted to use Fedora rather than CentOS so I made the required changes to the installer script to make it compatible with both RHEL/CentOS and Fedora. It was a lot less work than anticipated, just adding `--skip-broken` so it only installs `epel-release` if it's available and won't abort the installation if it's not (since it's required for RHEL/CentOS, thus will be installed, but is not present in Fedora since it is not necessary for that distro).
I confirmed that this makes Core installable and runnable on the latest Fedora and also continues to work fine on the latest CentOS.
If you only want to support RHEL/CentOS as far as RedHat distributions go then fair enough, feel free to close unmerged, but since I already wanted to fix it for myself so I could use my …
> chore: support fedora

- __tests__/unit/core-transaction-pool/sender-state.test.ts
- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-transaction-pool/src/sender-state.ts
- packages/core-transaction-pool/src/service.ts
PR included additional transaction-pool events, required by  #3753:
> feat(core-transaction-pool): disaptch additional transaction-pool events

- packages/core-database/src/repositories/block-repository.ts
Last block height was incorrectly used to calculate last round. Now target height (that is last height after deletion) is used to calculate target round. Every round after it is removed.
> fix(core-database): round deletion when deleting blocks

- __tests__/functional/core-database/repositories/block-repository.test.ts
- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-database/src/repositories/block-repository.ts
`Blockchain.removeTopBlocks` now calls `BlockRepository.deleteTopBlocks` instead of loading them first through `DatabaseService.getTopBlocks` and then deleting through `BlockRepository.deleteBlocks`.
Note that previously `Blockchain.removeTopBlocks` was eating error, only logging it instead of re-throwing.
There are two use-cases when blocks have to be deleted:
1. During rollback top 1000 blocks (up to 10000) are removed.
Improved by this PR.
1. When reverting, reverted blocks are deleted at the end.
I plan to refactor revertion to use new `BlockRepository.delgetTopBlock` that pops single block from database rendering `BlockRepository.deleteBlocks` obsolete.
> fix(core-database): straight delete blocks during rollback

- __tests__/unit/core-webhooks/listener.test.ts
- packages/core-webhooks/src/events.ts
- packages/core-webhooks/src/listener.ts
This PR adds functionality into webhook listener, that will emit webhook event every time event has been broasted. PR is part of: #3753.
Included data are:
- executionTime
- webhook
- payload
- error (if present)
> feat(core-webhooks): dispatch webhook events

- packages/core-transaction-pool/src/service.ts
Introduced new environment variable `CORE_RESET_POOL` which only resets pool. Unlike `CORE_RESET_DATABASE` that resets both main and pool databases.
> fix(core-transaction-pool): introduce CORE_RESET_POOL env variable

- packages/core-api/src/routes/blocks.ts
- packages/core-api/src/routes/transactions.ts
- packages/core-api/src/routes/votes.ts
- packages/core-api/src/routes/wallets.ts
- packages/core-api/src/schemas.ts
Order transactions and blocks in reverse chronological order by default.
> fix(core-api): set default orderBy value

- __tests__/unit/core-kernel/services/schedule/block-job.test.ts
- __tests__/unit/core-kernel/services/schedule/cron-job.test.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-kernel/src/services/schedule/block-job.ts
- packages/core-kernel/src/services/schedule/cron-job.ts
This PR adds functionality into scheduler, that will emit execution time on every successful cron or block job.
> feat(core-kernel): dispatch schedule events

- __tests__/unit/core-transaction-pool/service.test.ts
- __tests__/unit/core-transaction-pool/storage.test.ts
- packages/core-kernel/src/contracts/transaction-pool/storage.ts
- packages/core-transaction-pool/src/service.ts
- packages/core-transaction-pool/src/storage.ts
When milestone changes previously valid transactions may become invalid, so they have to be deserialized and re-added into pool again.
> fix(core-transaction-pool): re-add transactions to pool when milestone changes

- packages/core-state/src/stores/state.ts
> refactor(core-state): log milestone change

- __tests__/functional/transaction-forging/entity-register.test.ts
- packages/core-transaction-pool/src/service.ts
Better readd logging printing only relevant information.
> refactor:(core-transaction-pool): better readd log

- packages/core-api/src/controllers/transactions.ts
- packages/core-api/src/controllers/wallets.ts
Fixes #3758 and #3759.
Fixed transaction resource responses. Added `confirmations` and `timestamp` fields. Same as before. This is a temporary solution until I can make a better one that doesn't require so much handling on API level.
> fix(core-api): fix transaction resource responses

- __tests__/unit/core-p2p/peer-connector.test.ts
- packages/core-p2p/src/peer-connector.ts
> fix(core-p2p): replace ws connection logging method

- __tests__/functional/transaction-forging/entity-register.test.ts
- __tests__/unit/core-api/__support__/index.ts
- __tests__/unit/core-magistrate-api/service-provider.test.ts
- __tests__/unit/core-state/block-state.test.ts
- __tests__/unit/core-state/setup.ts
- __tests__/unit/core-transaction-pool/expiration-service.test.ts
- __tests__/unit/core-transaction-pool/sender-state.test.ts
- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-kernel/src/contracts/transaction-pool/expiration-service.ts
- packages/core-kernel/src/contracts/transaction-pool/service.ts
- packages/core-transaction-pool/src/expiration-service.ts
- packages/core-transaction-pool/src/sender-state.ts
- packages/core-transaction-pool/src/service.ts
There are two kind of operations executed in pool:
* `addTransaction`, `removeTransaction`, `acceptForgedTransaction`, and `cleanUp` are update operations evolving pool.
* `flush` and `readdTransactions` are rebuild operations that work on pool as a whole.
These two kind of operations cannot happen simultaneously. The key difference is that `flush` and `readdTransaction` are wiping mempool, storage, and in general require full rebuild of senders wallet repositories.
While `addTransaction`, `removeTransaction`, `acceptForgedTransaction`, and `cleanUp` were synchronized on sender level, they were not synchronized with `flush` and `readdTransactions`. This caused problem in entity transaction handler after pool started handling milestone change. I wasn't able to pinpoint the actual race …
> fix(core-transaction-pool): rebuild vs update race

- __tests__/unit/core-transaction-pool/dynamic-fee-matcher.test.ts
- __tests__/unit/core-transaction-pool/errors.test.ts
- __tests__/unit/core-transaction-pool/processor.test.ts
- __tests__/unit/core-transaction-pool/service-provider.test.ts
- packages/core-api/src/server.ts
- packages/core-kernel/src/contracts/transaction-pool/errors.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-magistrate-transactions/src/handlers/business-update.ts
- packages/core-test-framework/src/matchers/functional/rejected.ts
- packages/core-transaction-pool/src/errors.ts
- packages/core-transaction-pool/src/processor.ts
- packages/core-transaction-pool/src/service.ts
- packages/core-transactions/src/handlers/one/delegate-registration.ts
- packages/core-transactions/src/handlers/one/multi-signature-registration.ts
- packages/core-transactions/src/handlers/one/second-signature-registration.ts
- packages/core-transactions/src/handlers/one/transfer.ts
- packages/core-transactions/src/handlers/one/vote.ts
- packages/core-transactions/src/handlers/two/delegate-resignation.ts
- packages/core-transactions/src/handlers/two/htlc-claim.ts
- packages/core-transactions/src/handlers/two/htlc-refund.ts
- packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Fix error seen in #3792. Transaction deserialization error wasn't handled properly.
> fix(core-transaction-pool): handle transaction deserialize error

- __tests__/unit/core-api/plugins/cache.test.ts
- __tests__/unit/core-api/plugins/hapi-ajv.test.ts
- __tests__/unit/core-api/plugins/pagination.test.ts
- __tests__/unit/core-api/plugins/rate-limit.test.ts
- __tests__/unit/core-api/plugins/whitelist.test.ts
- __tests__/unit/core-api/server.test.ts
- packages/core-api/src/defaults.ts
- packages/core-api/src/server.ts
This PR stops a user from opening and keeping open multiple long lived TCP connections to the public API server which is enabled by default. It prevents server resource starvation by implementing a shorter maximum timeout (default: 5 seconds) so connections will be closed if no request is received after that time.
> refactor(core-api): use shorter default timeouts

- __tests__/unit/core-database/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
Fixed typo when searching `recipientId` in multipayment transactions. It's `asset.payments`, not `asset.payment`.
> fix(core-database): transaction filter multipayment recipientId

- packages/core-database/package.json
- packages/core-database/src/repositories/round-repository.ts
- packages/core-database/src/repositories/transaction-repository.ts
- yarn.lock
Connection freezes on fresh Ubuntu 20.04, upgrading `typeorm` and `pg` packages fixes the issue.
> chore(core-database): upgrade typeorm and pg packages

- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
Added simple debug log line at the start of `processBlocks`.
> refactor(core-blockchain): process blocks log line

- __tests__/functional/core-database/repositories/block-repository.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-database/src/repositories/block-repository.ts
It appears that `BlockRepository.deleteBlocks` was called with array in reverse order (higher height first). This should have raised _Removing blocks from the middle_ error, but didn't. I added more checks, tests, and reversed block order (similarly to how transactions are re-added to pool).
This is an attempt to shield `BlockRepository.deleteBlocks` so it can't be called with incorrect arguments that will not throw some error.
> fix(core-database): fix delete blocks

- __tests__/functional/core-database/repositories/round-repository.test.ts
- __tests__/unit/core-database/database-service.test.ts
- packages/core-database/src/database-service.ts
- packages/core-database/src/repositories/round-repository.ts
While checking block generator block processor loads round from database, but rows aren't guaranteed to be ordered. There is no built-in guarantee in db on which order rows will come out. Usually they are in order they were added, but it might be mixed.
New `RoundRepository.getRound` method returns rows the same way they were sorted when list of round delegates was built ordered by `balance desc, public_key asc`.
Equivalent to:
```typescript
this.activeDelegates.sort((a, b) => {
const voteBalanceA = a.getAttribute("delegate.voteBalance");
const voteBalanceB = b.getAttribute("delegate.voteBalance");
const diff = voteBalanceB.comparedTo(voteBalanceA);
if (diff === 0) {
return a.publicKey.localeCompare(b.publicKey, "en");
}
return diff
})
```
> fix(core-database): fix round order

- packages/core-tester-cli/src/commands/make/block.ts
Blocks generated with this command no longer worked for tests because they contained a static timestamp while `blockchain.processBlocks` in v2.6.39 expects incremental timestamps. 
This fixes that.
> fix(core-tester-cli): use incremental timestamps for `make:block`

- __tests__/functional/core-database/__support__/index.ts
- packages/core-database/src/repositories/block-repository.ts
Return serialized transactions in `findByHeightRangeWithTransactions` as it's expected (same as in v2.6).
> fix(core-database): return serialized transactions

- __tests__/unit/core-state/setup.ts
- packages/core-state/src/block-state.ts
Tags got mixed. BlockState was referenced with `state=clone`, but it itself was using wallet repository with `state=blockchain`. There are legit cases where one would need access to both wallet repositories. I will try to find a way to make it more difficult to misuse them.
Gonna start on #3798 and replace tags with child containers. So that blockchain wallet repository is default root one. Temp and copy-on-write wallet repositories has to be explicitly created through factory while being in blockchain context. Attempting to get blockchain wallet repository will also require explicit function call that is available only in temp and copy-on-write contexts.
So that one can't mix them by accident, but can mix them explicitly only in specific known cases.
> fix(core-state): remove state=blockchain tag from block state

- __tests__/unit/core-manager/listener.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/defaults.ts
- packages/core-manager/src/listener.ts
- packages/core-manager/src/service-provider.ts
This PR implements additional logic for enabling and disabling single watcher component using environment variables.
List of env variables:
- CORE_WATCH_BLOCKS_DISABLED,
- CORE_WATCH_ERRORS_DISABLED,
- CORE_WATCH_LOGS_DISABLED,
- CORE_WATCH_QUERIES_DISABLED,
- CORE_WATCH_QUEUES_DISABLED,
- CORE_WATCH_ROUNDS_DISABLED,
- CORE_WATCH_SCHEDULES_DISABLED,
- CORE_WATCH_TRANSACTIONS_DISABLED,
- CORE_WATCH_WALLETS_DISABLED,
- CORE_WATCH_WEBHOOKS_DISABLED,
> feat(core-manager): disable individual watchers

- __tests__/unit/core-kernel/services/config/watcher.test.ts
- __tests__/unit/core-magistrate-api/__support__/index.ts
- __tests__/unit/core-p2p/network-monitor.test.ts
- __tests__/unit/core-p2p/utils/check-ntp.test.ts
- __tests__/unit/core-transactions/handlers/handler-registry.test.ts
- packages/core-api/src/server.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-database/src/service-provider.ts
- packages/core-kernel/src/application.ts
- packages/core-kernel/src/bootstrap/service-providers/boot-service-providers.ts
- packages/core-kernel/src/bootstrap/service-providers/register-service-providers.ts
- packages/core-kernel/src/contracts/kernel/application.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/core-p2p/src/socket-server/server.ts
- packages/core-p2p/src/utils/check-dns.ts
- packages/core-p2p/src/utils/check-ntp.ts
- packages/core-state/src/state-builder.ts
- packages/core-state/src/stores/state.ts
- packages/core-transactions/src/handlers/handler-registry.ts
- packages/core-transactions/src/handlers/transaction.ts
- packages/core-transactions/src/handlers/two/htlc-claim.ts
- packages/core-transactions/src/handlers/two/htlc-refund.ts
- packages/core-webhooks/src/server/index.ts
> refactor(core-kernel): remove app.log and all of its usages

- packages/core-kernel/src/services/config/watcher.ts
Watcher was calling `app.reboot` for every file that was changed.
> fix(core-kernel): prevent watcher from calling app.reboot multiple times

- __tests__/unit/core-manager/actions/process-list.test.ts
- __tests__/unit/core-manager/actions/process-restart.test.ts
- __tests__/unit/core-manager/actions/process-start.test.ts
- __tests__/unit/core-manager/actions/process-stop.test.ts
- __tests__/unit/core-manager/database-service.test.ts
- __tests__/unit/core-manager/server/server.test.ts
- __tests__/unit/core-manager/server/validators/token.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- __tests__/unit/core-manager/utils/api-connection.test.ts
- packages/core-manager/src/actions/process.stop.ts
- packages/core-manager/src/database-service.ts
- packages/core-manager/src/server/validators/token.ts
- packages/core-manager/src/watcher-wallet.ts
- yarn.lock
Increase coverage or core-manager package.
> test(core-manager): increase coverage to 100%

- __tests__/unit/core-database/database-service.test.ts
- __tests__/unit/core-kernel/services/queue/service-provider.test.ts
- __tests__/unit/core-kernel/services/schedule/schedule.test.ts
- __tests__/unit/core-manager/watcher-wallet.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/state-machine/actions/blockchain-ready.ts
- packages/core-database/src/database-service.ts
- packages/core-kernel/src/application.ts
- packages/core-kernel/src/bootstrap/service-providers/boot-service-providers.ts
- packages/core-kernel/src/contracts/kernel/application.ts
- packages/core-kernel/src/services/queue/drivers/memory.ts
- packages/core-kernel/src/services/schedule/block-job.ts
- packages/core-kernel/src/services/schedule/cron-job.ts
- packages/core-manager/src/listener.ts
- packages/core-manager/src/service-provider.ts
- packages/core-manager/src/watcher-wallet.ts
- packages/core-p2p/src/event-listener.ts
- packages/core-p2p/src/listeners.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-processor.ts
- packages/core-p2p/src/socket-server/controllers/internal.ts
- packages/core-snapshots/src/progress-dispatcher.ts
- packages/core-state/src/state-builder.ts
- packages/core-transaction-pool/src/sender-state.ts
- packages/core-transaction-pool/src/service.ts
- packages/core-webhooks/src/listener.ts
- packages/core-webhooks/src/service-provider.ts
- packages/core/src/utils/snapshot-progress-renderer.ts
Along with #3833 fixes #3798. Requires #3833 to be merged first.
> refactor(core-kernel): remove app.events and all of its usages

- __tests__/unit/crypto/transactions/builders/transactions/transaction-builder.test.ts
- packages/crypto/src/interfaces/transactions.ts
- packages/crypto/src/transactions/builders/transactions/transaction.ts
- packages/crypto/src/transactions/deserializer.ts
- packages/crypto/src/transactions/factory.ts
- packages/crypto/src/transactions/serializer.ts
- packages/crypto/src/transactions/signer.ts
- packages/crypto/src/transactions/types/transaction.ts
- packages/crypto/src/transactions/verifier.ts
This updates the `TransactionBuilder` to successfully build and sign transactions when the version number has been specifically set. 
Better dx - if the version has been specifically set on the transaction, we would not expect the Builder to throw a `TransactionVersionError`. As requested in #3099
Adds a flag to check to de/serialisation options
> fix(crypto): transaction builder should build and sign versioned transactions

- __tests__/unit/core-snapshots/verifier.test.ts
- packages/core-snapshots/src/verifier.ts
This PR fixes #3538 
Validation of transaction from multisignature wallets is skipped, because it will require additional logic, applying transactions and using wallet registry. Because core-snapshots should stay simple, lightweight and fast as possible we don't check those transactions. They should be validated on the node boot.
> chore(core-snapshots): skip verification of transactions sent from multisignature wallets

- packages/core-blockchain/src/blockchain.ts
Currently `yarn lint` fails on the master branch (2.6.39).
This PR fixes the related linting error by defining the return type for `this.queue` in `core-blockchain`.
> fix(core-blockchain): add missing return type to this.queue

- packages/core-kernel/src/contracts/transaction-pool/query.ts
- packages/core-transaction-pool/src/query.ts
Union `typeGroup` with `number` so that pool can be queried from other packages.
> refactor(core-transaction-pool): union query typeGroup with number

- __tests__/unit/core-p2p/socket-server/plugins/whitelist-forger.test.ts
- packages/core-kernel/src/contracts/p2p/peer-processor.ts
- packages/core-p2p/src/peer-processor.ts
- packages/core-p2p/src/socket-server/plugins/whitelist-forger.ts
- packages/core-p2p/src/socket-server/server.ts
This PR introduces a plugin to restrict internal p2p route access to whitelisted IPs only. It returns a 403 forbidden response for all other IP addresses.
These changes lead to enhanced security.
A `WhitelistForgerPlugin` has been added which hooks into Hapi's `onPreHandler` hook and which utilises the core-kernel Util's `isWhitelisted` method, to check against all configured `remoteAccess` IPs. As per #3838
> fix(core-p2p): Restrict internal routes to whitelisted IPs

- __tests__/unit/core-snapshots/database-service.test.ts
- __tests__/unit/core-snapshots/filesystem/filesystem.test.ts
- __tests__/unit/core-snapshots/filesystem/stream-reader-writer.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core-snapshots/workers/actions/__support__/helper.ts
- __tests__/unit/core-snapshots/workers/actions/test-worker-action.test.ts
- __tests__/unit/core-snapshots/workers/actions/worker-action.test.ts
- __tests__/unit/core-snapshots/workers/worker-wrapper.test.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/filesystem/filesystem.ts
- packages/core-snapshots/src/filesystem/stream-reader.ts
- packages/core-snapshots/src/repositories/block-repository.ts
- packages/core-snapshots/src/repositories/round-repository.ts
- packages/core-snapshots/src/repositories/transaction-repository.ts
- packages/core-snapshots/src/workers/actions/read-processor.ts
- packages/core-snapshots/src/workers/actions/restore-worker-action.ts
- packages/core-snapshots/src/workers/actions/test-worker-action.ts
- packages/core-snapshots/src/workers/actions/verify-worker-action.ts
- packages/core-snapshots/src/workers/worker-wrapper.ts
- packages/core-snapshots/src/workers/worker.ts
This PR increases coverage of the core-snapshots package to 100%. 
There is also small fix which will dump blocks rounded to the last known block in the round. Previous code included first block of the round, which can cause some problems. 
Snapshot limitations: 
- it is not possible to dump database if last block in round was missed
- dump requires n + 1 blocks in the database, if we want to dump n blocks.
> test(core-snapshot): increase coverage to 100%

- __tests__/unit/core-p2p/service-provider.test.ts
- __tests__/unit/core-p2p/socket-server/utils/get-headers.test.ts
- packages/core-p2p/src/service-provider.ts
- packages/core-p2p/src/socket-server/utils/get-headers.ts
Ensures that the port number used to construct the `Peer` class always uses an integer (instead of a string). This requires converting a string that may be set from config or environment variables.
This fixes the socket data validation issues. As per #3860
The change is implemented by using a `Number()` conversion on string config.
> fix(core-p2p): Ensure peer port is always an integer to avoid socket validation errors

- __tests__/unit/core-transactions/handlers/handler-registry.test.ts
- __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
- packages/core-transactions/src/handlers/one/multi-signature-registration.ts
The `MultiSignatureRegistrationTransactionHandler` (version 1) was always returning false for `.isActivated()` - this PR updates it to instead check milestones.
Fixes #3866. Stops `DeactivatedTransactionHandlerError` from being thrown while syncing with devnet.
> fix(core-transactions): version 1 multi-signature handler should check milestone data

- packages/core-p2p/src/network-monitor.ts
> fix(core-p2p): uses new Promise instead Promise.race

- __tests__/unit/core-state/block-state.test.ts
- packages/core-state/src/block-state.ts
This removes an assertion check inside `block-state.ts` which was causing problems with devnet sync. The behaviour was recently added and can therefore be removed. Change supports #3882.
> fix(core-state): remove unnecessary assertion check to enable devnet sync

- __tests__/unit/core-p2p/listeners.test.ts
- __tests__/unit/core-p2p/peer-communicator.test.ts
- __tests__/unit/core-p2p/service-provider.test.ts
- packages/core-kernel/src/contracts/p2p/peer.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/listeners.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer.ts
- packages/core-p2p/src/service-provider.ts
This PR solves issue #3880 and #3883
Peer will be removed from peer list after 3 (default) sequential unsuccessful responses. Each time peer respond error counter is reset. 
CORE_P2P_MAX_PEER_SEQUENTIAL_ERRORS flag is used  to increase the limit of unsuccessful responses, which can be useful on networks with quicker block times.
> feat(core-p2p): forget unresponsive peer

- __tests__/unit/core-api/plugins/pagination.test.ts
- packages/core-api/src/plugins/pagination/ext.ts
- packages/core-api/src/routes/blocks.ts
- packages/core-api/src/routes/delegates.ts
- packages/core-api/src/routes/locks.ts
- packages/core-api/src/routes/peers.ts
- packages/core-api/src/routes/transactions.ts
- packages/core-api/src/routes/votes.ts
- packages/core-api/src/routes/wallets.ts
This PR relates to #3894. 
Instead of exposing paginated routes list, every route can define optional paginate property inside options.plugins on route registration. 
Example: 
```
server.route({
method: "GET",
path: "...",
handler: ...,
options: {
plugins: {
pagination: {
enabled: true,
},
},
}
})
```
> feat(core-api): enable registering routes with pagination

- __tests__/unit/core-kernel/utils/is-blacklisted.test.ts
- __tests__/unit/core-p2p/peer-processor.test.ts
- packages/core-kernel/src/utils/index.ts
- packages/core-kernel/src/utils/is-blacklisted.ts
- packages/core-p2p/src/peer-processor.ts
This PR implements missing peer blacklisting. Additionally isBlacklisted function was added to core-kernel.
> feat(core-p2p): implement peer blacklisting

- packages/core-p2p/src/peer-communicator.ts
Sequential error counter is reset after successful response from peer, instead before each request.
> fix(core-p2p): reset sequentialErrorCounter after peer response

- packages/core-database/src/repositories/block-repository.ts
This PR solves issue that occurs while syncing blocks from another mainnet peer. Some transactions have order exceptions and  needs to be re-ordered by sequence number to be accepted by database.
> fix(core-database): order transactions by sequence on block save

- __tests__/unit/core-database/database-service.test.ts
- packages/core-database/src/database-service.ts
This PR set blocksInCurrentRound and forgingDelegates as array and remove possible undefined value. This fixes runtime errors when setting length value to undefined array.
> chore(core-database): blocksInCurrentRound and forgingDelegates are arrays

- packages/crypto/package.json
- packages/crypto/rollup.config.js
Some dependencies also use Node builtin modules, so it seems useless to build the current config.
> fix(crypto): use bundled file for `browser` field

- __tests__/functional/core-database/__support__/index.ts
- __tests__/unit/core-database/database-service.test.ts
- __tests__/unit/core-database/service-provider.test.ts
- packages/core-database/src/database-service.ts
- packages/core-database/src/repositories/block-repository.ts
This PR creates two similar methods findByHeightRangeWithTransactions and findByHeightRangeWithTransactionsForDownload. It fixes the problem on node boot, because serialized transaction cannot be verified by block schema. Second method is used for p2p purposes.
> fix(core-database): expose two methods for findByHeightRangeWithTransactions

- __tests__/unit/core-p2p/listeners.test.ts
- __tests__/unit/core-p2p/network-monitor.test.ts
- __tests__/unit/core-p2p/peer-communicator.test.ts
- packages/core-p2p/src/listeners.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/peer-communicator.ts
This PR solves #3903.  All pper sockets are closed on peer disconnect.
> fix(core-p2p): disconnect all sockets on peer disconnect

- packages/core-p2p/src/peer-connector.ts
This PR limits connection retries while making connection from infinity (default) to 1 retry. This fix removes repeated logs: 
Socket error (peer <IP>) : Connection terminated while waiting to connect, caused by infinite retries.
Number of retries can be increased to higher value if necessary.
> fix(core-p2p): limit max connection retries

- .github/workflows/unit.yml
- __tests__/unit/core-api/controllers/transactions.test.ts
- packages/core-api/src/controllers/transactions.ts
Quick fix of #3891 until I finish with #3911
> fix(core-api): fix transactions/${id} confirmations and timestamp fields

- __tests__/unit/core-p2p/peer-communicator.test.ts
- packages/core-cli/package.json
- packages/core-kernel/package.json
- packages/core-p2p/src/peer-communicator.ts
- packages/crypto/package.json
- yarn.lock
This PR solves #3920.
All @arkecosystem/utils dependencies has been updated to version 1.2.0.
P2P Ping method is using HEAD instead GET HTTP request.
> chore(core-p2p): implement HEAD HTTP request for ping

- __tests__/unit/core-api/server.test.ts
- packages/core-api/src/server.ts
This PR solves #3571 
ServerRoute can be obtained via getRoute method. ServerRoute can be later used for altering or extending response and overriding existing route handler.
> chore(core-api): get registered server route

- packages/core-api/src/routes/delegates.ts
Order block by `height:desc` for `delegates/{id}/blocks`
> fix(core-api): fix order in delegates/{id}/blocks

- packages/core-kernel/src/services/config/drivers/local.ts
This PR solves #3933 
If process.env is defined it will be used even if variable is defined in .env file.
> chore(core-kernel): process env over .env

- packages/core-api/src/schemas.ts
- packages/core-api/src/server.ts
Transform schemas back into form that similar to 2.6. Now they can be referenced from `core-api` and used by other `-api` packages. The reason why `createSchemas` function existed was to set max allowed value that is read from settings for limit query parameter. Now it's set and referenced through Joi context.
Schemas are still exported into `app.schemas`, but they should be referenced directly. This requires updating all routes.
> refactor(core-api): put configuration into Joi context

- packages/core-database/src/migrations/20200317000000-add-blocks-and-transactions-indexes.ts
This PR solves: #3947
Using GIN index for transactions.asset (JSONB type) instead default B-TREE index.
> chore(core-database): use GIN index on transactions.asset

- __tests__/integration/core-api/handlers/transactions.test.ts
- packages/core-api/src/schemas.ts
- packages/core-api/src/server.ts
Rollback recent #3940, fixes #3952, add limit parameter test.
> fix(core-api): limit parameter (rollback #3940)

- __tests__/integration/core-api/handlers/wallets.test.ts
- packages/core-api/src/schemas.ts
- packages/core-api/src/server.ts
Re-implemented #3940. Options were overwritten by `{ routes: { cors: true } }`, now they are deep-merged.
> refactor(core-api): pagination configuration through joi context

- __tests__/unit/core-state/wallets/wallet-repository.test.ts
- packages/core-state/src/wallets/utils/get-property.ts
- packages/core-state/src/wallets/utils/sort-entries.ts
> fix(core-state): fix delegate search order

- __tests__/unit/core-blockchain/blockchain.test.ts
- __tests__/unit/core-database/database-service.test.ts
- __tests__/unit/core-state/stores/state.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-database/src/database-service.ts
- packages/core-kernel/src/contracts/state/state-store.ts
- packages/core-state/src/stores/state.ts
- packages/core-transactions/src/handlers/two/ipfs.ts
This PR fixes: #3938
1. Removes ipfs entry from ipfs index on reverting ipfs transaction.
2. Take blocks for removal from state store if they exist, otherwise load them from database.
3. Limit enqued blocks chunk to fit stateStore maxLastBlocks lenght. This prevent loosing blocks if they not saved into the database and are removed from stateStore blocks ordered map.
> fix(core-database): revertBlock

- __tests__/functional/transaction-forging/delegate-resignation.test.ts
- __tests__/integration/core-api/handlers/delegates.test.ts
- __tests__/unit/core-magistrate-api/controllers/entities.test.ts
- __tests__/unit/core-state/__utils__/fixture-generator.ts
- __tests__/unit/core-state/block-state.test.ts
- __tests__/unit/core-state/wallets/wallet-index.test.ts
- __tests__/unit/core-state/wallets/wallet-repository-clone.test.ts
- __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
- __tests__/unit/core-state/wallets/wallet-repository.test.ts
- __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-magistrate-transactions/src/handlers/business-registration.ts
- packages/core-magistrate-transactions/src/handlers/business-resignation.ts
- packages/core-state/src/wallets/wallet-index.ts
- packages/core-state/src/wallets/wallet-repository.ts
- packages/core-transactions/src/handlers/one/delegate-registration.ts
- packages/core-transactions/src/handlers/two/delegate-resignation.ts
Remove all forget* methods on wallet-repository. Re implements index methods, which now forget wallet from all indexes and re add them back to keep consistency and integrity.
> chore(core-state): remove forget methods and use index instead

- packages/core-kernel/src/services/process-actions/drivers/pm2.ts
Dynamically import @pm2/io package. This prevents pm2 initialization before service registration. Pm2 was previously loaded on core-kernel import, which had unwanted side effects.
> fix(core-kernel): dynamically import @pm2/io

- __tests__/unit/core-state/__utils__/build-delegate-and-vote-balances.ts
- __tests__/unit/core-state/block-state.test.ts
- __tests__/unit/core-state/wallets/wallet-repository.test.ts
- __tests__/unit/crypto/identities/public-key.test.ts
- packages/crypto/src/identities/address.ts
- packages/crypto/src/identities/public-key.ts
Current master/develop only checks for valid hex during PublicKey validation, but does not verify the correctness of a publicKey.
This can lead to the unexpected creation of an unaccessible but technically-"valid" Address.
This PR recommends the following:
- add a `verify` method to `class PublicKey` using the already-present `secp256k1` module
- modify `Address.fromPublicKey` to drop hex-validation in favor of `PublicKey.verify`
- modify `PublicKey.fromMultiSignatureAsset` to drop hex-validation in favor of `PublicKey.verify`
- add relevant unit-tests
- No change of import modules needed
- maintains resolution of circular-dep fixes in c84b976
There are other areas that would benefit from the `PublicKey.verify` method; however, no additional checks are being added at this time.
It should …
> chore(crypto): add publickey verification

- __tests__/unit/core-magistrate-transactions/__support__/app.ts
- __tests__/unit/core-magistrate-transactions/handlers/__fixtures__/entity/index.ts
- __tests__/unit/core-magistrate-transactions/handlers/__fixtures__/index.ts
- __tests__/unit/core-magistrate-transactions/handlers/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/bridgechain-update.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/business-registration.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/business-resignation.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/business-update.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/register.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/resign.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/update.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/entity.test.ts
- __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
- packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
- packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
- packages/core-magistrate-transactions/src/handlers/index.ts
- packages/core-magistrate-transactions/src/wallet-indexes.ts
Solves #3971
Increase core-magistrate-transactions to 100 %.
> test(core-magistrate-transactions): increate coverage to 100 %

- __tests__/unit/core-magistrate-api/resources/entity.test.ts
Solves #3978
Increase core-magistrate-transactions to 100 %.
> test(core-magistrate-api): incrase test coverage to 100%

- __tests__/unit/core-api/__support__/index.ts
- __tests__/unit/core-magistrate-api/__support__/index.ts
- __tests__/unit/core-magistrate-transactions/__support__/app.ts
- __tests__/unit/core-state/wallets/wallet-index.test.ts
- __tests__/unit/core-state/wallets/wallet-repository.test.ts
- __tests__/unit/core-transactions/handlers/__support__/app.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-magistrate-transactions/src/service-provider.ts
- packages/core-state/src/wallets/indexers/wallet-indexes.ts
- packages/core-state/src/wallets/wallet-index.ts
- packages/core-state/src/wallets/wallet-repository.ts
Implements autoIndex option on indexes. When autoIndex is enabled, WalletRepository.index(wallet) method will remove all known index entries by wallet and will reindex wallet, otherwise developer is responsible to manually use index, set or delete methods directly on index. 
Disabling autoIndex option is useful in cases when index hold a lot of entries for the wallet and manual control over index will increase node performance.
> chore(core-state): autoIndex option

- packages/core-state/src/index.ts
> chore(core-state): export state-builder

- __tests__/unit/core-magistrate-crypto/builders/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate-crypto/builders/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate-crypto/builders/bridgechain-update.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-registration.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-resignation.test.ts
- __tests__/unit/core-magistrate-crypto/builders/business-update.test.ts
- __tests__/unit/core-magistrate-crypto/builders/enity.test.ts
- __tests__/unit/core-magistrate-crypto/fixtures/entity/assets/generate.ts
- __tests__/unit/core-magistrate-crypto/helper.ts
- __tests__/unit/core-magistrate-crypto/transactions/bridgechain-registration.test.ts
- __tests__/unit/core-magistrate-crypto/transactions/bridgechain-resignation.test.ts
- __tests__/unit/core-magistrate-crypto/transactions/bridgechain-update.test.ts
- __tests__/unit/core-magistrate-crypto/transactions/business-registration.test.ts
- __tests__/unit/core-magistrate-crypto/transactions/business-update.test.ts
- __tests__/unit/core-magistrate-crypto/transactions/entity.test.ts
Solves #3977
Increase core-magistrate-transactions to 100 %.
> test(core-magistrate-crypto): increase test coverage to 100%

- packages/core-api/package.json
- packages/core-api/src/plugins/rate-limit.ts
- packages/core-kernel/src/services/events/drivers/memory.ts
Replace micromatch with nanomatch. PR fixes missing dependancy when using core* packages form npm.
> fix: replace micromatch with nanomatch

- __tests__/unit/core-state/wallets/wallet-index.test.ts
- __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-state/src/wallets/wallet-index.ts
- packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
Extend wallet-index with walletKeys method. Clone wallet by walletKeys insted using index. This approach copy exactly stored keys and copy wallet from indexes even if autoIndex is set to false.
> fix(core-state): clone wallet on mempool wallet-repository

- packages/core-test-framework/package.json
- packages/core-test-framework/src/app/generators/core.ts
Use file path resolving based on package name rather than using relative structure used in packages/. Fixes problem which occur on booting sandbox.app when using published @arkecosystem/core-test-framework package.
> chore(core-test-framework): resolve .env and app.json file path from package name

- __tests__/unit/core-p2p/hapi-nes/listener.test.ts
- __tests__/unit/core-p2p/socket-server/server.test.ts
- packages/core-p2p/src/hapi-nes/listener.ts
- packages/core-p2p/src/hapi-nes/plugin.ts
- packages/core-p2p/src/socket-server/server.ts
> chore(core-p2p): set maxPayload on ws server

- __tests__/unit/core-p2p/socket-server/routes/blocks.test.ts
- __tests__/unit/core-p2p/socket-server/routes/transactions.test.ts
- __tests__/unit/core-p2p/socket-server/server.test.ts
- __tests__/unit/core-p2p/utils/build-rate-limiter.test.ts
- packages/core-p2p/src/peer-communicator.ts
Solves #3980
Increase core-p2p coverage to 100 %.
> test(core-p2p): increase test coverage to 100%

- packages/core-api/src/services/delegate-search-service.ts
Follow up to #3931 that fixes `delegate.lastBlock.timestamp` response property.
> fix(core-api): fix delegate.lastBlock.timestamp property

- packages/core-webhooks/src/database.ts
There's an issue with lowdb where lodash errors are thrown on certain deep method calls if another package or plugin has a `@types/lowdb` dependency: https://github.com/typicode/lowdb/issues/233
By adding a ts-ignore comment above the methods that cause the type error, core-webhooks can build without issue.
> fix(core-webooks): ignore type errors thrown with lowdb deep methods

- __tests__/unit/core-state/wallets/wallet-index.test.ts
- __tests__/unit/core-state/wallets/wallet-repository-clone.test.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-state/src/wallets/wallet-index.ts
- packages/core-state/src/wallets/wallet-repository-clone.ts
- packages/core-state/src/wallets/wallet-repository.ts
Clone of wallet repository was instantiated incorrectly:
```typescript
public initialize(): void {
for (const index of this.blockchainWalletRepository.getIndexNames()) {
this.indexes[index] = this.blockchainWalletRepository.getIndex(index).clone();
}
}
```
This error was actually made by me back in the days when I had little understanding of its internals. The issue is with the wallet index `clone` method:
```typescript
public clone(): Contracts.State.WalletIndex {
const walletIndex = new WalletIndex(this.indexer, this.autoIndex);
for (const [key, value] of this.entries()) {
walletIndex.set(key, value.clone());
}
return walletIndex;
}
```
It performs deep clone and as result cloned wallet repository will contain separate but identical wallet copies in all of its indexes:
```typescript …
```
> fix(core-state): wallet repository clone instantiation

- __tests__/unit/core-magistrate/handlers/entity.test.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
Entity delegate transactions have a specific check against the sender wallet which needs to be a delegate and username must match entity name.
But this check is only needed for register : as an update or resign needs first a register tx where the delegate check was already done.
This also fixes an issue with current implementation where update or resign entity delegate tx would not be accepted because of the name check which was incorrectly implemented.
> fix(magistrate): delegate check only needed on entity register

- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-state/src/wallets/wallet-repository-clone.ts
- packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
- packages/core-state/src/wallets/wallet-repository.ts
Implement cloneWallet method on main wallet-repository which clone wallet from passed wallet-repository. Clone method will clone wallet by each index and will copy all index entries.
> chore(core-state): cloneWallet method in wallet-repository

- __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
- packages/core-api/src/routes/blockchain.ts
- packages/core-api/src/routes/blocks.ts
- packages/core-api/src/routes/delegates.ts
- packages/core-api/src/routes/locks.ts
- packages/core-api/src/routes/node.ts
- packages/core-api/src/routes/peers.ts
- packages/core-api/src/routes/rounds.ts
- packages/core-api/src/routes/transactions.ts
- packages/core-api/src/routes/votes.ts
- packages/core-api/src/routes/wallets.ts
Following up issue #3571 and PR #3928 which allowed to extend api response by getting the registered handler : 
Refactor existing core-api routes handlers, using an arrow function to call the class method handler instead of directly binding the handler to the class method. This allow to easily extend the api response as shown in tests in PR #3928 .
(without using the arrow function, we would get issues with `this` when extending api response and calling the original handler)
> refactor(core-api): do not bind directly handler to class method to allow extending response

- packages/core/src/utils/snapshot-progress-renderer.ts
Solves #4014
Increase core coverage to 100 %.
> test(core): increase test coverage

- packages/core-database/package.json
- packages/core-manager/package.json
- packages/core-snapshots/package.json
We're having issues with latest version of typeorm (0.2.28), so for now just force version 0.2.25.
> chore: force typeorm version 0.2.25

- __tests__/unit/core-kernel/services/queue/drivers/memory.test.ts
- __tests__/unit/core-kernel/services/queue/drivers/null.test.ts
- __tests__/unit/core-kernel/services/queue/service-provider.test.ts
- packages/core-kernel/src/contracts/kernel/queue.ts
- packages/core-kernel/src/enums/events.ts
- packages/core-kernel/src/services/queue/drivers/memory.ts
- packages/core-kernel/src/services/queue/drivers/null.ts
- yarn.lock
Refactor Queue from core-kernel with corresponding MemoryQueue and NullQueue implementations. 
MemoryQueue will be used in the core-blockchain logic and that is why it implements additional methods:
- isRunning
- isStarted
- onDrain
- onError
- onData
> feat(core-kernel): implement `Queue#isRunning/isStarted/onDrain/onError/onData` methods

- __tests__/integration/core-api/handlers/delegates.test.ts
- __tests__/integration/core-api/handlers/wallets.test.ts
- __tests__/unit/core-magistrate-api/controllers/entities.test.ts
- packages/core-api/src/resources-new/delegate.ts
- packages/core-api/src/resources-new/lock.ts
- packages/core-api/src/resources-new/wallet.ts
- packages/core-api/src/routes/delegates.ts
- packages/core-api/src/routes/locks.ts
- packages/core-api/src/routes/wallets.ts
- packages/core-api/src/schemas.ts
- packages/core-magistrate-api/src/controllers/entities.ts
- packages/core-magistrate-api/src/resources/entity.ts
- packages/core-magistrate-api/src/routes/entities.ts
Follow-up on #4068 to allow comma-separated api query parameter (OR) on more endpoints. (was only on transactions and blocks).
Credits to @rainydio for the changes.
> chore(core-api): allow array query parameter in all schemas

- packages/core-kernel/src/services/attributes/attribute-map.ts
- packages/core-state/src/wallets/wallet.ts
Including `previousValue` into event that is fired during `forgetAttribute`﻿ requires workaround to avoid error if it is `undefined`.
> fix(core-state): don't throw forgetting undefined attribute

- packages/core-transactions/src/handlers/two/vote.ts
Fix unvote+vote bootstrap by making it nearly identical to `applyToSender`﻿
> fix(core-transactions): fix unvote+vote bootstrap

- __tests__/unit/core-transaction-pool/processor.test.ts
- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-transaction-pool/src/processor.ts
- packages/core-transaction-pool/src/service.ts
Move dynamic fee pool enter check into pool service after transaction was already added to storage. This will prevent spam in logs described in #4091.
> fix(core-transaction-pool): don't spam dynamic fee messages

- packages/core-api/src/controllers/blocks.ts
Use `Number()` to determine if parameter is block height﻿
> fix(core-api): fix block returned by api by either id or height

- __tests__/unit/core-p2p/hapi-nes/client.test.ts
- packages/core-p2p/src/hapi-nes/client.ts
Fix for issue #4114.
Clear hapi-nes request from request list on timeout. If server response with after timeout the error is logged.
> fix(core-p2p): clear hapi-nes request on timeout

- __tests__/unit/core-cli/components/fatal.test.ts
- __tests__/unit/core/commands/config-publish.test.ts
- __tests__/unit/core/commands/core-log.test.ts
- __tests__/unit/core/commands/core-restart.test.ts
- __tests__/unit/core/commands/core-status.test.ts
- __tests__/unit/core/commands/core-stop.test.ts
- __tests__/unit/core/commands/env-list.test.ts
- __tests__/unit/core/commands/forger-log.test.ts
- __tests__/unit/core/commands/forger-restart.test.ts
- __tests__/unit/core/commands/forger-status.test.ts
- __tests__/unit/core/commands/forger-stop.test.ts
- __tests__/unit/core/commands/manager-stop.test.ts
- __tests__/unit/core/commands/reinstall.test.ts
- __tests__/unit/core/commands/relay-log.test.ts
- __tests__/unit/core/commands/relay-restart.test.ts
- __tests__/unit/core/commands/relay-status.test.ts
- __tests__/unit/core/commands/relay-stop.test.ts
- __tests__/unit/core/commands/uninstall.test.ts
- packages/core-cli/src/components/fatal.ts
- packages/core-cli/src/exceptions/base.ts
- packages/core-cli/src/exceptions/index.ts
- packages/core-cli/src/exceptions/runtime.ts
- packages/core/bin/run
- packages/core/src/commands/env-get.ts
Fix for issue #4094.
- Log fatal errors from core-cli then throw error. 
- Require key on env:get command
- ./bin/run entry file now uses main function and exit process with status code 1 when error occurs.
> fix(core-cli): log fatal errors

- packages/core-database/src/wallets-table-service.ts
Not a real issue. `ROLLBACK TRANSACTION` was sent if `START TRANSACTION` somehow failed (it can't). Creating/releasing query runner is extracted into separate `try...finally` from commit/rollback `try...catch`.
> fix(core-database): don't rollback transaction that failed to start

- packages/core-kernel/src/bootstrap/app/load-cryptography.ts
Use setConfig on cryptography load which fix problem with milestones when using system default config location.
> fix(core-kernel): use setConfig on cryptography load

- packages/core-database/src/migrations/20201103000000-set-autovacuum-settings.ts
Autovacuuming (and `ANALYZE`) wasn't performed frequently enough because default values of `autovacuum_vacuum_scale_factor` and `autovacuum_analyze_scale_factor` are to high.
> fix(core-database): set adequate autovacuum settings

- packages/core-api/src/plugins/cache.ts
Include request.method name into cache key generator. This fixes issue on some clients and create separate cache for OPTIONS and GET method on the same route path.
> fix(core-api): add request.method in cache key

- __tests__/unit/core-p2p/peer-communicator.test.ts
- packages/core-p2p/src/peer-communicator.ts
Fixes #4167 .
Remove `transactions` field from block when requesting with `headersOnly`, as now ser/deserializing with protobuf sets default `transactions` field to empty array when we expect it to be undefined.
> fix(core-p2p): remove `transactions` field from block when requesting with `headersOnly`

- __tests__/unit/core-p2p/socket-server/plugins/is-app-ready.test.ts
- __tests__/unit/core-p2p/socket-server/plugins/whitelist-forger.test.ts
- packages/core-p2p/src/socket-server/plugins/accept-peer.ts
- packages/core-p2p/src/socket-server/plugins/is-app-ready.ts
- packages/core-p2p/src/socket-server/plugins/whitelist-forger.ts
- packages/core-p2p/src/socket-server/server.ts
Re-organize plugins in hapi lifecycle so that it makes more sense.
Also updated a bit AcceptPeerPlugin to be triggered on peer, blocks and transactions routes (all except internal). Might resolve #4124 .
> refactor(core-p2p): re-organize plugins in hapi lifecycle

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/info-core-version.test.ts
- packages/core-manager/src/actions/info-core-version.ts
Get version channel from core-cli config to remove code duplication.
> refactor(core-manager): get version channel from core-cli config

- __tests__/unit/crypto/validation/keywords.test.ts
- packages/core/src/commands/network-generate.ts
- packages/crypto/src/blocks/block.ts
- packages/crypto/src/validation/keywords.ts
Generate a genesis block with full sha256 is now that `idFullSha256` is set from height 1.
Needed some adjustments in crypto too.
Changed schema so that genesis block can be allowed to have a previous block : can seem weird but actually can make sense in my opinion so that we can build and serialize a genesis block like a normal block. In `network:generate` command as an example we set the previous block to `00000...` and we can then serialize with crypto methods without issue.
> fix(core): generate genesis block with id full sha256

- packages/core-state/src/database-interactions.ts
Fix issue #4089
Detect missed blocks before applying block. After latest changes in core-state blocks are set in apply method and check needs to execute before applying.
> fix(core-state): detect missed blocks

- __tests__/unit/core-p2p/socket-server/plugins/rate-limit.test.ts
- packages/core-p2p/src/socket-server/plugins/rate-limit.ts
- packages/core-p2p/src/socket-server/server.ts
> feat(core-p2p): rate limit plugin

- __tests__/unit/core-manager/action-reader.test.ts
- __tests__/unit/core-manager/actions/log-search.test.ts
- __tests__/unit/core-manager/database/logs-database-service.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/log-search.ts
- packages/core-manager/src/database/logs-database-service.ts
- packages/core-manager/src/defaults.ts
- packages/core-manager/src/ioc/identifiers.ts
- packages/core-manager/src/log-service-wrapper.ts
- packages/core-manager/src/service-provider.ts
- packages/core/bin/config/testnet/app.json
- yarn.lock
Store logs in sqlite database and use it on `log.search` action.
Keep logs history for 30 days. Different setting can be achieved via app.json.
> feat(core-manager): store logs in sqlite database

- __tests__/unit/core-manager/database/events-database-service.test.ts
- packages/core-manager/src/database/events-database-service.ts
Database file path should be set in the single setting from defaults.
> refactor(core-manager): single database path setting

- __tests__/unit/core-manager/database/logs-database-service.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/database/database.ts
- packages/core-manager/src/database/logs-database-service.ts
- packages/core-manager/src/service-provider.ts
- packages/core/bin/config/devnet/app.json
- packages/core/bin/config/mainnet/app.json
- packages/core/bin/config/testnet/app.json
- packages/core/src/commands/core-run.ts
- packages/core/src/commands/manager-run.ts
Enable core manager on all processes to enable logging to database. Prevent booting http and https servers when process is not manager.
> chore: enable core-manager on all processes

- __tests__/unit/core-manager/actions/info-core-status.test.ts
- __tests__/unit/core-manager/actions/info-current-delegate.test.ts
- __tests__/unit/core-manager/actions/info-last-forged-block.test.ts
- __tests__/unit/core-manager/actions/info-next-forging-slot.test.ts
- packages/core-manager/src/actions/info-core-status.ts
- packages/core-manager/src/actions/info-current-delegate.ts
- packages/core-manager/src/actions/info-last-forged-block.ts
- packages/core-manager/src/actions/info-next-forging-slot.ts
- packages/core-manager/src/utils/process.ts
Support custom tokens. Token name is read from app.token() and is the same as defined in flags. Custom token can also be set in params to override default app.token() option. 
Change supports processes with custom token like [cusomTokeName]-[core/relay/forger]. 
Affected endpoints:
- info.coreStatus
- info.nextForgingSlot
- info.currnetDelegate
- info.lastForgedBlock
> feat(core-manager): support custom tokens

- __tests__/unit/core-api/plugins/response-headers.test.ts
- packages/core-api/src/plugins/index.ts
- packages/core-api/src/plugins/response-headers.ts
Return block height as `X-Block-Height` header in API response.
> feat(core-api): return block height in API response headers

- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/service-provider.ts
- packages/core/bin/config/devnet/app.json
- packages/core/bin/config/testnet/app.json
Require core-snspshots dependency only when processType is manager. For other types (core, forger) this dependency is optional because actions are not loaded and https server is not booted.
> fix(core-manager): optional core-snapshots dependency when process is not manager

- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/src/service-provider.ts
Use core-managers dependencies only for manager process type to prevent warnings and to include package.
> refactor(core-manager): use dependencies only for manager process type

- packages/core-p2p/src/network-monitor.ts
Resolves #4225 : do not log download blocks failure message when peer returned no blocks for a "last chunk" of download, as in most cases it is normal (and in other cases, core will handle it without issue anyway).
> fix(core-p2p): download blocks log message when no blocks are returned

- packages/core/src/commands/core-start.ts
- packages/core/src/commands/forger-start.ts
- packages/core/src/commands/manager-start.ts
- packages/core/src/commands/relay-start.ts
- yarn.lock
Await deamonizeProcess on :start commands. This fixes missing error logs when pm2 package is not installed.
> fix(core-manager): await deamonizeProcess on start commnands

- __tests__/unit/core-blockchain/process-blocks-job.test.ts
- __tests__/unit/core-blockchain/state-machine/state-machine.test.ts
- packages/core-blockchain/src/process-blocks-job.ts
- packages/core-blockchain/src/state-machine/state-machine.ts
New getState() method on stateMachine. 
Broadcast only new blocks. Skip broadcasting downloaded blocks, to prevent diconnectiong from other peers.
> fix(core-blockchain): broadcast only new blocks

- packages/core-p2p/src/hapi-nes/client.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/socket-server/controllers/blocks.ts
We currently have a basic way of dealing with blocks that collectively exceed the max payload value : we try to download a whole chunk, if that does not work we reduce the chunk until it works.
This PR improves it a bit : when we are requested a chunk of blocks, we will only return a chunk of blocks that fits the max payload value (so it can be a sub-interval of what is asked).
This way we don't generate errors sending data exceeding max payload, and the client will handle fine receiving a sub-interval of what it asked.
> chore(core-p2p): improve block download when above maxPayload

- __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
- packages/core-p2p/src/socket-server/controllers/blocks.ts
Prevent punishing clients with connection drop for broadcasting unchained blocks.
> chore(core-p2p): don't throw when receiving unchained block

- package.json
- packages/core-api/package.json
- packages/core-blockchain/package.json
- packages/core-cli/package.json
- packages/core-database/package.json
- packages/core-forger/package.json
- packages/core-kernel/package.json
- packages/core-logger-pino/package.json
- packages/core-magistrate-api/package.json
- packages/core-magistrate-crypto/package.json
- packages/core-magistrate-transactions/package.json
- packages/core-manager/package.json
- packages/core-p2p/package.json
- packages/core-snapshots/package.json
- packages/core-state/package.json
- packages/core-test-framework/package.json
- packages/core-transaction-pool/package.json
- packages/core-transactions/package.json
- packages/core-webhooks/package.json
- packages/core/package.json
- packages/crypto/package.json
- yarn.lock
**Note:**
Windows build tools are required to successfully build and run Ark Core and can be installed using opening PowerShell as Administrator and running a command `yarn global add windows-build-tools`
I didn't amend all the scripts just the ones that are required to successfully build and run ark core on windows, hence development & debugging are now working.
**What changes are being made?**
Amend scripts (required to build and run the project) which should now run under windows.
Bump hapi dependencies to resolve `Topo is not a constructor error`.
**Why are these changes necessary?**
To allow building and running ark core on windows without using docker or wsl.
> feat: partial windows support

- __tests__/unit/core-api/controllers/node.test.ts
- packages/core-api/src/controllers/node.ts
Include transaction-pool options in `node/configuration` response.
> feat(core-api): include transaction-pool options in node/configuration

- __tests__/unit/core-manager/database/logs-database-service.test.ts
- packages/core-manager/src/actions/log-search.ts
- packages/core-manager/src/database/logs-database-service.ts
Sort logs by time descending on `log.search` action.
Added optional parameter `order` which accepts values `DESC` (default) or `ASC`.
> feat(core-manager): sort logs descending by defaut on `log.search`

- __tests__/unit/core-manager/actions/log-archived.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/log-archived.ts
- packages/core-manager/src/defaults.ts
- yarn.lock
Generate full download link on `log.archived` action. 
Path will use HTTPS settings if HTTPS server is running, otherwise it will use HTTP options. Optionally custom IP can be defined via CORE_MONITOR_PUBLIC_IP ENV variable.  If value is empty, public IP will be obtained via[ public-ip](https://www.npmjs.com/package/public-ip) package.
> chore(core-manager): full download link on `log.archived`

- __tests__/unit/core-p2p/peer-connector.test.ts
- packages/core-p2p/src/peer-connector.ts
Add a 10 seconds delay on multiple reconnections to same peer to prevent possible abuse. Under normal conditions we should not need to connect twice (creating new socket) within 10 seconds.
> chore(core-p2p): add delay on multiple reconnections (client socket)

- __tests__/unit/core-kernel/providers/plugin-configuration.test.ts
- packages/core-kernel/src/providers/plugin-configuration.ts
Override array on merge in plugin configuration to prevent duplicates and give user ability to override default values.
> fix(core-kernel): override array on merge

- __tests__/unit/core-manager/server/server.test.ts
- packages/core-manager/src/server/plugins/plugin-factory.ts
Allow beaer token in URL.
Example:
http://127.0.0.1:4005/log/archived/2021-01-21_03-05-51.log.gz `?token=secret_token`
> feat(core-manager): allow bearer token in URL

- __tests__/unit/core-manager/actions/log-archived.test.ts
- __tests__/unit/core-manager/server/http-server.test.ts
- __tests__/unit/core-manager/server/plugins/rpc-response-handler.test.ts
- __tests__/unit/core-manager/server/routes/log-achived.test.ts
- __tests__/unit/core-manager/server/server-boot-dispose.test.ts
- __tests__/unit/core-manager/server/server.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- packages/core-manager/package.json
- packages/core-manager/src/actions/log-archived.ts
- packages/core-manager/src/contracts/plugins.ts
- packages/core-manager/src/ioc/identifiers.ts
- packages/core-manager/src/server/http-server.ts
- packages/core-manager/src/server/index.ts
- packages/core-manager/src/server/plugins/plugin-factory.ts
- packages/core-manager/src/server/server.ts
- packages/core-manager/src/service-provider.ts
Implements separate HTTP server for downloading logs to prevent overlapping with JSON-RPC server. 
HTTP port is offset by 1 from JSON_RPC server port. Defaults: HTTP: 4006, HTTPS: 8446
> refactor(core-manager): separate HTTP and JSON-RPC server

- __tests__/unit/core-api/service-provider.test.ts
- __tests__/unit/core-magistrate-api/service-provider.test.ts
- __tests__/unit/core-p2p/socket-server/controllers/transactions.test.ts
- __tests__/unit/core-test-framework/mocks/transaction-pool-processor.test.ts
- __tests__/unit/core-transaction-pool/processor.test.ts
- __tests__/unit/core-webhooks/service-provider.test.ts
- packages/core-api/src/controllers/transactions.ts
- packages/core-kernel/src/contracts/transaction-pool/processor.ts
- packages/core-p2p/src/socket-server/controllers/transactions.ts
- packages/core-test-framework/src/mocks/transaction-pool-processor.ts
- packages/core-transaction-pool/src/processor.ts
Allow pool processor to be injected directly (instead of having to use factory).
> refactor(core-transaction-pool): pool processor to be injected directly

- __tests__/integration/core-state/__support__/utils.ts
- __tests__/integration/core-state/block-state/lock-then-claim.test.ts
- __tests__/integration/core-state/block-state/lock-then-refund.test.ts
- __tests__/integration/core-state/block-state/multi-payment.test.ts
- __tests__/integration/core-state/block-state/transfer.test.ts
- __tests__/integration/core-state/block-state/unvote-by-forger-then-vote-by-forger.test.ts
- __tests__/integration/core-state/block-state/unvote-by-forger-vote-by-forger-twice.test.ts
- __tests__/integration/core-state/block-state/unvote-then-vote-unvote.test.ts
- __tests__/integration/core-state/block-state/unvote-then-vote.test.ts
- __tests__/integration/core-state/block-state/unvote-vote-by-forger.test.ts
- __tests__/integration/core-state/block-state/unvote-vote.test.ts
Tests are now comparing results of two functions to check vote balances:
- `getExpectedVoteBalances` that returns calculated vote balance values.
- `getActualVoteBalances` that returns actual `delegate.voteBalance` values.
> refactor(core-state): test every wallet vote balance

- __tests__/unit/core-p2p/service-provider.test.ts
- packages/core-p2p/src/defaults.ts
Add **CORE_P2P_MIN_NETWORK_REACH** ENV variable. Used to set minimum network reach when using custom number of delegates.
> chore(core-p2p): add CORE_P2P_MIN_NETWORK_REACH env variable

- __tests__/unit/core-api/service-provider.test.ts
- __tests__/unit/core-blockchain/service-provider.test.ts
- __tests__/unit/core-database/service-provider.test.ts
- __tests__/unit/core-forger/service-provider.test.ts
- __tests__/unit/core-logger-pino/service-provider.test.ts
- __tests__/unit/core-manager/service-provider.test.ts
- __tests__/unit/core-p2p/service-provider.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core-state/service-provider.test.ts
- __tests__/unit/core-transaction-pool/service-provider.test.ts
- __tests__/unit/core-webhooks/service-provider.test.ts
- packages/core-api/src/service-provider.ts
- packages/core-blockchain/src/service-provider.ts
- packages/core-database/src/service-provider.ts
- packages/core-forger/src/service-provider.ts
- packages/core-logger-pino/src/service-provider.ts
- packages/core-manager/src/service-provider.ts
- packages/core-p2p/src/service-provider.ts
- packages/core-snapshots/src/service-provider.ts
- packages/core-state/src/service-provider.ts
- packages/core-transaction-pool/src/service-provider.ts
- packages/core-webhooks/src/service-provider.ts
Allow unknown filed in configuration schema to allow other developers to extend configuration with custom fields via app.json file.
> chore: allow unknow fields in package configuration

- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/service-provider.ts
- packages/core-p2p/src/socket-server/plugins/rate-limit.ts
- packages/core-p2p/src/utils/build-rate-limiter.ts
Set up a logic rate limit on `postTransactions` as currently there is not (it is limited by the global limit of 100/sec). 25/sec looks more than enough : even if using the endpoint sending 1 transaction each time, we'd be able to send 200 txs in 8 seconds (which is the block time, so it would fill the block). At any moment if there is more transactions to be processed, the txs will still be sent to other nodes but it will just be throttled.
This specific rate limit on `postTransactions` can be customized from app.json / env.
> chore(core-p2p): set up a rate limit on `postTransactions`

- __tests__/unit/core-p2p/peer-communicator.test.ts
- packages/core-p2p/src/peer-communicator.ts
Use a queue for sending postTransactions requests, so that we send them sequentially and allowing us to better control throttling according to rate limit (adding a slight delay between each request).
> chore(core-p2p): queue postTransactions requests

- __tests__/unit/core-manager/actions/info-database-size.test.ts
- __tests__/unit/core-snapshots/database-service.test.ts
- __tests__/unit/core-snapshots/service-provider.test.ts
- __tests__/unit/core/commands/config-manager.test.ts
- __tests__/unit/core/commands/snapshot-dump.test.ts
- __tests__/unit/core/commands/snapshot-restore.test.ts
- __tests__/unit/core/commands/snapshot-rollback.test.ts
- __tests__/unit/core/commands/snapshot-truncate.test.ts
- __tests__/unit/core/commands/snapshot-verify.test.ts
- packages/core-manager/src/actions/info-database-size.ts
- packages/core-snapshots/src/database-service.ts
- packages/core-snapshots/src/defaults.ts
- packages/core-snapshots/src/service-provider.ts
- packages/core/bin/config/devnet/app.json
- packages/core/bin/config/mainnet/app.json
- packages/core/bin/config/testnet/app.json
- packages/core/src/commands/config-manager.ts
Use core-database connection in core-snapshots.
Changes:
- core-snapshots depends on core-database package
- pass core-database connection data to snapshot workers
- updated `app.json` files
- use core-database connection in core-manager for  `info.databaseSize` action
- update `config:manager` CLI command
> refactor: use core-database connection in core-snapshots

- __tests__/unit/core-p2p/hapi-nes/client.test.ts
- packages/core-p2p/src/hapi-nes/client.ts
And remove useless `_isBrowser`
Needs #4309 before merge to fix failing test.
> chore(core-p2p): set default max payload on ws client

- __tests__/unit/core-snapshots/progress-renderer.test.ts
- packages/core-snapshots/package.json
- packages/core-snapshots/src/index.ts
- packages/core-snapshots/src/progress-renderer.ts
- packages/core/package.json
- packages/core/src/commands/snapshot-dump.ts
- packages/core/src/commands/snapshot-restore.ts
- packages/core/src/commands/snapshot-verify.ts
Move snapshots `ProgressRenderer` from core to core-snapshots.
> refactor: move snapshot progress renderer to core-snapshots package

- packages/core-kernel/src/contracts/kernel/queue.ts
`Queue` accepts only instances of `QueueJob` and not functions.
> refactor(core-kernel): allow only QueueJob in Queue

- __tests__/unit/core-cli/commands/command.test.ts
- packages/core/src/cli.ts
- packages/core/src/commands/help.ts
- Remove unused flags from core help command.
- Test verbosity
- Exit process with 0 when using --help flag
> fix(core): help output message and --help flag

- packages/core-p2p/src/socket-server/codecs/blocks.ts
Set hard limit number of txs to 500. (fixes devnet sync issue - we have at some point 500 txs per block)
> fix(core-p2p): hard limit number of txs in codec

- __tests__/unit/core-p2p/socket-server/routes/blocks.test.ts
- __tests__/unit/core-p2p/socket-server/routes/internal.test.ts
- __tests__/unit/core-p2p/socket-server/routes/peer.test.ts
- __tests__/unit/core-p2p/socket-server/routes/transactions.test.ts
- packages/core-p2p/src/hapi-nes/socket.ts
- packages/core-p2p/src/socket-server/routes/route.ts
Prevent exposing core-p2p routes on HTTP server. Are routes are now internal. Call are forwarded via websocket server.
> fix(core-p2p): use internal Hapi routes

- __tests__/unit/core-api/service-provider.test.ts
- packages/core-api/src/plugins/cache.ts
Cache plugin now caches:
- Status code of successful responses. Subsequent responses will return status code of original response instead of hard-coded 200.
- Headers. Subsequent responses will return headers of original response.
> fix(core-api): cache status code and headers

- __tests__/unit/core-p2p/service-provider.test.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-p2p/src/service-provider.ts
Build server on boot to allow usage of ioc in server routes. 
Use bootWhen and disposeWhen methods to control p2p server boot.
> chore(core-p2p): build server on boot

- __tests__/unit/core-p2p/service-provider.test.ts
- packages/core-p2p/src/service-provider.ts
Remove disposeWhen to prevent continuous server rebooting. Use check inside dispose to determine if server was booted.
> fix(core-p2p): dispose server

- __tests__/unit/core-forger/forger-service.test.ts
- __tests__/unit/core-p2p/network-state.test.ts
- packages/core-forger/src/forger-service.ts
- packages/core-kernel/src/contracts/p2p/network-state.ts
- packages/core-p2p/src/network-state.ts
Expose NetworkState getters for nodeHeight and lastBlockId. 
Make setLastBlock private.
> refactor(core-p2p): expose NetworkState getters

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/network-monitor.ts
Schedule network status updates when networkStart flag is set to enable peer reconnection.
> chore(core-p2p): schedule network status updates when networkStart flag is set

- __tests__/unit/core-transaction-pool/worker-script-handler.test.ts
- __tests__/unit/core-transaction-pool/worker.test.ts
- packages/core-kernel/src/contracts/transaction-pool/worker.ts
- packages/core-transaction-pool/src/worker-script-handler.ts
- packages/core-transaction-pool/src/worker.ts
Pass additional parameter `isVerified` form workers getTransactionFromData method. 
This PR ensures that transaction verify status is valid when transaction is made on worker pool and prevents invalid transactions to enter transaction pool and potentially being forged.
> fix(core-transaction-pool): accept only verified transactions

- __tests__/unit/core-magistrate-transactions/handlers/entity.test.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
Implement throwIfCannotEnterPool to prevent accepting register transactions with the same name into pool.
> chore(core-magistrate-transactions): implement throwIfCannotEnterPool on Entity

- __tests__/unit/core-transactions/handlers/__support__/app.ts
- __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
- packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Implement throwIfCannotEnterPool to prevent accepting transactions with the same MultiSignature address into pool.
> chore(core-transactions): implement throwIfCannotEnterPool on MultiSignatureRegistration

- __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
- packages/core-transactions/src/handlers/two/ipfs.ts
Implement throwIfCannotEnterPool to prevent accepting transactions with the same IPFS address into pool.
> chore(core-transactions): implement throwIfCannotEnterPool on IPFS

- packages/core-logger-pino/package.json
- yarn.lock
There were some issue in devnet sync over night that might be solved by using latest version 2.1.5 from rotating-file-stream.
Log of the devnet sync error : 
```
out: TypeError: Cannot read property 'write' of null
out:     at rewrite (/core/node_modules/rotating-file-stream/index.js:86:25)
out:     at /core/node_modules/rotating-file-stream/index.js:97:28
out:     at FSReqCallback.oncomplete (fs.js:169:5)
out:  ✖  uncaughtException (an exception was thrown but not caught)  TypeError: Cannot read property 'write' of null
out:     at rewrite (/core/node_modules/rotating-file-stream/index.js:86:25)
out:     at /core/node_modules/rotating-file-stream/index.js:97:28
out:     at FSReqCallback.oncomplete (fs.js:169:5)
out: terminate called after throwing an instance of 'std::bad_alloc'
out: …
```
> deps: bump rotating-file-stream min version to 2.1.5

- packages/core-state/src/service-provider.ts
Bind RoundState as singleton. It prevents unnecessary reads from DB because forgingDelegates are not initialized.
> fix(core-state): bind RoundState as singleton

- __tests__/unit/core-state/round-state.test.ts
- packages/core-state/src/round-state.ts
Remove last block from blocksInCurrent round after calling revert method, to successfully calculate previous delegates.
> fix(core-state): revert block

- __tests__/unit/core-test-framework/utils/transaction-factory.test.ts
- packages/core-test-framework/src/utils/transaction-factory.ts
I added `withVendorField` support to transaction factory.
The reason for this is that `TransactionFactory` from `core-test-framework` is extended and there is no support for testing vendorField via that `TransactionFactory`.
> feat(core-test-framework): added vendor field support to transaction factory

- __tests__/unit/core-p2p/chunk-cache.test.ts
- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-kernel/src/contracts/p2p/chunk-cache.ts
- packages/core-kernel/src/contracts/p2p/index.ts
- packages/core-kernel/src/ioc/identifiers.ts
- packages/core-p2p/src/chunk-cache.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/service-provider.ts
Reimplement downloaded chunkc cache, that uses FIFO (First In - First Out) to limit cache size.
> refactor(core-p2p): downloaded chunks cache

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-kernel/src/contracts/state/state-store.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-state/src/stores/state.ts
Skip 500 ms broadcast delay when block is forged.
> refactor(core-p2p): broadcast block delay

- __tests__/unit/core-state/wallets/wallet-repository.test.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-state/src/wallets/wallet-repository.ts
Remove duplicated method `valuesByIndex`. Keep `allByIndex` with same functionality.
> chore(core-state): remove valuesByIndex

- __tests__/unit/core-transaction-pool/processor.test.ts
- packages/core-transaction-pool/src/processor.ts
Use `Core` transaction type group by default for cases when transaction group is not provided. Now even transactions without defined `typeGroup` are processed by workers.
> chore(core-transaction-pool): use Core transaction group as default

- __tests__/unit/core-transaction-pool/sender-mempool.test.ts
- packages/core-transaction-pool/src/sender-mempool.ts
`removeForgedTransaction` no longer awaits potentially long `addTransaction` queue.
> fix(core-transaction-pool): prioritized removeForgedTransaction

- __tests__/unit/core-transaction-pool/service.test.ts
- packages/core-transaction-pool/src/service.ts
Do not remove just recently applied transaction from storage.
> fix(core-transaction-pool): keep previously forged transaction

- packages/core-p2p/src/peer-verifier.ts
If the starting height for the round is `X`, then last block height for the round is `X + <activeDelegates> - 1`.
Example : starting height for round 1 is 1, last block height in round is `1 + 51 - 1 = 51`
> fix(core-p2p): lastBlockHeightInRound computation

- packages/core-p2p/src/peer-verifier.ts
Use blockchain DposState in PeerVerifier.
> fix(core-p2p): use blockchain DposState in PeerVerifier

- __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
- packages/core-blockchain/src/processor/handlers/unchained-handler.ts
Remove BlockNotReadyCounter on Unchained handler. All downloaded blocks that have height higher than currentBlockHeight + 2 should be rejected.
> fix(core-blockchain): remove BlockNotReadyCounter on Unchained handler

- packages/core-kernel/package.json
- packages/core-kernel/src/services/search/pagination-service.ts
- yarn.lock
Improve pagination service sorting performance. Results (offset + limit) are kept sorted in binary tree rest remains unsorted. It's 10x faster at getting first page.
> fix(core-kernel): improve sorting performance

- packages/core-database/src/database-service.ts
Use deserializeTransactionsUnchecked on block factory to bypass api11 check. Transactions can not be successfully deserialzied when blockchain is already on height where api11 is set, but we are retrieving older block.
> fix(core-blockchain): deserializeTransactionsUnchecked

- __tests__/unit/core-logger-pino/driver.test.ts
- __tests__/unit/core-logger-pino/service-provider.test.ts
- packages/core-logger-pino/src/driver.ts
Split log files for each process. This will probably fix issue with missing logs. 
Log error when fileStream or stdout is closed or destoryed.
> fix(core-logger-pino): split log files per process

- install-next.sh
`ark config:cli --channel=next` causes an early exit bc we're already on `@arkecosystem/core@next`.
Removing the following line resolves this issue and allows successful completion of setup:
https://github.com/ArkEcosystem/core/blob/60bf124f393c908db23cec5b3bd7cd1d497653f7/install-next.sh#L227
> fix(install-next): remove bad line

- __tests__/unit/core-state/round-state.test.ts
- packages/core-kernel/src/contracts/state/dpos.ts
- packages/core-state/src/dpos/dpos-previous-round.ts
- packages/core-state/src/round-state.ts
Iterate over `getActiveDelegates()` because those have ranks.
> fix(core-state): iterate over active delegates who have ranks

- __tests__/unit/core-forger/client.test.ts
- packages/core-forger/src/client.ts
- packages/core-p2p/src/hapi-nes/client.ts
- Set max payload to `this._settings.ws.maxPayload` value provided during instantiation.
- Set high max payload for whole forger connection.
> fix(core-forger): set max payload for whole forger connection

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/network-monitor.ts
Fix rollback condition. Previously it simply looked for _majority had forked_ condition which resulted in stalemate when enough peers were not synced up to fork height.
```
10 peers at height 101
/
10 peers still syncing at height 90 ... 100
\
15 peers at height 101
```
Only those who passed fork height are compared now.
> fix(core-p2p): fix rollback condition

- __tests__/unit/core-p2p/network-monitor.test.ts
- packages/core-p2p/src/network-monitor.ts
Fix #4425.
Parse peers from URL response if response is type of string
> fix(core-p2p): parse peers from URL response

- __tests__/unit/core/commands/config-forger-bip38.test.ts
- __tests__/unit/core/commands/config-forger-bip39.test.ts
- __tests__/unit/core/commands/config-forger.test.ts
- packages/core/src/commands/config-forger-bip38.ts
- packages/core/src/commands/config-forger-bip39.ts
- packages/core/src/commands/config-forger.ts
Fix #4437.
Add `--skipValidation` flag to `config:forger`command, that allows setting bip39 incompatible passphrases.
> chore(core): allow invalid bip39 passphrases

- __tests__/unit/core-p2p/hapi-nes/client.test.ts
- packages/core-p2p/src/hapi-nes/client.ts
- packages/core-p2p/src/hapi-nes/listener.ts
Disable perMessageDefalate option on client and listener. Setting perMessageDefalate to false disables [websocket compression](https://github.com/websockets/ws#websocket-compression).
> fix(core-p2p): disable perMessageDeflate on WS

- __tests__/unit/core-logger-pino/driver.test.ts
Fix log rotate check. 
Rotating file stream is comparing interval to local time. To produce deterministic results tests are delayed and starts every time with 400ms delay after the last second.
> test(core-pino-logger): fix log rotate check

- __tests__/unit/core-p2p/hapi-nes/client.test.ts
- packages/core-p2p/src/hapi-nes/client.ts
_Re-opened_ #4434 by @alessiodf because it sill reduces probability of race when peers are communicating with each other.
> fix(core-p2p): reset max payload after ping

- packages/core-manager/src/utils/cli-manager.ts
Resolve @arkecosystem/core commands correctly. Fixes issue when commands can not be resolved when plugin is installed globaly.
> fix(core-manager): resolve commands path

- __tests__/unit/core-manager/actions/info-core-update.test.ts
- packages/core-manager/src/actions/info-core-update.ts
Use --force flag on update CLI command call to prevent asking for user input.
> fix(core-manager): use force flag on update

- __tests__/functional/transaction-forging/__support__/index.ts
- __tests__/integration/core-api/__support__/setup.ts
- __tests__/integration/core-magistrate-api/__support__/setup.ts
- __tests__/integration/core-state/__support__/setup.ts
- __tests__/integration/core-test-framework/utils/__support__/setup.ts
- __tests__/unit/core-blockchain/blockchain.test.ts
- __tests__/unit/core-kernel/ioc/decorator.test.ts
- __tests__/unit/core-kernel/services/queue/drivers/memory.test.ts
- __tests__/unit/core-kernel/services/queue/drivers/null.test.ts
- __tests__/unit/core-kernel/services/queue/service-provider.test.ts
- __tests__/unit/core-snapshots/database-service.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-kernel/src/contracts/kernel/queue.ts
- packages/core-kernel/src/ioc/decorator.ts
- packages/core-kernel/src/ioc/index.ts
- packages/core-kernel/src/services/queue/drivers/memory.ts
- packages/core-kernel/src/services/queue/drivers/null.ts
- packages/core-snapshots/src/database-service.ts
Improve MemoryQueue functionality by extending EventEmitter. 
OnDrain, OnError, OnData are replaced with appropriate emits.
> chore(core-kernel): Queue extends EventEmitter

- __tests__/unit/core-p2p/socket-server/plugins/await-block.test.ts
- packages/core-p2p/src/socket-server/plugins/await-block.ts
- packages/core-p2p/src/socket-server/server.ts
Implements await block processing plugin that delays non internal p2p server calls and prioritize block processing over request processing until block is applied. Implementation makes DoS attacks over P2P harder. 
Delay is not applied when downloading blocks, but only when node is synced. Delay is in rage of few milliseconds.
> chore(core-p2p): implements await block processing plugin

- __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
- packages/core-p2p/src/socket-server/controllers/blocks.ts
Remove unnecessary `transactions.length` check and unstable test. There is no way to deserialize `block.transactions` so its `length` will not match `block.data.numberOfTransactions`.
> chore(core-p2p): remove unnecessary transactions.length check

- __tests__/unit/core-transaction-pool/sender-state.test.ts
- packages/core-transaction-pool/src/sender-state.ts
Compare length of transaction binary representation to `maxTransactionBytes`.
> fix(core-transaction-pool): compare transaction.serialized.length with maxTransactionBytes

- packages/core-manager/package.json
Include @arkecosystem/core dependency to take advantage of update action, when core-manager is installed as plugin.
> deps(core-manager): include @arkecosystem/core

- __tests__/integration/core-magistrate-api/__support__/set-indexes.ts
- __tests__/integration/core-magistrate-api/controllers/entities.test.ts
- __tests__/integration/core-magistrate-api/services/entity-search-service.test.ts
- __tests__/unit/core-magistrate-api/__support__/index.ts
- __tests__/unit/core-magistrate-transactions/__support__/app.ts
- __tests__/unit/core-magistrate-transactions/handlers/__mocks__/wallet-repository.ts
- __tests__/unit/core-magistrate-transactions/handlers/entity.test.ts
- packages/core-magistrate-transactions/src/handlers/entity.ts
- packages/core-magistrate-transactions/src/service-provider.ts
- packages/core-magistrate-transactions/src/wallet-indexes.ts
Use EntityNamesTypes instad foreach to improve performance.  AutoIndex is set to false.
> chore(core-magistrate-transactions): use EntityNamesTypes index

- __tests__/unit/core-forger/client.test.ts
- __tests__/unit/core-p2p/peer-communicator.test.ts
- __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
- packages/core-kernel/src/contracts/p2p/blocks.ts
- packages/core-kernel/src/contracts/p2p/index.ts
- packages/core-p2p/package.json
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/schemas.ts
- packages/core-p2p/src/socket-server/codecs/blocks.ts
- packages/core-p2p/src/socket-server/codecs/proto/blocks.proto
- packages/core-p2p/src/socket-server/codecs/proto/protos.d.ts
- packages/core-p2p/src/socket-server/codecs/proto/protos.js
- packages/core-p2p/src/socket-server/controllers/blocks.ts
Send new height with `postBlock` response. It's used to update `/api/peers` endpoint. Fixes #4448
> Send new height with postBlock response

- __tests__/integration/core-api/controllers/locks.test.ts
- __tests__/unit/core-api/routes/locks.test.ts
- packages/core-api/src/routes/locks.ts
Require `/api/lock/unlocked` payload to be object and that it has `ids` property. Fixes #4481.
> fix(core-api): fix `/api/lock/unlocked` payload validation

- __tests__/unit/core/commands/plugin-install.test.ts
- __tests__/unit/core/source-providers/npm.test.ts
- packages/core/src/commands/plugin-install.ts
- packages/core/src/source-providers/abstract-source.ts
- packages/core/src/source-providers/contracts.ts
- packages/core/src/source-providers/npm.ts
Support installation of specific version of plugin. `ark plugin:install` command implements additional `--version` flag.
> chore(core): install specific version of plugin

- __tests__/unit/core-cli/services/process-manager.test.ts
- __tests__/unit/core-cli/utils/flags.test.ts
- __tests__/unit/core/commands/core-start.test.ts
- __tests__/unit/core/commands/forger-run.test.ts
- __tests__/unit/core/commands/forger-start.test.ts
- __tests__/unit/core/commands/relay-start.test.ts
- packages/core-cli/src/utils/flags.ts
Wrap flags, which are of type string in single quotes. This fix solves issues, when flag value includes [special characters](https://www.oreilly.com/library/view/learning-the-bash/1565923472/ch01s09.html). 
Single quote is exception and should be escaped with backslash character.
> fix(core-cli): wrap string flags in single quotes

- __tests__/unit/core-cli/actions/daemonize-process.test.ts
- packages/core-cli/src/actions/daemonize-process.ts
Available memory is unreliable indicator. Only check total memory when daemonizing the process.
> fix(core-cli): check total memory only

- packages/core/src/cli.ts
Set NODE_PATH and reinit resolve paths. NODE_PATH is set to node_modules folder that holds @arkecosystem packages. This enables plugins to use @arkecosystem pakages as peerDependencies.
> chore(core): set `NODE_PATH`

- __tests__/unit/core/cli.test.ts
- packages/core/src/cli.ts
Detect network from config paths. If only single network folder exists, then this is valid network. Network detection is used to load plugins from valid network, without using --network flag.
> fix(core): detect network from config path

- __tests__/unit/core/commands/core-start.test.ts
- __tests__/unit/core/commands/forger-start.test.ts
- __tests__/unit/core/internal/crypto.test.ts
- packages/core/src/commands/core-run.ts
- packages/core/src/commands/core-start.ts
- packages/core/src/commands/forger-run.ts
- packages/core/src/commands/forger-start.ts
- packages/core/src/exceptions/base.ts
- packages/core/src/exceptions/crypto.ts
- packages/core/src/exceptions/index.ts
- packages/core/src/index.ts
- packages/core/src/internal/crypto.ts
Implement and export custom crypto exceptions.
Use **skipPrompts** flag on:
- forger:run
- forger:start
- core:run
- core:start
> refactor(core): implements crypto exceptions and skipPrompts flag

- packages/core/package.json
Include joi in module aliases. Required by core-manager plugin.
> chore(core): include joi in module aliases

- __mocks__/better-sqlite3.js
- __mocks__/execa.js
- packages/core-cli/__tests__/__mocks__/execa.js
- packages/core-cli/__tests__/services/installer.test.ts
- packages/core-cli/__tests__/services/source-providers/git.test.ts
- packages/core-cli/__tests__/services/updater.test.ts
- packages/core/__tests__/__mocks__/execa.js
- packages/core/__tests__/commands/config-cli.test.ts
- packages/core/__tests__/commands/reinstall.test.ts
- packages/core/__tests__/commands/update.test.ts
Move root mocks under packages tests. Fixes issues with jest when single test is run from package.
> test: move root mocks under packages tests

- packages/core-blockchain/src/state-machine/actions/initialize.ts
The error message `FATAL: The genesis block payload hash is different from configured the nethash` does not make sense so I rearranged the word order so it makes sense: `FATAL: The genesis block payload hash is different from the configured nethash`.
> chore(core-blockchain): rearrange word order in error message

- packages/core-cli/src/input/parser.ts
- packages/core/__tests__/cli.test.ts
- packages/core/src/cli.ts
Disable prompts for network selection when multiple network configurations are present. 
This PR is required for core-manager and other plugins that requires running CLI command without additional prompts. 
Network selection can be achieved with --network=${network} flag to load plugins for selected network.
> fix(core): disable prompts for network selection

- packages/core-cli/__tests__/services/updater.test.ts
- packages/core-cli/src/services/updater.ts
- packages/core/__tests__/cli.test.ts
- packages/core/src/cli.ts
- await version check on cli and render if new version is available
- check can be skipped with `--skipVersionCheck` flag 
- remove check period from updated *
*Keeping check period results in false check and it may cause troubles with detecting latest version.
> fix(core): fix check for new version

- packages/core-kernel/src/contracts/transaction-pool/worker.ts
- packages/core-transaction-pool/src/worker-script-handler.ts
- packages/core-transaction-pool/src/worker.ts
Transform buffer to string before sending it to the child process. When worker receives string content it transform it back to buffer in order to deserialize it. 
This fixes exiting issue when broadcasting tranactions to other peers, where transactions are not processed.
> fix(core-transaction-pool): pass buffer content as string to child processes

- docker/production/Dockerfile
> chore: use `python3` in docker

- packages/core-cli/__tests__/actions/daemonize-process.test.ts
- packages/core-cli/__tests__/services/setup.test.ts
- packages/core-cli/src/actions/daemonize-process.ts
- packages/core-cli/src/application-factory.ts
- packages/core-cli/src/contracts.ts
- packages/core-cli/src/ioc/identifiers.ts
- packages/core-cli/src/services/index.ts
- packages/core-cli/src/services/setup.ts
- packages/core/__tests__/commands/core-start.test.ts
- packages/core/__tests__/commands/forger-start.test.ts
- packages/core/__tests__/commands/relay-start.test.ts
- packages/core/src/commands/core-start.ts
- packages/core/src/commands/forger-start.ts
- packages/core/src/commands/relay-start.ts
Check if core is installed globally using pnpm when daemonizing processes. If global setup is detected then create path to ark command from pnpm root dir. This prevents starting core from specific relese, but uses a [Capistrano like deployments](https://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments).
This fixes the issues with version lock. Now latest core version is selected on restart after updating. 
Notes: Running start:* commands is also possible when yarn is used.
> fix(core-cli): use global entrypoint when core is installed globaly

- packages/core/__tests__/commands/reinstall.test.ts
- packages/core/src/commands/reinstall.ts
Skip prompts if --force is used in reinstall command.
Mock installer in tests.
> fix(core): skip prompts if --force is used in `reinstall` command

- packages/core/__tests__/commands/update.test.ts
- packages/core/src/commands/update.ts
Set --updateProcessManager to false by default in update command.
Mock installer in tests.
> refactor(core): set --updateProcessManager to false by default in `update` command

- __tests__/unit/core-cli/services/installer.test.ts
- packages/core-cli/src/services/installer.ts
Fixes #4601.
Two things worth mentioning:
1. This could be refactored to use `fs.existsSync` and `fs.unlinkSync` if desired rather than `rm -f` via the shell, but I thought the latter would be easier since we're already executing a command via the shell anyway when running `yarn global add`.
2. This PR is aimed at the `master` branch since it is specific to `yarn` rather than `pnpm` as used in `develop` and I think the issue is important enough to warrant being fixed in Core 3.1 rather than being deferred to 4.0.
> fix(core-cli): delete better_sqlite3.node before installing

- packages/core-cli/__tests__/services/installer.test.ts
- packages/core-cli/__tests__/services/updater.test.ts
- packages/core-cli/src/services/installer.ts
- packages/core/__tests__/commands/config-cli.test.ts
Fix peerDependencies installation in Installer. Code is modified because, pnpm uses different command output than yarn. 
Install peer dependencies only if existing peer dependency doesn't satisfy defined version range. 
This prevents pm2 package installation every time new pm2 version is published. Pm2 causes issues with ProcessManager class when installed version is not the same as currently running version.
> fix(core-cli): peerDependencies installation

- __tests__/integration/core-api/services/__support__/setup.ts
- __tests__/unit/core-api/services/delegate-search-service.test.ts
- packages/core-api/src/services/delegate-search-service.ts
> fix(core-api): use current supply to calculate delegates approval

- __tests__/unit/core-api/controllers/controller.test.ts
- __tests__/unit/core-api/controllers/delegates.test.ts
- __tests__/unit/core-api/controllers/locks.test.ts
- __tests__/unit/core-api/controllers/wallets.test.ts
- packages/core-api/src/controllers/controller.ts
- packages/core-api/src/resources-new/block.ts
- packages/core-api/src/resources-new/transaction.ts
- packages/core-api/src/schemas.ts
Fix sorting with multiple orderBy values
Remove excess transform code
> fix(core-api): sorting with multiple orderBy values

- packages/core-api/src/plugins/pagination/ext.ts
Take orderBy from original query to generate pagination. This fixes issue when orderBy is set by default and it produces invalid pagination value.
> fix(core-api): empty orderBy in pagination result 

- packages/core-api/package.json
- packages/core-api/src/plugins/pagination/ext.ts
- pnpm-lock.yaml
Replace **querystring** with [qs](https://www.npmjs.com/package/qs). 
Use **allowDots** option for nesting. 
Fixes: #4647
> fix(core-api): replace deprecated `querystring` with `qs` and use dot notation

- packages/core-api/src/plugins/pagination/ext.ts
Use comma separator for query array.
> fix(core-api): use comma separator for query array

- packages/core-api/package.json
- packages/core-api/src/plugins/pagination/ext.ts
- yarn.lock
Cherry pick:
- fix(core-api): replace deprecated `querystring` with `qs` and use dot notation (#4648)
- fix(core-api): use comma separator for query array (#4650)
- fix(core-api): undencoded query (#4652)
Changes:
- Yarn lock
> merge: cherry-pick `core-api` changes from develop

- packages/core-p2p/src/peer-processor.ts
> fix(core-p2p): set default headers

- packages/core-database/src/migrations/20220606000000-disable-fastupdate-on-gin-indexes.ts
Disable fastupdate option on GIN indexes to achieve constant insert time. It fixes random delays when processing blocks due cleanup cycle. 
The credit for the reported issue and suggesting various solutions goes to: @alessiodf
> fix(core-database): disable fastupdate option on GIN indexes

- packages/crypto/__tests__/blocks/block.test.ts
- packages/crypto/src/transactions/serializer.ts
Reduce buffer allocated for transaction to maxBlockPaylod / maxTransaction. Fix drasticaly improves serialization performance (4 - 8 times faster, depending on system configuration and network setting).
> fix(crypto): Reduce allocated buffer size for transaction serialization

- packages/core-database/__tests__/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
Convert vendorField query parameter to buffer. Solves issues with queries like:
https://api.ark.io/api/transactions?vendorField=%00
https://api.ark.io/api/transactions?vendorField=\
The credit for the reported issue goes to: @alessiodf
> fix(core-database): convert vendorField query parameter to buffer

- CODEOWNERS
- __tests__/unit/core-database/transaction-filter.test.ts
- __tests__/unit/crypto/blocks/block.test.ts
- packages/core-database/src/migrations/20220606000000-disable-fastupdate-on-gin-indexes.ts
- packages/core-database/src/transaction-filter.ts
- packages/core/src/commands/config-forger.ts
- packages/crypto/src/transactions/serializer.ts
- packages/crypto/src/validation/schemas.ts
- fix(crypto): walletVote schema is public key (#4663)
- fix(core): remove unused bip38 flag (#4666)
- chore: update codeowners (#4673)
- Disable fast update (#4671)
- fix(crypto): Reduce allocated buffer size for transaction serialization (#4670)
- fix(core-database): convert vendorField query parameter to buffer (#4672)
> merge: cherry pick from `develop`

- packages/core-p2p/src/defaults.ts
- packages/core-p2p/src/utils/is-valid-version.ts
- don't use min versions defined in milestones
- use versions defined in default.ts
- add 4.0.0-next in version checks
> refactor(core-p2p): get min peer version from `default.ts` instead of milestones

- packages/core-kernel/src/contracts/p2p/peer-verifier.ts
- packages/core-kernel/src/contracts/p2p/peer.ts
- packages/core-p2p/__tests__/network-monitor.test.ts
- packages/core-p2p/__tests__/network-state.test.ts
- packages/core-p2p/__tests__/peer-communicator.test.ts
- packages/core-p2p/__tests__/peer-verifier.test.ts
- packages/core-p2p/src/network-monitor.ts
- packages/core-p2p/src/network-state.ts
- packages/core-p2p/src/peer-communicator.ts
- packages/core-p2p/src/peer-verifier.ts
- packages/core-p2p/src/peer.ts
Add fast option to the peer verification. Fast option is only used to calculate quorum before forging. It skips the calculation of the highest common block. Result is saved in separate property to prevent collision with the normal check.
> fix(core-p2p): skip highest common block search on fast validation 

- packages/core-api/src/controllers/blocks.ts
Use ITransactionData insted ITransaction data type as part of resource attribute when using BlockWithTransactionsResource. 
This fixes the issue caused by missing asset property on transaction object when MultiPayment total transfer ammount is calculated, that caused internal server errors.
Issue is described in details on: https://github.com/Solar-network/core/pull/63 by @alessiodf
> fix(core-api): use `ITransactionData` in argument with `BlockWithTransactionsResource`

- packages/core-blockchain/__tests__/processor/block-processor.test.ts
- packages/core-blockchain/src/processor/block-processor.ts
- packages/core-database/__tests__/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
- packages/core-state/src/block-state.ts
Check if wallet exist before calling findByAddress or findByPublicKey on walletRepository. Side effect of named methods is wallet creation, which can be inappropriately used to generate wallets that are not generated by any know transaction. 
This PR is partially based on the code from: https://github.com/Solar-network/core/pull/99 by @alessiodf
> fix: prevent new wallet creation in API requests

- packages/core-api/src/services/delegate-search-service.ts
Order resigned delegates by publicKey. Non resigned delegates are ordered by rank by default.
> refactor(core-api): order resigned delegates by publicKey

- packages/core-state/__tests__/wallets/wallet-repository-copy-on-write.test.ts
- packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
Create new wallet in WalletRepositoryCopyOnWrite instead main WalletRepository. This prevents WalletRepository pollution in transaction pools sender state. When address does not exists in WalletRepository neither in WalletRepositoryCopyOnWrite, then new wallet is created only in WalletRepositoryCopyOnWrite. WalletRepository is not aware of the new wallet until block is processed.
> fix(core-state): create new wallet instance in `WalletRepositoryCopyOnWrite` 

- packages/core-p2p/__tests__/utils/is-valid-version.test.ts
- packages/core-p2p/src/utils/is-valid-version.ts
- packages/crypto/package.json
- pnpm-lock.yaml
Node version should pass both version setting in configuration and in milestones. If value is not defined, then check is skipped.
> fix(core-p2p): node version should pass min version defined in configuration and milestones

- packages/core-cli/src/services/setup.ts
Exclude node_modules from global path check. 
New pnpm version stores files differently under: 
`/home/ark/.pnpm/5/.pnpm/`
compared to previous version:
`/home/ark/.pnpm/5/node_modules/.pnpm/`
When `node_modules` is excluded from isGlobal check satisfies both structures.  This PR fixes the issue when `ark <relay|core|forge>:start` is run with direct path instead relative path and causes problem with `ark update` command.
> fix(core-cli): exclude `node_modules` folder from global path check

- packages/crypto/package.json
- yarn.lock
Update @arkecosystem/typescript-crypto-networks to 1.2.2. New version sets p2p.minimumVersions [milestone](https://github.com/ArkEcosystem/typescript-crypto-networks/commit/863e0f607898defd20d2e8e23c351df08cfb4057) on mainnet.
> deps(crypto): update `@arkecosystem/crypto-networks` to 1.2.2

- packages/core-api/src/controllers/delegates.ts
Use block query criteria on delegates route. Fixes  #4700
> fix(core-api): use block query criteria on delegates route

- packages/core/__tests__/commands/pool-clear.test.ts
- packages/core/src/commands/pool-clear.ts
Fixes invalid path defined in pool:clear command. Now all 3 files created by sqlite are removed:
- transaction-pool.sqlite
- transaction-pool.sqlite-shm
- transaction-pool.sqlite-wal
> fix(core): remove all sqlite files with `pool:clear` command

- packages/core-webhooks/__tests__/listener.test.ts
- packages/core-webhooks/src/listener.ts
Use timeout form defaults.ts for broadcast timeout value.
> fix(core-webhooks): use timeout form defaults.ts for broadcast

- packages/core-webhooks/__tests__/service-provider.test.ts
- packages/core-webhooks/src/service-provider.ts
Enable listener only when core-webhooks are enabled. This prevents starting listener and sending webhook POST messages out to previously added webhooks. Webhooks can be enabled with `CORE_WEBHOOKS_ENABLED` flag.
> fix(core-webhooks): enable listener when webhooks are enabled

- tsconfig.json
Enable [declarationMap](https://www.typescriptlang.org/tsconfig#declarationMap) for TS.
_Generates a source map for .d.ts files which map back to the original .ts source file. This will allow editors such as VS Code to go to the original .ts file when using features like Go to Definition._
> chore: enable `declarationMap` typescript option

- packages/core-blockchain/__tests__/process-blocks-job.test.ts
- packages/core-blockchain/__tests__/processor/handlers/accept-block-handler.test.ts
- packages/core-blockchain/__tests__/processor/handlers/revert-block-handler.test.ts
- packages/core-blockchain/src/process-blocks-job.ts
- packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
- packages/core-blockchain/src/processor/handlers/revert-block-handler.ts
- packages/core-transaction-pool/__tests__/service.test.ts
- packages/core-transaction-pool/src/service.ts
Apply block on transaction-pool after block broadcast. 
Use direct transaction-pool service calls instead handler. 
applyBlock is run exclusively.
> fix(core-blockchain): apply block on transaction-pool after block broadcast

- packages/core-database/src/repositories/abstract-repository.ts
Change order by on first column to force PostgreSQL query optimizer to take faster query procedure when transactions are ordered by timestamp:asc only and limit is less than 6.
> fix(core-database): query optimizer workaround

- package.json
- yarn.lock
Update [lerna](https://github.com/lerna/lerna) to 6.0.3
> deps: update lerna to 6.0.3

- install-rc.sh
> chore: add install-rc.sh script

- __tests__/unit/core-api/controllers/blockchain.test.ts
- __tests__/unit/core-api/services/delegate-search-service.test.ts
- __tests__/unit/core-kernel/utils/delegate-calculator.test.ts
- __tests__/unit/core-kernel/utils/supply-calculator.test.ts
- __tests__/unit/core-transactions/handlers/__support__/app.ts
- __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
- __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
- __tests__/unit/core-transactions/handlers/two/transaction.test.ts
- __tests__/unit/core/commands/network-generate.test.ts
- packages/core-api/src/controllers/blockchain.ts
- packages/core-api/src/services/delegate-search-service.ts
- packages/core-kernel/src/contracts/state/wallets.ts
- packages/core-kernel/src/utils/delegate-calculator.ts
- packages/core-kernel/src/utils/supply-calculator.ts
- packages/core-state/src/wallets/wallet-repository.ts
- packages/core-test-framework/src/app/generators/crypto.ts
- packages/core-transactions/src/errors.ts
- packages/core-transactions/src/handlers/transaction.ts
- packages/core-transactions/src/handlers/two/htlc-lock.ts
- packages/core-transactions/src/handlers/two/multi-payment.ts
- packages/core/src/commands/network-generate.ts
- packages/crypto/package.json
- yarn.lock
Add support for burn address.
- prevents sending transactions from burn address
- prevent sending multi payments to burn address
- prevent sending HTLC Lock to burn address
- changes in supply calculator (returns BigNumber)
- changes in delegate calculator (requires burned supply)
- generate burn address with **network:generate** command
- /api/blockchain return **supply**, **generated**, **burned** fields
- add **blockBurnAddress** milestone used in HTLCLock and MultiPayment transactions
> feat: support burn address

- packages/core-cli/src/services/config.ts
Allow `rc` channel in config. This fixes problem while using `ark update` command. Before fix, it defaults to **latest** channel when `rc` channel was actually used.
> fix(core-cli): allow `rc` channel in config

- packages/core-database/src/repositories/abstract-repository.ts
Reverts ArkEcosystem/core#4726
#4758 Fixes the problem and workaround is not needed.
> revert: "fix(core-database): query optimizer workaround"

- __tests__/integration/core-api/services/delegate-search-service.test.ts
- __tests__/integration/core-api/services/lock-search-service.test.ts
- __tests__/integration/core-api/services/wallet-search-service.test.ts
- __tests__/integration/core-magistrate-api/services/entity-search-service.test.ts
- __tests__/unit/core-api/controllers/delegates.test.ts
- __tests__/unit/core-api/controllers/locks.test.ts
- __tests__/unit/core-api/controllers/wallets.test.ts
- __tests__/unit/core-api/services/delegate-search-service.test.ts
- __tests__/unit/core-api/services/lock-search-service.test.ts
- __tests__/unit/core-api/services/wallet-search-service.test.ts
- __tests__/unit/core-kernel/services/search/pagination-service.test.ts
- __tests__/unit/core-magistrate-api/controllers/entities.test.ts
- packages/core-api/src/controllers/delegates.ts
- packages/core-api/src/controllers/locks.ts
- packages/core-api/src/controllers/wallets.ts
- packages/core-api/src/services/delegate-search-service.ts
- packages/core-api/src/services/lock-search-service.ts
- packages/core-api/src/services/wallet-search-service.ts
- packages/core-kernel/src/services/search/pagination-service.ts
- packages/core-magistrate-api/src/controllers/entities.ts
- packages/core-magistrate-api/src/services/entity-search-service.ts
Make pagination service non blocking, by using setImmediate callback every 1000 items.
> fix(core-kernel): make pagination service non blocking

- __tests__/unit/core-api/service-provider.test.ts
- packages/core-api/src/defaults.ts
- packages/core-api/src/service-provider.ts
Set queueLimit to 5. And allow setting concurrency to 0.
> chore(core-api): adjust semaphore plugin defaults & allow 0 concurrency

- __tests__/integration/core-api/handlers/transactions.test.ts
- __tests__/unit/core-database/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
Remove the delegateRegistrationExpression, because it is unnecessary expression. Generated query is already comparing senderPublicKey.
Expression:
```
{
op: "or",
expressions: [
{ property: "senderPublicKey", op: "equal", value: "456" },
{ property: "recipientId", op: "equal", value: "123" },
{
op: "and",
expressions: [
{ property: "typeGroup", op: "equal", value: Enums.TransactionTypeGroup.Core },
{ property: "type", op: "equal", value: Enums.TransactionType.MultiPayment },
{ property: "asset", op: "contains", value: { payments: [{ recipientId: "123" }] } },
],
},
{
op: "and",
expressions: [
{ property: "typeGroup", op: "equal", value: Enums.TransactionTypeGroup.Core },
{ property: "type", op: "equal", value: Enums.TransactionType.DelegateRegistration },
{ property: "senderPublicKey", …
```
> fix(core-database): remove delegate registration expression

- __tests__/unit/core-database/transaction-filter.test.ts
- packages/core-database/src/transaction-filter.ts
Remove type and typeGroup for recipients included in multi payment transactions.  Payments in multi payment asset are indexed and removing type and type group helps SQL optimizer to select better query plan.
> fix(core-database): improve search by address

- packages/core-api/src/resources-new/transaction.ts
Add `address` into transactionQueryLevelOptions. Queries which filter by address are marked as L1 in semaphore plugin. This is because request is transformed to query that is using recipientId and senderPublicKey, which are both indexed fields on transactions table.
> fix(core-api): add `address` into transactionQueryLevelOptions

- __tests__/unit/core-blockchain/blockchain.test.ts
- packages/core-blockchain/src/blockchain.ts
- packages/core-blockchain/src/defaults.ts
- packages/core-blockchain/src/service-provider.ts
On readonly nodes that have p2p disabled or doesn't expose public IP fastSync mode can be used to improve the download block frequency. Node that have fastSync enabled will use the 8 sec rate over the default 60 sec rate to improve sync. This results in more frequent block download actions. 
Feature can be enabled via: **CORE_BLOCKCHAIN_FAST_SYNC** env variable.
> feat(core-blockchain): increase block download frequency using fastSync option 

- packages/core/bin/run
Discover libjemalloc.so without installed gcc. This adds support for docker builds without gcc.
> feat(core): discover libjemalloc.so without installed gcc
