README.md

useful to understand the ecosystem of packages.

chore: add core packages to readme

---

packages/core-p2p/lib/server/versions/1/handlers.js

Improve readability of log message

fix: getBlocks log wording

---

packages/core-blockchain/lib/state-machine.js

Thanks Brian
#devnet discussion with Brian to improve log messages

Log message improvements

---

packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-database/lib/interface.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/1/handlers.js

The broadcast system is improved in order to decrease the number of blocks flying on the network, and thus decreasing bandwidth pressure on nodes issue.
The main idea is to listen for the numbers of blocks you received. If 'too many' blocks are received it means it has been broadcasted quite a lot.
One concept has been introduced: BlockPing, counting the number of time the last block has pinged the node
2 parameters have been introduced:
- `maxhop` ( default 4): how many times you got pinged by the same block. this is roughly linked to the number of times a block has jumped between nodes, while not exactly this
- `delay`: we count the number of hops during a minimum period of 0.5s
both parameters are empiric. Later on `delay` could be calculated from network stats by listening how long …

Broadcast improvements

---

packages/core-json-rpc/lib/server/services/network.js

In the current situation where v1 and v2 (relay) nodes are mixed on the network some queries need to be executed on the p2p port (4001/4002) and others on the API port 4003. (e.g. /peer/list vs /api/loader/autoconfigure: both of these example queries are used by this RPC). When queried on the wrong port, the node will reply with a 404 error. This fix checks for that error and will try the query again switching between p2p and api ports.
If this is a …

fix: let JSON RPC getFromNode() method query v1 and v2 nodes (p2p/api)

---

packages/core-api/lib/utils/delegate-calculator.js
packages/core-api/lib/versions/1/handlers/accounts.js
packages/core-api/lib/versions/1/handlers/blocks.js
packages/core-api/lib/versions/1/handlers/delegates.js
packages/core-api/lib/versions/1/handlers/loader.js
packages/core-api/lib/versions/1/handlers/signatures.js
packages/core-api/lib/versions/1/transformers/transaction.js
packages/core-api/lib/versions/2/handlers/node.js
packages/core-api/lib/versions/2/transformers/delegate.js
packages/core-api/lib/versions/2/transformers/transaction.js
packages/core-blockchain/__tests__/blockchain.test.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-database-sequelize/__tests__/spv.test.js
packages/core-database/lib/interface.js
packages/core-forger/lib/manager.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/internal/handlers.js
packages/core-transaction-pool/lib/interface.js
packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

This change brings consistency to how the getLastBlock and getLastDownloadedBlock methods work by returning a Block model instance.

refactor: return block model for getLastBlock & getLastDownloadedBlock

---

lerna.json
package.json
plugins/.gitignore

This adds a `plugins` directory that can be used to install third-party plugins without causing any conflicts with the upstream when core updates are available.

feat: third-party plugins folder

---

packages/core-forger/lib/manager.js

A newly forged block was never logged which made testing somewhat annoying.

chore: log newly forged block

---

packages/core-p2p/lib/monitor.js

Adding detail to generic error messages

Error logging updates per function

---

packages/core-api/lib/versions/1/handlers/accounts.js
packages/core-api/lib/versions/1/handlers/blocks.js
packages/core-api/lib/versions/1/handlers/delegates.js
packages/core-api/lib/versions/1/handlers/transactions.js
packages/core-api/lib/versions/1/utils.js

Resolves https://github.com/ArkEcosystem/core/issues/656
- [ x Lint and unit tests pass locally with my changes

fix: bad method call for unconfirmed transaction endpoint

---

packages/core-api/lib/versions/2/transformers/delegate.js

/api/v2/delegates API endpoint fails (see #665)

fix: delegate object has no data property

---

packages/core-api/lib/versions/2/handlers/transactions.js

The unconfirmed transactions endpoint failed because of bad method calls to the transaction pool.

fix: bad method calls for unconfirmed transactions

---

README.md

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Added Github Development Bounty link

---

packages/crypto/__tests__/crypto/crypto.test.js

Corrected expected value in getId test description to match actual expected value in test.
This change is more of a typo fix as it does not change any test logic, just the description.

Correct test description

---

packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/utils/tick-sync-tracker.js
packages/core-database-sequelize/lib/repositories/blocks.js
packages/core-p2p/lib/manager.js
packages/core-p2p/lib/monitor.js

Implementation of the code @zillionn posted here https://github.com/ArkEcosystem/core/issues/680#issuecomment-398333793.

refactor: use download progress instead of timestamps for tracker

---

packages/core-api/lib/versions/2/handlers/delegates.js
packages/core-api/lib/versions/2/index.js
packages/core-api/lib/versions/2/schema/delegates.js

This endpoint will allow delegates to perform a fast API call to get a list of all their voters and balances. If they need full details about their voters they can call `/api/delegates/{id}/voters` with `API-Version: 2` as header.

feat: voter balances endpoint in v2

---

packages/core-blockchain/lib/utils/tick-sync-tracker.js
packages/core-blockchain/package.json

Resolves https://github.com/ArkEcosystem/core/issues/688

feat: add time estimate to sync tracker

---

packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/utils/tick-sync-tracker.js
packages/core-database-sequelize/lib/repositories/blocks.js

Improves the time tracking during sync as the previous was somewhat inaccurate.

refactor: improved time tracking during sync

---

packages/core-database-sequelize/__tests__/connection.test.js
packages/core-database-sequelize/lib/connection.js

Fix for database verification with postgres

Verify blockchain fix

---

packages/core-api/lib/index.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-config/lib/loader.js
packages/core-container/lib/container.js
packages/core-database-sequelize/lib/connection.js
packages/core-database-sequelize/lib/index.js
packages/core-database/lib/index.js
packages/core-database/lib/interface.js
packages/core-forger/lib/manager.js
packages/core-graphql/lib/index.js
packages/core-json-rpc/lib/index.js
packages/core-p2p/lib/index.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-transaction-pool-redis/lib/index.js
packages/core-webhooks/lib/index.js

Less noise in the logs and readable logging of the height by using `toLocaleString`.

imp: less noise & readable height logging

---

packages/core-api/lib/index.js
packages/core-api/lib/server.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/index.js
packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/utils/tick-sync-tracker.js
packages/core-forger/lib/client.js
packages/core-graphql/lib/index.js
packages/core-graphql/lib/server.js
packages/core-json-rpc/lib/index.js
packages/core-json-rpc/lib/server/index.js
packages/core-logger-winston/lib/driver.js
packages/core-logger-winston/lib/formatter.js
packages/core-p2p/lib/index.js
packages/core-p2p/lib/manager.js
packages/core-p2p/lib/monitor.js
packages/core-webhooks/lib/index.js

Follow up to https://github.com/ArkEcosystem/core/pull/704 to further reduce logging noise and reduce the strain on eyes to read debug messages.

imp: further reduce log noise

---

packages/core-blockchain/lib/utils/tick-sync-tracker.js
packages/core-logger-winston/lib/driver.js
packages/core-logger/lib/interface.js

Fixes an issue with postgres and numbers being not casted which resulted in the tracker being hidden.

fix: sync tracker with postgres

---

packages/core-api/lib/versions/1/transformers/voter.js

Another day, another PR: voter balance is a String and not a number to match v1 api.

imp: made voter balance String to match v1 api

---

packages/crypto/__tests__/handlers/transactions/multi-signature.test.js

rename multiSignature to multisignatureTest to reflect consistency; and change this constant to include min, lifetime (and keysgroup, the original keys were part of the root array of the constant) properties to enable proper testing of the wallet.multisignature when it gets passed to multisignature-handler, transaction-handler and wallet-model
- [ x ] Test (adding missing tests or fixing existing tests)
- [ x ] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation
- [ x ] Lint and unit tests pass locally with my changes
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added necessary documentation (if appropriate)
closes #703

rename and mock value structure change

---

packages/crypto/__tests__/crypto/crypto.test.js

Added additional test result validation.  Added new crypto.sign test.
Updated existing tests with additional validation

Add additional test result validation

---

packages/crypto/__tests__/utils/network-list.js

module.exports = { NETWORKS_LIST, NETWORKS } instead or export {...}
fixes logged errors when testing multiple modules in packages/crypto
- [ x ] Test (adding missing tests or fixing existing tests)
- [ x ] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation
- [ x ] Lint and unit tests pass locally with my changes
closes #716

fix export statement

---

packages/core-forger/__tests__/client.test.js
packages/core-forger/lib/client.js
packages/core-forger/lib/manager.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js
packages/core-p2p/lib/utils/network-state.js
packages/core/lib/config/devnet/peers.json
packages/core/lib/config/mainnet/peers.json
packages/core/lib/config/testnet.1/peers.json
packages/core/lib/config/testnet.2/peers.json
packages/core/lib/config/testnet/peers.json

- Refactor of forger
- Added coldStart and whitelist to the peers
- Added blacklist on getPeers function return

Forger refactoring

---

packages/core-p2p/__tests__/server/internal.test.js
packages/core-p2p/__tests__/utils/is-myself.test.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/internal/handlers.js
packages/core-p2p/lib/utils/is-myself.js

P2P updates  and tests and bugsfixes

---

packages/core-api/lib/utils/transformer.js
packages/core-api/lib/versions/2/handlers/peers.js
packages/core-api/lib/versions/2/index.js
packages/core-forger/lib/manager.js
packages/core-p2p/__tests__/utils/is-myself.test.js
packages/core-p2p/lib/manager.js
packages/core-p2p/lib/monitor.js

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

feat: suspended peers endpoint for v2

---

.travis.yml
packages/client/package.json
packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-config/package.json
packages/core-container/package.json
packages/core-database-sequelize/package.json
packages/core-deployer/package.json
packages/core-json-rpc/package.json
packages/core-logger-winston/package.json
packages/core-p2p/package.json
packages/core-test-utils/package.json
packages/core-tester-cli/package.json
packages/core-transaction-pool-redis/package.json
packages/core-transaction-pool/package.json
packages/core-webhooks/package.json
packages/core/package.json
packages/crypto/package.json
packages/validation/package.json

Check the dependencies on Travis

Add depcheck command to Travis CI

---

packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/machines/actions/rebuild-from-network.js
packages/core-blockchain/lib/machines/blockchain.js
packages/core-blockchain/lib/state-machine.js

- When rebuilding from 0, after last sync, and error would occur 
- State machine didn't move forward after complete rebuild

State machine rebuild  chain fix

---

packages/core-database-sequelize/__tests__/spv.test.js

The lastBlock has no data property.

Fix spv __buildLastForgedBlocks unit test

---

packages/core-blockchain/lib/state-machine.js
packages/core-database-sequelize/lib/connection.js
packages/core-database-sequelize/lib/migrations/20180305163243-create-transaction.js
packages/core-database-sequelize/lib/migrations/20180628100408-update-transaction.js.back
packages/core-database-sequelize/lib/models/transaction.js
packages/crypto/lib/models/block.js
packages/crypto/lib/models/transaction.js

Fix to address correct sequence of transaction in blocks (same as in v1).
**
> Rebuild from 0  after this update!!!
**
Rebuild from 0 is needed after this update!!!

Sequence tx fix

---

.travis.yml

Travis is not generating the code coverage

Fix Travis CI code coverage

---

jest.config.js
packages/core-transaction-pool-redis/__tests__/connection.test.js
packages/core-transaction-pool/__tests__/guard.test.js
packages/core-transaction-pool/__tests__/interface.test.js
packages/core/lib/config/mainnet/peers.json

This will run those tests on Travis CI

Enable the core-test-utils tests on the root Jest config

---

.travis.yml

Includes a change that should have been included on https://github.com/ArkEcosystem/core/pull/757

Fix the test command (`script`) of Travis CI

---

packages/core-database-sequelize/__tests__/repositories/transactions.test.js

Remove unneeded check for valid transactions in supposedly empty array. We already check that the transaction array is empty.

Test refactor : Remove unneeded check for valid transactions in supposedly empty array

---

packages/core-transaction-pool-redis/CHANGELOG.md
packages/core-transaction-pool/CHANGELOG.md

docs: changelogs

---

packages/core-database-sequelize/lib/connection.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-tester-cli/lib/commands/transfer.js

Adding missing fields from v2 api response. Edge case, was happening only when v2 forged, and other v1 nodes requested forged transaction data from v2 node. The data did not contain all the fields....
As is critical, still leaves room for improvement. We need transformers and other stuff on p2p api, to have one place for such transformations. Similar to core-api.

Sender id patch

---

packages/core-p2p/lib/monitor.js

Rejects blacklisted peers to prevent them from being added to the

feat: reject blacklisted peers

---

packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/interface.js

The code before this change operated with two arrays:
1. all transactions ids (N elements)
2. forged transactions ids (M elements)
for each element in 1.
if it is in 2. (linear search, O(M)), then remove it from 1.
This has complexity of O(N*M).
Change the check whether an element is in 2. to O(1) by using Set
instead of an array. So, overall this becomes O(N).

Improve computational complexity when removing forged transactions

---

packages/core-blockchain/lib/queue/rebuild.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-tester-cli/lib/utils/get-constants.js

branch for #801 
when: `console.log(error)` 
replace by: import logger instance and `logger.error(error)`
working on a well-structured comment to illustrate and compare clearly for easier merging
- [ x ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ x ] I have read the [CONTRIBUTING](https://docs.ark.io/developers/guidelines/contributing.html) documentation
- [ x ] Lint and unit tests pass locally with my changes
- [ x ] I have added necessary documentation (if appropriate)
track documentation in issue #801 ; will be posting a larger comment

console.log(error) >> logger.error(error)

---

packages/core-database-sequelize/lib/spv.js
packages/crypto/__tests__/models/wallet.test.js
packages/crypto/lib/models/wallet.js

There are issues when applying a block to a wallet. I've done casting to number in a few places to ensure values get incremented and not concatenated.
@faustbrian can you confirm whether bignum is necessary here please.

Fix forged casting

---

packages/core-database-sequelize/lib/connection.js
packages/core-json-rpc/lib/server/services/network.js
packages/core-p2p/lib/server/versions/internal/handlers.js

Remove commented console.log calls
Resolves #801

rm all commented console.log

---

packages/core-api/lib/versions/1/handlers/accounts.js

fix(core-api): bug in the v1/accounts/delegate endpoint

---

packages/core-blockchain/lib/blockchain.js
packages/core-database-sequelize/__tests__/connection.test.js
packages/core-database-sequelize/lib/connection.js
packages/core-database/lib/interface.js

refactor: Optimisations fix

---

packages/core-tester-cli/bin/tester
packages/core-tester-cli/lib/commands/transfer.js
packages/core-tester-cli/lib/commands/vote.js
packages/core-tester-cli/package.json

Added addition features for testing with (E.g. --flood-attempts which sends X amount of times before waiting for the final validation). Also bug fixes when running non-transfer tests.

feat: tester cli updates

---

packages/client/package.json
packages/crypto/package.json

Changes required for pushing Client and Crypto packages to npmjs

[WIP] Publish client & crypto

---

packages/core-database-sequelize/lib/connection.js

Fix the small eslint error described in #862 
Removed a space

Fix eslint error (#862)

---

packages/core-api/lib/versions/2/transformers/wallet.js
packages/core-tester-cli/lib/commands/delegate-registration.js
packages/core-tester-cli/lib/commands/multi-signature.js
packages/core-tester-cli/lib/commands/second-signature.js
packages/core-tester-cli/lib/commands/transfer.js
packages/core-tester-cli/lib/commands/vote.js
packages/core-tester-cli/lib/utils/get-delegates.js
packages/core-tester-cli/lib/utils/get-transaction-delay.js
packages/core-tester-cli/lib/utils/get-transaction.js
packages/core-tester-cli/lib/utils/get-voters.js
packages/core-tester-cli/lib/utils/get-wallet-balance.js
packages/core-tester-cli/lib/utils/get-wallet.js
packages/core-tester-cli/lib/utils/index.js
packages/core-tester-cli/lib/utils/paginate.js
packages/core-tester-cli/lib/utils/post-transactions.js

Updating Tester CLI to use only v2 endpoints. Other small changes are included here.

Tester CLI tweaks - v2 endpoints

---

packages/core-api/lib/versions/2/handlers/blocks.js
packages/core-api/lib/versions/2/handlers/delegates.js
packages/core-api/lib/versions/2/handlers/peers.js
packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-api/lib/versions/2/handlers/votes.js
packages/core-api/lib/versions/2/handlers/wallets.js

More descriptive error messages. Resolves https://github.com/ArkEcosystem/core/issues/865.

refactor: better v2 API error messages

---

packages/core-api/lib/versions/2/handlers/blocks.js
packages/core-api/lib/versions/2/handlers/delegates.js
packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-api/lib/versions/2/handlers/votes.js
packages/core-api/lib/versions/2/handlers/wallets.js
packages/core-api/lib/versions/2/schema/blocks.js
packages/core-api/lib/versions/2/schema/delegates.js
packages/core-api/lib/versions/2/schema/pagination.js
packages/core-api/lib/versions/2/schema/peers.js
packages/core-api/lib/versions/2/schema/transactions.js
packages/core-api/lib/versions/2/schema/votes.js
packages/core-api/lib/versions/2/schema/wallets.js
packages/core-database/lib/repositories/wallets.js

Issues with paginated endpoints (E.g. orderBy missing, limit max not set)
Resolves #876

[WIP] Pagination v2 fixes

---

jest.config.js

Add core-forger to jest config, as tests are passing (on my machine) without any changes. So let's see if everything is passing on Travis !

test: add core-forger package to jest config

---

packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

We should enable those log statements as we are currently on devnet and everyone will be testing dynamic fees.

refactor: enable logging of dynamic fee actions

---

packages/crypto/lib/networks/ark/devnet.json

That is the way to perform softork/hardfork:
- fix a block height
- add the new or upgraded parameters to be used by the node

intended way to upgrade network config

---

packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

The current dynamic fee debug messages can be quite confusing so they have been reworded.

refactor: improved dynamic fee log messages

---

packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

Rewording dynamic fee log messages to be more clear about what happened.

misc: more meaningful dynamic fee log messages

---

jest.config.js
packages/core-json-rpc/__tests__/__support__/setup.js
packages/core-json-rpc/__tests__/accounts.test.js
packages/core-json-rpc/__tests__/blocks.test.js
packages/core-json-rpc/__tests__/transactions.test.js
packages/core-json-rpc/lib/server/methods/accounts/bip38/create.js
packages/core-json-rpc/lib/server/methods/transactions/create.js
packages/core-json-rpc/lib/server/services/database.js
packages/core-json-rpc/package.json

Fix tests in core-json-rpc package and add to jest config.
Also fixed `server/methods/transactions/create.js` which was not creating the transaction correctly.

Test: core-json-rpc package

---

packages/core/lib/config/devnet/plugins.js
packages/core/lib/config/mainnet/plugins.js
packages/core/lib/config/testnet.1/plugins.js
packages/core/lib/config/testnet.2/plugins.js
packages/core/lib/config/testnet.live/plugins.js
packages/core/lib/config/testnet/plugins.js

Registers the `core-storage` plugin so we can start working on making use of it.

chore: register core-storage plugin

---

jest.config.js
packages/crypto/__tests__/builder/transactions/__shared__/transaction.js
packages/crypto/__tests__/managers/config.test.js
packages/crypto/__tests__/models/block.test.js

Add crypto package to jest config + some test fixes.

Test: add crypto package

---

packages/core-api/__tests__/__support__/config/plugins.js
packages/core-database-sequelize/lib/connection.js
packages/core-database/__tests__/wallet-manager.test.js
packages/core-database/lib/interface.js
packages/core-database/lib/wallet-manager.js
packages/core-p2p/__tests__/__support__/config/plugins.js
packages/core-storage/lib/storage.js
packages/core-transaction-pool/lib/interface.js
packages/core-transaction-pool/lib/pool-wallet-manager.js

Use the new Immutable Storage plugin to manage the wallet manager wallets.

refactor: wallet manager immutable storage

---

jest.config.js
packages/core-api/__tests__/__support__/config/genesisBlock.json
packages/core-api/__tests__/__support__/setup.js
packages/core-api/__tests__/v1/handlers/accounts.test.js
packages/core-api/__tests__/v1/handlers/delegates.test.js
packages/core-api/__tests__/v1/handlers/peers.test.js
packages/core-api/__tests__/v1/handlers/transactions.test.js
packages/core-api/__tests__/v1/utils.js
packages/core-api/__tests__/v2/handlers/blocks.test.js
packages/core-api/__tests__/v2/handlers/delegates.test.js
packages/core-api/__tests__/v2/handlers/transactions.test.js
packages/core-api/__tests__/v2/utils.js
packages/core-api/lib/versions/2/handlers/wallets.js
packages/core-database-sequelize/__tests__/repositories/transactions.test.js
packages/core-database-sequelize/lib/repositories/utils/filter-query.js
packages/core-forger/lib/index.js
packages/core-forger/lib/manager.js

- [Test] Fixed core-api broken tests + used Hapi request injection instead of axios
- [Fix] Fixed a bug in core-database-sequelize where queries with condition 'column = 0' were wrongly interpreted
- [Fix] Fixed a bug in core-api wallet handler, deleting request.params.id so that it does not produce a wrong SQL query
- [Feat] Added new method to stop forger manager + deregister plugin method, useful in tests `afterAll`

Test: core-api package + bug fix

---

packages/core-api/lib/versions/2/handlers/delegates.js
packages/core-database-sequelize/lib/connection.js
packages/core-database-sequelize/lib/spv.js
packages/core-database/__tests__/repositories/delegates.test.js
packages/core-database/__tests__/repositories/wallets.test.js
packages/core-database/__tests__/wallet-manager.test.js
packages/core-database/lib/repositories/delegates.js
packages/core-database/lib/repositories/wallets.js
packages/core-database/lib/wallet-manager.js
packages/core-transaction-pool/lib/pool-wallet-manager.js

The method names in wallet manager were rather unintuitive and had redundant prefixes and suffixes.

refactor: improve method names in wallet manager

---

packages/core-graphql/README.md
packages/core-graphql/lib/defaults.js
packages/core-graphql/lib/defs/root.js
packages/core-graphql/lib/helpers/unserialize-transactions.js
packages/core-graphql/lib/resolvers/queries/block/blocks.js
packages/core-graphql/lib/resolvers/queries/transaction/transaction.js
packages/core-graphql/lib/resolvers/queries/transaction/transactions.js
packages/core-graphql/lib/resolvers/queries/wallet/wallet.js
packages/core-graphql/lib/resolvers/relationship/block.js
packages/core-graphql/lib/resolvers/relationship/wallet.js
packages/core-graphql/lib/schema.js
packages/core-graphql/lib/server.js
packages/core-graphql/package.json

The graphql service was not starting properly, then I refactored the implementation with apollo-server and fixed the requests made to the db.
Testes will be implemented by @air1one next.

refactor(graphql): migrate to apollo server 2

---

packages/core-blockchain/lib/blockchain.js
packages/core-webhooks/__tests__/__support__/setup.js
packages/core-webhooks/lib/manager.js
packages/core-webhooks/package.json

Webhooks were only listening for specific events, now they will listen for all available events.

fix: listen for all events on webhooks

---

packages/core-p2p/__tests__/server/peer.test.js
packages/core-p2p/lib/server/index.js
packages/core-p2p/lib/server/versions/peer/handlers/blocks.js
packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
packages/core-p2p/lib/server/versions/peer/schemas/blocks.js
packages/core-p2p/package.json
packages/core-test-utils/lib/matchers/api/block.js
packages/core-test-utils/lib/matchers/api/peer.js
packages/core-test-utils/lib/matchers/api/response.js
packages/core-test-utils/lib/matchers/index.js

- Initial tests on p2p v2 /peer API which was not tested yet because the v2 /peer route was not published
- Used new ARK_V2 environment variable to enable publishing v2 /peer route based on it
- Some fixes also related to v2 /peer endpoint (related to schema validation)

Initial tests on p2p v2 /peer API + related fixes + new ARK_V2 environment variable for V2 behavior

---

packages/core-database-sequelize/lib/migrations/20180305163239-create-wallet.js
packages/core-database-sequelize/lib/migrations/20182506163244-rename-wallet-columns.js
packages/core-database/__tests__/wallet-manager.test.js
packages/core-database/lib/wallet-manager.js

Recently `votebalance` was renamed to `voteBalance`, but not so in `updateDelegates` (though it is in #969). Rename the last occurrences and add unit test for `updateDelegates` to ensure it works correctly.

Fix updateDelegates

---

packages/crypto/lib/crypto/crypto.js
packages/crypto/lib/models/block.js
packages/crypto/lib/models/wallet.js

As mentioned in #991 , by using secp256k1 natively the time spent verifying and signing is cut down by half or more on average.
I have been working on a bigger refactor of `crypto`, but I don't feel comfortable pushing these two changes together. So let's first get this one in.

perf: use secp256k1 for verifying and signing

---

packages/client/package.json

bump client version as published to npmjs

chore: bump client version

---

packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-config/package.json
packages/core-container/package.json
packages/core-database-postgres/package.json
packages/core-database/package.json
packages/core-deployer/package.json
packages/core-forger/package.json
packages/core-graphql/package.json
packages/core-json-rpc/package.json
packages/core-p2p/package.json
packages/core-test-utils/package.json
packages/core-tester-cli/package.json
packages/core-transaction-pool-redis/package.json
packages/core-transaction-pool/package.json
packages/core/package.json
packages/crypto/package.json

Bump `@arkecosystem/crypto` to `0.2.0`.

chore: bump crypto version

---

packages/core-database-postgres/lib/migrations/20180305200000-create-rounds-table.sql

solving issue on slow rebuild for our test servers

wrong order of indexing round

---

packages/client/CHANGELOG.md
packages/client/package.json

Bump API client version to 0.1.4

---

packages/core-database/__tests__/repositories/wallets.test.js
packages/core-database/lib/repositories/wallets.js

This was broken by https://github.com/ArkEcosystem/core/commit/09f4acea0ccb6a44dea0cc31d8d507f446e7dd34 which results in wrong API output.

fix: sorting of top wallets

---

packages/core-database/lib/wallet-manager.js

Compares the numerical values rather then the BigNumber.js objects.

fix: turn vote balance to number

---

packages/crypto/lib/models/block.js

When a block contains invalid transactions, also log the serialized transaction.
<!--

Log which transactions failed to verify

---

packages/crypto/lib/models/transaction.js

small fix, improves serialization
todo

use else if, return if delegate reg

---

.travis.yml
docker/development/docker-compose.yml
packages/core-p2p/__tests__/__support__/setup.js
packages/core-test-utils/config/testnet/plugins.js

Docker development config did not match out test suites configuration for postgres database.
This updates the docker development config + test configs so that they match.

Tests: update docker development config + core-test-utils config + travis

---

packages/core-p2p/__tests__/peer.test.js
packages/core-p2p/__tests__/server/peer.test.js
packages/core-p2p/lib/peer.js
packages/core-p2p/lib/server/plugins/set-headers.js

A peer's `height` would not be updated once accepted. This patch ensures that the `height` is updated with each response from the respective peer. Fixes #901.
<!--

Update peer height

---

packages/core-p2p/lib/server/plugins/set-headers.js

When a forger starts up the blockchain may not yet be avaiable in which case it blows up.

fix: check if blockchain is ready

---

packages/crypto/lib/models/transaction.js

Fix the small eslint error described in #1062 
Fix eslint errors.

Fix eslint errors (fix #1062)

---

packages/client/CHANGELOG.md
packages/client/package.json

Prepares the new version of the API client

Bump API client version to 0.1.5

---

docker/development/docker-compose.yml
docker/devnet/docker-compose.yml
docker/testnet/docker-compose.yml

Update container name for docker development to avoid conflict with other docker containers.

chore: update container name for docker development to avoid conflict

---

docker/development/purge.sh

Include a shell script for purging the `development` containers, volumes and network

---

docker/devnet/entrypoint.sh
docker/testnet/entrypoint.sh
package.json
packages/core/package.json
yarn.lock

Chore: Docker adjusting the entrypoint script to recent changes. We renamed container names in `docker-compose.yml` but did not adjust the `entrypoint.sh`
Tnx @adrian69 
Delete all containers if you where using ark-core from the docker, and start them again.

Chore: Docker adjusting the entrypoint script to recent changes

---

packages/core-api/lib/plugins/endpoint-version.js
packages/core-api/lib/server.js

Fixes #1074 
This is a side effect of #1051 which effectively removed the code to parse the endpoint version, because it is not part of upstream.

fix: parse endpoint version

---

packages/core-transaction-pool-redis/lib/connection.js

fix: Promise.all() usage

---

packages/client/CHANGELOG.md
packages/client/package.json

Bump API client version to 0.1.6

---

packages/core-tester-cli/__tests__/commands/transfer.test.js
packages/core-tester-cli/bin/tester
packages/core-tester-cli/lib/commands/command.js
packages/core-tester-cli/lib/commands/delegate-registration.js
packages/core-tester-cli/lib/commands/multi-signature.js
packages/core-tester-cli/lib/commands/second-signature.js
packages/core-tester-cli/lib/commands/transfer.js
packages/core-tester-cli/lib/commands/vote.js
packages/core-tester-cli/package.json

Adds a cli option to specify your own smart-bridge value

Add core-tester-cli option for custom smartBridge values

---

packages/core-p2p/lib/server/plugins/set-headers.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/internal/handlers/utils.js

Gets rid of output like this which pollutes the unit test logs:
```javascript
console.error node_modules/hapi/lib/core.js:125
Debug: internal, implementation, error 
TypeError: Cannot read property 'data' of null
at method (/home/travis/build/ArkEcosystem/core/packages/core-p2p/lib/server/plugins/set-headers.js:28:26)
at Object.<anonymous>.module.exports.internals.Manager.execute (/home/travis/build/ArkEcosystem/core/node_modules/hapi/lib/toolkit.js:35:106)
at Request._invoke (/home/travis/build/ArkEcosystem/core/node_modules/hapi/lib/request.js:293:55)
at Request._postCycle (/home/travis/build/ArkEcosystem/core/node_modules/hapi/lib/request.js:356:86)
at Request._reply (/home/travis/build/ArkEcosystem/core/node_modules/hapi/lib/request.js:335:20)
at Request._execute …
```

fix: check lastBlock for null to reduce noise in unit tests

---

.circleci/config.yml

Integrating code coverage in CircleCI build. (only running in node 10 test job as it causes javascript heap out of memory error in node 9)
Also including lint and depcheck inside tests jobs.

build: integrating code coverage + optimizations

---

packages/client/CHANGELOG.md
packages/client/package.json

chore: bump api client

---

packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool-mem/lib/defaults.js
packages/core-transaction-pool-mem/lib/storage.js
packages/core-transaction-pool-mem/package.json
packages/core/lib/config/devnet/plugins.js
packages/core/lib/config/mainnet/plugins.js
packages/core/lib/config/testnet.1/plugins.js
packages/core/lib/config/testnet.2/plugins.js
packages/core/lib/config/testnet.live/plugins.js
packages/core/lib/config/testnet/plugins.js
yarn.lock

Follow up to the new transaction pool to make sure the database file exists.

fix: ensure database exists

---

packages/core-utils/__tests__/delegate-calculator.test.js
packages/core-utils/lib/delegate-calculator.js

fix: delegate approval calculation

---

packages/core-logger-winston/lib/defaults.js
packages/core-logger-winston/lib/formatter.js

The file logger format changed to json with #1112, this PR restores the console logger format.
<!--

fix: winston file logger format

---

packages/core-api/README.md
packages/core-blockchain/README.md
packages/core-database-postgres/README.md
packages/core-database/README.md
packages/core-forger/README.md
packages/core-graphql/README.md
packages/core-json-rpc/README.md
packages/core-json-rpc/jest.config.js
packages/core-logger-winston/README.md
packages/core-p2p/README.md
packages/core-p2p/__tests__/monitor.test.js
packages/core-p2p/lib/defaults.js
packages/core-transaction-pool-mem/README.md
packages/core-transaction-pool-redis/README.md
packages/core-webhooks/__tests__/server/handler.test.js
packages/core/lib/config/mainnet/delegates.json

Some configurations were outdated and had no effect or had wrong documentation.

refactor: update docs and remove unused configs

---

packages/core-logger-winston/README.md
packages/core-logger-winston/lib/defaults.js
packages/core-test-utils/config/testnet/plugins.js
packages/core/lib/config/devnet/plugins.js
packages/core/lib/config/mainnet/plugins.js
packages/core/lib/config/testnet.1/plugins.js
packages/core/lib/config/testnet.2/plugins.js
packages/core/lib/config/testnet.live/plugins.js
packages/core/lib/config/testnet/plugins.js

Resolves https://github.com/ArkEcosystem/core/issues/1125.

chore: use static log file path

---

packages/client/package.json
packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-config/package.json
packages/core-container/package.json
packages/core-database-postgres/package.json
packages/core-database/package.json
packages/core-debugger-cli/package.json
packages/core-deployer/package.json
packages/core-event-emitter/package.json
packages/core-forger/package.json
packages/core-graphql/package.json
packages/core-json-rpc/package.json
packages/core-logger-winston/package.json
packages/core-logger/package.json
packages/core-p2p/package.json
packages/core-test-utils/package.json
packages/core-tester-cli/package.json
packages/core-transaction-pool-mem/package.json
packages/core-transaction-pool/package.json
packages/core-utils/package.json
packages/core-webhooks/package.json
packages/crypto/package.json

I'm having problems when trying to use it with that option.
@supaiku0 maybe this was the reason that you have problems in the past. Could you try it, please?

Remove the `--watch` option of the `test:debugger` script

---

packages/core-utils/lib/create-table.js
packages/core-utils/lib/index.js
packages/core-utils/package.json
yarn.lock

Small helper to create readable tables for testing via https://github.com/cli-table/cli-table3.

feat: create table util

---

packages/core-api/__tests__/__support__/setup.js
packages/core-api/lib/server.js
packages/core-p2p/__mocks__/sntp.js

Fix for CircleCI builds which were failing randomly on core-api because of test setup skipping blockchain started check ; and on core-p2p because relying on external servers for ntp.

test: update core-api test setup + core-p2p ntp mocking for CircleCI

---

packages/core-p2p/lib/monitor.js

style: prune stale code from monitor

---

packages/core-database-postgres/lib/connection.js
packages/core-database/__tests__/interface.test.js
packages/core-database/lib/interface.js

Some methods were marked and tested as async while they in reality are sync methods.

fix: invalid async methods

---

packages/core-p2p/__tests__/court/guard.test.js
packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/court/offences.js
packages/core-p2p/lib/monitor.js

Handles the "Unknown" ban scenario.

feat: handle common block bans

---

packages/core-database-postgres/lib/spv.js
packages/crypto/lib/models/wallet.js

Without the `wallet.voted` flag unvotes are practically ignored and the previous vote is restored which causes a lot of problems.

Revert: remove unused wallet.voted property (#1161)

---

packages/core-database-postgres/lib/connection.js
packages/core-database-postgres/lib/spv.js
packages/core-database/__tests__/wallet-manager.test.js
packages/core-database/lib/interface.js
packages/core-database/lib/wallet-manager.js
packages/crypto/lib/models/wallet.js

This PR changes how vote balances are calculated. Instead of calculating them from scratch all the time, use a "delta update" approach.
The most relevant changes can be found here:
- `applyTransaction/revertTransaction`
- `applyBlock/revertBlock`
Additionally I changed the order of `buildVotes` and `buildDelegates` during SPV. By doing so the
delegate vote balances can be easily validated.
~~Marked as WIP as my node just got stuck around height 8416 with generator mismatch (sync from 0 on devnet), but recovered... and then got stuck a few more times at later heights. I still need to investigate it.~~
Now also resolves #1010

Optimize vote balance calculation

---

packages/core-api/lib/versions/1/handlers/delegates.js

Resolves https://github.com/ArkEcosystem/core/issues/1164

fix(core-api): return delegates list in proper v1 format

---

packages/core-blockchain/lib/queue/process.js
packages/core-database-postgres/lib/connection.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-webhooks/lib/database/index.js

Those were never printed correctly.

fix: error logging

---

packages/core-database/lib/wallet-manager.js

The delegate ranks were never updated for the wallet manager.

fix: update delegate ranks for the wallet manager

---

packages/core-p2p/__tests__/server/peer.test.js
packages/core-transaction-pool-mem/__tests__/guard.test.js

fix: failing tests

---

packages/core-transaction-pool/lib/interface.js

Getting all transactions by using
this.getTransactionIdsForForging(start=0, size=0) was a redis pool
specialty. The mem pool would just return an empty array in this case.
Properly use the getPoolSize() for the "size" parameter to denote that
all transactions are desired.

fix(mempool): call getTransactionIdsForForging() properly

---

packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool/__tests__/interface.test.js
packages/core-transaction-pool/lib/interface.js

refactor(mempool): remove forged only during startup

---

packages/client/CHANGELOG.md
packages/core-api/CHANGELOG.md
packages/core-blockchain/CHANGELOG.md
packages/core-config/CHANGELOG.md
packages/core-container/CHANGELOG.md
packages/core-database-postgres/CHANGELOG.md
packages/core-database/CHANGELOG.md
packages/core-debugger-cli/CHANGELOG.md
packages/core-deployer/CHANGELOG.md
packages/core-event-emitter/CHANGELOG.md
packages/core-forger/CHANGELOG.md
packages/core-graphql/CHANGELOG.md
packages/core-json-rpc/CHANGELOG.md
packages/core-logger-winston/CHANGELOG.md
packages/core-logger/CHANGELOG.md
packages/core-p2p/CHANGELOG.md
packages/core-test-utils/CHANGELOG.md
packages/core-tester-cli/CHANGELOG.md
packages/core-transaction-pool-mem/CHANGELOG.md
packages/core-transaction-pool/CHANGELOG.md
packages/core-utils/CHANGELOG.md
packages/core-webhooks/CHANGELOG.md
packages/core/CHANGELOG.md
packages/crypto/CHANGELOG.md

Documents some of the changes made in the last months.

chore: compile preliminary changelogs

---

packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool/__tests__/interface.test.js
packages/core-transaction-pool/lib/interface.js

refactor(mempool): remove unused method removeTransactions()

---

.codecov.yml

Ignores the plugin main files for coverage.

chore: ignore index.js files for coverage

---

packages/core-database-postgres/lib/connection.js

By properly batching the wallets when doing a force insert we can cut down the time spent considerably. Increasing the chunk size has no visible effect, so I left it unchanged.
Before (devnet):
```
saveWallets: 2456.495ms
saveWallets: 2487.363ms
saveWallets: 2148.759ms
saveWallets: 2336.846ms
saveWallets: 1850.622ms
saveWallets: 1862.646ms
saveWallets: 1843.057ms
saveWallets: 1936.318ms
saveWallets: 1806.108ms
saveWallets: 1906.639ms
```
After (devnet):
```
saveWallets: 1190.114ms
saveWallets: 1162.871ms
saveWallets: 1218.505ms
saveWallets: 1288.276ms
saveWallets: 1119.453ms
saveWallets: 1365.919ms
saveWallets: 1572.861ms
saveWallets: 1252.263ms
saveWallets: 1317.798ms
saveWallets: 1177.376ms
```

perf: batch wallets on insert

---

packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/lib/connection.js

test(mempool): extend test coverage

---

packages/client/CHANGELOG.md
packages/client/lib/resources/v1/loader.js

Fixes a wrong method mapping for the v1 API in the client.

fix(client): wrong loader methods

---

packages/crypto/CHANGELOG.md

Updates the crypto changelog as good as I could from past commits.

chore(crypto): update changelog

---

packages/core-api/lib/repositories/transactions.js

Adds support for the `ownerId` property which allows to search for transactions by sender and recipient.

feat(core-api): search by owner id

---

packages/core-api/lib/repositories/transactions.js

If there were no conditions that were actual database columns it wouldn't make use of the ownerId.

fix(core-api): properly filter by ownerId

---

packages/core-transaction-pool-mem/__tests__/connection.test.js

…othing
The test was adding an invalid transaction to the pool (invalid because
of not enough funds) and was expecting that transaction not to be
returned by getTransactionsForForging(). The problem is that the method
was called with an argument of 0: getTransactionsForForging(blockSize=0).
The blockSize argument denotes the maximum number of transactions to
return and using 0 would always cause an empty array to be returned.
To fix this use some arbitrary number, larger than 0. Also, extend the
test in two ways:
* Add one valid transaction from another sender to verify that the
removal of the invalid one will not also ditch the valid one.
* Add one valid transaction from the same sender - it should also be
removed because all transactions from the same sender are removed upon …

test(mempool): fix test "amount > wallet balance" which was testing nothing

---

package.json
packages/client/package.json
packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-config/package.json
packages/core-container/package.json
packages/core-database-postgres/package.json
packages/core-database/package.json
packages/core-debugger-cli/package.json
packages/core-deployer/package.json
packages/core-event-emitter/package.json
packages/core-forger/package.json
packages/core-graphql/package.json
packages/core-json-rpc/package.json
packages/core-logger-winston/package.json
packages/core-logger/package.json
packages/core-p2p/package.json
packages/core-test-utils/package.json
packages/core-tester-cli/package.json
packages/core-transaction-pool-mem/package.json
packages/core-transaction-pool/package.json
packages/core-utils/package.json
packages/core-webhooks/package.json
packages/crypto/package.json

index.js and defaults.js do not contain any real code, so skip them from
the output of `yarn test:coverage`

test(mempool): ignore index.js and defaults.js in coverage report

---

packages/core-tester-cli/__tests__/commands/transfer.test.js

Additional test coverage around core-tester-cli/transfer command

test(core-tester-cli): additional test coverage for transfer command

---

packages/core-transaction-pool-mem/__tests__/connection.test.js

Instead of forging a transaction while the pool is shut down, we plug a
forged transaction into it and then restart it and observe that it has
been wiped away.

test(mempool): implement the 'remove forged during our downtime' test

---

packages/core-database-postgres/lib/repositories/wallets.js

The description of the `findNegativeBalances` and `findNegativeVoteBalances` was misleading, as those functions return a count of wallets, not the wallets themselves.

chore(core-database-postgres): add better function description

---

packages/crypto/CHANGELOG.md
packages/crypto/__tests__/crypto/message.test.js
packages/crypto/lib/crypto/message.js

This allows the signing of messages with a WIF (which are a result of BIP38 decrypted passphrases)

feat: sign message with wif

---

packages/crypto/CHANGELOG.md
packages/crypto/package.json

chore: bump crypto release

---

packages/core-api/lib/repositories/transactions.js

Handles the `senderId` as `sender_id` if present.

fix(core-api): handle senderId as snake_case

---

packages/core-api/lib/versions/1/handlers/loader.js
packages/core-api/lib/versions/1/schemas/transport.js
packages/core-api/lib/versions/1/transformers/block.js
packages/core-blockchain/__tests__/blockchain.test.js
packages/core-blockchain/__tests__/state-machine.test.js
packages/core-blockchain/__tests__/state-storage.test.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/defaults.js
packages/core-blockchain/lib/index.js
packages/core-blockchain/lib/queue/index.js
packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/state-storage.js
packages/core-blockchain/package.json
packages/core-database-postgres/lib/connection.js
packages/core-database/lib/interface.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/1/index.js
packages/core-p2p/lib/server/versions/1/schema.js
packages/core-p2p/lib/server/versions/peer/handlers/blocks.js
yarn.lock

Introduces a new storage for the blockchain state. It caches the last processed blocks (100 by default). `getCommonBlocks` and `getBlocks` have been changed to make use of the cache and they will only fallback to the database if necessary.
The state can be requested via `container.resolve('state')` after the blockchain has been registered.
Resolves #818

feat: stateful data storage

---

packages/crypto/lib/models/block.js

Writing transaction bytes in `Block.serializeFull` requires three loops and two loops when reading.
Both are replaced with a single loop which achieves the same.

refactor: reduce number of loops when reading/writing transaction bytes

---

packages/core-tester-cli/__tests__/commands/vote.test.js
packages/core-tester-cli/lib/commands/vote.js
packages/core-tester-cli/lib/utils/paginate.js

test(core-tester-cli): vote command

---

packages/core-json-rpc/__tests__/blocks.test.js
packages/core-json-rpc/__tests__/transactions.test.js
packages/core-json-rpc/__tests__/wallets.test.js
packages/core-json-rpc/lib/server/methods/blocks/info.js
packages/core-json-rpc/lib/server/methods/blocks/latest.js
packages/core-json-rpc/lib/server/methods/blocks/transactions.js
packages/core-json-rpc/lib/server/methods/transactions/bip38/create.js
packages/core-json-rpc/lib/server/methods/transactions/broadcast.js
packages/core-json-rpc/lib/server/methods/transactions/info.js
packages/core-json-rpc/lib/server/methods/wallets/bip38/show.js
packages/core-json-rpc/lib/server/methods/wallets/info.js
packages/core-json-rpc/lib/server/methods/wallets/transactions.js
packages/core-json-rpc/lib/server/services/processor.js

Errors were poorly handled so this PR fixes that. Boom objects will need to be returned if any errors occur like an empty response and the processor will turn this into a valid error response object.
**Will add some more tests to the RPC now to make sure error cases are properly handled.**

refactor(core-json-rpc): properly handle errors and empty data

---

packages/core-transaction-pool-mem/package.json

chore: remove duplicated argument to jest

---

packages/core-api/lib/versions/1/handlers/transactions.js
packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-blockchain/__tests__/blockchain.test.js
packages/core-blockchain/lib/blockchain.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool/__tests__/interface.test.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/interface.js
packages/core-transaction-pool/package.json

chore: remove unneeded await/async from mem pool methods

---

packages/core/lib/start-forger.js

Removes stale config code from start-forger script.

chore: remove stale config from start-forger

---

packages/core-blockchain/lib/state-machine.js
packages/core-container/lib/container.js
packages/core-database-postgres/lib/connection.js
packages/core-database/lib/wallet-manager.js
packages/core-http-utils/lib/server/mount.js
packages/core-p2p/lib/monitor.js
packages/core-webhooks/lib/database/index.js

Resolves #1219 
```javascript
[2018-10-30 14:31:26][INFO]    : Connecting to transaction pool
[2018-10-30 14:31:26][INFO]    : Starting P2P Interface
[2018-10-30 14:31:27][INFO]    : P2P API Server running at: http://0.0.0.0:4000
[2018-10-30 14:31:27][ERROR]   : 💥 Container force shutdown 💥
[2018-10-30 14:31:27][ERROR]   : Could not start P2P API Server!
[2018-10-30 14:31:27][ERROR]   : Error: aaaaa
at Object.<anonymous>.module.exports (/home/supaiku/projects/ark-core/packages/core-http-utils/lib/server/mount.js:12:11)
at process._tickCallback (internal/process/next_tick.js:68:7)
●  process.exit called with "1"
140 | 
141 |     setTimeout(() => {
> 142 |       process.exit(exitCode)
|               ^
143 |     }, 10)
144 |   }
145 | 
at Timeout.setTimeout …
```

fix: replace process.exit with container.exit to process final log messages

---

packages/core-api/CHANGELOG.md
packages/core-blockchain/CHANGELOG.md
packages/core-config/CHANGELOG.md
packages/core-container/CHANGELOG.md
packages/core-database-postgres/CHANGELOG.md
packages/core-database/CHANGELOG.md
packages/core-debugger-cli/CHANGELOG.md
packages/core-deployer/CHANGELOG.md
packages/core-event-emitter/CHANGELOG.md
packages/core-forger/CHANGELOG.md
packages/core-graphql/CHANGELOG.md
packages/core-http-utils/CHANGELOG.md
packages/core-json-rpc/CHANGELOG.md
packages/core-logger-winston/CHANGELOG.md
packages/core-logger/CHANGELOG.md
packages/core-p2p/CHANGELOG.md
packages/core-test-utils/CHANGELOG.md
packages/core-tester-cli/CHANGELOG.md
packages/core-transaction-pool-mem/CHANGELOG.md
packages/core-transaction-pool/CHANGELOG.md
packages/core-utils/CHANGELOG.md
packages/core-webhooks/CHANGELOG.md
packages/core/CHANGELOG.md
packages/crypto/CHANGELOG.md

Updates the changelogs with the changes of the last 8 days.

chore: update changelogs

---

packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/state-storage.js
packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/court/offences.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js
packages/core/lib/start-relay-and-forger.js

When entering a fork due to a bad block from a peer, that peer is now correctly banned. It didn't work before, as the ban would be lifted immediately. Additionally, all peers are refreshed and those without common blocks will be suspended.
Peers are also grouped by height now, though that information is not used anywhere yet.

refactor: peer ban after fork

---

packages/core-transaction-pool-mem/lib/storage.js
packages/crypto/__tests__/handlers/transactions/handler.test.js
packages/crypto/lib/handlers/transactions/handler.js

fix: Uppercase publicKey/signature fields when read from sqlite

---

packages/core-forger/lib/client.js
packages/core-p2p/__tests__/__support__/utils.js
packages/core-p2p/__tests__/server/internal.test.js
packages/core-p2p/lib/server/plugins/accept-request.js

Adds an additional header which is used by forgers so that they don't get erroneously accepted as a peer only to end up getting banned.

fix(core-p2p): dont accept forger as peer

---

packages/core-p2p/lib/monitor.js

fix: remove assert when updating peer height

---

packages/core-config/lib/loader.js

Without the restriction the loader would also load backup files like `network.json~`.

fix(core-config): restrict regex to .js and .json files

---

packages/core-tester-cli/lib/commands/multi-signature.js
packages/core-tester-cli/lib/commands/second-signature.js
packages/core-tester-cli/lib/commands/transfer.js

Continuation of my previous commit, had missed a few places

refactor(core-tester-cli): use full Ark amounts(had missed a few places)

---

packages/core-api/lib/repositories/blocks.js
packages/core-api/lib/repositories/transactions.js
packages/core-graphql/lib/repositories/blocks.js
packages/core-graphql/lib/repositories/transactions.js

Calling the api with a non-lowercase orderBy direction causes an internal server error, for instance https://dexplorer.ark.io:8443/api/v2/blocks?orderBy=height:DESC
Fixes #1276

fix(misc): lowercase orderBy params

---

packages/core-api/__tests__/v2/handlers/blocks.test.js
packages/core-api/lib/repositories/blocks.js

#1277 Fallback to `height:desc` when:
1. no param specified
2. split param by : isn't an array with 2 members
3. split param by : and the second member is not `asc || desc`
Added test to endpoint which fails under `develop`, here succeeds.
NOTE: the original issue makes it clear that `blocks?orderBy=height` returns an error, whereas under testnet it didn't, even in the `develop` branch.
To be sure this fix works, I have also tested `blocks?orderBy=height:descc`, which doesn't work on `develop` but does with this fix.

fix: core-api blocks orderBy malformed query behavior

---

packages/core-test-utils/lib/helpers/container.js

In case of wanting to test changes using a valid devnet (or even mainnet) node, it could be useful to provide a way to pass configuration options to core-test-utils' `containerHelper.setUp` function.
This doesn't impact existing implementations, though it opens the door to pass different data and config folders (for example).
Tested to work properly in my environment, here is a demo:
the old:
```js
await containerHelper.setUp({
exclude: [
'@arkecosystem/core-api',
'@arkecosystem/core-forger'
]
})
```
is equivalent to the new:
```js
await containerHelper.setUp({
network: 'testnet',
config: path.resolve(__dirname, '../../../core-test-utils/config/testnet'),
exclude: [
'@arkecosystem/core-api',
'@arkecosystem/core-forger'
]
})
```
but we can also use
```js
await containerHelper.setUp({ …
```

feat: add test-utils network options

---

packages/core-tester-cli/lib/commands/transfer.js

The `Command.__arktoshiToArk()` has been called on the wrong argument.

fix(core-tester-cli): incorrect destination balance logs

---

package.json
packages/core-api/package.json
packages/core-blockchain/package.json
packages/core-config/package.json
packages/core-container/package.json
packages/core-database-postgres/package.json
packages/core-database/package.json
packages/core-elasticsearch/package.json
packages/core-error-tracker-bugsnag/package.json
packages/core-error-tracker-sentry/package.json
packages/core-event-emitter/package.json
packages/core-forger/package.json
packages/core-graphql/package.json
packages/core-json-rpc/package.json
packages/core-logger-winston/package.json
packages/core-logger/package.json
packages/core-p2p/package.json
packages/core-snapshots-cli/package.json
packages/core-snapshots/package.json
packages/core-transaction-pool-mem/package.json
packages/core-transaction-pool/package.json
packages/core-utils/package.json
packages/core-vote-report/package.json
packages/core-webhooks/package.json
packages/crypto/package.json
yarn.lock

chore: remove jsdoc

---

packages/core-forger/lib/client.js
packages/core-forger/lib/manager.js

Adds error handling to `getRound()` and guards the logging of the round information to avoid the following log outputs:
```
2|ark-core-forger  | [...][ERROR] : Forging failed: timeout of 2000ms exceeded ‼️
2|ark-core-forger  | [...][INFO]  : Round:
```

refactor: error handling on getRound() and conditional logging

---

packages/core-database-postgres/lib/queries/spv/votes.sql

Resolves the vote sorting issue during the SPV.

fix(core-database-postgres): fix sorting of votes during SPV

---

packages/core-transaction-pool-mem/lib/defaults.js

chore: reducing expiration in transaction pool to 45 minutes.

chore: reducing expiration in transaction pool to 45 minutes

---

packages/core-database-postgres/lib/queries/spv/votes.sql

use ASC with second sort of trx

fix(core-database-postgresql): sort votes by ascending sequence

---

packages/core-snapshots/lib/transport/index.js
packages/core-snapshots/lib/utils/index.js

fix the location and naming of rollbacktransaction.json.

fix(core-snapshots): rollback file location storage

---

packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool/__tests__/interface.test.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/interface.js
packages/crypto/lib/constants.js

fix: do not handle all !=TRANSFER transactions as VOTE

---

packages/core-container/lib/container.js
packages/core-logger-winston/__tests__/logger.test.js
packages/core-logger-winston/lib/driver.js
packages/core-logger/__tests__/interface.test.js
packages/core-logger/lib/interface.js
packages/core-snapshots-cli/bin/snapshot

Introduces a new container flag which allows for a silent shutdown. This is useful for programs like `core-snapshots-cli`.

feat(core-container): silent shutdown

---

packages/core-blockchain/lib/state-machine.js
packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/court/offences.js
packages/core-p2p/lib/monitor.js

When all peers are sitting at the same height, but with different block ids it might not be possible to get quorum. This is what happened earlier, when the devnet was bombed with tx.
See:
```javascript
// block id => peers
5608510382673108576:Array(45)
8715075780824486592:Array(36)
12925129249951878700:Array(1)
```
This PR changes how nodes handle this case. They will look for the most common block id (in this case `5608510382673108576`), ban the other peers at the same height, rollback and try again.

fix(core-p2p): try to recover when missing blocks

---

packages/core-p2p/__tests__/court/guard.test.js
packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/court/offences.js

Adds a check for status 429 (rate-limit) in case that code ever comes up with a peer.

feat(core-p2p): add rate limit offence

---

packages/core-p2p/lib/peer.js

Log the error for `Invalid Response Status`.

chore(core-p2p): log invalid response status error

---

packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/court/offences.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js

Removes unnecessary code and improves how missing blocks are handled. Also changes that more offences stay banned until expired when recovering from a  fork.

refactor(core-p2p): improve behavior when network is missing blocks

---

packages/core-forger/lib/manager.js

Removes duplicate secrets so the same delegate doesn't run 10 times on a single forger.

fix(core-forger): remove duplicate secrets

---

packages/core-p2p/lib/peer.js

Log the address and error message when a request to a peer fails.

refactor(core-p2p): log the address to which the request failed

---

packages/core-p2p/lib/peer.js

Matches the behaviour of the `__post` method with the `__get` method.

refactor(core-p2p): match __post method with __get

---

packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/lib/state-storage.js
packages/core-p2p/lib/monitor.js

Previously we would always check the peers when missing blocks, this change introduces a counter to only check if we keep missing blocks consecutively. It should take care of unwanted rollbacks and other issues which were introduced with #1342 .

fix(core-p2p): add update counter

---

.circleci/config.yml
packages/crypto/CHANGELOG.md
packages/crypto/lib/builder/transactions/mixins/sign.js
packages/crypto/package.json

Use network version in transaction builder when signing with mixin

fix: tx builder network sign

---

packages/core-blockchain/lib/blockchain.js

The `lastDownloadedBlock` was not correctly updated in `manageUnchainedBlock` and thus effectively prevented the chain from advancing under certain circumstances.
```
[2018-11-09 23:35:07][DEBUG] : Blockchain not ready to accept new block at height 703,647. Last block: 703,626 ⚠️
[2018-11-09 23:35:39][INFO] : Downloading blocks from height 703,647 via 80.211.65.198
```

fix(core-blockchain): correctly update lastDownloadedBlock

---

packages/core-p2p/__tests__/server/peer.test.js
packages/core-transaction-pool-mem/__tests__/guard.test.js
packages/core-transaction-pool/__tests__/guard.test.js
packages/core-transaction-pool/lib/guard.js

Returns error types together with a message.

refactor(core-api): return type and message for transaction errors

---

packages/core-api/__tests__/v2/utils.js
packages/core-api/lib/versions/2/transformers/block.js

Returns the total forged and total transactions amount forged, previously returned the total transaction amount as total forged.

fix(core-api): return total forged and total transaction amount

---

packages/core-forger/lib/manager.js

The pluralisation had a wrong conditional.

fix(core-forger): pluralisation condition

---

packages/crypto/lib/models/block.js

Removed some forgotten payload length check.

fix(crypto): remove maximum payload length check for blocks

---

.snyk
package.json
yarn.lock

Setup of https://snyk.io/ to stay on top of known security issues and vulnerabilities in npm modules.
Follow up to https://github.com/ArkEcosystem/core/pull/1364 and https://github.com/ArkEcosystem/core/pull/1366.

chore: setup snyk

---

.circleci/config.yml
packages/core-api/lib/versions/2/schema/wallets.js

Allows the orderBy query string parameter for wallet transactions

fix: orderBy for wallet transaction endpoints

---

packages/core-api/lib/versions/2/handlers/wallets.js

Wallet Transactions endpoint doesn't use the query string data passed in, meaning pagination and orderBy isn't used at all. This resolves that.

fix(core-api): pagination in wallet transactions endpoint

---

packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-api/package.json
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-blockchain/package.json
packages/core-database-postgres/lib/connection.js
packages/core-database-postgres/package.json
packages/core-database/lib/wallet-manager.js
packages/core-database/package.json
packages/core-forger/lib/index.js
packages/core-forger/lib/manager.js
packages/core-forger/package.json
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
packages/core-p2p/package.json
packages/core-snapshots/lib/transport/index.js
packages/core-snapshots/package.json
packages/core-tester-cli/lib/commands/command.js
packages/core-tester-cli/lib/commands/delegate-registration.js
packages/core-tester-cli/lib/commands/multi-signature.js
packages/core-tester-cli/lib/commands/second-signature.js
packages/core-tester-cli/lib/commands/transfer.js
packages/core-tester-cli/lib/commands/vote.js
packages/core-tester-cli/lib/utils/copy-to-clipboard.js
packages/core-tester-cli/package.json

Adds proper pluralization of every occurrence of `wallet`, `delegate`, `transaction` and `block` in the log outputs using the `pluralize` package.

refactor(misc): proper pluralization in logs

---

packages/core-api/__tests__/v1/utils.js
packages/core-api/__tests__/v2/utils.js
packages/core-api/lib/server.js
packages/core-p2p/lib/monitor.js

Fixing some naming issues that were not caught by unit tests.

fix(misc): broken naming

---

packages/core-container/lib/container.js

The `core-container` registers exit handlers when the `Container` constructor is called. This happens as soon as the module is required, but this does not mean that we also want the exit handlers. The `core-tester-cli` indirectly requires the container and then has exit handlers which fail to run since the container was never properly started in the first place.

fix(core-container): move exit handler registration to setUp

---

packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/__tests__/guard.test.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool-mem/lib/mem-pool-transaction.js
packages/core-transaction-pool-mem/lib/mem.js
packages/core-transaction-pool-mem/lib/storage.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/interface.js

Removes the `isBroadcasted` flag and instead introduces a transaction ping  counter which is incremented
whenever a transaction is received from a peer while it is in the transaction pool.
While the ping count is 0, we assume the transaction was not properly broadcasted. On startup all
transactions from the pool where the ping count is 0 will be rebroadcasted.
This PR requires to get rid of any existing transaction pool database (i.e.`rm ~/.ark/database/transaction-pool-devnet.sqlite`), because it changes the schema.

feat(core-transaction-pool): transaction ping and rebroadcast

---

packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/pool-wallet-manager.js

Revert also excess and possible duplicate transactions

fix(core-transaction-pool): revert excess and possible duplicates due to race conditions.

---

packages/core-blockchain/lib/blockchain.js
packages/core-snapshots-cli/README.md

Removes typos (`heigt -> height`) and unnecessary call to `JSON.stringify()`.

fix(core-blockchain): remove typo in processBlock()

---

packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
yarn.lock

If the node gets spammed with low value transactions that are valid the waiting can cause long response times.

refactor(misc): do not wait for broadcasting on API requests

---

packages/core-blockchain/__tests__/blockchain.test.js
packages/core-blockchain/lib/state-machine.js
packages/core-database/lib/interface.js

- Rebuild pool wallet manager after a fork
- `validateForkedBlock` now returns a boolean, fixing the following condition which always evaluated to false and thus never dispatched a fork event:
https://github.com/ArkEcosystem/core/blob/0f3a945fc4278bed09f94820dd509621398774ae/packages/core-blockchain/lib/blockchain.js#L498-L500
- `__getBlocksForRound` had an off by one error, returning up to `52` instead of `51` blocks, the last block being the first of the next round

fix(core-blockchain): fork fixes

---

packages/core-blockchain/__tests__/blockchain.test.js
packages/core-blockchain/lib/blockchain.js
packages/core-blockchain/lib/state-machine.js
packages/core-database-postgres/lib/connection.js
packages/core-database/lib/interface.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/peer/handlers/blocks.js
packages/core-snapshots-cli/lib/commands/rollback.js
packages/core-snapshots/lib/manager.js
packages/crypto/lib/models/block.js
packages/crypto/package.json

The use of `toLocaleString()` when logging block heights is pretty inconsistent at the moment. This adds the localization of block heights and rounds to (hopefully) all places where necessary.

 refactor(misc): localized height and round in logs

---

packages/core-p2p/lib/peer.js

Reduce block download timeout to `10s` as discussed.

misc(core-p2p): reduce block download timeout to 10s

---

packages/core-tester-cli/__tests__/commands/second-signature.test.js

Adding simple test coverage for the second-signature command

test(core-tester-cli): second-signature command

---

packages/core-api/lib/server.js
packages/core-api/package.json
packages/core-http-utils/lib/server/create.js
packages/core-http-utils/package.json
yarn.lock

Follow up to https://github.com/ArkEcosystem/core/pull/1405 so all hapi servers avoid this issue.

refactor(misc): trim trailing slashes for all hapi servers

---

packages/crypto/lib/crypto/slots.js

resolves https://github.com/ArkEcosystem/core/issues/1385.

refactor(crypto): simpler forging allowance check

---

packages/core-tester-cli/__tests__/commands/command.test.js

- x ] Test (adding missing tests or fixing existing tests)

test(core-tester-cli): run command

---

packages/core-tester-cli/__tests__/commands/command.test.js

This Tests Could Conflict With #1415. Will Fix
- [xx] Test (adding missing tests or fixing existing tests)

test(core-tester-cli): private functions tests

---

packages/core-tester-cli/__tests__/__fixtures__/delegates-page-1.json
packages/core-tester-cli/__tests__/__fixtures__/delegates-page-2.json
packages/core-tester-cli/__tests__/__fixtures__/transaction-1.json
packages/core-tester-cli/__tests__/__fixtures__/transaction-response-1.json
packages/core-tester-cli/__tests__/__fixtures__/voters-page-1.json
packages/core-tester-cli/__tests__/__fixtures__/voters-page-2.json
packages/core-tester-cli/__tests__/__fixtures__/wallet-1.json
packages/core-tester-cli/__tests__/commands/command.test.js
packages/core-tester-cli/lib/commands/command.js
packages/core-tester-cli/lib/commands/transfer.js

test(core-tester-cli): finish commands tests

---

packages/core-database/lib/wallet-manager.js
packages/core-transaction-pool/lib/interface.js
packages/core-transaction-pool/lib/pool-wallet-manager.js
packages/crypto/__tests__/handlers/transactions/delegate-registration.test.js
packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.js
packages/crypto/__tests__/handlers/transactions/handler.test.js
packages/crypto/__tests__/handlers/transactions/ipfs.test.js
packages/crypto/__tests__/handlers/transactions/multi-payment.test.js
packages/crypto/__tests__/handlers/transactions/multi-signature.test.js
packages/crypto/__tests__/handlers/transactions/second-signature.test.js
packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.js
packages/crypto/__tests__/handlers/transactions/transfer.test.js
packages/crypto/__tests__/handlers/transactions/vote.test.js
packages/crypto/__tests__/models/wallet.test.js
packages/crypto/lib/handlers/transactions/delegate-registration.js
packages/crypto/lib/handlers/transactions/delegate-resignation.js
packages/crypto/lib/handlers/transactions/handler.js
packages/crypto/lib/handlers/transactions/index.js
packages/crypto/lib/handlers/transactions/ipfs.js
packages/crypto/lib/handlers/transactions/multi-payment.js
packages/crypto/lib/handlers/transactions/multi-signature.js
packages/crypto/lib/handlers/transactions/second-signature.js
packages/crypto/lib/handlers/transactions/timelock-transfer.js
packages/crypto/lib/handlers/transactions/transfer.js
packages/crypto/lib/handlers/transactions/vote.js
packages/crypto/lib/models/wallet.js

refactor: log reason why transaction fails

---

packages/crypto/lib/validation/extensions/transactions/transfer.js
packages/crypto/lib/validation/extensions/transactions/vote.js

Adjusts some rules that have values that can sometimes be empty.

fix(core-crypto): adjust some validation extensions

---

packages/core-p2p/lib/court/guard.js
packages/core-p2p/lib/defaults.js
packages/crypto/lib/models/wallet.js

Reduce frequency of `x.x.x.x still suspended for x minutes because of ...` messages and remove the network config from the transaction audit.

misc: reduce log spam

---

packages/crypto/lib/validation/extensions/block-id.js
packages/crypto/lib/validation/extensions/block.js
packages/crypto/lib/validation/extensions/index.js
packages/crypto/lib/validation/extensions/transactions/base.js
packages/crypto/lib/validation/rules/models/transactions/delegate-registration.js
packages/crypto/lib/validation/rules/models/transactions/delegate-resignation.js
packages/crypto/lib/validation/rules/models/transactions/ipfs.js
packages/crypto/lib/validation/rules/models/transactions/multi-payment.js
packages/crypto/lib/validation/rules/models/transactions/multi-signature.js
packages/crypto/lib/validation/rules/models/transactions/second-signature.js
packages/crypto/lib/validation/rules/models/transactions/timelock-transfer.js
packages/crypto/lib/validation/rules/models/transactions/transfer.js
packages/crypto/lib/validation/rules/models/transactions/vote.js

Adds the `arkBlockId` Joi extension for readability. Some places checked against the previously defined regex, others against `.number().unsafe()`. In the latter case both alternatives are checked against.

refactor(crypto): joi block id extension

---

packages/core-api/lib/versions/2/handlers/transactions.js
packages/core-blockchain/__tests__/blockchain.test.js
packages/core-p2p/__tests__/server/peer.test.js
packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-p2p/lib/server/versions/peer/handlers/transactions.js
packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool-mem/lib/storage.js
packages/core-transaction-pool/__tests__/guard.test.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/pool-wallet-manager.js
packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js
packages/crypto/lib/validation/extensions/bignumber.js

Refactors the filter logic from the guard and moves the `applyTransaction` on the pool wallet manager to the transaction pool. This way a transaction is added first and then applied. So the guard no longer has to check wether a tx is already in the pool, after it applied a transaction, because of the async nature.
Couldn't test it properly yet, since devnet is broken.
Also fixes #1349

refactor(core-transaction-pool): apply transaction after it has been added

---

packages/core-transaction-pool-mem/lib/connection.js

loggedAllowedSender -> loggedAllowedSenders

refactor(transaction-pool): fix typo

---

packages/core-transaction-pool-mem/lib/connection.js

fix(core-transaction-pool-mem): allowed sender check

---

.eslintrc.json

chore: set max line length to 120

---

.eslintrc.json

chore: adjust max-len rules

---

packages/core-p2p/lib/server/versions/1/handlers.js
packages/core-transaction-pool/lib/interface.js

fix(core-transaction-pool): also remove cached transactions when building wallets

---

packages/core-transaction-pool/lib/guard.js

This explains the following from devnet log:
` Received 40 transactions (accept: 0 broadcast: 40 excess: 0 invalid: 40).`

fix(core-transaction-pool): remove tx from broadcast when already forged

---

package.json
yarn.lock

Was previously using the repository instead of the published package.

chore: use @arkecosystem/eslint-config-base via npm

---

packages/core-blockchain/__tests__/state-storage.test.js
packages/core-blockchain/lib/state-storage.js
packages/core-transaction-pool/lib/guard.js

The [node profiler](https://nodejs.org/en/docs/guides/simple-profiling/) revealed during the previous stress test that a lot of time is spent with immutable.js.
Make proper use of [Seq](https://facebook.github.io/immutable-js/docs/#/Seq) and [withMutations](https://facebook.github.io/immutable-js/docs/#/Set/withMutations) to improve the performance of the state storage operations especially of cache inserts when it is full.
My local test showed that inserts on a full cache are now almost instant, while previously already a small amount of transactions would take ages.

perf(core-blockchain): refactor immutable.js usage

---

packages/core-transaction-pool-mem/lib/storage.js

If any of the BEGIN/INSERT/COMMIT statements fails it will throw an
exception and we should make sure the transaction is rolled back in this
case (if it managed to start).

fix: rollback the sqlite transaction if it aborts

---

packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js

chore: fix typo

---

packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/package.json

Pluralizes a recently added log where the pluralization was missing.

refactor(core-transaction-pool): pluralize log output

---

packages/core-blockchain/lib/state-machine.js
packages/core-p2p/__tests__/monitor.test.js
packages/core-p2p/__tests__/peer.test.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js

The monitor now keeps track of pending peers (those who are sitting in `acceptNewPeer`). This prevents that if a peer is new and sends multiple requests in a small timeframe that the monitor does not enter `acceptNewPeer` multiple times for the same peer. See screenshot:
Pings are now also remembered and a peer is not pinged again if the last ping is not older than 2 minutes.
Lastly, if the number of available peers is below a minimum, the node will now attempt to fetch new peers. This is primarily for nodes without incoming requests, since the peers are depleting over time due to suspensions.

refactor(core-p2p): peer update

---

packages/core-p2p/lib/server/versions/1/handlers.js

Adds payload validation to the v1 p2p transaction endpoint.

fix(core-p2p): payload validation for v1 p2p tx endpoint

---

packages/core-test-utils/config/testnet/plugins.js
packages/core-transaction-pool-mem/lib/defaults.js
packages/core/lib/config/devnet/plugins.js
packages/core/lib/config/mainnet/plugins.js
packages/core/lib/config/testnet.1/plugins.js
packages/core/lib/config/testnet.2/plugins.js
packages/core/lib/config/testnet.live/plugins.js
packages/core/lib/config/testnet/plugins.js

Unless I overlooked something the `whitelist` property was replaced by `allowedSenders`.

chore: remove old and unused config

---

packages/core-blockchain/lib/blockchain.js
packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool/lib/interface.js

When `processBlock` encounters a bad block, purge all transactions from any sender with invalid transactions in that block.

fix(core-blockchain): remove invalid transactions from pool when receiving a bad block

---

packages/core-api/lib/versions/1/handlers/peers.js
packages/core-blockchain/lib/defaults.js
packages/core-container/__tests__/container.test.js
packages/core-container/lib/container.js
packages/core-forger/lib/client.js
packages/core-p2p/lib/peer.js
packages/core-p2p/lib/server/plugins/set-headers.js
packages/core-p2p/lib/server/versions/config/handlers/index.js
packages/core-snapshots-cli/lib/utils/index.js
packages/core-test-utils/lib/helpers/container.js
packages/core/CHANGELOG.md
packages/core/bin/ark
packages/core/lib/start-forger.js
packages/core/lib/start-relay-and-forger.js
packages/core/lib/start-relay.js
packages/core/package.json

Grabs the version of `@arkecosystem/core` from the `package.json` file and uses it as application version.

refactor: base core version on package.json

---

packages/core-blockchain/lib/blockchain.js

This needs to be done here as well in case transactions from a block cannot be applied.

fix(core-blockchain): purge bad block transactions from pool

---

packages/core-blockchain/lib/blockchain.js
packages/core-transaction-pool-mem/__tests__/connection.test.js
packages/core-transaction-pool/lib/interface.js

The approach in #1509  is wrong, we always want to remove all transactions.

fix(core-transaction-pool): purge block

---

packages/core-transaction-pool/lib/interface.js

fix(core-transaction-pool): remove cold wallet check

---

packages/core-elasticsearch/lib/index.js

fix: change alias from arkx to elasticsearch

---

packages/core-tester-cli/lib/commands/delegate-registration.js
packages/core-tester-cli/lib/commands/second-signature.js
packages/core-tester-cli/lib/commands/transfer.js
packages/core-tester-cli/lib/commands/vote.js

Fixes some logs in core-tester-cli.

chore(core-tester-cli): pluralization in logs

---

packages/core-http-utils/lib/plugins/transaction-payload.js

Comment in the code explains it.

fix(core-http-utils): handle empty transaction payloads due to content-type

---

packages/core-transaction-pool/lib/interface.js

According to AIP17 the delete condition is as follows:
>if sender wallet is empty and no other tx with sender as recipient in txpool, remove it from txpool.

fix(core-transaction-pool): delete condition of pool wallet

---

packages/core-transaction-pool-mem/lib/connection.js
packages/core-transaction-pool/lib/guard.js
packages/core-transaction-pool/lib/pool-wallet-manager.js

Take edge case into account and revert transaction when making room for a transaction with higher fee.

fix(core-transaction-pool): dont cache if tx cannot be applied

---

packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js

When calculating quorum, we always need up-to-date peers.

fix(core-p2p): quorum regression

---

packages/core-p2p/lib/peer.js
packages/core-p2p/lib/server/versions/1/handlers.js
yarn.lock

This is a first implementation of the p2p algorithm specified by @zillionn in #1494. I'm not familiar enough with the rationale behind the limit to suggest which solution is best -- the current code, Zillion's first solution (which is what this PR attempts to implement), or his second solution: to forgo rebroadcasting.
If the decision is to forgo rebroadcasting, most of this code can be rolled back and replaced with the previous error code commented out in this PR.

refactor(core-p2p): remove chunk broadcasting

---

packages/core-transaction-pool/lib/interface.js
packages/core-transaction-pool/lib/pool-wallet-manager.js

Also check if recipient balance is zero. And don't purge transactions of recipient when apply failed.

fix(core-transaction-pool): fix cold wallet check

---

packages/core-p2p/__tests__/monitor.test.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/lib/peer.js

revert(core-p2p): properly filter out any version mismatch peers (#1529)

---

packages/core-api/lib/versions/1/transformers/peer.js
packages/core-api/lib/versions/2/transformers/peer.js
packages/core-container/lib/container.js
packages/core-p2p/lib/peer.js

Will make it easier to identify which nodes run which code on development networks.

feat: add git commit hash for development environments to peers

---

packages/core-api/lib/versions/2/transformers/peer.js
packages/core-container/lib/container.js
packages/core-p2p/lib/peer.js
packages/core-p2p/lib/server/plugins/set-headers.js

The commit hash was not properly written to the header, so peers never sent them.

fix(core-p2p): hashid missing from headers

---

packages/core-transaction-pool/__tests__/pool-wallet-manager.test.js

Test when receiving and processing a new block if all wallets are correctly updated : 
- forging delegate should have his wallet increased with block reward + transaction fees
- wallets involved in the block transactions should have the balances updated

test: pool wallet manager update wallets when receiving new block

---

packages/core-database-postgres/lib/connection.js
packages/core-database-postgres/lib/spv.js

If we detected a negative balance during `verifyBlockchain`, we could not recover from it as the rollback does not rebuild wallets. Moving this check to SPV (where it belongs to anyway) solves it.

fix(core-database): move negative balance check to SPV

---

packages/crypto/lib/networks/ark/devnet.json
packages/crypto/lib/networks/ark/mainnet.json
packages/crypto/lib/networks/ark/testnet.json

This PR enables dynamic fees by default. It also fixes block max transactions and increases limits for mainnet

[WIP] chore: dynamic fees on by default

---

packages/core-elasticsearch/package.json
packages/core-error-tracker-bugsnag/package.json
packages/core-error-tracker-sentry/package.json
packages/core-vote-report/package.json

Adjusting some versions that where filled out wrong.

chore: adjust some package versions

---

packages/crypto/lib/networks/ark/devnet.json
packages/crypto/lib/networks/ark/mainnet.json
packages/crypto/lib/networks/ark/testnet.json

Increasing offset for delegate registration. So now with default settings of multiplier 3000 and offset-the fee would be around 12.xxx ARK

chore: increasing offset for delegate registration

---

packages/crypto/__tests__/managers/config.test.js
packages/crypto/lib/networks/ark/devnet.json

Increasing devnet block size on block 1MIL. For the purpose of simulating the auto switch and to test bigger block size:)

chore(crypto): increase devnet block size at height 1000000

---

packages/core-api/src/versions/2/blocks/methods.ts

When fetching the latest block the explorer would occasionally fetch the wrong cached block.

refactor(core-api): lower blocks index timeout

---

.circleci/config.yml
packages/core-blockchain/src/blockchain.ts

Logging was missing which made it hard to see what issues a block had.

fix(core-blockchain): add missing log statement for block verification

---

packages/core-api/src/versions/2/wallets/schema.ts

Wasn't possible to filter transactions on the resource based endpoints.

feat(core-api): allow filtering of transactions for wallet resources

---

packages/core-p2p/package.json
packages/core-p2p/src/monitor.ts
yarn.lock

Properly handle promise timeouts and call `updateNetworkStatusIfNotEnoughPeers` in the right context.

fix(core-p2p): call updateNetworkStatusIfNotEnoughPeers in the correct context

---

packages/crypto/__tests__/identities/address.test.ts
packages/crypto/__tests__/identities/keys.test.ts
packages/crypto/__tests__/identities/public-key.test.ts

Increases coverage by adding tests for lines reported by codecov.

test(crypto): increase identity coverage

---

packages/crypto/__tests__/handlers/transactions/delegate-registration.test.ts
packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.ts
packages/crypto/__tests__/handlers/transactions/handler.test.ts
packages/crypto/__tests__/handlers/transactions/ipfs.test.ts
packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
packages/crypto/__tests__/handlers/transactions/second-signature.test.ts
packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.ts
packages/crypto/__tests__/handlers/transactions/vote.test.ts
packages/crypto/src/handlers/transactions/vote.ts

Increases coverage by adding tests for lines reported by codecov.

test(crypto): increase handler coverage

---

packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
packages/crypto/src/handlers/transactions/handler.ts
packages/crypto/src/handlers/transactions/multi-payment.ts

Increases coverage by adding tests for lines reported by codecov.

test(crypto): increase multi signature/payment coverage

---

.circleci/config.yml
packages/core-blockchain/lib/state-machine.js
packages/core-p2p/CHANGELOG.md
packages/core-p2p/__tests__/monitor.test.js
packages/core-p2p/lib/monitor.js
packages/core-p2p/package.json
packages/core/CHANGELOG.md
packages/core/package.json

This ports 95025854, 9c545bc2 and e42f4c78 from branch 'develop'
to branch 'master'.

fix(core-p2p): prevent the list of peers to become too short

---

packages/core-api/__tests__/v2/handlers/wallets.test.ts
packages/core-api/src/versions/2/wallets/schema.ts
packages/core-database/__tests__/repositories/utils/filter-rows.test.ts
packages/core-database/__tests__/repositories/wallets.test.ts
packages/core-database/src/repositories/utils/filter-rows.ts
packages/core-database/src/repositories/wallets.ts

feat: allow searching wallets by several addresses at once

---

packages/core-api/src/repositories/repository.ts
packages/core-api/src/repositories/transactions.ts
packages/core-graphql/package.json
packages/core-graphql/src/repositories/repository.ts
packages/core-graphql/src/repositories/transactions.ts

refactor: add minimum of minFeeBroadcast for getFeeStatistics query

---

.circleci/config.yml
packages/core-api/src/defaults.ts
packages/core-api/src/server.ts
packages/core-api/src/versions/1/accounts/methods.ts
packages/core-api/src/versions/1/blocks/methods.ts
packages/core-api/src/versions/1/delegates/methods.ts
packages/core-api/src/versions/1/transactions/methods.ts
packages/core-api/src/versions/2/blocks/methods.ts
packages/core-api/src/versions/2/delegates/methods.ts
packages/core-api/src/versions/2/transactions/methods.ts
packages/core-api/src/versions/2/votes/methods.ts
packages/core-api/src/versions/2/wallets/methods.ts
packages/core-database/src/repositories/delegates.ts
yarn.lock

Disable caching for the whole API if wanted, will have a big performance impact to do so.

refactor(core-api): allow full disabling of caching

---

packages/core-p2p/src/monitor.ts

refactor(core-p2p): simplify updatePeersOnMissingBlocks()

---

packages/core-api/__tests__/repositories/transactions.test.ts
packages/core-api/__tests__/repositories/utils/build-filter-query.test.ts
packages/core-api/package.json
packages/core-api/src/index.ts
packages/core-api/src/interfaces/index.ts
packages/core-api/src/plugin.ts
packages/core-api/src/repositories/blocks.ts
packages/core-api/src/repositories/index.ts
packages/core-api/src/repositories/repository.ts
packages/core-api/src/repositories/transactions.ts
packages/core-api/src/server.ts

refactor: export core-api types

---

packages/core-blockchain/lib/blockchain.js
packages/core-database/lib/interface.js
packages/core/package.json

fix: blockchain issues

---

packages/core-blockchain/src/state-storage.ts

Avoid a pattern like
for each element in array1 do: check if it exists in array2 (linearly)
aka
for each element in array1 do: for each element in array2 ...
because its complexity is O(array1.length * array2.length). It can be
easily reduced to O(array1.length) if the check for existence is made
O(1) (hash lookup).

perf(core-blockchain): optimize StateStorage.getCommonBlocks()

---

packages/core-p2p/src/peer.ts

perf(core-p2p): optimize Peer.getPeers()

---

packages/core-webhooks/__tests__/conditions.test.ts
packages/crypto/__tests__/client.test.ts
packages/crypto/__tests__/validation/extensions/bignumber.test.ts
packages/crypto/src/validation/extensions/bignumber.ts

- crypto/client.ts tests against src/ instead of dist/ & added get tests for managers and tx builder
- webhooks/conditions.ts test against a number smaller than condition's between min/max
- crypto/validation/extensions/bignumber.ts tests all the extension's functionality
- also bignumber: rename Bignumber to BigNumber following crypto/utils

test(crypto): bignumber coverage

---

packages/core-container/__tests__/container.test.ts
packages/core-container/src/environment.ts
packages/core-test-utils/src/helpers/container.ts
packages/core/__tests__/__support__/app.ts
packages/core/src/index.ts

A follow up to https://github.com/ArkEcosystem/core/pull/1987.

fix(core-container): always set path variables and overwrite custom ones

---

docker/development/docker-compose.yml
docker/devnet/docker-compose.yml
docker/mainnet/docker-compose.yml
docker/testnet/docker-compose.yml

Following "debranding" refactor there was needed to update docker-compose files, because database user was changed in networks plugins.js config to "core".
Also changed the name of the container from ark to core, hope it's ok.

chore: ark => core in docker-compose files

---

packages/core-json-rpc/__tests__/blocks.test.ts
packages/core-json-rpc/src/server/methods/blocks/transactions.ts
packages/core-json-rpc/src/server/services/network.ts
packages/core-json-rpc/src/server/services/processor.ts

- __ methods marked as private  (with __ removed) ; these were only used internally, not even in tests
- Add single test case
- Reformat the error checking logic on blockTransactions to match latestBlock (check for response, return response or error)

refactor(core-json-rpc): mark __ methods as private

---

packages/crypto/__tests__/models/block.test.ts
packages/crypto/__tests__/models/delegate.test.ts
packages/crypto/__tests__/models/wallet.test.ts
packages/crypto/src/models/wallet.ts

Added tests to crypto models to get coverage to 100% for the models folder.
Also please have a look at the refactor on models/wallet.
- [x I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation

test(crypto): increase model coverage

---

packages/crypto/__tests__/validation/rules/models/transactions/common.ts
packages/crypto/__tests__/validation/rules/models/transactions/delegate-registration.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/delegate-resignation.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/ipfs.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/multi-payment.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/multi-signature.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/second-signature.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/timelock-transfer.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/transfer.test.ts
packages/crypto/__tests__/validation/rules/models/transactions/vote.test.ts
packages/crypto/src/builder/transactions/delegate-resignation.ts
packages/crypto/src/builder/transactions/multi-payment.ts
packages/crypto/src/builder/transactions/timelock-transfer.ts
packages/crypto/src/validation/extensions/bignumber.ts
packages/crypto/src/validation/rules/models/transactions/delegate-registration.ts
packages/crypto/src/validation/rules/models/transactions/delegate-resignation.ts
packages/crypto/src/validation/rules/models/transactions/ipfs.ts
packages/crypto/src/validation/rules/models/transactions/multi-payment.ts
packages/crypto/src/validation/rules/models/transactions/multi-signature.ts
packages/crypto/src/validation/rules/models/transactions/second-signature.ts
packages/crypto/src/validation/rules/models/transactions/timelock-transfer.ts
packages/crypto/src/validation/rules/models/transactions/transfer.ts
packages/crypto/src/validation/rules/models/transactions/vote.ts

Add tests for crypto rules/models/transactions + refactor a the same time as I found some slight improvements to do (please review if it's ok).

test: crypto transaction validators tests + refactor

---

packages/crypto/__tests__/builder/transactions/delegate-registration.test.ts
packages/crypto/__tests__/builder/transactions/multi-payment.test.ts
packages/crypto/__tests__/builder/transactions/multi-signature.test.ts
packages/crypto/__tests__/builder/transactions/second-signature.test.ts
packages/crypto/__tests__/builder/transactions/transfer.test.ts
packages/crypto/__tests__/builder/transactions/vote.test.ts
packages/crypto/__tests__/crypto/bip38.test.ts
packages/crypto/__tests__/crypto/crypto.test.ts
packages/crypto/__tests__/crypto/hdwallet.test.ts
packages/crypto/__tests__/crypto/slots.test.ts
packages/crypto/__tests__/deserializers/transaction.test.ts
packages/crypto/__tests__/handlers/transactions/handler.test.ts
packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
packages/crypto/__tests__/managers/config.test.ts
packages/crypto/__tests__/managers/fee.test.ts
packages/crypto/__tests__/managers/network.test.ts
packages/crypto/__tests__/utils/sort-transactions.test.ts
packages/crypto/src/builder/transactions/multi-payment.ts

Finally ! :100: 
Added missing tests to get to 100% coverage.

test(crypto): add missing tests to get coverage to 100%

---

scripts/upgrade/upgrade.js

As documented in https://github.com/ArkEcosystem/core/blob/develop/UPGRADE.md#upgrade-from-core-20-to-210 those changes are required for mainnet or a relay will fail to start due to invalid configuration.

chore: update the plugins.js file through the upgrade script

---

install.sh

Continue instead exit (Line 301).
- [x ] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation

fixed exit

---

packages/core-database/src/defaults.ts
packages/core-database/src/plugin.ts
packages/core-snapshots-cli/src/commands/verify.ts
packages/core-snapshots-cli/src/index.ts
packages/core-snapshots/src/utils/index.ts
scripts/upgrade/upgrade.js

fix(core-snapshots): use correct paths and add migration

---

.circleci/config.yml
packages/core-blockchain/lib/blockchain.js
packages/core-p2p/__tests__/utils/is-myself.test.js
packages/core-p2p/lib/utils/is-myself.js
packages/core/package.json

fix: Core-SV-009 and Core-SV-010

---

packages/core-p2p/src/server/plugins/validate-headers.ts

Needed for testing in the future with releases that contain alpha or beta suffixes.

refactor(core-p2p): allow longer version strings

---

packages/core-p2p/src/peer.ts
packages/core-utils/src/nsect.ts

Fragmented the network, needs to be checked. Won't go into 2.2.

fix(core-p2p): disable peer verifier

---

.circleci/config.yml
.circleci/configTemplate.json
.circleci/generateConfig.js

Run linting on CircleCI as some people seem to push with linting disabled.

 chore: run linting on CircleCI

---

packages/core-elasticsearch/src/indices/transactions.ts

fix(core-elasticsearch): build failure

---

packages/core-p2p/src/peer-verifier.ts

This is only duplicates the message we already print in `acceptNewPeer`.

misc(core-p2p): remove superfluous log message

---

packages/core-p2p/src/monitor.ts
packages/core-p2p/src/peer-verifier.ts
packages/core-p2p/src/peer.ts

The recent change to channel each new peer through `acceptNewPeer` made it quite verbose. This PR also silences most of the peer verifier messages, if anyone is really interested in them they can be enabled via the undocumented env variable `CORE_P2P_PEER_VERIFIER_DEBUG_EXTRA`.

refactor(core-p2p):  reduce logging noise

---

packages/core-container/src/config/loaders/file-loader.ts

Throw an error if any of the required files are missing.

refactor(core-container): throw an error if the peers or plugins file are missing

---

packages/core/src/commands/command.ts

fix(core): do not ignore the network flag in parseWithNetwork

---

packages/core/src/commands/command.ts

fix(core): overwrite the config path if an env variable is provided

---

packages/core-interfaces/src/core-p2p/monitor.ts
packages/core-p2p/__tests__/monitor.test.ts
packages/core-p2p/src/monitor.ts

Do not attempt to download blocks from peers that are on a different
chain because we know those blocks are not suitable for our chain.

refactor(core-p2p): Improve selection of peer for downloading blocks

---

packages/core/src/commands/core/restart.ts

```
ark core:restart
Restarting ark-core-forger... done
›   Warning: The "ark-core-forger" process does not exist.
```
Reported by `alessio / fun`.

fix(core): return correct suffix for core:restart command

---

packages/core/src/commands/snapshot/dump.ts
packages/core/src/commands/snapshot/restore.ts
packages/core/src/commands/snapshot/rollback.ts
packages/core/src/commands/snapshot/truncate.ts
packages/core/src/commands/snapshot/verify.ts

Exit the CLI with an error message rather then showing a generic error.

refactor(core): exit the CLI if snapshots are not available

---

docker/production/entrypoint.sh

The `--force` flag was removed to avoid accidental user errors so we need to use `config:reset` to emulate the behaviour.
@adrian69 check if that resolves your issues

fix(docker): remove force flag and add a forger check

---

benchmark/block/create.js
benchmark/index.js
benchmark/transaction/create/0.js
benchmark/transaction/deserialize/methods.js
benchmark/transaction/serialize/0.js
packages/crypto/src/crypto/crypto.ts
packages/crypto/src/transactions/index.ts
packages/crypto/src/transactions/serializers/block.ts
packages/crypto/src/transactions/serializers/transaction.ts
yarn.lock

Makes the Transaction/Block benchmarks more meaningful, since they weren't properly updated to reflect the changes with AIP29.

refactor(crypto): benchmarks

---

packages/core/src/commands/command.ts
packages/core/src/process-manager.ts

If a process is not online we assume it is offline on purpose, thus we won't ask to restart it.

refactor(core): only ask to restart processes that are online

---

packages/core-p2p/src/server/versions/internal/handlers/rounds.ts

Pegs the block timestamp to slot time. In case someone accidentally double forges (empty) blocks they are at least guaranteed to have the same timestamp.

refactor(core-forger): use slot time for block timestamp

---

packages/core/src/commands/command.ts
packages/core/src/enums.ts
packages/core/src/process-manager.ts
packages/core/src/shared/start.ts

Add proper state checks based on the states specified in the pm2 god module.

refactor(core): add methods for online, stopped and errored states

---

packages/core/src/commands/command.ts
packages/core/src/commands/core/start.ts
packages/core/src/commands/forger/start.ts
packages/core/src/commands/relay/start.ts
packages/core/src/process-manager.ts
packages/core/src/shared/log.ts
packages/core/src/shared/restart.ts
packages/core/src/shared/start.ts
packages/core/src/shared/status.ts
packages/core/src/shared/stop.ts

Clean up of all state check logic.

refactor(core): add abortion state helpers

---

CHANGELOG.md

Changelog for the `2.2.0` release.

docs: 2.2.0 changelog

---

packages/crypto/package.json

chore(crypto): add missing devDependencies

---

.circleci/config.yml
__tests__/unit/core-tester-cli/commands/debug/deserialize.test.ts
__tests__/unit/core-tester-cli/commands/debug/identity.test.ts
__tests__/unit/core-tester-cli/commands/debug/serialize.test.ts
__tests__/unit/core-tester-cli/commands/debug/verify-second.test.ts
__tests__/unit/core-tester-cli/commands/debug/verify.test.ts
packages/core-tester-cli/src/commands/command.ts
packages/core-tester-cli/src/commands/debug/deserialize.ts
packages/core-tester-cli/src/commands/debug/identity.ts
packages/core-tester-cli/src/commands/debug/serialize.ts
packages/core-tester-cli/src/commands/debug/verify-second-signature.ts
packages/core-tester-cli/src/commands/debug/verify.ts
packages/crypto/src/managers/index.ts

The `debug:*` commands would always use the `devnet` configuration.

fix(core-tester-cli): set crypto network for debug commands

---

packages/core-forger/src/client.ts
packages/core-forger/src/manager.ts

The 2 seconds timeout is too short and can unnecessary blow up the
forging process in cases where it is possible to forge successfully.
Set it to an arbitrary 7 seconds which is block time minus 1 second for
other activities.
Elaborate log messages by explicitly saying "Will not forge" + an
explanation "why" when the code would decide not to forge.

refactor(core-forger): Increase timeout for getting the network state

---

packages/core-tester-cli/src/commands/debug/serialize.ts

The string provided as an input is supposed to be JSON that is to be
serialized.

fix(core-tester-cli): Fix the description of debug:serialize

---

packages/core-p2p/src/network-state.ts

We need >66% quorum to forge and thus we should not count peers that
report "forgingAllowed: false" towards no-quorum ones, because too many
such peers could trip the forger to skip a block.

feat(core-p2p): Don't spoil the quorum if the peer has !forgingAllowed

---

packages/crypto/src/models/block.ts

fix(crypto): cast tx buffer to string in block audit

---

packages/core-p2p/src/defaults.ts
packages/core/src/commands/config/cli.ts
packages/core/src/helpers/update.ts
packages/core/src/hooks/init/update.ts

Support for https://github.com/ArkEcosystem/core/pull/2249 in the CLI.

feat(core): support for the next channel

---

__tests__/unit/core-webhooks/database.test.ts
packages/core-webhooks/src/database.ts
packages/core-webhooks/src/manager.ts

Add unit tests for the lowdb database of core-webhooks.

test(core-webhooks): unit test the database

---

CHANGELOG.md

Initial changelog for `2.3.0`.

docs: initial 2.3.0 changelog

---

__tests__/unit/core-blockchain/blockchain.test.ts
packages/core-blockchain/src/blockchain.ts
packages/core-blockchain/src/machines/actions/sync-with-network.ts
packages/core-blockchain/src/state-machine.ts

When the chain is only a few slots behind when syncing it can happen that the state machine misses an event and gets stuck in limbo. This is because downloading and processing blocks happens in parallel and the queue can finish while there's a pending download. In which case the download will return without dispatching a new event.
This is fixed by actually handling the `PROCESSFINISHED` event when in `downloadBlocks` state.
Additionally, all events without actions are logged as well so debugging becomes less of a guessing game.

fix(core-blockchain): handle unhandled event

---

deprecated/core-graphql/README.md
deprecated/core-logger-winston/README.md
deprecated/core-snapshots-cli/README.md
packages/core-api/README.md
packages/core-blockchain/README.md
packages/core-container/README.md
packages/core-database/README.md
packages/core-elasticsearch/README.md
packages/core-error-tracker-bugsnag/README.md
packages/core-error-tracker-sentry/README.md
packages/core-event-emitter/README.md
packages/core-forger/README.md
packages/core-http-utils/README.md
packages/core-json-rpc/README.md
packages/core-logger/README.md
packages/core-p2p/README.md
packages/core-tester-cli/README.md
packages/core-transaction-pool/README.md
packages/core-transactions/README.md
packages/core-utils/README.md
packages/core-vote-report/README.md
packages/core-webhooks/README.md
packages/core/README.md

Updates various readme.md files to resolve #2262

docs: fix broken references to plugins docs

---

README.md
deprecated/core-graphql/README.md
deprecated/core-logger-winston/README.md
deprecated/core-snapshots-cli/README.md
packages/core-api/README.md
packages/core-blockchain/README.md
packages/core-container/README.md
packages/core-database-postgres/README.md
packages/core-database/README.md
packages/core-elasticsearch/README.md
packages/core-error-tracker-bugsnag/README.md
packages/core-error-tracker-sentry/README.md
packages/core-event-emitter/README.md
packages/core-forger/README.md
packages/core-http-utils/README.md
packages/core-jest-matchers/README.md
packages/core-json-rpc/README.md
packages/core-logger-pino/README.md
packages/core-logger/README.md
packages/core-p2p/README.md
packages/core-snapshots/README.md
packages/core-tester-cli/README.md
packages/core-transaction-pool/README.md
packages/core-transactions/README.md
packages/core-utils/README.md
packages/core-vote-report/README.md
packages/core-webhooks/README.md
packages/core/README.md
packages/crypto/README.md

Link to the contributors page instead of adding them one by one and fix the banner.

chore: update readme files with all contributors and fix banners

---

deprecated/core-snapshots-cli/package.json
package.json
packages/core-tester-cli/package.json
packages/core/package.json
yarn.lock

chore: add missing oclif dependency

---

packages/core-snapshots/src/db/index.ts
packages/core-snapshots/src/db/queries/transactions/timestamp-range.sql
packages/core-snapshots/src/db/utils/column-set.ts
packages/core-snapshots/src/transport/codecs/core-codec.ts
packages/core-snapshots/src/transport/codecs/core/index.ts
packages/core-snapshots/src/transport/verification.ts

Didn't work at all and produced corrupt dumps.

fix(core-snapshots): snapshot manager

---

packages/core-logger-pino/package.json
packages/core-logger-pino/src/driver.ts
packages/core-tester-cli/package.json

Fixes a crash on rotate, same issue as described in detail [here](https://github.com/iccicci/rotating-file-stream/issues/25).
Also enables gzip compression and fixes wrong dependencies.

fix(core-logger-pino): don't crash on rotate

---

packages/core-api/package.json
packages/core-database-postgres/package.json
packages/core-elasticsearch/package.json
packages/core-http-utils/package.json
packages/core-jest-matchers/package.json
packages/core-tester-cli/package.json
packages/core-transactions/package.json
packages/core-utils/package.json
packages/crypto/package.json
yarn.lock

A few dependencies were missing from packages directly which caused npm build issues.
_Works fine with `lerna bootstrap` because packages are symlinked but once build they are not available if they're not direct dependencies of a package._

chore: add missing dependencies

---

docker/production/Dockerfile
docker/production/devnet/docker-compose-build.yml
docker/production/devnet/docker-compose.yml
docker/production/mainnet/docker-compose-build.yml
docker/production/mainnet/docker-compose.yml

Remove source from image. Add build time ARG variable, so NPM channel channel can be defined on image build.

Remove source from image. Add build time ARG variable, so NPM channel channel can be defined on image build.

---

packages/core-logger-pino/package.json
packages/core-logger-pino/src/driver.ts
packages/core-tester-cli/package.json
packages/core/package.json
yarn.lock

fix(core-logger-pino): prettify filestream

---

packages/core-database-postgres/src/postgres-connection.ts
packages/crypto/src/transactions/serializers/transaction.ts

Use correct transaction id of mainnet exceptions for database query.

fix(core-database-postgres): asset migration on mainnet

---

.circleci/config.yml
packages/core-error-tracker-rollbar/.gitattributes
packages/core-error-tracker-rollbar/README.md
packages/core-error-tracker-rollbar/package.json
packages/core-error-tracker-rollbar/src/defaults.ts
packages/core-error-tracker-rollbar/src/index.ts
packages/core-error-tracker-rollbar/tsconfig.json

Error Tracker integration for https://rollbar.com/.

feat(core-error-tracker-rollbar): initial implementation

---

.circleci/config.yml
packages/core-error-tracker-raygun/.gitattributes
packages/core-error-tracker-raygun/README.md
packages/core-error-tracker-raygun/package.json
packages/core-error-tracker-raygun/src/defaults.ts
packages/core-error-tracker-raygun/src/index.ts
packages/core-error-tracker-raygun/tsconfig.json

Error Tracker integration for https://raygun.com/.

feat(core-error-tracker-raygun): initial implementation

---

.circleci/config.yml
packages/core-error-tracker-airbrake/.gitattributes
packages/core-error-tracker-airbrake/README.md
packages/core-error-tracker-airbrake/package.json
packages/core-error-tracker-airbrake/src/defaults.ts
packages/core-error-tracker-airbrake/src/index.ts
packages/core-error-tracker-airbrake/tsconfig.json

Error Tracker integration for https://airbrake.io/.

feat(core-error-tracker-airbrake): initial implementation

---

packages/core-snapshots/src/transport/codec.ts

#2301 changed the default codec which serializes the wrong timestamp and deserializes broken buffers.

fix(core-snapshots): core codec

---

packages/core-database-postgres/src/postgres-connection.ts
packages/core-database/src/database-service.ts

Store the correct timestamp in the transactions table.

fix(core-database): transaction timestamp

---

__tests__/unit/crypto/transactions/transaction.test.ts
benchmark/transaction/create/0.js
packages/core-database-postgres/src/postgres-connection.ts
packages/core-database-postgres/src/queries/transactions/find-by-block.sql
packages/core-database-postgres/src/queries/transactions/latest-by-block.sql
packages/core-database-postgres/src/queries/transactions/latest-by-blocks.sql
packages/core-database/src/database-service.ts
packages/core-elasticsearch/src/indices/transactions.ts
packages/core-snapshots/src/transport/codec.ts
packages/crypto/src/transactions/deserializers/transaction.ts
packages/crypto/src/transactions/types/transaction.ts

Fetching transactions from the database is super slow, because we always perform crypto verify,
id calculation and other overhead. All of this shouldn't be necessary, since all the steps are already performed before a transaction is even allowed to enter the database in the first place.
This PR introduces a new function called `fromBytesUnsafe` which deserializes a transaction
without all the overhead.
Non-scientific benchmark:
(400 blocks, 15000+ transactions)
```
GET localhost:4002/peer/blocks?lastBlockHeight=269572
GET BLOCKS: 12493.502ms	  | no change
GET BLOCKS: 3695.236ms 	  | skip verify
GET BLOCKS: 1985.264ms 	  | skip verify, skip id
```
This explains many block download timeouts and nodes that get stuck around height 270000.

perf(crypto): skip transaction verification overhead

---

packages/core/src/commands/update.ts

Regression from 2.3 changes for the `next` channel support.

fix(core): read the correct property for the new CLI version

---

packages/crypto/src/transactions/types/schemas.ts

fix(crypto): add signSignature to schema

---

packages/core-p2p/src/monitor.ts

When a network health check is performed, we also need to refresh all peers afterwards to
update the `peer.verification` status, otherwise they still report to be forked.

fix(core-p2p): always refresh peer status

---

packages/core-database-postgres/src/models/block.ts

Resolves https://github.com/ArkEcosystem/core/issues/2314

feat(core-database-postgres): support IN operator for block id, height and generator

---

packages/crypto/src/models/block.ts

Some exceptions are not schema conform and prevent a sync from 0.
E.g. this vendor field from before the milestone:
https://dexplorer.ark.io/transaction/76bd168e57a4431a64617c4e7864df1e0be89831eabaa230e37643efae2def6f

fix(crypto): check if block contains exceptions

---

packages/core-container/src/container.ts
packages/core-database-postgres/src/postgres-connection.ts

Exit core instead of continuing the startup since it's not going to work anyway.

fix(core-database-postgres): shutdown when integrity check fails

---

packages/core/package.json
packages/core/src/shared/log.ts
yarn.lock

@supaiku0 when testing this check if any lines are missing compared to `pm2 logs` and that it now behaves as closely as possible like `pm2 logs`.

fix(core): preserve existing logs and attach the last line when the log is modified

---

packages/core-api/src/repositories/transactions.ts
packages/core-api/src/versions/1/transactions/transformer.ts
packages/core-api/src/versions/2/transactions/controller.ts
packages/core-api/src/versions/2/transactions/transformer.ts
packages/core-api/src/versions/2/wallets/controller.ts
packages/crypto/src/transactions/types/transaction.ts

#2307 introduced a new function to deserialize transactions with less overhead. This PR adapts the transaction transformer to make use of it.

perf(core-api): transaction transformer

---

packages/core-p2p/src/monitor.ts

fix(core-p2p): accept accepted peers

---

packages/core-database-postgres/src/postgres-connection.ts

The `20190313000000-add-asset-column-to-transactions-table.sql` file has to be executed before the migration of the table rows can start.

fix(core-database-postgres): run the asset migration before starting the record migration

---

install.sh

Install node.js with our setup script since it has been stable for quite some time now.

chore: install node.js 11 now that it is stable

---

.circleci/config.yml
__tests__/unit/core-database/repositories/blocks-business-repository.test.ts
packages/core-database/src/repositories/blocks-business-repository.ts

Follow up to https://github.com/ArkEcosystem/core/commit/eae1c87551a957ebc1c04ee656065faa669296cf.

refactor(core-database): use a raw query to get a block by height

---

.circleci/config.yml
__tests__/unit/core-logger-signale/logger.test.ts
packages/core-logger-signale/.gitattributes
packages/core-logger-signale/README.md
packages/core-logger-signale/package.json
packages/core-logger-signale/src/defaults.ts
packages/core-logger-signale/src/driver.ts
packages/core-logger-signale/src/index.ts
packages/core-logger-signale/src/plugin.ts
packages/core-logger-signale/tsconfig.json
yarn.lock

A logger that allows a lot of customisation https://github.com/klaussinani/signale.

feat(core-logger-signale): initial implementation

---

packages/crypto/src/crypto/crypto.ts

fix(crypto): use calculated id

---

__tests__/unit/core-logger-pino/logger.test.ts
packages/core-logger-pino/src/defaults.ts
packages/core-logger-pino/src/driver.ts

Partially resolves #2365. The first point still needs to be addressed.

fix(core-logger-pino): initial rotation

---

__tests__/integration/core-p2p/network-monitor.test.ts
__tests__/integration/core-p2p/socket-server/peer.test.ts
__tests__/unit/core-p2p/mocks/p2p/peer-processor.ts
__tests__/unit/core-p2p/network-monitor.test.ts
__tests__/unit/core-p2p/peer-processor.test.ts
packages/core-interfaces/src/core-p2p/peer-communicator.ts
packages/core-interfaces/src/core-p2p/peer-processor.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/peer-processors.ts
packages/core-p2p/src/socket-server/worker.ts

Adds more type hints, changes the visibility of some methods and includes minor fixes.

refactor(core-p2p): types, method visibility and various fixes

---

packages/core-container/src/container.ts
packages/core-interfaces/src/core-container/container.ts
packages/core-logger-pino/package.json
packages/core-logger-pino/src/driver.ts
packages/core-logger/package.json
packages/core-logger/src/factory.ts
packages/core/src/commands/command.ts
packages/core/src/commands/core/run.ts
packages/core/src/commands/core/start.ts
packages/core/src/commands/forger/run.ts
packages/core/src/commands/forger/start.ts
packages/core/src/commands/relay/run.ts
packages/core/src/commands/relay/start.ts
packages/core/src/shared/run.ts
packages/core/src/shared/start.ts

refactor(core-container): pass suffix to container

---

packages/core-p2p/src/network-monitor.ts

Caused a stack overflow when no peers were available.

fix(core-p2p): sync with network

---

packages/core-database/src/repositories/transactions-business-repository.ts

Searching through `api/v2/wallets/transactions` a valid but not recorded transaction, causes HTTP 500 and log error. 
This case wasn't handled previously.

fix(core-database): handle unknown transaction search

---

packages/core-database-postgres/src/integrity-verifier.ts

fix(core-database): broken genesis wallet check

---

__tests__/unit/core-database/repositories/delegates-business-repository.test.ts
__tests__/unit/core-database/wallet-manager.test.ts
packages/core-api/src/versions/2/delegates/methods.ts
packages/core-database-postgres/src/integrity-verifier.ts
packages/core-database/src/repositories/delegates-business-repository.ts
packages/core-database/src/wallet-manager.ts
packages/core-interfaces/src/core-database/wallet-manager.ts

Resolves #2350 for real this time.

fix(core-database): wrong delegate order after start up

---

__tests__/unit/core-p2p/network-monitor.test.ts
packages/core-interfaces/src/core-p2p/network-monitor.ts
packages/core-p2p/src/network-monitor.ts

feat(core-p2p): parallel block download

---

packages/core-database-postgres/src/integrity-verifier.ts

If there is an integrity issue with the wallets we need to throw so the state machine can know about it and act accordingly.

refactor(core-database-postgres): throw an error if there is a wallet integrity issue

---

__tests__/unit/crypto/blocks/block.test.ts
__tests__/unit/crypto/blocks/factory.test.ts
__tests__/unit/crypto/transactions/factory.test.ts
packages/crypto/src/blocks/factory.ts
packages/crypto/src/errors.ts
packages/crypto/src/transactions/factory.ts
packages/crypto/src/transactions/serializer.ts

Initial tests for the factories in `packages/src/crypto`.

test(crypto): unit test the BlockFactory and TransactionFactory

---

__tests__/integration/core-json-rpc/transactions.test.ts
packages/core-json-rpc/src/server/services/database.ts

Add tests for 422 responses caused by transaction verification failures.

test(core-json-rpc): test responses with verification failures

---

__tests__/unit/core-database/wallet-manager.test.ts
packages/core-database-postgres/src/integrity-verifier.ts
packages/core-database/src/wallet-manager.ts

Fix build issues after 2.3 was merged into 2.4.

fix: issues after merging 2.3

---

.circleci/config.yml
CHANGELOG.md
__tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
__tests__/unit/core-transaction-pool/guard.test.ts
packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
packages/core-transactions/src/handlers/delegate-registration.ts
packages/core-transactions/src/handlers/transaction.ts
packages/core-transactions/src/handlers/transfer.ts
packages/core-transactions/src/handlers/vote.ts

fix(core-transaction-pool): refuse transactions from senders with pending second signature registrations

---

packages/crypto/src/transactions/builders/transactions/ipfs.ts

fix(crypto): don't use vendorField type as buffer encoding for IPFS

---

.github/PULL_REQUEST_TEMPLATE.md

docs(template): add release section to pull request template

---

__tests__/integration/core-transaction-pool/processor.test.ts
__tests__/integration/core-transaction-pool/wallet-manager.test.ts
__tests__/unit/core-database/database-service.test.ts
__tests__/unit/core-transaction-pool/connection.test.ts
__tests__/unit/core-transactions/handler-registry.test.ts
__tests__/unit/core-transactions/handler.test.ts
packages/core-database/src/database-service.ts
packages/core-state/src/wallets/wallet-manager.ts
packages/core-transaction-pool/src/connection.ts
packages/core-transaction-pool/src/processor.ts
packages/core-transaction-pool/src/wallet-manager.ts
packages/core-transactions/src/handlers/handler-registry.ts
packages/core-transactions/src/handlers/index.ts
packages/core-transactions/src/index.ts

Extracted this from my local AIP18 branch, so it doesn't get too ugly staying in sync with develop. This is reorganizing all exports using nicer names.

refactor(core-transactions): reorganize exports

---

package.json
packages/core-p2p/src/utils/is-valid-peer.ts
packages/core/src/process-manager.ts
packages/crypto/src/transactions/types/schemas.ts
tslint.json

Enable the `no-use-before-declare` rule for `tslint`.

style: enable "no-use-before-declare" rule

---

__tests__/functional/transaction-forging/__support__/index.ts
__tests__/functional/transaction-forging/delegate-registration.test.ts
__tests__/functional/transaction-forging/second-signature-registration.test.ts
__tests__/functional/transaction-forging/vote.test.ts
__tests__/unit/core-state/wallets/wallet.test.ts
__tests__/unit/crypto/transactions/schemas.test.ts
packages/core-transactions/src/errors.ts
packages/core-transactions/src/handlers/delegate-registration.ts
packages/core-transactions/src/handlers/second-signature.ts
packages/crypto/src/transactions/types/schemas.ts

Adds functional multi sig tests for `second signature registration`, `delegate registration` and `vote`.

test(functional): more multi signature tests

---

packages/core-transactions/src/handlers/delegate-registration.ts
packages/crypto/src/transactions/factory.ts

Also call `applyV1Compatibility` when the version is missing. This check somehow got lost after the AIP18 branch got merged.

fix(crypto): handle missing version

---

__tests__/unit/crypto/crypto/hash.test.ts

Add tests for ECDSA signing and verifying.

test(crypto): ECDSA signature

---

CHANGELOG.md

Preliminary changelog for `2.4.0`.

docs: 2.4.0 changelog

---

packages/core/package.json

fix(core): use the --env flag to start testnet via CLI

---

__tests__/integration/core-api/v1/handlers/peers.test.ts
__tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
__tests__/integration/core-p2p/__support__/utils.ts
__tests__/integration/core-p2p/peer-communicator.test.ts
__tests__/integration/core-p2p/socket-server/peer.test.ts
__tests__/unit/core-p2p/peer-guard.test.ts
__tests__/unit/core-p2p/peer.test.ts
packages/core-api/src/versions/1/peers/controller.ts
packages/core-api/src/versions/1/peers/schema.ts
packages/core-api/src/versions/1/peers/transformer.ts
packages/core-api/src/versions/2/peers/controller.ts
packages/core-api/src/versions/2/peers/schema.ts
packages/core-api/src/versions/2/peers/transformer.ts
packages/core-forger/src/client.ts
packages/core-interfaces/src/core-p2p/peer-guard.ts
packages/core-interfaces/src/core-p2p/peer.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/peer-guard.ts
packages/core-p2p/src/peer-processors.ts
packages/core-p2p/src/peer.ts
packages/core-p2p/src/socket-server/utils/get-headers.ts
packages/core-p2p/src/socket-server/utils/validate-headers.ts
packages/core-p2p/src/socket-server/versions/peer.ts

Temporarily reverting #2552 and #2553 since they cause some issues for the seed nodes.

revert(core-p2p): peer header changes

---

__tests__/functional/transaction-forging/__support__/index.ts
__tests__/functional/transaction-forging/delegate-registration.test.ts
__tests__/functional/transaction-forging/ipfs.test.ts
__tests__/functional/transaction-forging/multi-signature-registration.test.ts
__tests__/functional/transaction-forging/second-signature-registration.test.ts
__tests__/functional/transaction-forging/transfer.test.ts
__tests__/functional/transaction-forging/vote.test.ts
__tests__/helpers/transaction-factory.ts
packages/core-jest-matchers/package.json
packages/core-jest-matchers/src/functional/accepted.ts
packages/core-jest-matchers/src/functional/forged.ts
packages/core-jest-matchers/src/functional/index.ts
packages/core-jest-matchers/src/functional/rejected.ts
packages/core-jest-matchers/src/index.ts
yarn.lock

Resolves https://github.com/ArkEcosystem/core/issues/2561

feat(core-jest-matchers): functional test matchers

---

packages/core-http-utils/src/plugins/hapi-ajv.ts

refactor(core-http-utils): return all schema errors

---

__tests__/unit/core-transactions/handler-registry.test.ts
packages/crypto/src/transactions/types/schemas.ts

fix(crypto): make amount required

---

__tests__/unit/crypto/transactions/verifier.test.ts
packages/crypto/src/transactions/verifier.ts

Use the signature length instead of the transaction version to determine how to verify the signature.

refactor(crypto): signature verification

---

.circleci/config.yml
CHANGELOG.md

chore(changelog): add latest changes for 2.4.0

---

packages/core-database-postgres/src/repositories/transactions.ts

fix(core-database-postgres): use day instead of date

---

packages/core-database-postgres/package.json

Add missing core-state dependency to core-database-postgres.

chore: add core-state dependency to core-database-postgres

---

packages/core-json-rpc/src/server/modules.ts

refactor(core-json-rpc): use blockId schema for validation

---

__tests__/unit/core-p2p/peer-guard.test.ts
packages/core-blockchain/package.json
packages/core-database-postgres/package.json
packages/core-database/package.json
packages/core-forger/package.json
packages/core-json-rpc/package.json
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/peer-guard.ts
packages/core-p2p/src/peer-processors.ts
packages/core-p2p/src/peer.ts
packages/core-state/package.json
packages/core-transaction-pool/package.json
packages/core-wallet-api/package.json

Merge develop into 2.5

---

packages/core-database/src/database-service.ts

Fixes #2350 this time for real.

fix(core-database): assign calculated delegate ranks from temp wallets

---

__tests__/e2e/lib/generate-files.js
__tests__/functional/transaction-forging/__support__/index.ts
__tests__/integration/core-p2p/__support__/setup.ts
__tests__/integration/core-transaction-pool/__support__/setup.ts
__tests__/unit/core-forger/manager.test.ts
__tests__/unit/core-p2p/network-monitor.test.ts
__tests__/utils/config/testnet/plugins.js
__tests__/utils/config/unitnet/plugins.js
packages/core-forger/src/manager.ts
packages/core-interfaces/src/core-p2p/network-monitor.ts
packages/core-p2p/src/defaults.ts
packages/core-p2p/src/enums.ts
packages/core-p2p/src/network-monitor.ts
packages/core-p2p/src/network-state.ts
packages/core-p2p/src/peer-communicator.ts
packages/core-p2p/src/socket-server/index.ts
packages/core/bin/config/devnet/plugins.js
packages/core/bin/config/testnet/plugins.js

Serves no purpose anymore since a relay doesn't start without enough peers anyway so it makes no difference for a forger.

refactor(core-blockchain): remove coldstart period

---

__tests__/unit/core-forger/manager.test.ts
packages/core-forger/src/client.ts
packages/core-forger/src/manager.ts

The schema expects an object and not a string. Therefore the forger failed to notify the relay whenever it encountered an error while forging a block.

fix(core-forger): wrap error message to satisfy schema

---

install.sh

ask for a retry if installing core fails from install.sh

refactor: ask for a retry if installing core fails from install.sh

---

install.sh

Fix https://github.com/ArkEcosystem/core/issues/2623

refactor: improve database configuration in install.sh script

---

.yarnrc

The sqlite build fails more often than it should, which is a big waste of time. Building all modules sequentially seems to do the trick as I'm no longer able to reproduce it. The setup doesn't feel much slower either.

build: sequentially build modules with yarn

---

packages/core-api/package.json
packages/core-api/src/handlers/blocks/methods.ts
packages/core-api/src/handlers/delegates/methods.ts
packages/core-api/src/handlers/rounds/methods.ts
packages/core-api/src/handlers/transactions/methods.ts
packages/core-api/src/handlers/utils.ts
packages/core-api/src/handlers/votes/methods.ts
packages/core-api/src/handlers/wallets/methods.ts

Add missing dependencies to the 2.5 branch.

chore(deps): add missing @hapi/boom and @hapi/joi dependencies

---

packages/core-snapshots/README.md

misc(core-snapshots): fix the link to the documentation

---

deprecated/core-snapshots-cli/src/commands/restore.ts
deprecated/core-snapshots-cli/src/commands/verify.ts
packages/core-snapshots/src/utils.ts
packages/core/src/commands/snapshot/restore.ts
packages/core/src/commands/snapshot/verify.ts

The log message would say "file ...directoryname...", reword it so that
it does not mention whether it is a file or directory.
Also fix typo: s/corelates/correlates/

misc: reword log message and fix typo

---

packages/core-container/src/registrars/plugin.ts
packages/core-utils/src/transform-plugins.ts
packages/core-wallet-api/src/defaults.ts
packages/core-wallet-api/src/plugin.ts
packages/core-wallet-api/src/server/index.ts
packages/core-webhooks/src/index.ts

Exposes a new env variable for changing the wallet api port: `CORE_WALLET_API_PORT`.

refactor(core-wallet-api): allow custom wallet api port
