packages/core-api/lib/versions/1/handlers/delegates.js
To return the total forged amount, `forgedFees` and `forgedRewards` need to be added, but were concatenated instead (Wooh, JavaScript). This PR ensures that the values are being added (as intended) by converting them to `Number` first.
Resolves #654 
=> Ensure that values are added and not concatenated

packages/core-tester-cli/__tests__/utils/generate-wallets.test.js
related to #701 
fix expected values to make tests green, unsure whether the intended port for baseURLApi is really 4102 instead of mine (4300)
this pr is only for generateWallet until confirmed the port should be either of the above.
- [ x ] Test (adding missing tests or fixing existing tests)
- [ x ] I have read the [CONTRIBUTING](https://docs.ark.io/docs/contributing) documentation
- [ x ] Lint and unit tests pass locally with my changes
=> Fix/jest/tester cli wallet+base ur lapi

packages/core-api/lib/versions/1/transformers/delegate.js
Changes the "votes" property that is currently returned by the delegates API to "vote" (and also from Number to String) to be in line with the v1 api
=> imp: change delegate "votes" property to "vote" as in v1

packages/core-p2p/lib/monitor.js
Nothing big, just some refactoring.
* Reduce amount of iterations by marrying some iterators
* Make consistent use of `getPeers()`/`getPeer(ip)`
* Fix typo
* Use oldschool for-loop construct  in `getPBFTForgingStatus()` to iterate peers only once.
It is a bit faster (measured avg of 1000 runs with ~90 peers in ms) compared to before:
```
Before: 0.07180065929889679
After : 0.060611721277236935
```
I also noticed that `delete this.peers[random]` is called if `!randomPeer`, which is only true if `!this.peers.hasOwnProperty(random)`, but then the delete is not necessary in the first place. Thus I removed it.
Attached with a debugger and checked that the behavior before and after is the same.
=> monitor: some refactor, fix typo

packages/core-container/__tests__/__stubs__/plugins.js, packages/core-container/__tests__/registrars/plugin.test.js, packages/core-container/lib/registrars/plugin.js
These tests were failing because the plugin registrar was trying to find them on the wrong path:
`.../core/__tests__/__stubs__/plugin-a.js`
while the real path was:
`.../core/packages/core-container/__tests__/__stubs__/plugin-a.js`
This was provoked by the configuration of the `plugins.js` file, which was using the root of the package (`core-container`) as the base path for its plugins. So, when the tests were executed from that path (`core-container`) they were successful, but when the tests were run on other path, like the real root path of the project, those files weren't found.
The solution of this PR, is requiring the plugins using the path relative to the configuration file (`plugins.json`), which seems that it was the original intention. Is that right, @faustbrian?
=> Fix core-container tests

docker/development/docker-compose.yml
The aim of this PR is provide an easy way to run `core` without installing and configuring PostgreSQL and Redis.
=> Add a docker-compose configuration for development

jest.config.js, packages/core-webhooks/__tests__/__support__/setup.js, packages/core-webhooks/__tests__/api/handler.test.js, packages/core-webhooks/lib/database/index.js, packages/core-webhooks/lib/index.js
Apart from fixing a problem that provokes that `core-webhooks` can't run due to database already initialised, this PR changes the Jest environment to Node.js, which means faster tests and avoids problems with `jsdom`.
It also means that we should have a different configuration for other tests, like the `client` package that should be tested on browser too. But that's a different and future task.
=> Fix `core-webhooks` tests

packages/core-p2p/lib/monitor.js
When both allowedToForge and syncedPeers are 0 the division returns NaN which looks a bit weird in the log. Return 0 instead of NaN.
Before:
`[2018-07-10 19:11:28][INFO]    : Network PBFT status: NaN`
After:
`[2018-07-10 19:13:17][INFO]    : Network PBFT status: 0`
=> Fix getPBFTForgingStatus returning NaN

packages/core-database-sequelize/__tests__/connection.test.js
~~The test `should find all transactions that holds all the conditions (AND)`  didn't pass, because the genesis transaction is of type 0.~~
The test `should update the delegate` didn't pass, because calling `updateDelegateStats`  when `blocksInCurrentRound` is not set has no effect. Calling `applyRound` ensures that `blocksInCurrentRound` is set and the last failing test passes.
=> Fix remaining core-database-sequelize tests

jest.config.js, packages/core-container/__tests__/container.test.js
Travis CI is failing when running the test with the message:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```
=> Remove from Travis CI the tests that produce the no output problem

packages/core-p2p/lib/monitor.js
acceptNewPeer was accepting only its own IP, this fixes it by accepting peers others than 'myself'.
This was tested on community-run v2 devnet. I'm not sure how to add this kind of test to be run on testnet (need 2 peers + ark_env test is changing behaviour).
=> Fix : acceptNewPeer condition to accept peers others than 'myself'

packages/core-p2p/lib/manager.js
On p2p initialization, we were starting monitor before p2p api.
Problem is, when starting monitor we query remote nodes /peer endpoint, so remote node will try to add us as a peer querying our own /peer endpoint (ping to check we are alive).
But as our p2p api isn't started yet, we are unresponsive and therefore added to suspendedPeers list on remote (we are suspended for 1 hour).
Solution is simple, just start p2p api before monitor.
This was tested on community-run v2 devnet, I'm not sure how to add this kind of test to be run on testnet (need 2 peers + ark_env test is changing behaviour).
=> Fix: Start p2p api before starting monitor to be able to be pinged by external peers

packages/core-transaction-pool/lib/guard.js
I found two little bugs in the `TransactionGuard` while looking over https://github.com/ArkEcosystem/core/pull/785 but they are not directly related to that PR since they are already on master.
The first seems to be a copy paste mistake and the second a typo.
=> fix: errors in transaction guard

jest.config.js, packages/core-api/__tests__/__support__/setup.js, packages/core-api/__tests__/v1/handlers/accounts.test.js, packages/core-api/__tests__/v1/handlers/blocks.test.js, packages/core-api/__tests__/v1/handlers/delegates.test.js, packages/core-api/__tests__/v1/handlers/loader.test.js, packages/core-api/__tests__/v1/handlers/peers.test.js, packages/core-api/__tests__/v1/handlers/signatures.test.js, packages/core-api/__tests__/v1/handlers/transactions.test.js, packages/core-api/__tests__/v2/handlers/blocks.test.js, packages/core-api/__tests__/v2/handlers/delegates.test.js, packages/core-api/__tests__/v2/handlers/node.test.js, packages/core-api/__tests__/v2/handlers/peers.test.js, packages/core-api/__tests__/v2/handlers/statistics.test.js, packages/core-api/__tests__/v2/handlers/transactions.test.js, packages/core-api/__tests__/v2/handlers/votes.test.js, packages/core-api/__tests__/v2/handlers/wallets.test.js, packages/core-blockchain/__tests__/blockchain.test.js, packages/core-database-sequelize/__tests__/connection.test.js, packages/core-database-sequelize/__tests__/repositories/blocks.test.js, packages/core-database-sequelize/__tests__/repositories/transactions.test.js, packages/core-database-sequelize/__tests__/spv.test.js, packages/core-database/__tests__/repositories/delegates.test.js, packages/core-database/__tests__/repositories/wallets.test.js, packages/core-database/__tests__/wallet-manager.test.js, packages/core-p2p/__tests__/peer.test.js, packages/core-p2p/__tests__/server/1.test.js, packages/core-p2p/__tests__/server/internal.test.js
My original plan was to simply fix the tests  `should search transactions that includes all of them (AND)` and `should find all transactions that holds all the conditions (AND)` of  `core-database-sequelize`, but it turned out to be a fundamental issue.
They both use the genesis transaction's recipientId to find a type-3 transaction. When the genesis block is created and serialized, the transactions are serialized with a **devnet** network version. Now when a transaction is deserialized a wrong recipientId is calculated and since all addresses in the genesis block start with `A`, it fails to find anything.
It is the default config. The creation of the genesis block happens **before** any test has the chance to run `app.setUp()`. This means all tests right now (except those using a devnet …
=> Fix: Delay creation of Genesis Block in unit tests to after setup

packages/core-database-sequelize/README.md, packages/core-database-sequelize/lib/defaults.js, packages/core-json-rpc/lib/defaults.js, packages/core-transaction-pool-redis/lib/defaults.js, packages/core-webhooks/README.md, packages/core-webhooks/lib/defaults.js, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
`expression || true` always evaluates to `true`.
`expression || false` always evaluates to `expression`.
So, while it makes perfect sense to have something like
`process.env.ARK_JSON_RPC_PORT || 8080`, constructs like
`process.env.ARK_TRANSACTION_POOL_ENABLED || true` mean that it is not
possible to disable (the transaction pool).
`process.env.ARK_DB_LOGGING || false` is just clutter and is the same as
`process.env.ARK_DB_LOGGING`.
After this change it is possible to disable
ARK_API_ENABLED
ARK_GRAPHQL_ENABLED
ARK_TRANSACTION_POOL_ENABLED
ARK_WEBHOOKS_ENABLED
by not setting the relevant variable in the environment (or setting it
to an empty string).
This is a behavioral change - users that did not had e.g.
ARK_TRANSACTION_POOL_ENABLED set in the environment before this change
would have …
=> Fix handling of "boolean" environment variables

.github/PULL_REQUEST_TEMPLATE.md
Fixing an invalid link to the docs.
=> fix: wrong docs link

packages/core-deployer/bin/deployer, packages/core-p2p/lib/monitor.js, packages/core-p2p/lib/server/plugins/throttle/bucket.js, packages/core-p2p/lib/server/plugins/throttle/index.js, packages/core-p2p/package.json, packages/core/lib/config/devnet/peers.json, packages/core/lib/config/mainnet/peers.json, packages/core/lib/config/testnet.1/peers.json, packages/core/lib/config/testnet.2/peers.json, packages/core/lib/config/testnet.live/peers.json, packages/core/lib/config/testnet/peers.json
Allows to set version constraints for peers by using https://github.com/npm/node-semver. This makes it easy to exclude certain peers, for example all v1 nodes while allowing v2 nodes to join. Whitelisted IPs will go around the version constraints and still be accepted.
=> feat: minimum peer version

packages/core-transaction-pool-redis/__tests__/connection.test.js
Add a missing test for removeTransactionById()
=> Add a missing test for removeTransactionById()

package.json
Add support for running the core tests under Windows.  The current issue is that the script syntax assumes a *nix enviroment variable format and does not work with Windows.
Fixes: #822
=> Add cross-env to support Windows

packages/client/README.md, packages/client/build/webpack.config.js
To keep it consistent with other API clients.
=> Rename the global `ArkClient` variable to `ArkEcosystemClient`

packages/client/README.md, packages/client/__tests__/http.test.js, packages/client/__tests__/matchers/http/headers.js, packages/client/build/webpack.config.js, packages/client/lib/http.js, packages/client/package.json
The  `crypto` dependency is almost useless currently but it increase the size of the browser bundle a lot.
=> Remove the usage of the `core/crypto` package on `core/client`

package.json, packages/client/package.json, packages/crypto/package.json
Added support for building crypto and client on Windows.  Explicit calls to "rm" have been replaced with the rimraf package to provide a platform agnostic way to delete a directory.
Fixes: #841
=> chore: Add Windows support for building crypto and client

packages/core-api/lib/versions/1/handlers/peers.js, packages/core-api/lib/versions/2/handlers/peers.js, packages/core-p2p/lib/server/versions/1/handlers.js
It's currently fairly useless to sort peers randomly. Due to the pagination used, peers are randomly sorted and then cropped at the page limit. This could result in getting the X amount of bad peers, and never a peer with a low latency, because every page request (e.g. page 2 of the peer list) will result in a new completely random set of peers. 
I understand this is likely to prevent some sort of attack, but I can think of 3 easy ways to get round this and no easy solution for any of them:
1. send necessary headers and access the p2p endpoint `:4002/peer/list` which has the full list
2. spam the public peer endpoint `:4003/api/v2/peers` a few hundred times until i've got a good chunk of the list
3. run my own node and have access to them all in any way i want
I don't see the benefit of …
=> fix: sort peers by latency, not random

packages/core-forger/lib/manager.js
The forger couldn't start because it made use of the database dependency for logging usernames. The forger runs split from the relay so it has no access to the database or wallet manager.
=> fix: remove username logging in forger (no access to wallets)

.travis.yml, package.json
Added a new command `test:force-exit` command that uses `forceExit` instead of `detectOpenHandles` and update the Travis configuration to use it. Both options are exclusive, provoking that some Travis builds weren't working as expected. This should fix that
=> Update Travis to `forceExit` on tests and not conflict with `detectOpenHandles`

packages/core-api/lib/versions/2/handlers/transactions.js
Currently the v2 endpoint only returns IDs of accept, excess or invalid transactions. If a server doesn't have dynamic fees enabled transactions will be broadcasted until someone is found that will forge it but the user would not know that his transaction is getting broadcasted instead of already being accepted straight away.
=> refactor: return broadcast IDs for better feedback

packages/core-forger/lib/client.js, packages/core-forger/lib/manager.js, packages/core-p2p/lib/server/versions/internal/handlers.js, packages/core-p2p/lib/server/versions/internal/index.js
Adds the ability to log usernames in the forger as it usually doesn't have access to that kind of data. Currently the forger only logs public keys which makes testing really tedious unless you want to remember every public key in existence.
=> feat: log usernames in forger (via P2P API)

packages/core-p2p/lib/server/versions/internal/handlers.js
If a request would be send to the P2P API to get usernames before the node is synced it would throw a 500. This handles it by returning a response with a message.
=> fix: blockchain not ready for usernames

packages/core-api/lib/versions/1/handlers/delegates.js
If a delegate cannot be found on the v1 endpoint `/api/v1/delegates/voters`, it throws a 500 error. The changes here mean it now returns `success: true` and an empty array (which matches current mainnet - http://node1.arknet.cloud:4001/api/delegates/voters?publicKey=02de5a05e931d09f752811ea933d07461ff6937253a8a6e9f45a2385c9c0ef45d1)
=> fix: delegate voters endpoint 500 error

packages/core-api/lib/versions/2/handlers/wallets.js
The ID parameter from the path was causing a wrong query to be generated when requesting http://localhost:4003/api/v2/wallets/AbgXLcnUo61JFsnFaAmoXE54wVc5L7Roa5/votes.
=> fix: delete ID query parameter to prevent faulty query for votes

packages/core-p2p/lib/server/index.js, packages/core-p2p/lib/server/plugins/accept-request.js, packages/core-p2p/lib/server/versions/1/index.js, packages/core-p2p/lib/server/versions/config/handlers.js, packages/core-p2p/lib/server/versions/config/index.js, packages/core-p2p/lib/server/versions/config/transformers/plugins.js, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
Resolves https://github.com/ArkEcosystem/core/issues/877, https://github.com/ArkEcosystem/core/issues/884 https://github.com/ArkEcosystem/core/issues/888.
This PR adds a new config endpoint under http://0.0.0.0:4000/config, where 4000 is the P2P port of the corresponding network, meaning it can vary between main, dev and testnet.
It exposes information like versions of core and the network, detailed information about plugins and their state and more.
```
{
"data": {
"version": "2.0.0",
"network": {
"version": 23,
"nethash": "d9acd04bde4234a81addb8482333b4ac906bed7be5a9970ce8ada428bd083192",
"explorer": "http://texplorer.ark.io"
},
"token": {
"name": "TARK",
"symbol": "TѦ"
},
"plugins": {
"@arkecosystem/core-api": {
"enabled": true,
"port": 4003
},
"@arkecosystem/core-webhooks": { …
```
=> feat: P2P Config API

packages/core-forger/lib/client.js, packages/core-forger/package.json
The forger was sending wake-up signals to all relays instead of choosing one which could result in a lot of requests and missing blocks in certain cases. Resolves https://github.com/ArkEcosystem/core/issues/886
=> fix: sending too many requests to relays in forger

packages/core-api/lib/versions/2/transformers/peer.js
Return height of peers when accessing v2 endpoints
=> fix: return peer height on v2 endpoints

packages/crypto/lib/managers/dynamic-fee.js
If i set the feeMultiplier to a negative number, it allows me to accept all transactions. On the basis a feeMultiplier of 0 isn't allowed, I'm making this assumption for negative numbers also.
Edit: see screenshot below
=> fix: prevent feeMultiplier from being negative

packages/core-api/__tests__/__support__/config/network.json, packages/core-config/__tests__/__fixtures__/constants.json, packages/core-config/__tests__/__stubs__/network.json, packages/core-p2p/__tests__/__support__/config/network.json, packages/crypto/lib/networks/ark/devnet.json, packages/crypto/lib/networks/ark/mainnet.json, packages/crypto/lib/networks/ark/testnet.json
Increasing the number of transactions a block can hold.
**DO NOT MERGE THIS YET.**
=> chore: increase transactions per block to 150

packages/core-p2p/lib/server/versions/1/handlers.js
This is to match v1 transactions endpoint. Currently, the `/peer/transactions` endpoint is used in v1 to post transactions. We need that same functionality on core v2, for the same endpoint.
=> feat: enable cors for p2p post transactions endpoint

packages/core-p2p/lib/index.js
This swaps the order in which the p2p server is started. The current order means that the node tries to connect with peers, before its own server is online. This results in other peers trying to ping but the server is offline, resulting in it being suspended.
=> fix: launch p2p server before pinging peers

packages/core-api/lib/versions/2/handlers/peers.js, packages/core-p2p/lib/monitor.js
The suspended peers endpoint didn't work because it was calling non-existent methods
=> fix: bad method call on suspended peers endpoint

packages/core-p2p/__tests__/monitor.test.js, packages/core-p2p/lib/monitor.js
Updated monitor.test.js to match the new logic, removed { ban: 0 } which is now not needed.
Changed logic in monitor.js : getRandomPeer > keys.filter, was too permissive. It returned true on any matching conditions.
Instead, here returning false on any unmatched condition, then returning true.
=> fix: changed logic in getRandomPeer > keys.filter, was too permissive

packages/core-api/lib/versions/2/transformers/peer.js, packages/core-p2p/lib/peer.js
The peer list has inconsistent JSON - all endpoints; `/peer/list`, `/api/peers` and `/api/v2/peers`. This causes issues for SDKs (e.g. C++) that require strict type mappings, but it's impossible if a value can be both a string or an integer.
=> fix: cast port number in peer list to number

packages/core-database-sequelize/lib/connection.js
Return an empty object to match the type of `walletsByAddress`.
=> Return empty object instead of array

packages/crypto/__tests__/crypto/slots.test.js, packages/crypto/lib/crypto/slots.js
Makes it possible to set the height in the slot module of the crypto package. Partially resolves https://github.com/ArkEcosystem/core/issues/748.
=> feat: setting slot height

packages/core-storage/.gitattributes, packages/core-storage/CHANGELOG.md, packages/core-storage/LICENSE, packages/core-storage/README.md, packages/core-storage/__tests__/storage.test.js, packages/core-storage/jest.config.js, packages/core-storage/jsdoc.json, packages/core-storage/lib/index.js, packages/core-storage/lib/storage.js, packages/core-storage/package.json
This PR provides an immutable storage in the form of the new package `core-storage`. This package makes use of https://facebook.github.io/immutable-js/ under the hood so everything that can be done by immutable.js can be done with core-storage.
`core-storage` only is a wrapper around immutable.js in order to make it possible to have a shared instance for in-memory information that all plugins and core itself can access at any time without having to worry about the data in it getting modified without being told to do so.
We could use this storage for peers, wallets, blockchain state, blocks and many more things were we need the certainty that the data stays how it was stored.
The usage is pretty simple, an example would be the wallet manager. Below example demonstrates how we replace POJOs …
=> feat: immutable storage

packages/core-p2p/__tests__/__support__/config/peers.json, packages/core-p2p/__tests__/guard.test.js, packages/core-p2p/lib/guard.js, packages/core-p2p/lib/monitor.js, packages/core-p2p/lib/peer.js
Right now we have a very harsh system for peer suspensions which doesn't care about the reason why a peer was identified as a troublemaker.
In order to make a better assessment about what a peer has done that deemed him as a problem I've implemented the `__determineSuspensionTime` method. This method will perform a few checks on the peer in question and determine a fair ban time for each cause of trouble instead of flat out banning for 5+ hours for everything.
=> feat: criteria based peer suspensions

packages/core-forger/__tests__/client.test.js, packages/core-forger/__tests__/manager.test.js, packages/core-forger/lib/defaults.js, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
This PR will change the `plugins.js` to use the P2P port as default for the forger host.
=> refactor: use p2p port for forger in plugins config

packages/core-container/lib/environment.js
The `~/.ark/.env` doesn't exist on Travis, so it makes sense to not even attempt to load it 
when `ARK_ENV=test` is true. 
This fixes an issue I ran into when running tests (core-forger) locally:
Since the container loaded my `.env` and thus set `ARK_P2P_PORT` to `4002`, which caused `process.env.ARK_P2P_PORT || 4000` from `core/lib/config/testnet/plugins.js` to return the wrong port.
=> Don't load .env in test environment

packages/core-storage/__tests__/creators.test.js, packages/core-storage/__tests__/setters.test.js, packages/core-storage/__tests__/storage.test.js, packages/core-storage/lib/storage.js, packages/core-storage/package.json
_This PR refactors the `core-storage` package to use an immutable map to handle the storage instead of a plain object._
Maps have the same performance, sometimes are even faster, and have built-in methods to modify their state that make dependencies like `lodash` unnecessary. Also added some helper methods to create immutable objects without straight-away adding them to the storage.
=> refactor: use immutable Map instead of object as storage

packages/core-database/lib/interface.js
Fix of saving only modified wallets. Back to old setting. 
Fix
=> fix: revert on wallets save in updatedelegate stats

packages/core-p2p/lib/server/plugins/accept-request.js
Sometimes if you run `pm2 restart all` the forger would be sending requests to the P2P API before the monitor itself was mounted which could result in exceptions in connection to `monitor.guard` not being available. This PR gracefully returns a 503 while the monitor is not ready.
=> fix: P2P API requests before the monitor is ready

packages/core-config/lib/loader.js
Crypto was using the default configuration which is `devnet`. This will set the configuration for the crypto package on launch of core.
=> fix: properly set crypto config on launch

packages/core-p2p/lib/monitor.js
Suspend(peer) method was crashing as the peer sent to the method was not a `Peer` object, but just `peer` received from `accept-request`. Moved the object creation higher and passing `Peer` object to the suspend method.
=> fix: Suspending peer object

packages/core-api/lib/versions/1/handlers/delegates.js, packages/core-api/lib/versions/2/transformers/block.js, packages/core-database-sequelize/__tests__/connection.test.js, packages/core-database-sequelize/__tests__/repositories/transactions.test.js, packages/core-database-sequelize/__tests__/spv.test.js, packages/core-database-sequelize/lib/repositories/transactions.js, packages/core-database-sequelize/lib/spv.js, packages/core-database/__tests__/wallet-manager.test.js, packages/core-database/lib/interface.js, packages/core-database/lib/wallet-manager.js, packages/core-p2p/lib/server/versions/internal/handlers/utils.js, packages/core-transaction-pool/lib/interface.js, packages/core-transaction-pool/lib/pool-wallet-manager.js, packages/core-transaction-pool/lib/utils/validation-helpers.js
Renaming some methods as having the prefix `getWallet` is redundant if the methods are inside the `WalletManager`. Also includes a small refactor for more consistent behaviour of trigger the `wallet:cold:created` event as a method was rendered useless after some renaming and looking at the logic.
=> refactor: improve wallet manager method names

packages/core-webhooks/lib/database/index.js, packages/core-webhooks/lib/manager.js
Updated to correct variables to fix the following error
1|ark-core-relay  | [2018-09-07 13:46:42][ERROR]                      : Webhooks Job 1 failed: Cannot read property 'webhook' of undefined
<!--
=> fix - webhooks

packages/crypto/__tests__/builder/transactions/__shared__/transaction.js, packages/crypto/__tests__/builder/transactions/multi-signature.test.js, packages/crypto/__tests__/builder/transactions/vote.test.js, packages/crypto/__tests__/crypto/crypto.test.js, packages/crypto/__tests__/handlers/transactions/handler.test.js, packages/crypto/__tests__/handlers/transactions/ipfs.test.js, packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.js, packages/crypto/__tests__/handlers/transactions/transfer.test.js, packages/crypto/__tests__/models/wallet.test.js, packages/crypto/lib/crypto/crypto.js
A follow-up to the arkjs removal, where a few regressions slipped in.
This [check](https://github.com/ArkEcosystem/ark-js/blob/master/lib/transactions/crypto.js#L460) somehow didn't made it, so I added it back. Some unit tests were adjusted, since they can't just pass anything to `getAddress` anymore.
A bug in `getBytes` resulted in wrong bytes for type 1 transactions which caused block 9887 on devnet to fail verification.
Lastly, return early in `verifySecondSignature` if no second signature is set.
<!--
=> arkjs removal follow-up fixes

packages/core-database-postgres/lib/repositories/blocks.js
If a node is not yet synced this could result in no results so we need to use `heightRange`.
=> fix: expect many or no results from heightRange

packages/core-api/lib/repositories/blocks.js, packages/core-api/lib/repositories/transactions.js
Enables caching of the block height again so confirmations can be viewed properly.
=> fix: enable block height caching

.travis.yml
Tests are more important then linting or depchecks, there is no point in waiting 10 minutes for tests to run just because of those.
=> chore: run tests first

packages/crypto/lib/models/transaction.js
The following multi signature transaction `c7778b52f808b29d7f8de036a7686e2e4bf8cbeda360ed432a26c089efbeb31b` of block `4756553835950051038` from devnet fails signature verification.
Before this would fail with `Error: couldn't parse DER signature`
```javascript
await this.getBlock('4756553835950051038')
```
The keys in the keysgroup are not prefixed with a '+', but the serializer slices off the first byte nethertheless, messing up everything once it is missing.
=> fix: multisignature keysgroup serialization

jest.config.js, packages/core-graphql/lib/repositories/blocks.js, packages/core-graphql/lib/repositories/index.js, packages/core-graphql/lib/repositories/repository.js, packages/core-graphql/lib/repositories/transactions.js, packages/core-graphql/lib/repositories/utils/filter-query.js, packages/core-graphql/lib/resolvers/queries/block/block.js, packages/core-graphql/lib/resolvers/queries/block/blocks.js, packages/core-graphql/lib/resolvers/queries/transaction/transaction.js, packages/core-graphql/lib/resolvers/queries/transaction/transactions.js, packages/core-graphql/package.json
Fix graphql queries which were not working after postgres migration + re-enable tests.
Added a `repositories` folder where queries are built (copy-pasted from core-api). This might need some rework to keep only what is needed.
=> Fix graphql queries which were not working after postgres migration + re-enable tests

packages/client/__tests__/client.test.js, packages/client/__tests__/http.test.js, packages/client/__tests__/mocks/v2/blocks.js, packages/client/__tests__/mocks/v2/delegates.js, packages/client/__tests__/mocks/v2/multisignatures.js, packages/client/__tests__/mocks/v2/node.js, packages/client/__tests__/mocks/v2/peers.js, packages/client/__tests__/mocks/v2/signatures.js, packages/client/__tests__/mocks/v2/statistics.js, packages/client/__tests__/mocks/v2/transactions.js, packages/client/__tests__/mocks/v2/votes.js, packages/client/__tests__/mocks/v2/wallets.js, packages/client/__tests__/mocks/v2/webhooks.js, packages/client/examples/README.md, packages/client/lib/http.js
https://github.com/p-meier/hapi-api-version checks the `api-version` header and then it rewrites the URL to the versioned version (`/api/blocks` to `/api/v2/blocks`). Since during the `OPTIONS` request, `axios` doesn't include custom headers (such as the necessary `api-version`), those API client requests were always resolved to a V1 endpoint.
When the endpoint was existing on V1 and V2 (like `/api/delegates`) the behaviour was successful, but on V2-only endpoints, this was provoking a problem, because the pre-flight `OPTIONS` request was redirected to an nonexistent endpoint.
This PR removes the usage of the `api-version` header, but adds the version to the API endpoint URL.
Other option is using an [`Accept` header](https://github.com/p-meier/hapi-api-version#accept-header), but it …
=> Fix how the client connects to endpoints depending on the API version

packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
We already rotate logs daily. This also adds a size-based rolling set to 100M
This would partly address the "crazy logging" pointed in issue #1023
=> Add size-based log rolling in addition to daily rotation

packages/core-forger/__tests__/client.test.js, packages/core-forger/lib/client.js
This was broken by https://github.com/ArkEcosystem/core/commit/3474e414714711dc9682529b96780b08cf3109cd which breaks any event emitting in the forger.
=> fix: failed to emit event in forger

packages/core-tester-cli/__tests__/utils/copy-to-clipboard.test.js, packages/core-tester-cli/bin/tester, packages/core-tester-cli/lib/utils/copy-to-clipboard.js
The tester allows to copy transacitons to the clipboard, which can be useful especially if you want the serialized data. Unfortunately the Buffer object is not turned into a hex string before it is copied, which is a bit useless.
Before:
```json
"serialized":{"type":"Buffer","data":[255,1,30,0,232,19,219,2,3,215,223,228,78,119,16,57,51,79,71,18,251,149,173,53,82,84,246,116,200,245,210,134,80,49,153,21,123,123,247,195,87,128,150,152,0,0,0,0,0,6,84,73,68,58,32,48,0,242,5,42,1,0,0,0,15,0,0,0,30,2,29,129,190,6,43,194,100,182,140,88,192,222,2,251,160,147,25,146,120,48,68,2,32,37,122,108,207,148,185,247,92,59,147,60,125,206,12,103,239,76,162,251,24,197,197,142,124,239,143,188,187,108,73,48,113,2,32,96,210,114,207,31,13,188,255,195,130,69,244,202,132,223,206,214,216,129,247,223,254,179,226,170,22 …
```
=> core-tester-cli: improve transaction to clipboard

packages/core-forger/__tests__/client.test.js, packages/core-forger/lib/manager.js, packages/core-p2p/__tests__/monitor.test.js, packages/core-p2p/__tests__/peer.test.js, packages/core-p2p/__tests__/server/1.test.js, packages/core-p2p/__tests__/server/internal.test.js, packages/core-p2p/__tests__/server/peer.test.js, packages/core-p2p/lib/monitor.js, packages/crypto/__tests__/models/transaction.test.js, packages/crypto/lib/models/block.js, packages/crypto/lib/models/transaction.js
When `Block.toRawJson`  started using `Transaction#toBroadcastV1`  the delegate registration stopped working. The latter treats delegate registrations slightly different, in that it creates an object using `this.timestamp` instead of `this.data.timestamp` as is the case for all other tx types. The former timestamp is the modified timestamp by the Block and explains why delegate registrations cannot be verified anymore.
Since the code was [introduced](https://github.com/ArkEcosystem/core/pull/355/files#diff-7db79b34868931dce067b5ca7e46ca9f) in may and that there have been a lot of changes all over the place, it's probably safe to remove it as it doesn't appear to have any side effects besides that delegate registrations work again. In worst case we learn what is was meant to prevent from …
=> fix: delegate registration

packages/crypto/lib/models/block.js
Using the correct value in the verify method. Found it yesterday with @vasild 
Currently the if block was like this
```
// wrong property name made this to constants.undefined which is false always in this case
if (block.payloadLength > constants.maxPayloadLength) {
result.errors.push('Payload length is too high')
}
```
=> Fix: Using correct constant name in block verify

packages/core-blockchain/lib/blockchain.js, packages/core-database-postgres/lib/connection.js, packages/core-database/__tests__/interface.test.js, packages/core-database/lib/interface.js, yarn.lock
Fix: Saving to database only when saveBlockCommit is called. This is related when fastRebuild is active, when we download 10000 of blocks, save them in memory with `saveBlockAsync` and then call saveBlockCommit.
Current implementation was calling insert on every block added to `this.asyncTransaction`.
Increased limit from 10000 to 20000 as postgres and node memory can handle this with ease.
=> Fix: Saving to database only when saveBlockCommit is called

packages/core-api/__tests__/v1/handlers/transactions.test.js, packages/crypto/lib/models/transaction.js
This commit broke the vendorField https://github.com/ArkEcosystem/core/pull/956/files#diff-20020cdc4aa37467285162d1bf6da2e0 
Basically, it was applied in  `Transaction.deserialize` before, which was then extracted into `applyV1Compatibility` . The transaction constructor calls `applyV1Compatibility`, but what is missing is that `Transaction.deserialize` modified the actual tx object, while `applyV1Compatibility` modifies what is later assigned to `tx.data`. 
Now `vendorField` is correctly assigned to the transaction again. Also extended a unit test to make sure it doesn't go unnoticed anymore.
=> fix: missing transaction vendorfield

.travis.yml
Use "standard" travis postgres 9.6, so remove custom postgres 10 steps from travis config (was only useful before for sequelize).
=> chore: travis config use postgres 9.6

packages/core-p2p/lib/server/versions/1/handlers.js
This replaces the thrown error with a response as this is the v1 P2P API and errors are handled as `success: false`. Because this error was unhandled it would get caught as an unhandled exception.
=> fix: return false instead of throwing

packages/core-forger/lib/client.js, packages/core-forger/lib/manager.js
When starting a forger and relay simultaneously, the forger tries to connect to the relay immediately, even though it is not ready causing this:
I added a small delay, so that calling `__chooseHost` during forger startup doesn't flood the poor relay with requests.
=> misc: add retry delay when calling __chooseHost on forger startup

.circleci/config.yml
This is a working CircleCI config to execute core tests with node 9 and 10, along with lint and depcheck (these only on node 10).
From the tests I made CircleCI is way faster than Travis and allows parallelization so that we can have the 4 jobs (tests node 9 / node 10 / lint / depcheck) running at the same time. Total time was around 3 minutes vs around 15 min right now on Travis.
=> chore: circleci config

packages/core-forger/lib/client.js, packages/crypto/lib/utils/bignum.js
Limits the decimals to 0 for any bignumber.js objects.
=> fix: limit decimals to 0

packages/core-api/__tests__/__support__/setup.js, packages/core-api/__tests__/v2/handlers/transactions.test.js, packages/core-p2p/__tests__/server/peer.test.js, packages/core-test-utils/fixtures/testnet/delegates.js, packages/core-transaction-pool-redis/__tests__/guard.test.js
Double spend tests on api, p2p, transaction-pool-redis. (+ minor refactor on core-test-utils)
Please review and tell me if this needs to be improved or have some more complex test case.
=> test: double spend tests on api, p2p, transaction-pool-redis

packages/core-test-utils/__tests__/matchers/transactions/types/timelock-transfer.test.js, packages/core-test-utils/lib/matchers/transactions/types/timelock-transfer.js
The code before this patch used
const { TIMELOCK_TRANSFER } = require('@arkecosystem/crypto').constants
but packages/crypto/lib/constants.js contains:
exports.TRANSACTION_TYPES = Object.freeze({
...
TIMELOCK_TRANSFER: 6,
...
})
So TIMELOCK_TRANSFER ends up being undefined. The test ended up comparing
undefined with undefined instead of 6 with 6.
=> test: fix TIMELOCK_TRANSFER usage

packages/client/__tests__/client.test.js, packages/client/lib/index.js
Fixes an issue when getting peer list response & also adds a timeout of 5 seconds to each request, in case the peer is not responsive.
=> refactor: find peers timeout

packages/client/lib/index.js
Fixes findPeers method when accessing the v2 peer list endpoint (`/api/v2/peers`)
=> fix: client cater for v2 peer list endpoint

packages/core-container/lib/registrars/plugin.js, packages/core-database-postgres/lib/index.js, packages/core-logger-winston/README.md, packages/core-logger-winston/lib/defaults.js, packages/core-logger-winston/lib/index.js, packages/core-test-utils/config/testnet/plugins.js, packages/core-test-utils/package.json, packages/core-transaction-pool-mem/lib/defaults.js, packages/core-transaction-pool-mem/lib/index.js, packages/core-transaction-pool-redis/lib/index.js, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
This adds an `extends` prop for plugins which can be used to extend interfaces like the database and transaction pool packages as it was kind of pointless to register them via configuration without them accepting a configuration.
=> refactor: plugin extensions

packages/core-api/__tests__/v1/handlers/blocks.test.js, packages/core-blockchain/__tests__/blockchain.test.js, packages/core-container/__tests__/container.test.js, packages/core-database/__tests__/wallet-manager.test.js, packages/core-json-rpc/__tests__/accounts.test.js, packages/core-json-rpc/__tests__/transactions.test.js, packages/core-p2p/__tests__/peer.test.js, packages/core-p2p/__tests__/utils/is-myself.test.js, packages/core-p2p/__tests__/utils/is-whitelist.test.js, packages/core-transaction-pool-mem/__tests__/connection.test.js, packages/core-transaction-pool/__tests__/dynamic-fee.test.js, packages/core-transaction-pool/__tests__/guard.test.js, packages/core-transaction-pool/__tests__/interface.test.js, packages/crypto/__tests__/crypto/crypto.test.js, packages/crypto/__tests__/handlers/transactions/delegate-registration.test.js, packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.js, packages/crypto/__tests__/handlers/transactions/handler.test.js, packages/crypto/__tests__/handlers/transactions/ipfs.test.js, packages/crypto/__tests__/handlers/transactions/multi-payment.test.js, packages/crypto/__tests__/handlers/transactions/multi-signature.test.js, packages/crypto/__tests__/handlers/transactions/second-signature.test.js, packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.js, packages/crypto/__tests__/handlers/transactions/transfer.test.js, packages/crypto/__tests__/models/transaction.test.js, packages/crypto/__tests__/models/wallet.test.js, packages/crypto/__tests__/validation/rules/address.test.js, packages/crypto/__tests__/validation/rules/public-key.test.js, packages/crypto/__tests__/validation/rules/username.test.js, packages/crypto/__tests__/validation/validator.test.js
Replace toBeTruthy / Falsy by toBeTrue / False to strictly compare boolean values when appropriate. ( === true , === false)
=> test: replace toBeTruthy / Falsy by toBeTrue / False when appropriate

packages/client/lib/utils/sort-peers.js
'delay' is changed to 'latency' in v2
=> Updated for v2

packages/core-transaction-pool-mem/__tests__/connection.test.js
The fixtures in
packages/core-transaction-pool-mem/__tests__/__fixtures__/ contain
transactions that are set to expire after 5 seconds:
expiration: slots.getTime() + 5
but this is evaluated as soon as jest starts and it takes some time to
set up the test environment which may be more than 5 seconds. If this
happens then the transactions are already expired by the time the
expiration test starts.
To fix this set the expiration from within the test, just before
executing it.
=> test: reduce nondeterminism in the tx expiration test

packages/core-database-postgres/lib/spv.js, packages/crypto/lib/models/wallet.js
Removes the `voted` property on the `Wallet` class as it was used in the same was as `wallet.vote` can be used to check if it has a value and thus indicating the wallet is voting.
*Unless I am missing something this property is redundant.*
=> refactor: remove unused wallet.voted property

packages/core-logger-winston/lib/driver.js
The padding is currently not being calculated correctly in the `printTracker` function:
Fixed:
=> fix: calculate correct logger padding

packages/core-database-postgres/lib/spv.js, packages/core-database/lib/interface.js
Fixes some invalid docs for the `enqueue` methods and explains the `voted` property during SPV.
=> docs: fix wrong database docs and add SPV info

packages/core-database/lib/wallet-manager.js, packages/core-transaction-pool/lib/pool-wallet-manager.js
The transaction audit was not getting logged because of invalid syntax.
=> fix: properly log the transaction audit

packages/core-p2p/lib/server/index.js, packages/core-p2p/lib/server/plugins/accept-request.js, packages/core-p2p/lib/server/versions/remote/handlers/blockchain.js, packages/core-p2p/lib/server/versions/remote/schemas/blockchain.js
Enables the P2P remote API and fixes the authentication via whitelisting to avoid accepting requests to the internal and remote APIs as a new peer.
=> feat(core-p2p): remote API authentication

packages/core-transaction-pool-mem/lib/connection.js, packages/core-transaction-pool-mem/lib/mem-pool-transaction.js, packages/core-transaction-pool-mem/lib/mem.js, packages/core-transaction-pool-mem/lib/storage.js, packages/core-transaction-pool-mem/package.json
Do not convert transaction.expiration to "number of seconds since 1970",
but instead compare the provided number with slots.getTime() as the unit
for both is "number of seconds since genesis block".
As a side effect we do not need the MemPoolTransaction.expireAt member
anymore which used to store the expiration in "number of seconds since
1970".
=> refactor(mempool): simplify transaction expiration

packages/crypto/CHANGELOG.md, packages/crypto/lib/builder/transactions/transaction.js
The default WIF was always set to 170 instead of using the network WIF.
=> fix(crypto): use the network WIF as default

packages/core-database-postgres/lib/connection.js, packages/core-database/lib/interface.js
Now that the calculations are performed in-memory,
we can get rid of the remaining blocking db calls in`applyRound`.
I'm specifically talking about
`await this.saveWallets(false)`
`await this.saveRound(delegates)`
which should be save to be called non-blocking now as we don't rely on them anymore.
Nevermind `getActiveDelegates` which doesn't block anymore during `applyRound` since some commits.
--
Here's a comparison between blocking and non-blocking:
Before:
`saveWallets: 250.177m`
After:
`saveWallets: 29.492ms`
Before:
`saveRound: 82.768ms`
After:
`saveRound: 3.854 ms`
Total before:
`applyRound: 271.226ms`
Total after:
`applyRound: 80.579ms`
=> perf: make db calls during applyRound non-blocking

packages/core-api/lib/versions/2/handlers/blocks.js, packages/core-api/lib/versions/2/schema/blocks.js
The `orderBy` parameter was missing from the blocks endpoint that returns transactions.
=> fix(core-api): add missing orderBy parameter to block transactions

packages/core-transaction-pool-mem/lib/connection.js
If we assert that arr.length == 0, and if that fails, then we would only
see e.g. 5 != 0 in the output. Instead, assert that arr == [], so that
if the array contains some elements we will see those elements in the
assertion failure message.
=> chore(mempool): use an assert with more verbose output

.circleci/config.yml
Looks like sometimes, the test output is too big and CircleCI crops it (providing the full log for download).
With this, we can still see the last 1000 lines of test output which generally are useful because containing the possibly failed tests.
Also, I noticed parallelization of tests was not correctly done for CircleCI node 10 job. This fixes it.
=> chore: circleci show last 1000 lines of test output + update node 10 test

packages/core-blockchain/lib/state-machine.js, packages/core-database-postgres/lib/spv.js, packages/core-p2p/lib/server/index.js, packages/core-p2p/lib/server/plugins/validate-headers.js, packages/core-transaction-pool-mem/__tests__/connection.test.js
Enables the plugin that validates the P2P headers like on v1. Currently you can just hit the P2P API without providing any of those headers.
@supaiku0 when you test it make sure your node can sync from 0 and accept new peers.
=> refactor(core-p2p): enable validate-headers plugin

packages/core-api/lib/repositories/repository.js, packages/core-transaction-pool-mem/__tests__/connection.test.js
@dated reported that an API endpoint returned code 500 when sorting them. The issue was that a wrong column name wasn't handled so it would just blow up instead of gracefully handling the rest of the request.
=> fix(core-api): invalid sorting columns crash

packages/core-p2p/lib/server/plugins/validate-headers.js
This is to allow the p2p `/config` endpoint without the need for the `port`, `nethash` or `version` endpoint. @faustbrian could you confirm if you intentionally wanted the headers for this endpoint, as it's not really used for p2p functionality 🤔 thanks!
=> fix: allow p2p config without headers

packages/core-forger/lib/index.js, packages/core/lib/start-forger.js
Passing the bip38 password by parameter is now deprecated... Instead the forger now reads
the env variables `ARK_FORGER_BIP38` and `ARK_FORGER_PASSWORD`. 
See also https://github.com/ArkEcosystem/core-commander/pull/74
=> feat: read bip38 from env

packages/core-logger-winston/README.md, packages/core-logger-winston/lib/defaults.js, packages/core-test-utils/config/testnet/plugins.js, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
This reverts commit 8f35ab8
Why? It doesn't address the issue, and creates an odd notation where the file extension ".log" is not actually the extension..
=> Revert "chore: use static log file path (#1129)"

packages/core-json-rpc/lib/server/methods/blocks/info.js, packages/core-json-rpc/lib/server/methods/blocks/transactions.js
The latest version of `Joi` has better handling for unsafe integers in javascript but this also means that block IDs got rejected as invalid because of their size.
=> fix(json-rpc): mark block IDs as unsafe integers

packages/core-transaction-pool/lib/guard.js
After recent changes __determineValidTransactions() is not async
anymore.
=> chore: remove async from __determineValidTransactions()

packages/core-api/lib/versions/2/transformers/wallet.js
The wallets API response does currently not include the associated username of an address.
=> fix: add associated username to wallet api response

packages/core-api/package.json, packages/core-blockchain/package.json, packages/core-config/package.json, packages/core-container/package.json, packages/core-database-postgres/package.json, packages/core-database/package.json, packages/core-debugger-cli/package.json, packages/core-deployer/package.json, packages/core-event-emitter/package.json, packages/core-forger/package.json, packages/core-graphql/package.json, packages/core-http-utils/package.json, packages/core-json-rpc/package.json, packages/core-logger-winston/package.json, packages/core-logger/package.json, packages/core-p2p/package.json, packages/core-test-utils/package.json, packages/core-tester-cli/package.json, packages/core-transaction-pool-mem/package.json, packages/core-transaction-pool/package.json, packages/core-utils/package.json, packages/core-webhooks/package.json, packages/core/package.json
Follow up to https://github.com/ArkEcosystem/core/pull/1245 as we use some features for snapshots that are only available from node 10 and afterwards.
=> chore: require node 10 as minimum engine

packages/core-container/lib/container.js, packages/core-logger-winston/lib/defaults.js
Using setTimeout() to "wait" for the log to be flushed is
non-deterministic it may happen that process.exit() is called before the
log is flushed. Also it has another problem that other error messages
are printed because the process continues execution.
Instead log errors and warnings to stderr instead of stdout. For some
reason stderr is properly flushed before the process is terminated by
process.exit() (whereas stdout is not). Also, error messages belong to
stderr anyway.
=> refactor: avoid the non-deterministic setTimeout

packages/core-api/lib/versions/1/transformers/delegate.js, packages/core-api/lib/versions/2/transformers/delegate.js
The delegate `rate` property now always exists after the latest PRs.
=> refactor(core-api): use delegate rank as it is always available

packages/core-api/CHANGELOG.md, packages/core-api/lib/defaults.js, packages/core-api/lib/server.js
Makes it possible to register additional plugins and moves the API versions to additional plugins so they can receive configuration for things like route prefixes.
=> refactor(core-api): allow registration of additional plugins

packages/core-error-tracker-bugsnag/.gitattributes, packages/core-error-tracker-bugsnag/CHANGELOG.md, packages/core-error-tracker-bugsnag/LICENSE, packages/core-error-tracker-bugsnag/README.md, packages/core-error-tracker-bugsnag/jest.config.js, packages/core-error-tracker-bugsnag/jsdoc.json, packages/core-error-tracker-bugsnag/lib/defaults.js, packages/core-error-tracker-bugsnag/lib/index.js, packages/core-error-tracker-bugsnag/package.json, yarn.lock
Adds support for error tracking and monitoring via https://docs.bugsnag.com/platforms/nodejs/other/configuration-options/ so node maintainers can provide better feedback if they decide to use a proper monitoring service for their node.
Other integrations will follow in the next days to provide a variety of services.
=> feat: add core-error-tracker-bugsnag package

packages/core-vote-report/lib/handler.js, packages/core-vote-report/lib/templates/index.html
To get a better picture about vote distribution, only wallets with a balance over 0.1 should be regarded - as is currently done in the explorer. Take delegate dr10 for instance, for which the vote report shows 1151 voters. Out of these wallets 542 have a balance smaller than 0.1
This PR also adds localized formating of the voters count
=> refactor(core-vote-report): only wallets with balance > 0.1

packages/core-transaction-pool-mem/package.json
Without it, if there is more than one test file (__tests__/*.test.js)
then jest would try to start them in parallel, leading to multiple
"Starting P2P Interface" followed by
"Error: listen EADDRINUSE 0.0.0.0:4000"
=> test: add --runInBand jest's argument where it is missing

packages/core-api/lib/server.js, packages/core-http-utils/lib/index.js, packages/core-http-utils/lib/plugins/cors-headers.js
Based on https://github.com/gr2m/hapi-cors-headers which offers better CORS handling to resolve some issues that popped up with the desktop wallet.
=> feat(core-http-utils): add cors-headers plugin

packages/core-tester-cli/lib/commands/command.js, packages/core-tester-cli/lib/commands/delegate-registration.js, packages/core-tester-cli/lib/commands/multi-signature.js, packages/core-tester-cli/lib/commands/second-signature.js, packages/core-tester-cli/lib/commands/transfer.js, packages/core-tester-cli/lib/commands/vote.js
The recent changes to `core-tester-cli` caused the random fee calculation to not work as expected when a fee-range was provided, always returning `0` or `1`. This also changes the log outputs to display the numeric values in ARK instead of ARKtoshis.
=> fix(core-tester-cli): fee parsing & display output in ark

packages/core-api/__tests__/v1/utils.js, packages/core-api/__tests__/v2/utils.js, packages/core-tester-cli/lib/commands/command.js, packages/core-utils/__tests__/delegate-calculator.test.js, packages/core-vote-report/lib/handler.js, packages/crypto/lib/constants.js
Replaces `Math.pow(10, 8)` with `1e8` as it is quicker to type and yields the same result, just a syntax nitpick.
=> refactor: use 1e8 instead of math.pow

packages/core-transaction-pool-mem/__tests__/connection.test.js, packages/core-transaction-pool-mem/lib/mem.js, packages/core-transaction-pool-mem/package.json
In [getTransactionsOrderedByFee()](https://github.com/ArkEcosystem/core/blob/0ab42975b23a479c6168fb5a73ebbbc51932f031/packages/core-transaction-pool-mem/lib/mem.js#L218) `a.transaction.fee` and `b.transaction.fee` are BigNumber objects not numbers and the comparison fails.
=> fix(core-transaction-pool-mem): sort transactions by numerical fee value

packages/core-deployer/bin/deployer, packages/core-test-utils/config/testnet/peers.json, packages/core/lib/config/devnet/peers.json, packages/core/lib/config/mainnet/peers.json, packages/core/lib/config/testnet.1/peers.json, packages/core/lib/config/testnet.2/peers.json, packages/core/lib/config/testnet.live/peers.json, packages/core/lib/config/testnet/peers.json
ark-node has received some important updates so we only want to peer with the latest version.
=> chore: raise minimumVersion to 1.3.3

packages/core-transaction-pool-mem/lib/connection.js, packages/core-transaction-pool/__tests__/interface.test.js, packages/core-transaction-pool/lib/interface.js
#1301 introduces validity checks for transactions in the transaction pool, which currently invalidate second signature and delegate registration transactions. This PR adds methods to check if there are pending transactions of the afore mentioned types already, which can be used in the `switch/case` statement used in #1301.
=> refactor: add additional checks for transactions types

packages/core-test-utils/config/testnet/plugins.js, packages/core-transaction-pool-mem/README.md, packages/core/lib/config/devnet/plugins.js, packages/core/lib/config/mainnet/plugins.js, packages/core/lib/config/testnet.1/plugins.js, packages/core/lib/config/testnet.2/plugins.js, packages/core/lib/config/testnet.live/plugins.js, packages/core/lib/config/testnet/plugins.js
Follow up to https://github.com/ArkEcosystem/core/commit/fa14ee59cedb5ff3b2b8f48cf3584ec881713244
=> chore: adjust transaction pool timeouts in config

packages/core-p2p/lib/court/guard.js
Only checks for fork causing peers if the state is ready.
=> fix(core-p2p): make sure state is ready in guard

.circleci/config.yml
Adds support for node.js 11 as CircleCI now has an image for that. Currently disabled as there are known SQLite build issues on node.js 11.
=> chore: setup node 11 for CircleCI

packages/core-api/lib/versions/2/schema/blocks.js, packages/core-api/lib/versions/2/schema/delegates.js, packages/core-api/lib/versions/2/schema/transactions.js, packages/core-api/lib/versions/2/schema/votes.js
Some API endpoints were missing proper validation of the input values in their schemata, such as block and transaction ids, allowing for requests such as the following to be valid:
https://dexplorer.ark.io:8443/api/v2/blocks/xxx
https://dexplorer.ark.io:8443/api/v2/transactions/aaa
https://dexplorer.ark.io:8443/api/v2/votes/bbb
=> refactor(core-api): add number validation to schemata

packages/core-container/.gitignore, packages/core-container/__tests__/remote-loader.test.js, packages/core-container/lib/container.js, packages/core-container/lib/remote-loader.js, packages/core-container/package.json, packages/core-p2p/lib/server/versions/config/handlers/index.js, packages/core-p2p/lib/server/versions/config/index.js, packages/core/bin/ark, packages/core/lib/config/devnet/delegates.json, packages/core/lib/config/testnet.live/delegates.json, yarn.lock
Resolves https://github.com/ArkEcosystem/core/issues/1002.
`yarn relay --remote ip:p2p-port`
=> feat(core-container): configure via remote peer

packages/core-transaction-pool/lib/guard.js
Invalidates a transaction when an unexpected errors occurs instead of returning a code 500.
=> fix(core-transaction-pool): handle unexpected transaction errors in guard

packages/core-p2p/lib/monitor.js, packages/core/bin/ark, packages/core/lib/start-relay-and-forger.js, packages/core/lib/start-relay.js
Starting nodes with `--network-start` will already skip the peer discovery but it will also skip a bunch of other things in regards to the state-machine. The `--skip-discovery` flag will allow a node to be started in normal mode and skip the initial peer discovery like `--network-start` does without any of the side effects.
=> feat(core-p2p): add ability to skip initial peer discovery

.circleci/config.yml, .circleci/configTemplate.json, .circleci/generateConfig.js, package.json, pre-commit.sh
For CircleCI to cache correctly the node_modules folders, we have to explicitly list every node_modules folder we have.
So when we add / remove a package (to our packages folder), we have to update the CircleCI config, which is not cool.
This PR adds a pre-commit script that will generate the CircleCI config so that we don't have to worry about updating manually config.yml.
So now config.yml is generated on pre-commit, based on configTemplate.json and with the generateConfig.js script.
=> build: CircleCI improve caching - generate yml config on pre-commit

packages/core-forger/lib/index.js, packages/core-forger/lib/manager.js
Prettifies the loaded delegates logs output.
```
[DEBUG]: Loaded dated_test_del (pubkey),multiforger (pubkey) delegates.
[INFO]:  ForgerManager started with 2 forgers
```
```
[DEBUG]: Loaded 2 delegates: dated_test_del (pubkey), multiforger (pubkey)
[INFO]:  Forger Manager started with 2 forgers
```
=> refactor(core-forger): prettify loaded delegate logs

packages/core-api/lib/versions/2/transformers/block.js
If the `totalAmount` is available we can use that prop instead of calculating it.
=> refactor(core-api): use totalAmount of block if available

packages/crypto/lib/models/block.js
The payload length was checked against undefined, which would always result in `false` and allow blocks to be send broadcasted that are bigger than the allowed size. You could for example forge blocks that contain more transaction than the allowed maximum.
=> fix(crypto): properly verify the payload length of blocks

packages/core-api/lib/versions/2/schema/pagination.js
The `Joi.positive()` does not allow zero, which means the most recent value can't be fetched if offset is used.
Resolves #1375
=> fix: pagination allow 0 offset

packages/core-api/lib/server.js, packages/core-api/lib/versions/1/index.js, packages/core-api/lib/versions/2/schema/peers.js, packages/core-api/package.json
Adds the `hapi-trailing-slash` package, so that incoming requests with a trailing slash are redirected to the correct url. This should also eliminate the need for the `v1 inconsistency` routes.
It also adds the `ip` parameter to the peers API endpoint.
=> refactor(core-api): redirect requests with trailing slash

packages/core-container/__tests__/remote-loader.test.js
The `RemoteLoader` tests create a `config` directory, but never remove it. Changed the name to something less generic and make sure it is deleted after all tests are done.
=> test(core-container): cleanup after remote loader test

packages/core-p2p/lib/server/versions/1/handlers.js, packages/core-p2p/lib/server/versions/peer/handlers/blocks.js
One occurrence was missed in #1397, which required a bit of adjustment.
The tests for the block handler would output:
```
127.0.0.1 has downloaded 1 block from height 0
127.0.0.1 has downloaded 1 block from height undefined
```
After:
```
127.0.0.1 has downloaded 1 block from height 1
127.0.0.1 has downloaded 1 block from height 1
```
Also, shouldn't the following two `if`s be the same? They behave differently when passed height 0.
https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/versions/1/handlers.js#L377
https://github.com/ArkEcosystem/core/blob/develop/packages/core-p2p/lib/server/versions/peer/handlers/blocks.js#L32
=> refactor(core-p2p): peer blocks request handling

packages/core-snapshots/lib/manager.js
In theory, as DB is not needed to export the metafile to disk, closing DB connection earlier could free the connection for other processes.
=> refactor: close database connection earlier

packages/core-api/lib/defaults.js, packages/core-p2p/lib/defaults.js
Changes the p2p rate limiting to allow 20 requests per second. Will have to see if that results in more stable rate limiting rather then using a minute based approach.
=> chore(core-p2p): adjust rate limit values

.gitignore, packages/core-p2p/lib/index.js, packages/core-p2p/lib/monitor.js
Dumps the list of registered peers into the peers.json file on shutdown so we don't have to 100% rely on seeds when a node starts up the next time.
=> feat(core-p2p): dump the peer list on shutdown

packages/core-p2p/lib/defaults.js, packages/core-p2p/lib/monitor.js
Don't broadcast to all peers, but a fixed number of random peers instead. Defaults `20`.
Should improve #1444 .
=> refactor(core-p2p): limit number of peers during broadcast

packages/core-database/lib/wallet-manager.js, packages/core-test-utils/lib/generators/transactions/transaction.js
This log statement passes `data` as the second argument:
```javascript
logger.warn(
'Transaction forcibly applied because it has been added as an exception:',
data,
)
```
Funnily the `data` object in this case has a `timestamp` property which is interpreted by winston and sets the timestamp. 
Resulting in:
`[1970-01-01 14:00:04][WARN] : Transaction forcibly applied because it has been added as an exception:`
Example to reproduce:
```javascript
logger.info(`Bla`, { timestamp: 12000000 })
```
`[1970-01-01 04:20:00][INFO]    : Bla`
Fixed by properly interpolating the log string.
=> fix(core-database): wrong log statements

.circleci/config.yml, .circleci/configTemplate.json
The `*-browsers` docker images come with `yarn` preinstalled already, and the way CircleCI is configured it does not use the yarn version installed in the `Install yarn` step.
=> chore: remove yarn install step

packages/core-tester-cli/__tests__/commands/command.test.js, packages/core-transaction-pool/lib/utils/dynamicfee-matcher.js, packages/crypto/lib/utils/format-arktoshi.js
The original change was proposed in #1427, which stood in conflict with some pending changes at the time. This PR makes the transaction logs a bit more verbose and adds formatting of the arktoshi values.
e.g.
```
Transaction TXID eligible to enter pool (fee=10000000 >= min=280)
```
becomes
```
Transaction TXID eligible to enter pool - fee of 0.1 Ѧ is greater than minimum fee (0.0000028 Ѧ)
```
It also removes the loop from the `arktoshiToArk` function.
=> refactor(core-transaction-pool): transaction fee logs

packages/core-transaction-pool-mem/lib/mem.js
We do not need to keep the list of transactions ordered by expiration
all the time, after every new transaction is added. We only need to
sort it whenever we are about to read that list - when fetching
transactions by expiration.
=> perf: lazily sort transactions by expiration when adding them

packages/core-container/__tests__/registrars/plugin.test.js, packages/core-container/lib/registrars/plugin.js
If we set defaults via env (i.e `ARK_TRANSACTION_POOL_MAX_PER_REQUEST`) it gets interpreted as a string.
So this is not a number anymore:
```javascript
maxTransactionsPerRequest:
process.env.ARK_TRANSACTION_POOL_MAX_PER_REQUEST || 40,
```
This has a lot of potential side effects, the precursor being Joi blowing up:
```javascript
exports.store = {
payload: {
transactions: Joi.arkTransactions()
.min(1)
.max(
container.resolveOptions('transactionPool').maxTransactionsPerRequest,
)
.options({ stripUnknown: true }),
},
}
AssertionError [ERR_ASSERTION]: limit must be a positive integer or reference
```
=> fix(core-container): cast env options to number

packages/core-transaction-pool-mem/lib/connection.js
Before we check whether a transaction exists in the pool we remove
expired ones to avoid false positive - pretending that an expired
transaction exists in the pool.
However, if a transaction is not in the pool there is no need to purge
in order provide a definite answer.
=> perf: don't always purge expired txs when checking for existence

packages/core-blockchain/lib/blockchain.js, packages/core-p2p/lib/monitor.js
Outputs the median block height in localized form and shortens the `nextState.actions` portion of the state machine logs.
e.g.
```
event 'PROCESSFINISHED': "newBlock" -> "idle" -> actions: [{"type":"checkLater"},{"type":"blockchainReady"}]
```
becomes
```
event 'PROCESSFINISHED': "newBlock" -> "idle" -> actions: [checkLater, blockchainReady]
```
=> refactor(core-blockchain): median block height and action logs

packages/core-transaction-pool/__tests__/guard.test.js, packages/core-transaction-pool/lib/guard.js
Don't remove a transaction from broadcast when it was rejected due to `ERR_POOL_FULL` and include the broadcast ids when looking up forged transactions.
Also added some missing tests.
=> fix(core-transaction-pool): keep tx broadcast when pool is full

packages/core-api/lib/utils/generate-cache-key.js, packages/core-api/lib/versions/1/handlers/accounts.js, packages/core-api/lib/versions/1/handlers/blocks.js, packages/core-api/lib/versions/1/handlers/delegates.js, packages/core-api/lib/versions/1/handlers/transactions.js, packages/core-api/lib/versions/1/index.js, packages/core-api/lib/versions/1/methods/accounts.js, packages/core-api/lib/versions/1/methods/blocks.js, packages/core-api/lib/versions/1/methods/delegates.js, packages/core-api/lib/versions/1/methods/transactions.js, packages/core-api/lib/versions/1/utils.js, packages/core-api/lib/versions/2/handlers/blocks.js, packages/core-api/lib/versions/2/handlers/delegates.js, packages/core-api/lib/versions/2/handlers/transactions.js, packages/core-api/lib/versions/2/handlers/votes.js, packages/core-api/lib/versions/2/handlers/wallets.js, packages/core-api/lib/versions/2/index.js, packages/core-api/lib/versions/2/methods/blocks.js, packages/core-api/lib/versions/2/methods/delegates.js, packages/core-api/lib/versions/2/methods/transactions.js, packages/core-api/lib/versions/2/methods/votes.js, packages/core-api/lib/versions/2/methods/wallets.js, packages/core-api/lib/versions/2/utils.js, packages/core-api/package.json
Quickly implemented server methods to provide caching for blocks and transactions. Function wise everything is still the same but methods are now called through server methods and cached rather then directly in the server handler.
=> refactor(core-api): implement server methods

packages/core-api/lib/versions/1/utils.js, packages/core-api/lib/versions/2/utils.js
Cached `Boom` errors were not properly returned which resulted in a 500 because errors can't be wrapped again.
=> fix(core-api): properly return boom errors if cached

packages/core-test-utils/fixtures/testnet/delegates.js, packages/core-transaction-pool/__tests__/guard.test.js, packages/core-transaction-pool/__tests__/pool-wallet-manager.test.js
Tests for "chained transfers" : for example A => B => C with B and C being cold wallets.
Default behavior now is B => C cannot happen if B didn't received first a transaction, forged in a block (so can't do A => B => C within the same block).
=> test: pool wallet "chained transfers" tests

packages/core-snapshots-cli/bin/snapshot
`const app` was being declared twice, preventing the snapshot script to run. This fixed the issue and I was able to create, rollback and restore snapshots again.
=> fix(core-snapshots-cli) fix app being declared twice

packages/core-p2p/lib/monitor.js
When a node is launched with network start option, it should not discover peers.
Fix updateNetworkStatusIfNotEnoughPeers which was calling updateNetworkStatus without possible networkStart option, therefore making a node with network start option try to discover peers anyway.
=> fix: call updateNetworkStatus with possible networkStart option

packages/core-p2p/lib/monitor.js
The discovery logs were shown even if the discovery was skipped.
=> fix(core-p2p): do not show discovery logs when discovery is skipped

packages/core-api/__tests__/v2/handlers/transactions.test.js, packages/core-database-postgres/lib/migrations/20181129400000-add-block_id-index-to-transactions-table.sql, packages/core-database-postgres/lib/migrations/index.js
Adds a missing index on the block_id column to the transactions table.
=> fix(core-database-postgres): add missing block_id index to transactions table

packages/core-database-postgres/lib/models/block.js, packages/core-database-postgres/lib/models/round.js, packages/core-database-postgres/lib/models/transaction.js, packages/core-database-postgres/lib/models/wallet.js
The wallets rebuild is triggered too often, even though it shouldn't (i.e. clean shutdown). So the reason is that at startup there's a minor difference in balances:
```
dbWallet.balance: "12394029028487604"
inMemoryWallet.balance: "12394029028487605"
```
The issue is we cast the bignumber to a number on insert, which causes an overflow:
```
12394029028487605 > Number.MAX_SAFE_INTEGER
true
Number("12394029028487605")
12394029028487604
```
Fixed by casting to string instead of number. With that change I can't reproduce it anymore.
=> fix(core-database): cast bignumber to string on insert

packages/core-container/lib/container.js
`git rev-parse --short HEAD` returns different revision lengths:
> Discovered 15 peers on commit `d0ec1f6`.
Discovered 18 peers on commit `d0ec1f6c`.
> --short[=length]
Same as --verify but shortens the object name to a unique prefix with at least length characters. The minimum length is 4, the default is the effective value of the `core.abbrev` configuration variable (see git-config[1]).
> `core.abbrev`
Set the length object names are abbreviated to. If unspecified or set to "auto", an appropriate value is computed based on the approximate number of packed objects in your repository, which hopefully is enough for abbreviated object names to stay unique for some time. The minimum length is 4.
So I've changed the command to:
`git rev-parse --short=8 HEAD`
=> fix(core-container): fixed hashid length

packages/core-blockchain/__tests__/blockchain.test.js
transaction pool's flush() method is not async, no need to call it with
await.
=> chore: remove unnecessary await

packages/core-api/CHANGELOG.md, packages/core-api/lib/versions/2/handlers/peers.js
Return the correct total count for `/api/v2/peers`
=> fix(core-api): return the correct total count for /api/v2/peers

packages/core-transaction-pool/lib/interface.js
Passing `transaction` to `wallet.canApply` is wrong, as the timestamp is modified by the Block constructor to match its own timestamp.  We need to pass `transaction.data` as we only have here the unmodified timestamp  which was used to calculate the signature(s).
Second signature transactions no longer cause a double spend error.
=> fix(core-transaction-pool): pass correct transaction data

packages/core-api/CHANGELOG.md, packages/core-api/lib/repositories/blocks.js
Allows to display blocks via `http://localhost:4003/api/v2/blocks/14367` based on a height to remove the need to know the block ID.
=> feat(core-api): allow block display via height in v2 API

packages/core-database-postgres/lib/migrations/20181204100000-blocks-generator_public_key-index.sql, packages/core-database-postgres/lib/migrations/index.js
The "blocks_unique" on (height, generator_public_key) is redundant
because we already have an index on (height) alone.
Also, we do queries like:
SELECT count(*) FROM blocks WHERE generator_public_key = '...'; [1]
and thus we need an index on (generator_public_key), add that missing
one.
The removal of the redundant index does not change timings:
selects that return small count: ~500ms
selects that return big count: ~500ms
The addition of an index on (generator_public_key) changes it to:
selects that return small count: ~50ms
selects that return big count: ~500ms
=> perf(core-database-postgres): drop redundant and add missing index on blocks

packages/core-api/__tests__/v2/handlers/transactions.test.js, packages/core-database-postgres/lib/migrations/20181204300000-transactions-sender-and-receiver-indexes.sql, packages/core-database-postgres/lib/migrations/index.js
Add indexes on transactions's sender_public_key and recipient_id
columns.
Impact on queries:
SELECT count(*) AS count FROM transactions WHERE
sender_public_key = '... many matches ...' OR
recipient_id = '... many matches ...';
~230ms -> 230ms (no change)
SELECT count(*) AS count FROM transactions WHERE
sender_public_key = '... many matches ...' OR
recipient_id = '... few matches ...';
~230ms -> 90ms
SELECT count(*) AS count FROM transactions WHERE
sender_public_key = '... few matches ...' OR
recipient_id = '... many matches ...';
~230ms -> 70ms
SELECT count(*) AS count FROM transactions WHERE
sender_public_key = '... few matches ...' OR
recipient_id = '... few matches ...';
~230ms -> 50ms
=> perf(core-database-postgres): add sender&receiver indexes

packages/core-api/lib/versions/1/handlers/blocks.js, packages/core-utils/__tests__/supply-calculator.test.js, packages/core-utils/lib/index.js, packages/core-utils/lib/supply-calculator.js, packages/core-vote-report/lib/handler.js
The supply calculation assumed the milestone would never change, which is not the case.
This PR adds a new helper to calculate the correct supply at the given height
by taking all the milestones up to the height into account.
=> fix: supply calculation

.circleci/config.yml, packages/core-api/CHANGELOG.md, packages/core-api/lib/versions/1/methods/blocks.js, packages/core-api/lib/versions/1/methods/transactions.js, packages/core-api/lib/versions/2/methods/blocks.js, packages/core-api/lib/versions/2/methods/delegates.js, packages/core-api/lib/versions/2/methods/transactions.js, packages/core-api/lib/versions/2/methods/votes.js, packages/core-api/lib/versions/2/methods/wallets.js
Increasing the timeouts for block and transaction cache generation as it can take a long time on potatos that a lot of people run which results in a 503 status code.
=> chore(core-api): increase cache generation timeout for block and transaction endpoints

packages/core-api/CHANGELOG.md, packages/core-api/lib/versions/1/methods/accounts.js, packages/core-api/lib/versions/1/methods/blocks.js, packages/core-api/lib/versions/1/methods/delegates.js, packages/core-api/lib/versions/1/methods/transactions.js, packages/core-api/lib/versions/2/methods/blocks.js, packages/core-api/lib/versions/2/methods/delegates.js, packages/core-api/lib/versions/2/methods/transactions.js, packages/core-api/lib/versions/2/methods/votes.js, packages/core-api/lib/versions/2/methods/wallets.js, packages/core-api/lib/versions/utils.js, packages/core-api/package.json
Ensures that booleans and numbers are properly handled for the `generateTimeout` config.
=> fix(core-api): ensure booleans for the cache timeout are handled

.circleci/config.yml, packages/core-json-rpc/CHANGELOG.md, packages/core-json-rpc/__tests__/wallets.test.js, packages/core-json-rpc/lib/server/methods/blocks/latest.js, packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js, packages/core-json-rpc/lib/server/methods/wallets/bip38/show.js, packages/core-json-rpc/lib/server/utils/bip38-keys.js, packages/core-json-rpc/lib/server/utils/decrypt-wif.js
Resolves https://github.com/ArkEcosystem/core/issues/1644 and also changes how BIP38 wallets are accessed.
- [x Lint and unit tests pass locally with my changes
=> fix(core-json-rpc): return the encoded WIF for BIP38 wallets instead of the encrypted WIF

.circleci/config.yml, packages/core-api/CHANGELOG.md, packages/core-api/lib/repositories/blocks.js, packages/core-api/package.json, packages/core/CHANGELOG.md, packages/core/package.json, yarn.lock
We store heights as integers in postgresql which can cause issues when block IDs are tried as heights as the max allowed size is 2147483647.
=> fix(core-api): ensure safe integer range for block height lookups

packages/core-http-utils/lib/plugins/whitelist.js, packages/core-http-utils/package.json, packages/core-p2p/CHANGELOG.md, packages/core-p2p/lib/server/plugins/accept-request.js, packages/core-p2p/lib/server/versions/1/handlers.js, packages/core-p2p/lib/server/versions/internal/handlers/blocks.js, packages/core-p2p/lib/utils/is-myself.js, packages/core-p2p/package.json, packages/core/CHANGELOG.md, packages/core/lib/config/mainnet/peers.json, packages/core/package.json, yarn.lock
Improves the behaviour of how remote addresses are checked and filtered.
=> refactor: improve remote address checks

packages/core-p2p/src/court/guard.ts
Same issue as further down the file where we logged 5 milliseconds instead of minutes.
=> fix(core-p2p): get difference in milliseconds

packages/core-p2p/__tests__/court/guard.test.ts, packages/core-p2p/src/court/offences.ts
Adjusts some ban durations to make network recovery more stable and take proper advantage of the repeat offender ban.
=> refactor(core-p2p): adjust some ban durations

packages/core-api/__tests__/v2/handlers/delegates.test.ts, packages/core-database/__tests__/repositories/delegates.test.ts, packages/core-database/src/repositories/delegates.ts
Ordering on the delegates API does not seem to work. This PR adjusts the delegates `findAll` method so that is consistent with the respective method for wallets.
=> fix(core-database): delegate ordering

.circleci/config.yml, packages/core-blockchain/src/state-machine.ts, packages/core-p2p/package.json, packages/core-p2p/src/monitor.ts
The whole logic around how the `updateNetworkStatusIfNotEnoughPeers` method is called is rather odd so it is replaced with a period check instead.
=> refactor(core-p2p): replace the network update timeout with a period check

packages/crypto/__tests__/handlers/transactions/delegate-registration.test.ts, packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.ts, packages/crypto/__tests__/handlers/transactions/handler.test.ts, packages/crypto/__tests__/handlers/transactions/ipfs.test.ts, packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts, packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts, packages/crypto/__tests__/handlers/transactions/second-signature.test.ts, packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.ts, packages/crypto/__tests__/handlers/transactions/vote.test.ts, packages/crypto/src/handlers/transactions/handler.ts, packages/crypto/src/handlers/transactions/multi-payment.ts, packages/crypto/src/handlers/transactions/multi-signature.ts
Increases coverage by adding tests for lines reported by codecov.
=> test(crypto): increase handler coverage

packages/core-blockchain/src/state-machine.ts, packages/core-container/src/config/index.ts, packages/core-p2p/__tests__/court/guard.test.ts, packages/core-p2p/src/court/guard.ts, packages/core-p2p/src/court/index.ts, packages/core-p2p/src/court/offences.ts, packages/core-p2p/src/monitor.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/server/plugins/set-headers.ts
Reject peers with a different milestone hash.
=> feat(core-p2p): milestone hash

packages/core-p2p/__tests__/court/guard.test.ts, packages/core-p2p/src/court/guard.ts
Instead of throwing a TypeError return false if the version is invalid.
=> fix: check semver validity

packages/core-database/__tests__/repositories/delegates.test.ts, packages/core-database/src/repositories/delegates.ts
Searching delegates without parameters return the delegate with username "undefined" when it should not return anything.
=> fix(core-database): ensure that delegate search deals with "undefined" as username

packages/core-api/src/versions/1/shared/transformers/ports.ts, packages/core-api/src/versions/2/shared/transformers/ports.ts
https://dexplorer.ark.io:8443/api/v2/node/configuration
The p2p port isn't casted to a numerical type.
=> fix(core-api): cast core-p2p port to number

packages/core-logger-winston/__tests__/logger.test.ts, packages/core-logger-winston/package.json, packages/core-logger-winston/src/driver.ts, packages/core-logger-winston/src/index.ts, packages/core-logger-winston/src/plugin.ts, packages/core-logger/src/logger.ts
Further addresses #1795. While we're exporting the `Logger` type defined in this module. The rest of the modules will only depend on `core-logger` module for its `AbstractLogger` type. This ensures that, even though we're introducing a `core-logger` dependency to all modules that need to log(so as to benefit from type-safety), we still retain the ability to supplant the `core-logger-winston` implementation with a different implementation as long as that implementation extends from `core-logger`'s `AbstractLogger` 
i.e. Override the winston logger with a logstash json encoded logger or RDMS logger or even a network streaming logger. As long as all these extend from the `AbstractLogger` in `core-logger` module, they still benefit from the type-safety but don't restrict the rest of the …
=> chore: export core-logger-winston types.

packages/core-api/__tests__/v2/handlers/delegates.test.ts, packages/core-database/src/repositories/delegates.ts
Allows for ordering of the delegates by `approval` and `productivity` which is needed for ArkEcosystem/desktop-wallet#763.
=> feat(core-database): delegate ordering by 'productivity' & 'approval'

packages/core-database-postgres/src/queries/spv/last-forged-blocks.sql, packages/core-database-postgres/src/spv.ts
Instead of fetching only the last 51 blocks during the SPV this PR fetches the last block of all delegates, fixing https://github.com/ArkEcosystem/core/issues/1847.
=> fix(core-database-postgres): set last block of all delegates during SPV

packages/core-transaction-pool/src/guard.ts
Resolves a comment from https://github.com/ArkEcosystem/core/issues/1937
=> refactor(core-transaction-pool): use distinct error codes for different fee problems

packages/core-transaction-pool/src/guard.ts
All a client needs to know is wether it's transaction got accepted (either accepted and/or broadcasted by a node). In which case there's no need to return an error unless neither is the case.
Resolves #1937
=> fix(core-transaction-pool): only return error when min fee is too low for broadcast and accept

packages/crypto/__tests__/handlers/transactions/handler.test.ts
In crypto transaction handlers, we have one abstract handler which is extended for transfer, vote, etc handlers.
We have basic tests for this abstract handler, but these tests should also be done on each sub-handler. This was the 1st change for this PR.
Also added to these basic tests a "insufficient balance in wallet" test.
=> test(crypto): update handler tests to apply basic tests to all handlers

packages/core-api/__tests__/v1/handlers/accounts.test.ts, packages/core-api/src/repositories/transactions.ts, packages/core-database/src/wallet-manager.ts, packages/core-transaction-pool/src/pool-wallet-manager.ts
- When querying for /accounts?address, return error if account.publicKey === null (cold wallet)
- Add test to check for bug
Ref: #1949
I will test if the bug is also present on v2 today, I would like to get a review on whether this makes sense. All tests were done incrementally, initially the response (without account.publicKey === null) check was that of an empty cold wallet; now it simply returns an error "Account not found" (as wanted).
=> fix(core-api): prevent cold wallet response

packages/core-jest-matchers/__tests__/api/block.test.ts, packages/core-jest-matchers/__tests__/api/peer.test.ts, packages/core-jest-matchers/__tests__/api/response.test.ts, packages/core-jest-matchers/__tests__/api/transaction.test.ts, packages/core-jest-matchers/__tests__/fields/address.test.ts, packages/core-jest-matchers/__tests__/fields/public-key.test.ts, packages/core-jest-matchers/__tests__/models/delegate.test.ts, packages/core-jest-matchers/__tests__/models/transaction.test.ts, packages/core-jest-matchers/__tests__/models/wallet.test.ts, packages/core-jest-matchers/__tests__/transactions/types/delegate-resignation.test.ts, packages/core-jest-matchers/__tests__/transactions/types/delegate.test.ts, packages/core-jest-matchers/__tests__/transactions/types/ipfs.test.ts, packages/core-jest-matchers/__tests__/transactions/types/multi-payment.test.ts, packages/core-jest-matchers/__tests__/transactions/types/multi-signature.test.ts, packages/core-jest-matchers/__tests__/transactions/types/second-signature.test.ts, packages/core-jest-matchers/__tests__/transactions/types/timelock-transfer.test.ts, packages/core-jest-matchers/__tests__/transactions/types/transfer.test.ts, packages/core-jest-matchers/__tests__/transactions/types/vote.test.ts, packages/core-jest-matchers/__tests__/transactions/valid-second-signature.test.ts, packages/core-jest-matchers/__tests__/transactions/valid.test.ts
#1967
I've added tests following the existing implementations for the api/ source files.
I've also added or changed existing tests to also check that upon failure the message is as defined in the source files.
=> test(core-jest-matchers): increase coverage

packages/crypto/__tests__/builder/builder.test.ts, packages/crypto/__tests__/builder/transaction-builder-factory.test.ts, packages/crypto/__tests__/builder/transactions/__shared__/transaction-builder.ts, packages/crypto/__tests__/builder/transactions/delegate-registration.test.ts, packages/crypto/__tests__/builder/transactions/delegate-resignation.test.ts, packages/crypto/__tests__/builder/transactions/ipfs.test.ts, packages/crypto/__tests__/builder/transactions/multi-payment.test.ts, packages/crypto/__tests__/builder/transactions/multi-signature.test.ts, packages/crypto/__tests__/builder/transactions/second-signature.test.ts, packages/crypto/__tests__/builder/transactions/timelock-transfer.test.ts, packages/crypto/__tests__/builder/transactions/transfer.test.ts, packages/crypto/__tests__/builder/transactions/vote.test.ts, packages/crypto/__tests__/client.test.ts, packages/crypto/src/builder/index.ts, packages/crypto/src/builder/transactions/transaction.ts
Remove the hacky usage of global in builder tests, use a lambda function to implemented the needed functionality
Renamed TransactionBuilderDirector to TransactionBuilderFactory to more accurately describe what it is and what it's responsibilities are.
Added some coverage to said factory methods.
=> refactor: remove hacky use of 'global' in transaction builder tests

packages/core-blockchain/__tests__/processor/block-processor.test.ts
Added block-processor tests, checking blocks are correctly handled depending on the situation : chained / unchained blocks, invalid forging delegate, and last downloaded / last block status when rejecting blocks.
=> test: adding block-processor tests

packages/core-debugger-cli/__tests__/commands/identity.test.ts, packages/crypto/__tests__/builder/transactions/multi-payment.test.ts
There was one missing scenario for core-debugger-cli; where `identity({})` (blank options) wasn't tested and resulted in missing coverage.
Add needed test with this PR.
Also, added a file which was linted when committing.
=> test(core-debugger-cli): increase coverage

packages/core-api/__tests__/__support__/setup.ts, packages/core-api/package.json, packages/core-blockchain/__tests__/__support__/setup.ts, packages/core-blockchain/__tests__/processor/block-processor.test.ts, packages/core-database-postgres/__tests__/__support__/setup.ts, packages/core-database-postgres/__tests__/connection.test.ts, packages/core-database/__tests__/wallet-manager.test.ts, packages/core-graphql/__tests__/__support__/setup.ts, packages/core-json-rpc/__tests__/__support__/setup.ts, packages/core-p2p/__tests__/__support__/setup.ts, packages/core-p2p/__tests__/court/guard.test.ts, packages/core-p2p/__tests__/monitor.test.ts, packages/core-p2p/__tests__/peer.test.ts, packages/core-test-utils/package.json, packages/core-test-utils/src/helpers/container.ts, packages/core-transaction-pool/__tests__/__support__/setup.ts, packages/core-transaction-pool/__tests__/connection.test.ts, packages/core-transaction-pool/__tests__/dynamic-fee.test.ts, packages/core-transaction-pool/__tests__/guard.test.ts, packages/core-transaction-pool/__tests__/pool-wallet-manager.test.ts
Fixes the current coverage issue.
We had the issue because when testing some packages, we let core-container register all the needed plugins, including the one that we are currently testing.
By doing this, the container would simply call each package from its `dist` folder and register it (which is normal).
But as for testing we use `ts-jest` which transpiles on-the-fly our package, what `ts-jest` transpiled was not called and therefore we didn't have coverage.
See issue #1977 for the full discussion.
=> test: fix coverage by registering current package plugin manually

packages/core-transaction-pool/src/defaults.ts
=> fix(core-transaction-pool): increase max transaction age to 6 hours

packages/core-logger-winston/src/defaults.ts, packages/core-logger-winston/src/formatter.ts, packages/core-logger-winston/src/index.ts, packages/core-logger-winston/src/plugin.ts
Adds the `makeReadable` flag which enables extra spacing by default but can be set to false to remove that.
=> refactor(core-logger-winston): add flag to disable extra spacing for readability

.gitignore, packages/core-logger-winston/package.json, packages/core-logger-winston/src/driver.ts, packages/core-logger/src/logger.ts
An improved version of https://github.com/ArkEcosystem/core/pull/2010 to handle the issue everywhere on the logger level.
=> refactor(core-logger-winston): do not log empty values and stringify non-string values

packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/utils/tick-sync-tracker.ts, packages/core-database-postgres/src/spv.ts, packages/core-interfaces/src/core-logger/logger.ts, packages/core-logger-winston/__tests__/logger.test.ts, packages/core-logger-winston/src/defaults.ts, packages/core-logger-winston/src/driver.ts, packages/core-logger-winston/src/formatter.ts, packages/core-logger/__tests__/__stubs__/logger.ts, packages/core-logger/src/logger.ts, packages/core-p2p/src/monitor.ts
Reduce the log noise and remove the atrocious progress bars that make the log unreadable during start up.
=> refactor: remove progress tracker and further reduce log noise

packages/core-blockchain/__tests__/processor/block-processor.test.ts, packages/core-blockchain/src/processor/handlers/unchained-handler.ts
Timestamp check from #2042 plus unit test.
=> fix(core-blockchain): invalid timestamp check

packages/core-p2p/src/court/guard.ts
```
|ark-core-relay  | Debug: internal, implementation, error
1|ark-core-relay  |     Error: Could not resolve 'state'.
1|ark-core-relay  | Resolution path: state
1|ark-core-relay  |     at method (/home/ark/core/packages/core-p2p/src/server/plugins/accept-request.ts:46:33)
1|ark-core-relay  |     at process._tickCallback (internal/process/next_tick.js:68:7)
1|ark-core-relay  | [2019-01-31 19:17:18][DEBUG]: Rejected peer 5.135.22.95 as it doesn't meet the minimum version requirements. Expected: >=2.1.0 - Received: 2.0.19
1|ark-core-relay  | Debug: internal, implementation, error
1|ark-core-relay  |     Error: Could not resolve 'state'.
1|ark-core-relay  | Resolution path: state
1|ark-core-relay  |     at method (/home/ark/core/packages/core-p2p/src/server/plugins/accept-request.ts:46:33) …
```
=> fix(core-p2p): check if state is available

packages/core-p2p/src/utils/restore-peers.ts
If the `~/.cache/ark-core/devnet/peers.json` file is malformed the `JSON.parse` will fail as only Joi errors are currently handled.
=> fix(core-p2p): return an empty array if the peers cache parsing fails

.gitignore, install.sh, scripts/docker/templates/development/purge.sh, scripts/docker/templates/mainnet/docker-compose.yml, scripts/docker/templates/unitnet/docker-compose.yml, scripts/docker/templates/unitnet/purge.sh
Renamed `development` to `unitnet` to make it clear that it is meant to run the test suite together with the `unitnet` network.
=> chore(docker): rename development to unitnet

docker/production/devnet/enc.sh, docker/production/mainnet/enc.sh
Changed script to interactively ask for forging secret and password instead of asking the user to put them manually in advance.
=> chore(docker): changed forging secret and password handling

packages/core-transaction-pool/__tests__/guard.test.ts, packages/core-transaction-pool/src/connection.ts, packages/core-transaction-pool/src/guard.ts, packages/core-transaction-pool/src/mem.ts
Only allow a single instance of a delegate registration in the pool per address.
=> fix(core-transaction-pool): disallow multiple registrations for same delegate

packages/core-api/src/versions/1/blocks/controller.ts
The v1 API was not using the supply calculator which caused a different result then the v2 API.
=> fix(core-api): use the supply calculator in the v1 API

packages/core-blockchain/src/blockchain.ts, packages/core-forger/src/manager.ts, packages/core-p2p/src/network-state.ts, packages/crypto/__tests__/crypto/slots.test.ts, packages/crypto/src/crypto/slots.ts
This PR resolves two different issues related to quorum.
1) Do not discard incoming blocks when syncing with network. See:
```
019-02-11 23:56:08][DEBUG]: Sending wake-up check to relay node http://127.0.0.1:4000
[2019-02-11 23:56:08][DEBUG]: Blockchain sync check WAKEUP requested by forger 🛏
[2019-02-11 23:56:08][DEBUG]: event 'WAKEUP': "idle" -> {"syncWithNetwork":"syncing"} -> actions: [checkLastDownloadedBlockSynced]
[2019-02-11 23:56:08][DEBUG]: Queued blocks (rebuild: 0 process: 0)
[2019-02-11 23:56:08][DEBUG]: event 'SYNCED': {"syncWithNetwork":"syncing"} -> {"syncWithNetwork":"downloadFinished"} -> actions: [downloadFinished]
[2019-02-11 23:56:08][INFO]: Block 130,749 pinged blockchain 19 times
[2019-02-11 23:56:08][INFO]: Received new block at height 130,750 with 0 transactions …
```
=> fix: quorum issues

packages/core-api/src/plugins/validation/formats/hex.ts
Buffer.from(value, "hex") will only throw an exception if value is not a
string, according to
https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_string_encoding
Indeed Buffer.from('foo', 'hex') does not throw. The schema has defined
`type: "string"`, which means that, in all cases when the validate
method is called, it will return true.
Use a proper validation using regular expression and a length check.
=> fix(core-api): Proper hex validation

packages/core-p2p/__tests__/court/guard.test.ts, packages/core-p2p/src/court/guard.ts, packages/core-p2p/src/defaults.ts, packages/core-p2p/src/monitor.ts, packages/core-test-utils/src/config/testnet/plugins.js, packages/core-test-utils/src/config/unitnet/plugins.js
Allow multiple minimum versions to allow testing of alpha/beta/rc releases alongside stable ones.
=> refactor(core-p2p): allow multiple minimum versions for alpha/beta/rc releases

packages/core-api/__tests__/v2/handlers/delegates.test.ts, packages/core-database/src/repositories/wallets.ts
Adds support for ordering to the `delegates/{id}/voters` endpoint and returns the voters ordered  by `balance:desc` by default.
=> feat(core-api): add sorting to voters endpoint

packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/processor/handlers/unchained-handler.ts, packages/core-blockchain/src/utils/validate-generator.ts
=> fix(core-blockchain): stuck at not ready to accept new block

packages/core/package.json, packages/core/src/commands/command.ts, packages/core/src/commands/config/cli.ts, packages/core/src/commands/config/publish.ts, packages/core/src/helpers/config.ts, packages/core/src/helpers/update.ts, packages/core/src/hooks/init/config.ts, packages/core/src/hooks/init/update.ts
- Adds support for npm channels to allow switching from alpha to beta, beta to rc and so on.
- Adds support for CLI configuration to allow other configuration values like setting a token.
=> feat(core): configuration and channel support for the CLI

packages/core/src/helpers/config.ts
Tries to read the file and if it fails removes it, creates it and writes the defaults to it. The new check ensures that non-existent and corrupted files are covered.
=> refactor(core): more robust check for ensureDefaults

packages/core-p2p/src/monitor.ts
Previously we would fetch the list of peers from a single other peer and
be satisfied with it as long as our list of peers satisfies
hasMinimumPeers().
With this change we will query at least 4 peers and combine their
lists. This will help in getting a better view of the network and all of
its peers in times of splits and bad network connectivity.
=> feat(core-p2p): Fetch list of peers from at least a few others

.circleci/config.yml, packages/core/src/commands/config/cli.ts, packages/core/src/commands/update.ts, packages/core/src/helpers/prompts.ts, packages/core/src/helpers/update.ts, packages/core/src/hooks/init/update.ts
The `init` hook for updates now only gives a notification if an update is available together with a link to the changelog instead of also performing the update.
_Until 2.2 is on mainnet we won't have a changelog for the non-stable releases so the link will be not of interest until then._
=> refactor(core): require the user to take action for updates

packages/core/src/commands/command.ts, packages/core/src/commands/config/cli.ts, packages/core/src/commands/update.ts, packages/core/src/helpers/prompts.ts, packages/core/src/helpers/update.ts
Ask the user if they want to restart their existing processes.
=> feat(core): ask for process restarts after updating

packages/core/src/commands/config/reset.ts
Remove the force flag and instead reset when the `--network` flag is provided.
=> fix(core): reset configuration if --network is passed

.circleci/config.yml, .circleci/generateConfig.js
Update circleci config to generate coverage for each package and each test type (unit / integration) in a different folder.
This fixes recent coverage issue as all coverage was generated in the same directory, each test step was overriding previous test step coverage.
=> chore: update circleci config to fix coverage

packages/core/src/commands/command.ts, packages/core/src/process-manager.ts, packages/core/src/shared/start.ts
Exit the start command if a process is already running, restart should be used instead for those cases.
Follow up to https://github.com/ArkEcosystem/core/pull/2178
=> refactor(core): exit start commands if the process is already running

packages/core/src/commands/forger/start.ts
`forger:run` would enter the interactive mode via `forger:start` as the required flags for non-interactive mode were missing.
=> fix(core): pass the bip38 and password flags to the forger:run command

packages/core/src/commands/reinstall.ts
Allow to reinstall the currently installed version in case something breaks.
**Fiddled this together on mobile, will test and finish it on monday.**
=> feat(core): add support for reinstalling the current version

packages/core/src/commands/snapshot/restore.ts
The `snapshot:restore` was not deciding what network to use if the `--network` flag was missing.
=> fix(core): parse the network for the snapshot restore command

__tests__/integration/core-api/v2/handlers/delegates.test.ts, __tests__/unit/core-database/repositories/delegates-business-repository.test.ts, packages/core-api/src/versions/2/delegates/controller.ts, packages/core-api/src/versions/2/delegates/methods.ts, packages/core-api/src/versions/2/delegates/routes.ts, packages/core-api/src/versions/2/delegates/schema.ts, packages/core-database/src/repositories/delegates-business-repository.ts, packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts, packages/core-p2p/src/peer-verifier.ts
Adds an additional endpoint to the delegates API to retrieve the active delegates at a certain height (use case: display rank changes in the explorer).
The `getActiveAtHeight` method was not being used anywhere, hence it took the liberty to modify it to the needs of this PR.
=> feat(core-api): add active delegates endpoint

packages/core-blockchain/__tests__/blockchain.test.ts, packages/core-database/__tests__/wallet-manager.test.ts, packages/core-database/src/wallet-manager.ts
Fixes the vote balance update after reverting a vote transaction. The transaction fee was incorrectly applied which lead to small discrepancies over time (number of reverts x fee).
=> fix: vote balance update

__tests__/integration/core-transaction-pool/guard.test.ts, __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts, __tests__/unit/core-transaction-pool/connection.test.ts, __tests__/unit/core-transaction-pool/guard.test.ts, __tests__/unit/core-transactions/handler.test.ts, packages/core-database/src/database-service.ts, packages/core-database/src/wallet-manager.ts, packages/core-interfaces/src/core-transaction-pool/transaction-guard.ts, packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts, packages/core-transaction-pool/src/guard.ts, packages/core-transaction-pool/src/mem.ts, packages/core-transaction-pool/src/pool-wallet-manager.ts, packages/core-transactions/package.json, packages/core-transactions/src/errors.ts, packages/core-transactions/src/interfaces.ts, packages/core-transactions/src/service-registry.ts, packages/core-transactions/src/services/delegate-registration.ts, packages/core-transactions/src/services/delegate-resignation.ts, packages/core-transactions/src/services/ipfs.ts, packages/core-transactions/src/services/multi-payment.ts, packages/core-transactions/src/services/multi-signature.ts, packages/core-transactions/src/services/second-signature.ts, packages/core-transactions/src/services/timelock-transfer.ts, packages/core-transactions/src/services/transaction.ts, packages/core-transactions/src/services/transfer.ts, packages/core-transactions/src/services/vote.ts, packages/core-transactions/src/utils.ts, packages/crypto/src/transactions/types/transaction.ts
Moves all tx type specific logic into `core-transactions`. Still WIP.
=> refactor: move transaction type specific logic into core-transactions

__tests__/integration/core-blockchain/blockchain.test.ts, __tests__/unit/core-database/wallet-manager.test.ts, packages/core-api/src/versions/2/delegates/methods.ts, packages/core-database/src/wallet-manager.ts, packages/core-utils/src/index.ts
Ports #2207 from `2.2` to `develop`.
=> fix: vote balance update (develop)

packages/core-blockchain/src/state-storage.ts, packages/core-transaction-pool/__tests__/connection.test.ts, packages/core-transaction-pool/src/connection.ts
After a rollback, the transaction pool could end up with transactions where the block timestamp is used, therefore failing verification and resulting in invalid blocks:
_This does not apply to `develop`, because of the much stricter separation of the transaction data introduced with AIP29._
```
|ark-relay  | [2019-03-08 08:15:32][INFO]: Received new block at height 1,714,194 with 5 transactions from 127.0.0.1
8|ark-relay  | [2019-03-08 08:15:32][WARN]: Block 1,714,194 (2420495039909631961) disregarded because verification failed 📜
8|ark-relay  | [2019-03-08 08:15:32][WARN]: {
8|ark-relay  |     "verified": false,
8|ark-relay  |     "errors": [
8|ark-relay  |         "One or more transactions are not verified:",
8|ark-relay  |         "=> …
```
=> fix(core-transaction-pool): invalid transactions after rollback

packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/state-machine.ts
It is not guaranteed that we still have use for the downloaded blocks by the time `downloadBlocks` finishes. It could happen that the processQueue ends up with blocks that are no longer relevant, because a rollback happened in the meantime.
=> fix(core-blockchain): return if last downloaded block changed

packages/core-p2p/src/peer.ts
```
[INFO]: Fetching a fresh peer list from http://185.170.115.40:4002
[ERROR]: Got unexpected reply from http://185.170.115.40:4002/peer/list: child "peers" fails because ["peers" at position 1 fails because [child "ip" fails because ["ip" must be a valid ip address with a forbidden CIDR]]] - ip: 2130706433
```
vs
```
[INFO]: Fetching a fresh peer list from http://185.170.115.40:4002
[ERROR]: Got unexpected reply from http://185.170.115.40:4002/peer/list: 
{"success":true,"peers":[{"ip":"2130706435","port":4002,"nethash":"2a44f340d76ffc3df204c5f38cd355b7496c9065a1ade2ef92071436bd72e867","milestoneHash":"3b7ee0793e2ddf23","version":"2.1.0","os":"linux","status":200,
"height":1571996,"delay":3,"hashid":"fb0491af"},{"ip":"2130706433","port":4002,"nethash":"2a44f340d76ffc3df204c5f38cd355b7496 …
```
=> refactor(core-p2p): dont dump the reply when /peer/list validation fails

packages/core-blockchain/src/state-machine.ts, packages/core-transaction-pool/src/connection.ts
Fixes a regression introduced by #2216.
```
ark-core  | [2019-03-10 05:19:57][DEBUG]: Delegate arkx (03bbfb43ecb5a54a1e227bb37b5812b5321213838d376e2b455b6af78442621dec) allowed to forge block 1,735,171 👍
0|ark-core  | [2019-03-10 05:19:57][DEBUG]: Delegate genesis_31 (027b320c5429334ecf846122492d12b898a756bf1347aa61f7bf1dcd706315a9fb) allowed to forge block 1,735,172 👍
0|ark-core  | [2019-03-10 05:19:57][DEBUG]: Delegate genesis_2 (0259d9ca7922c277b0e7407a88703bbb98f5da43a335b0eefa6c4642f072acfe79) allowed to forge block 1,735,173 👍
0|ark-core  | [2019-03-10 05:19:57][INFO]: Starting Round 34,024 🕊️
0|ark-core  | [2019-03-10 05:19:57][DEBUG]: Updating delegate statistics
0|ark-core  | [2019-03-10 05:19:57][DEBUG]: Delegate lol (03b383f3cb3c74d77ce0384412d996f9b617013758b38983f8ffa4115cc952 …
```
=> fix(core-blockchain): node stuck during sync 

packages/core/package.json, packages/core/src/commands/command.ts, packages/core/src/commands/config/cli.ts, packages/core/src/commands/reinstall.ts, packages/core/src/commands/update.ts
Adds the option to pass flags to the update command to specify the restart behaviour without prompting for user input:
- `--restart`: restarts all (running) processes
- `--no-restart`: no process will be restarted
- `--restart-core`: restarts the core process
- `--restart-relay`: restarts the relay process
- `--restart-forger`: restarts the forger process
=> feat(core): add restart flags to update command

.circleci/config.yml, .circleci/configTemplate.json, .circleci/generateConfig.js
CircleCI builds were becoming slow, around 6-7min.
- Fixed caching : we were not using caching anymore because when doing `yarn setup` we'd basically remove all we had cached.
- Re-organized circleci jobs : 1 job for all unit tests, and 2 jobs for integration tests.
Now jobs are faster : 3-4min.
=> chore: circleci restore caching + re-organize jobs for unit / integration tests

packages/core-tester-cli/src/http-client.ts
Before this patch we would just get the following error, leaving one to
wonder what went wrong:
[1552298227459] ERROR (core-tester-cli/40747 on smle): Cannot destructure property `data` of 'undefined' or 'null'.
After this patch:
[1552299329734] ERROR (core-tester-cli/3408 on smle): http://localhost:4003/api/v2/node/configuration: connect ECONNREFUSED 127.0.0.1:4003
[1552299329735] ERROR (core-tester-cli/3408 on smle): Cannot destructure property `data` of 'undefined' or 'null'.
=> fix(core-tester-cli): Don't hide errors from HTTP failures

__tests__/integration/core-api/v2/handlers/peers.test.ts, packages/core-api/package.json, packages/core-api/src/versions/2/peers/controller.ts
=> fix(core-api): properly sort semver versions

__tests__/unit/core-forger/manager.test.ts, packages/core-forger/src/manager.ts, packages/core-p2p/src/network-state.ts
Always use the height as reported by the network state and simplify quorum calculation.
=> refactor(core-forger): always use latest available height

packages/crypto/src/transactions/serializers/transaction.ts
Don't touch the vendor field padding of the legacy serialization format. Unbreaks devnet for nodes on `develop` now that the vendorfield length milestone has been reached.
=> fix(crypto): keep old vendor field padding

.github/PULL_REQUEST_TEMPLATE.md
Update the GitHub PR template to be less noisy and add an extra `breaking change` section.
=> docs: less noise in the GitHub PR template

packages/core/bin/config/testnet/plugins.js
chore(core): Disable webhooks on testnet
Webhooks are disabled on devnet and mainnet by default. Do the same with
testnet for consistency and because webhooks are broken and prevent
testnet from functioning:
$ yarn --cwd packages/core full:testnet
...
(node:44847) UnhandledPromiseRejectionWarning: TypeError: webhooks is not iterable
at WebhookManager.getMatchingWebhooks (core/packages/core-webhooks/dist/manager.js:47:31)
Disable broken component
=> chore(core): Disable webhooks on testnet

deprecated/core-graphql/package.json, deprecated/core-logger-winston/package.json, deprecated/core-snapshots-cli/package.json, package.json, packages/core-api/package.json, packages/core-blockchain/package.json, packages/core-container/package.json, packages/core-database-postgres/package.json, packages/core-database/package.json, packages/core-elasticsearch/package.json, packages/core-error-tracker-bugsnag/package.json, packages/core-error-tracker-sentry/package.json, packages/core-event-emitter/package.json, packages/core-forger/package.json, packages/core-http-utils/package.json, packages/core-interfaces/package.json, packages/core-jest-matchers/package.json, packages/core-json-rpc/package.json, packages/core-logger-pino/package.json, packages/core-logger/package.json, packages/core-p2p/package.json, packages/core-tester-cli/package.json, packages/core-transaction-pool/package.json, packages/core-utils/package.json, packages/core-vote-report/package.json, packages/core-webhooks/package.json, packages/core/package.json, scripts/publish/alpha.sh, yarn.lock
The `typedoc` dependency was not used.
=> chore: remove unused typedoc dependency

__tests__/utils/helpers/container.ts
"~" is expanded by the shell, if we use it in JavaScript it will end up
creating directories like "./packages/core-p2p/~/.core/"
Use HOME from the environment instead. If it is not set, then trying
"/.core/..." is fine.
=> fix(tests): Reference the home directory via HOME, not ~

deprecated/core-snapshots-cli/package.json, package.json, packages/core-logger-pino/package.json, packages/core-tester-cli/package.json, packages/core-transactions/package.json, scripts/publish/next.sh
Adds a `next` channel so people don't need to switch channels on devnet between alpha/beta/rc.
=> chore: add publish script for the next channel

__tests__/unit/core-utils/nsect.test.ts, packages/core-utils/src/nsect.ts
If the search range is narrowed too much then the condition
"if (low + this.nAry >= high) {" would catch it and return. But it could
happen that we still have neighboring elements and that condition is not
true.
Check whether the probe declared that the highest match is at some
height and if we have probed the next height - the fact that the next
height was not declared a match, implicitly means that it is not a
match. And if we have two neighboring heights, the lower one a match and
the higher one not, then we don't need to search further and have the
final result.
=> fix(core-utils): handle NSect edge case

__tests__/unit/core-logger-pino/logger.test.ts, packages/core-logger-pino/src/defaults.ts, packages/core-logger-pino/src/driver.ts
Allow different log levels for the console and files.
=> feat(core-logger-pino): set different log levels for console and file

packages/core-p2p/src/peer.ts
The http client needs all options instead of just the headers which were passed in wrongly.
=> fix(core-p2p): pass all opts to the http client instead of just headers

packages/crypto/src/networks/devnet/milestones.json
Height 1895000 at Mon Mar 25 16:56:22 CET 2019
=> misc(crypto): Update devnet blockid milestone

__tests__/integration/core-api/v2/handlers/peers.test.ts, packages/core-p2p/src/defaults.ts, packages/core-utils/package.json, packages/crypto/package.json, yarn.lock
Raise the minimum version to `>=2.3.0` for `mainnet` and `>=2.3.0-next.0` for `devnet`.
=> chore(core-p2p): raise the minimum version to 2.3.0

packages/core-database-postgres/src/migrations/20190313000000-add-asset-column-to-transactions-table.sql
Support PG9.5 for asset column migration
=> fix(core-database-postgres): support PG9.5 for asset column migration

__tests__/unit/core-database/repositories/transactions-business-repository.test.ts, packages/core-database/src/repositories/transactions-business-repository.ts
Default sorting by timestamps was missing for transactions.
=> fix(core-database): sort transactions by timestamp:desc by default

packages/core-snapshots/package.json, packages/core-snapshots/src/db/index.ts, packages/core-snapshots/src/plugin.ts, packages/core/src/helpers/snapshot.ts
`core-snapshots` implemented migrations itself which corrupted the database. Now instead
always load the `core-database-postgres` plugin which already performs the migrations and properly checks wether they were already applied or not.
=> fix(core-snapshots): always load core-database-postgres

packages/core-snapshots/src/manager.ts, packages/core/src/commands/snapshot/rollback.ts
Allows to run `ark snapshot:rollback --number=51` instead of `ark snapshot:rollback --height=123456789` to perform a rollback.
=> feat(core-snapshots): rollback by a given amount of blocks

__tests__/integration/core-api/v2/handlers/blocks.test.ts, packages/core-api/src/versions/2/blocks/schema.ts
The blocks/show endpoint does currently not accept block ids of the new sha256 format. There are no fixtures for blocks with the new id format i believe?
=> fix(core-api): adjust schema validation of blocks show

packages/core-database-postgres/src/models/block.ts
The block model does currently not allow the `equals` operator, passing a blockheight to the `blocks/{id}` endpoint will therefore result in a 404 error.
=> fix(core-database-postgres): add EQ operator to block height

docker/production/entrypoint.sh
Make symbolic link instead of exporting path to `ark`.
=> build(docker): create symbolic link for ark bin

packages/core-p2p/src/server/versions/1/handlers.ts
Only worked with old ids, so new nodes would always rollback to sha256 id milestone height - 1 since
the reported common block height is the last old id in the chain.
=> fix(core-p2p): common blocks with sha256 ids

__tests__/unit/core-database/repositories/transactions-business-repository.test.ts, packages/core-database/src/repositories/transactions-business-repository.ts
The `findById` method called by the `transactions/{id}` API endpoint does not map the block to the transaction.
[untested]
=> fix(core-database): map block to transaction in findById

packages/core-interfaces/src/core-p2p/monitor.ts, packages/core-p2p/src/monitor.ts, packages/core-p2p/src/server/plugins/accept-request.ts, packages/core-p2p/src/utils/index.ts, packages/core-p2p/src/utils/is-valid-peer.ts
A node would still accept blocks from a banned peer:
```
[INFO]: Received new block at height 7,816,623 with 0 transactions from 82.223.100.85
[2019-03-27 15:53:40][DEBUG]: Delegate calidelegate (037b4730e7c63252912825510423487e9ee507e1a5719dfeef52187d8ababe3048) allowed to forge block 7,816,623 👍
[2019-03-27 15:53:40][DEBUG]: event 'PROCESSFINISHED': "newBlock" -> "idle" -> actions: [checkLater, blockchainReady]
[2019-03-27 15:53:40][INFO]: Broadcasting block 7,816,623 to 0 peers
[2019-03-27 15:53:47][INFO]: Block 7,816,623 pinged blockchain 20 times
[2019-03-27 15:53:47][INFO]: Received new block at height 7,816,624 with 0 transactions from 82.223.100.85
[2019-03-27 15:53:47][DEBUG]: Delegate civseed (02b02cae6c53adcbbe2b88e3f21fff9e3ceb8c2f028fdfaecff9d393696eaa3d07) allowed to forge …
```
=> fix(core-p2p): two-way ban

packages/core-api/src/versions/2/transactions/schema.ts, packages/core-p2p/src/server/versions/1/schema.ts
Use the configuration value `maxTransactionsPerRequest` from the transaction pool to validate API requests, resolves the todo in the comment.
=> fix: use the maxTransactionsPerRequest configuration for API validation

__tests__/unit/core-event-emitter/emitter.test.ts, packages/core-event-emitter/package.json, packages/core-event-emitter/src/emitter.ts, packages/core-event-emitter/src/index.ts, packages/core-interfaces/package.json, packages/core-interfaces/src/core-event-emitter/index.ts, yarn.lock
Ensure that we tell node.js that we have a new listener by increasing the max listener count to avoid warnings.
**Also drops `eventemitter3` as there isn't that big of a difference between it and the node 11 emitter.**
=> fix(core-event-emitter): ensure the event listener won’t exceed the max listener count

.circleci/config.yml, __tests__/unit/core-p2p/monitor.test.ts, packages/core-p2p/src/monitor.ts
p2p getNetworkHeight() was sorting peer height with default array sort() method, but this method sorts using string representation, not actual numbers.
Which means that `[1, 30, 4, 21, 100000]` is sorted as `[1, 100000, 21, 30, 4]`.
Fixed by just sorting using custom method, comparing actual numbers.
=> fix(core-p2p): getNetworkHeight() was sorting incorrectly peer heights

__tests__/integration/core-api/v2/handlers/blocks.test.ts, packages/core-api/src/versions/2/blocks/methods.ts, packages/core-database/src/repositories/blocks-business-repository.ts, packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
Adds a new method to search blocks by id and height, currently only used in the API.
=> feat(core-database): add function to search a block by id or height

__tests__/unit/core-database/database-service.test.ts, packages/core-database-postgres/src/plugin.ts, packages/core-database-postgres/src/queries/blocks/find-by-height.sql, packages/core-database-postgres/src/queries/blocks/find-by-heights.sql, packages/core-database-postgres/src/queries/index.ts, packages/core-database-postgres/src/repositories/blocks.ts, packages/core-database-postgres/src/repositories/transactions.ts, packages/core-database/src/database-service.ts, packages/core-database/src/repositories/blocks-business-repository.ts, packages/core-database/src/repositories/transactions-business-repository.ts, packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
The `findByHeight` method in `core-database-postgres` at the moment has a very misleading name as the singular `height` in the same indicates that you will received a single block but it executes `manyOrNone` which means the result will be an array.
https://github.com/ArkEcosystem/core/blob/develop/packages/core-database-postgres/src/repositories/blocks.ts#L32
This PR provides a `findByHeight` and `findByHeights` method which return a single and multiple blocks. This will avoid confusion and unexpected behaviour like there currently is with the `findByHeight` method based on its name.
=> refactor(core-database-postgres): add findByHeight to avoid confusion with the misleading findByHeights

.circleci/config.yml, .circleci/configTemplate.json
Put `integration` into the name of the CircleCI jobs that run `integration` tests.
=> chore(ci): explicitly name integration test jobs

packages/core-database/src/repositories/blocks-business-repository.ts
The `try catch` only triggers when a legacy block ID (bigint) is passed as it exceeds the postgres int size but we also want to search by ID if the height was a valid int but didn't yield a result.
=> fix(core-database): search a block ID if there is no height match

.circleci/config.yml, .circleci/configTemplate.json
Remove all postgres steps from the unit test jobs as there is no need for pg, cuts off a bit of runtime.
=> chore(ci): remove the postgres setup from unit test jobs

packages/core-database-postgres/src/plugin.ts, packages/core-database/src/factory.ts, packages/core-database/src/manager.ts, packages/core-database/src/plugin.ts
Clearly separate the manager and factory behaviour in `core-database`.
=> refactor(core-database): clearly separate manager and factory behaviour

__tests__/integration/core-forger/client.test.ts, __tests__/unit/core-forger/manager.test.ts, packages/core-api/src/versions/1/delegates/controller.ts, packages/core-database-postgres/src/repositories/rounds.ts, packages/core-database/src/database-service.ts, packages/core-database/src/wallet-manager.ts, packages/core-forger/package.json, packages/core-forger/src/client.ts, packages/core-forger/src/errors.ts, packages/core-forger/src/index.ts, packages/core-forger/src/manager.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-interfaces/src/core-database/database-repository/rounds-repository.ts, packages/core-interfaces/src/core-database/database-service.ts, packages/core-interfaces/src/core-database/wallet-manager.ts, packages/core-p2p/src/index.ts, packages/core-p2p/src/server/types.ts, packages/core-p2p/src/server/versions/internal/handlers/utils.ts, packages/core-p2p/src/server/versions/internal/index.ts, packages/core-utils/src/httpie.ts, packages/core-utils/src/index.ts
Refactors the forger and addresses the following points:
- during startup, don't block when no host is responsive
- host selection now tries all configured hosts before throwing an error
- host selection no longer uses recursion
- no longer spams the log each possible event cycle when no host is available
- uses a timeout to schedule the next `__monitor()` call instead of promise recursion
- removes obsolete code
Resolves #2326 
The memory leak was caused by two things:
(https://github.com/nodejs/node/issues/6673)
1. promise recursion in `__monitor()`
2. promise recursion in `__chooseHost()`
The former is the lesser evil and only creeps up slowly over time, but once the forger relay becomes unresponsive the latter makes the memory leak really fast.
(It may be noted that the memory leak as …
=> refactor(core-forger): memory leak, log spam, cleanup

__tests__/unit/core-blockchain/blockchain.test.ts, __tests__/unit/core-database/database-service.test.ts, packages/core-blockchain/src/blockchain.ts, packages/core-database/package.json, packages/core-database/src/database-service.ts, packages/core-elasticsearch/package.json, packages/core-elasticsearch/src/indices/rounds.ts, packages/core-elasticsearch/src/indices/wallets.ts, packages/core-event-emitter/src/index.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-webhooks/package.json, packages/core-webhooks/src/manager.ts
Export the `ApplicationEvents` enum from `core-event-emitter` to keep all event names in a single place to make changes and access to the event list easier.
=> refactor(core-event-emitter): expose all application events through an enum

__tests__/unit/core-database/database-service.test.ts, __tests__/unit/core-database/wallet.test.ts, packages/core-database-postgres/src/integrity-verifier.ts, packages/core-database/src/database-service.ts, packages/core-database/src/wallet-manager.ts, packages/core-database/src/wallet.ts, packages/core-interfaces/src/core-database/database-service.ts, packages/core-interfaces/src/core-database/wallet-manager.ts, packages/core-p2p/src/peer-verifier.ts, packages/core-transactions/src/handlers/transaction.ts, packages/core-utils/src/round-calculator.ts
Removes some obsolete code, adds type hints and improves the round logic which now also handles the network start better. There will be more changes in an upcoming PR.
=> refactor(core-database): round logic

__tests__/unit/core-p2p/guard.test.ts, packages/core-p2p/src/guard.ts
Remove the height ban now that the verifier takes care of issues like that.
=> refactor(core-p2p): remove height difference ban

packages/core-container/src/config/loaders/file-loader.ts, packages/core-p2p/src/monitor.ts, packages/core-p2p/src/server/plugins/accept-request.ts
Each request goes through the `accept-request` handler which waits for `acceptNewPeer` to complete before returning a response. If `peer A` makes a request to `peer B` and `peer B` does not know `peer A`, it will try to ping `peer A` in `acceptNewPeer`. Now depending on different factors `peer A` might not respond so the ping runs into a timeout. When this happens the request of `peer A` runs into a timeout as well, since `peer B` did not respond fast enough, because `peer A` didn't reply to the ping. Afterwards `peer B` will suspend `peer A` since `acceptNewPeer` failed. The next time `peer A` makes a request `peer B` will not try to ping it again, thus the request completes without running into a timeout.
This can be easily observed when running a relay behind a firewall.
For example: …
=> fix(core-p2p): frequent peer timeout errors

__tests__/unit/core-p2p/court/guard.test.ts, __tests__/unit/core-p2p/peer.test.ts, packages/core-interfaces/src/core-p2p/monitor.ts, packages/core-p2p/src/court/offences.ts, packages/core-p2p/src/errors.ts, packages/core-p2p/src/monitor.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/server/plugins/accept-request.ts
Nodes behind a firewall do not respond to pings and are getting banned for not replying. This prevents nodes that are talking in one direction only from making POST requests. A ban only happens for timeouts when requesting `/peer/status`. This PR removes the ban for a timeout, which aligns the behavior with the requests to other endpoints. `acceptNewPeer` no longer bans peers for the wrong reason.
=> fix(core-p2p): remove ping timeout ban

CHANGELOG.md
Preliminary changelog for the `2.3.0` release.
=> docs: 2.3.0 changelog

__tests__/unit/core-blockchain/state-machine.test.ts, packages/core-api/src/services/transformer.ts, packages/core-blockchain/src/state-machine.ts, packages/core-database/src/database-service.ts, packages/core-interfaces/src/core-database/database-service.ts
When a node starts with a fresh database it won't have a genesis block until `core-blockchain` is mounted and the state machine entered the `init` state which will insert it.
This logic is flawed and causes issues with the peer verifier. The first problem is that during the start of a node https://github.com/ArkEcosystem/core/blob/2.4/packages/core-p2p/src/peer-verifier.ts#L122 will always be false as `core-p2p` is mounted before `core-blockchain` so it only becomes true once `core-blockchain` has created that registration in the container. As this will always be false we switch to hitting the database in https://github.com/ArkEcosystem/core/blob/2.4/packages/core-p2p/src/peer-verifier.ts#L125 which will also fail for the same reason as the first condition.
The result of that is that if …
=> fix: insert the genesis block as soon as the database is ready

__tests__/integration/core-p2p/network-monitor.test.ts, packages/core-api/src/versions/1/peers/transformer.ts, packages/core-api/src/versions/2/peers/transformer.ts, packages/core-interfaces/src/core-p2p/peer-connector.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-connector.ts, packages/core-p2p/src/peer-processors.ts, packages/core-p2p/src/utils/socket.ts
When accepting new peer, connect to peer before pinging.
Before we were doing :
- ping (without connecting before) : peer connection is made "on-the-fly" (ensureConnection method)
- connect to peer : creates a new connection to same peer resulting in socket error as there is already the connection from ping
Also some minor refactor on peer api (removing obsolete status), and giving more time to wait for peer socket to be open.
=> fix(core-p2p): avoid duplicate connections with the same peer

packages/core-p2p/src/peer-communicator.ts
Replace incorrectly used `this` by correct parameter `peer`.
=> fix(core-p2p): set headers on peer instance

__tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts, __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts, __tests__/integration/core-tester-cli/commands/send/transfer.test.ts, __tests__/integration/core-tester-cli/commands/send/vote.test.ts, packages/core-tester-cli/src/commands/command.ts
Configuration manager of `crypto` package is initialized from `devnet` preset by default (source [#1](https://github.com/ArkEcosystem/core/blob/accc4ff45c0431ffdec6f24397095c2d90ccf93d/packages/crypto/src/managers/config.ts#L28) 
[#2](https://github.com/ArkEcosystem/core/blob/accc4ff45c0431ffdec6f24397095c2d90ccf93d/packages/crypto/src/managers/config.ts#L185)).
When starting a new chain (for example `testnet`) with an updated config (for example `network.epoch`), `tester-cli` broadcasted transactions are not forged (and it fails silently which could be another issue).
The main reason is that `tester-cli` load local config  from node api ([source](https://github.com/ArkEcosystem/core/blob/accc4ff45c0431ffdec6f24397095c2d90ccf93d/packages/core-tester-cli/src/commands/command.ts#L75-L87)), …
=> fix(core-tester-cli): init config manager from network preset

__tests__/integration/core-api/v2/handlers/node.test.ts, __tests__/unit/core-container/__stubs__/config/network.json, packages/core-api/src/versions/2/node/controller.ts, packages/core-container/src/config/schema.ts, packages/crypto/src/networks/devnet/network.json, packages/crypto/src/networks/mainnet/network.json, packages/crypto/src/networks/testnet/network.json, packages/crypto/src/networks/unitnet/network.json
=> feat(core-api): return slip44 and wif via node/configuration

packages/crypto/src/networks/mainnet/milestones.json
Due to 2.3 release re-schedule:
Height 8128000 at Thu Apr 25 12:05:22 UTC 2019 (assuming no block misses)
Height 8128000 at Thu Apr 25 12:37:13 UTC 2019 (assuming block misses as in the last 30000 blocks)
Height 8204000 at Thu May  2 12:58:42 UTC 2019 (assuming no block misses)
Height 8204000 at Thu May  2 13:45:25 UTC 2019 (assuming block misses as in the last 30000 blocks)
=> chore(crypto): bump vendorFieldLength and blockid activation heights

packages/core-event-emitter/src/emitter.ts
Resolves https://github.com/ArkEcosystem/core/issues/2392
=> feat(core-event-emitter): add off method

__tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/utils/config/testnet/plugins.js, __tests__/utils/config/unitnet/plugins.js, packages/core-p2p/src/defaults.ts, packages/core-p2p/src/socket-server/index.ts, packages/core/bin/config/devnet/plugins.js, packages/core/bin/config/mainnet/plugins.js, packages/core/bin/config/testnet/plugins.js
Allow passing in SC specific configuration and specifically log `fail` events as errors.
=> refactor(core-p2p): make SocketCluster configurable

__tests__/integration/core-forger/client.test.ts, __tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/unit/core-p2p/mocks/scworker.ts, __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts, __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts, __tests__/unit/core-p2p/socket-server/worker.test.ts, packages/core-forger/src/client.ts, packages/core-p2p/src/defaults.ts, packages/core-p2p/src/socket-server/index.ts, packages/core-p2p/src/socket-server/versions/internal.ts, packages/core-p2p/src/socket-server/versions/utils.ts, packages/core-p2p/src/socket-server/worker.ts
Instead of keeping a separate banning list we suspend peers with `tooManyRequests`.
=> refactor(core-p2p): suspend peers if they exceed the rate limit

__tests__/unit/core-p2p/peer-guard.test.ts, packages/core-interfaces/src/core-p2p/peer-connector.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-connector.ts, packages/core-p2p/src/peer-guard.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/socket-server/versions/peer.ts
Resolves `@TODO: store errors in the PeerConnector`.
=> refactor(core-p2p): store connection errors in connector

__tests__/unit/core-p2p/peer-guard.test.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-guard.ts, packages/core-p2p/src/peer.ts
Removes the `peer.commonBlocks` property which was only used to suspend a peer and instead directly emits a suspension with the `noCommonBlocks` punishment.
=> refactor(core-p2p): suspend a peer directly with the noCommonBlocks punishment

packages/core-api/src/versions/1/peers/controller.ts, packages/core-api/src/versions/2/peers/controller.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer.ts
Removes the unused `peer.status` property.
=> refactor(p2p): remove the status property from peers

packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/socket-server/versions/peer.ts
Add an interface for the `peer.state` property.
=> refactor(core-p2p): add peer state interface

__tests__/integration/core-blockchain/blockchain.test.ts, __tests__/integration/core-forger/client.test.ts, __tests__/unit/core-database/database-service.test.ts, __tests__/unit/core-forger/manager.test.ts, packages/core-blockchain/src/state-machine.ts, packages/core-forger/src/client.ts, packages/core-forger/src/delegate.ts, packages/core-forger/src/interfaces.ts, packages/core-forger/src/manager.ts, packages/core-forger/src/plugin.ts, packages/core-p2p/src/socket-server/versions/internal.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-p2p/src/utils/socket.ts, packages/crypto/src/blocks/block.ts, packages/crypto/src/interfaces/block.ts
Adds missing interfaces, type hints and renames some methods to remove the need for comments.
=> refactor(core-forger): add interfaces, type hints and remove comments

__tests__/unit/core-utils/is-blocked-chained.test.ts, packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/processor/block-processor.ts, packages/core-blockchain/src/state-machine.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-utils/src/is-block-chained.ts
Removes the need for hacks like casting with `as IBlockData` or using `@ts-ignore` as the function only works with `IBlockData` and never used any instance props or functions of `IBlock`.
=> refactor: pass IBlockData instead of IBlock to isBlockChained

__tests__/integration/core-json-rpc/transactions.test.ts, packages/core-json-rpc/src/server/modules.ts
Allow setting a vendor field for transactions created via the RPC and respond with an error if the transaction doesn't verify.
=> feat(core-json-rpc): allow setting a vendor field for transactions

packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/state-storage.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-interfaces/src/core-blockchain/state-storage.ts, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/socket-server/versions/peer.ts
When block is received from forger, always broadcast to all peers.
Also refactored the block broadcast general logic, to use "peer quotas" based on block pings, instead of using randomization to select peers to broadcast to.
=> refactor: block broadcast when block comes from forger

__tests__/unit/core-database/__fixtures__/database-connection-stub.ts, packages/core-database-postgres/src/integrity-verifier.ts, packages/core-database-postgres/src/postgres-connection.ts, packages/core-database/src/database-service.ts, packages/core-interfaces/src/core-database/database-connection.ts
Errors in `buildWallets` were swallowed which meant the state machine would never be able to catch any issues with it.
=> fix(core-database): don't swallow errors in buildWallets

__tests__/integration/core-p2p/peer-communicator.test.ts, __tests__/unit/core-database/database-service.test.ts, __tests__/unit/core-database/wallet-manager.test.ts, __tests__/unit/core-forger/manager.test.ts, __tests__/unit/core-p2p/network-monitor.test.ts, __tests__/unit/core-transaction-pool/connection.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, __tests__/unit/core-transactions/handler.test.ts, __tests__/unit/crypto/transactions/deserializer.test.ts, __tests__/unit/crypto/transactions/transaction.test.ts, benchmark/transaction/create/0.js, packages/core-api/src/versions/1/transactions/transformer.ts, packages/core-api/src/versions/2/transactions/transformer.ts, packages/core-database-postgres/src/postgres-connection.ts, packages/core-database/src/database-service.ts, packages/core-elasticsearch/src/indices/transactions.ts, packages/core-forger/src/manager.ts, packages/core-snapshots/src/transport/codec.ts, packages/core-snapshots/src/transport/verification.ts, packages/core-tester-cli/src/commands/debug/deserialize.ts, packages/core-tester-cli/src/commands/debug/serialize.ts, packages/core-tester-cli/src/commands/debug/verify-second-signature.ts, packages/core-tester-cli/src/commands/debug/verify.ts, packages/core-transaction-pool/src/guard.ts, packages/core-transaction-pool/src/storage.ts, packages/crypto/src/blocks/deserializer.ts, packages/crypto/src/transactions/builders/transactions/transaction.ts, packages/crypto/src/transactions/factory.ts, packages/crypto/src/transactions/index.ts, packages/crypto/src/transactions/types/transaction.ts
Same as #2429 but for transactions.
=> feat(crypto): implement TransactionFactory

__tests__/unit/core-event-emitter/emitter.test.ts, packages/core-event-emitter/src/emitter.ts
Extend the node.js event emitter and overwrite certain methods to set the listener count.
=> refactor(core-event-emitter): extend the node.js event emitter

__tests__/integration/core-p2p/mocks/core-container.ts, __tests__/integration/core-p2p/mocks/p2p-options.ts, __tests__/integration/core-p2p/socket-server/peer.test.ts, packages/core-p2p/src/socket-server/worker.ts
Fixed rate limit which was incorrectly applied to forger. (authorized with remoteAccess config parameter)
=> fix(core-p2p): disable rate limit for forger

__tests__/unit/core-p2p/network-monitor.test.ts, packages/core-p2p/src/network-monitor.ts
In block download logic, networkHeight is what we believe network height is, so even if we have a value for it less than or equal to our height, we should still download blocks.
(we might not have up-to-date peers heights)
=> fix(core-p2p): still download blocks when network height <= our height

.snyk, packages/core-container/package.json, yarn.lock
Remove the no-longer used `jest-mock-process` dependency.
=> chore(deps): remove extraneous jest-mock-process dependency

CHANGELOG.md, packages/crypto/src/transactions/deserializers/transaction.ts
There's one tx on mainnet which fails to deserialize otherwise.
=> fix(crypto): deserialize type > 0 with vendor field instead of skipping it

packages/core-snapshots/src/transport/verification.ts
=> fix(core-snapshots): use correct genesis block instead of hardcoding devnet

packages/core/src/commands/config/forger/index.ts
`ark config:forger` works again.
=> fix(core): dont pass suffix flag to bip38 and bip39 command

.circleci/config.yml, __tests__/integration/core-blockchain/blockchain.test.ts, __tests__/integration/core-transaction-pool/processor.test.ts, __tests__/unit/core-blockchain/blockchain.test.ts, __tests__/unit/core-blockchain/state-machine.test.ts, __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts, __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts, __tests__/unit/core-transaction-pool/connection.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, __tests__/unit/core-utils/is-blocked-chained.test.ts, __tests__/unit/crypto/blocks/block.test.ts, __tests__/unit/crypto/crypto/slots.test.ts, __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts, packages/core-api/src/versions/1/delegates/controller.ts, packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/utils/validate-generator.ts, packages/core-database-postgres/src/repositories/transactions.ts, packages/core-forger/src/manager.ts, packages/core-p2p/src/network-state.ts, packages/core-p2p/src/socket-server/versions/internal.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-tester-cli/src/commands/make/block.ts, packages/core-transaction-pool/src/memory.ts, packages/core-transaction-pool/src/processor.ts, packages/core-utils/src/is-block-chained.ts, packages/crypto/src/blocks/block.ts, packages/crypto/src/crypto/index.ts, packages/crypto/src/crypto/slots.ts, packages/crypto/src/transactions/builders/transactions/transaction.ts, yarn.lock
Make all methods of `Crypto.Slots` static as there was no access to instance properties or methods other then `getMilestone` which doesn't need to be a method. Also removed some methods that were not used throughout the packages or tests.
=> refactor(crypto): make all Slots.* methods static

.circleci/config.yml, packages/core-database/src/database-service.ts
Otherwise milestones from height 1 are used when loading blocks for current round during startup.
=> fix(core-database): initialize height on startup

packages/core-forger/src/manager.ts
We need to ensure the configManager is always on the same height as the block that is about to be forged. Otherwise the forger can run into trouble when milestones alter the transaction validation. Currently this is only guaranteed when forger and relay run in the same process.
=> fix(core-forger): update configManager height

packages/core-snapshots/src/manager.ts, packages/crypto/src/transactions/serializers/block.ts
When the snapshot manager finishes an import it is supposed to reset an unfinished round by default, but because we passed the wrong parameter it stopped working.
=> fix(core-snapshots): reset unfinished round after import

packages/core/src/process-manager.ts
Fixes instances of `Error: The "XXX" process has entered an unknown state. (undefined)`
This is because sometimes the in-memory pm2 gets out of date (e.g. if multiple pm2 instances are installed on the system). When this happens, an error is printed to stdout prior to the JSON from `pm2 jlist` being dumped. This prevents `JSON.parse` from parsing the response properly. By only processing the last line of the output from `pm2 jlist`, we exclude the error text, so `JSON.parse` succeeds.
(The JSON output from `pm2 jlist` never contains newlines or carriage returns.)
=> fix(core): parse only the last line of pm2 stdout

packages/core-transaction-pool/src/memory.ts
The expiration field is part of the transaction signature, so we should
not modify it.
=> fix(core-transaction-pool): don't modify transaction's expiration

packages/core-json-rpc/src/index.ts, packages/core-json-rpc/src/server/methods/blocks/info.ts, packages/core-json-rpc/src/server/methods/blocks/latest.ts, packages/core-json-rpc/src/server/methods/blocks/transactions.ts, packages/core-json-rpc/src/server/methods/transactions/broadcast.ts, packages/core-json-rpc/src/server/methods/transactions/info.ts, packages/core-json-rpc/src/server/methods/wallets/info.ts, packages/core-json-rpc/src/server/methods/wallets/transactions.ts, packages/core-json-rpc/src/server/services/network.ts, packages/core-json-rpc/src/server/services/processor.ts
Select a random peer every time we send a request and try to do so up to 3 times before giving up.
=> fix(core-json-rpc): avoid getting stuck on a unresponsive peer by picking a random one each time

.circleci/config.yml, packages/core-snapshots/src/db/index.ts, packages/core-snapshots/src/db/queries/index.ts, packages/core-snapshots/src/db/queries/rounds/round-range.sql, packages/core-snapshots/src/manager.ts, packages/core-snapshots/src/transport/codec.ts, packages/core-snapshots/src/transport/verification.ts, packages/core-snapshots/src/utils.ts
Fixes assets that were incorrectly imported, because of `decamelizeKeys`. This PR also changes the `SnapshotManager` to include the rounds table when taking a snapshot since the `PeerVerifier` does not work properly without it. Theoretically we could regenerate the rounds table from the blocks and transactions table alone, but it takes approx. 1 hours for mainnet so this is not an option.
**This PR invalidates all existing snapshots.**
=> fix(core-snapshots): asset import, include rounds table

packages/core-p2p/src/server/plugins/accept-request.ts
This is giving relays with closed p2p ports a hard time broadcasting transactions. Therefore it's best to accept incoming `/transactions` POST  requests.
=> fix(core-p2p): accept requests to /transactions regardless of suspension

__tests__/unit/core-p2p/peer-processor.test.ts, packages/core-interfaces/src/core-p2p/peer-storage.ts, packages/core-p2p/src/defaults.ts, packages/core-p2p/src/peer-processors.ts, packages/core-p2p/src/peer-storage.ts
Resolves #2089.
This is a simple solution to #2089 but it might be enough, please review / comment if you feel something could be improved.
=> feat(core-p2p): filter peers that are on the same IP subnet

__tests__/e2e/lib/config/docker/docker-init.sh
Fixes a `sed` error which prevented the configuration to be generated on macOS.
=> test(e2e): specify sed extension to support macOS

__tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts, __tests__/integration/core-tester-cli/commands/send/multi-signature-registration.test.ts, __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts, __tests__/integration/core-tester-cli/commands/send/transfer.test.ts, __tests__/integration/core-tester-cli/commands/send/vote.test.ts, packages/core-api/src/versions/2/node/controller.ts, packages/core-api/src/versions/2/node/routes.ts, packages/core-tester-cli/src/commands/command.ts, packages/core-tester-cli/src/commands/send/delegate-registration.ts, packages/core-tester-cli/src/commands/send/multi-signature-registration.ts, packages/core-tester-cli/src/commands/send/second-signature-registration.ts, packages/core-tester-cli/src/commands/send/vote.ts, packages/core-tester-cli/src/signer.ts, packages/crypto/src/networks/unitnet/milestones.json
`core-tester-cli` previously was using the P2P API for auto-configuration of the crypto package but the endpoint it was using is gone with the migration to WebSockets.
This PR introduces a new endpoint at `:4003/api/v2/node/configuration/crypto` which returns the full crypto configuration for the network the node is running on which we then use to configure the CLI.
=> fix(core-tester-cli): use public API for auto-configuration

benchmark/crypto/hash-algorithms.js, benchmark/index.js
Fix the benchmark imports for hash algos so we get results again.
=> chore(benchmark): fix imports for hash algos

packages/core-snapshots/src/transport/codec.ts, packages/core/src/helpers/snapshot.ts
Make sure the numerical values of blocks are instances of `Utils.BigNumber` before serializing them.
=> fix(core-snapshots): transform numerical values to BigNumber before serializing

packages/core/src/commands/snapshot/verify.ts
Mark the `--blocks` flag as required for the `ark snapshot:verify` command to avoid errors if it is missing.
=> fix(core): mark the blocks flag as required for snapshot:verify

packages/core/src/commands/snapshot/restore.ts, packages/core/src/commands/snapshot/verify.ts, packages/core/src/helpers/snapshot.ts
Make the `--blocks` optional to make @adrian69 life easier with snapshots :trollface:
1. If `--blocks` is available it will use that value
2. If the `--blocks` flag is missing and only 1 snapshot exists it will use that for restore and verify
3. If the `--blocks` flag is missing and multiple snapshots exist it will prompt the user to select one
=> feat(core): require the user to choose a snapshot if the blocks flag is missing

.circleci/config.yml, packages/core-wallet-api/.gitattributes, packages/core-wallet-api/README.md, packages/core-wallet-api/package.json, packages/core-wallet-api/src/index.ts, packages/core-wallet-api/src/plugin.ts, packages/core-wallet-api/src/server/handlers.ts, packages/core-wallet-api/src/server/index.ts, packages/core-wallet-api/src/server/transformers.ts, packages/core-wallet-api/tsconfig.json, packages/core/bin/config/devnet/plugins.js, packages/core/bin/config/mainnet/plugins.js, packages/core/bin/config/testnet/plugins.js
Initial implementation of the planned Wallet API due to the fact that the wallet relied on a P2P Endpoint which no longer exists in `2.4.0`.
=> feat(core-wallet-api): initial implementation

__tests__/integration/core-api/v1/handlers/peers.test.ts, __tests__/unit/core-p2p/peer.test.ts, packages/core-api/src/versions/1/peers/controller.ts, packages/core-api/src/versions/1/peers/schema.ts, packages/core-api/src/versions/1/peers/transformer.ts, packages/core-api/src/versions/2/peers/controller.ts, packages/core-api/src/versions/2/peers/schema.ts, packages/core-api/src/versions/2/peers/transformer.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/socket-server/utils/get-headers.ts, packages/core-p2p/src/socket-server/utils/validate-headers.ts, packages/core-p2p/src/socket-server/versions/peer.ts
Remove the `os` property from a peer as it isn't used for anything, was a leftover from `ark-node`.
=> refactor(core-p2p): remove peer.os property

__tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts, __tests__/integration/core-p2p/__support__/utils.ts, __tests__/integration/core-p2p/peer-communicator.test.ts, __tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/unit/core-p2p/peer-guard.test.ts, __tests__/unit/core-p2p/peer.test.ts, packages/core-forger/src/client.ts, packages/core-interfaces/src/core-p2p/peer-guard.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-guard.ts, packages/core-p2p/src/peer-processors.ts, packages/core-p2p/src/peer.ts, packages/core-p2p/src/socket-server/utils/get-headers.ts, packages/core-p2p/src/socket-server/utils/validate-headers.ts, packages/core-p2p/src/socket-server/versions/peer.ts
Remove the `peer.nethash` property and instead let the peer verifier decide if a peer is on the same network as we are.
=> refactor(core-p2p): remove peer.nethash property

__tests__/unit/core-blockchain/mocks/transactionPool.ts, __tests__/unit/core-transaction-pool/__stubs__/connection.ts, packages/core-blockchain/src/processor/block-processor.ts, packages/core-interfaces/src/core-transaction-pool/connection.ts, packages/core-transaction-pool/src/connection.ts
When a block is discarded, because it contains already forged transactions make sure the transactions are also removed from the pool (if any).
=> fix(core-blockchain): remove forged transactions from pool before discarding block

packages/core-wallet-api/package.json, packages/core-wallet-api/src/plugin.ts, packages/core-wallet-api/src/server/index.ts
Proxy all calls to `4040` to `4003` locally until the Wallet API is fully developed.
=> feat(core-wallets-api): proxy API calls to core-api until fully developed

__tests__/helpers/transaction-factory.ts, __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts, packages/core-tester-cli/package.json, packages/core-tester-cli/src/commands/send/delegate-registration.ts, yarn.lock
Tests that rely on multiple delegate registrations will randomly fail because there is a high probability of the same value ending up in the list of names.
```
FAIL  __tests__/integration/core-transaction-pool/processor.test.ts (19.668s)
● Transaction Guard › validate › Sign a transaction then change some fields shouldn't pass validation › should not validate when changing fields after signing - delegate registration
expect(received).toEqual(expected) // deep equality
- Expected
+ Received
@@ -1,10 +1,10 @@
Array [
Array [
"b0ef0260e5011b8d451fb57a1c495febadfa8b6412146733de4359d4acaaa658",
-     "ERR_BAD_DATA",
-     "Transaction didn't pass the verification process.",
+     "ERR_CONFLICT",
+     "Multiple delegate registrations for \"ferroseed\" in transaction payload",
],
Array [ …
```
=> refactor: replace pokemon.random with Math.random to avoid value collision

packages/core/src/commands/config/database.ts, packages/core/src/commands/env/set.ts, packages/core/src/types.ts, packages/core/src/utils.ts, yarn.lock
Cleans up https://github.com/ArkEcosystem/core/pull/2557 and adds an interactive mode.
=> feat(core): interactive database configuration

__tests__/integration/core-p2p/network-monitor.test.ts, __tests__/unit/core-p2p/network-monitor.test.ts, packages/core-container/src/container.ts, packages/core-forger/src/client.ts, packages/core-forger/src/manager.ts, packages/core-interfaces/src/core-p2p/network-monitor.ts, packages/core-p2p/src/event-listener.ts, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-connector.ts, packages/core-p2p/src/peer-guard.ts, packages/core-p2p/src/peer-processors.ts, packages/core-p2p/src/plugin.ts
Removes a bunch of redundant logging and error stacks due to an unclean shutdown of the socketcluster.
=> refactor(core-p2p): socketcluster shutdown and logging

__tests__/unit/crypto/blocks/block.test.ts, packages/core-container/src/config/index.ts, packages/crypto/src/blocks/block.ts, packages/crypto/src/networks/devnet/milestones.json, packages/crypto/src/networks/mainnet/exceptions.json
Add new milestone to devnet to deal with expired transactions and fix the id order of two mainnet exceptions.
=> fix: sync issues with devnet and mainnet

__tests__/integration/core-api/v2/handlers/blocks.test.ts, packages/core-api/src/versions/2/blocks/methods.ts
Reading [doc](https://docs.ark.io/api/public/v2/blocks.html#list-all-transactions-in-a-block) we can get all transactions of block at specific height. 
That feature was not implemented.
=> feat(core-api): accept block height to list block transactions

__tests__/integration/core-transaction-pool/processor.test.ts, __tests__/unit/core-transaction-pool/__stubs__/connection.ts, __tests__/unit/core-transaction-pool/connection.test.ts, packages/core-interfaces/src/core-transaction-pool/connection.ts, packages/core-transaction-pool/src/connection.ts, packages/core-transaction-pool/src/processor.ts
refactor: change hasExceededMaxTransactions()'s argument type
hasExceededMaxTransactions() was taking an argument of type
Interfaces.ITransactionData and was just using its .senderPublicKey
member. Change it to take "senderPublicKey: string".
This makes it easier to use hasExceededMaxTransactions() from unit tests
with bogus senderPublicKey because no dummy transaction object is
necessary.
=> refactor: change hasExceededMaxTransactions()'s argument type

__tests__/unit/core-blockchain/mocks/container.ts, __tests__/unit/core-blockchain/state-machine.test.ts, packages/core-blockchain/src/state-machine.ts
Use `resolveOptions("blockchain")` to get _databaseRollback_ options. (instead of `resolveOptions("p2p")` which was not getting anything)
=> fix(blockchain): use resolveOptions("blockchain") to get databaseRollback options

__tests__/unit/core-transaction-pool/connection.test.ts
* Properly use TransactionFactory to generate transactions with
different ids instead of manually overriding the "id" member. Add a
generateTestTransactions() method, used in all 3 stress tests.
* The overall timing of "✓ multiple additions and retrievals (884ms)" is
now not sufficient to assess the speed of the add+retrieve of the pool
because it includes generating the test transactions with
TransactionFactory which is about 11 times slower than the actual
add+retrieve that is done by the test. Thus clock only the relevant
snippet of the code with console.time().
=> test(core-transaction-pool): polish stress test and don't clock the TransactionFactory

packages/core-api/src/defaults.ts, packages/core-api/src/handlers/index.ts, packages/core-api/src/server.ts
Support `/api` and `/api/v2` as some people use the URL paths even though the docs advise against it.
**This will be removed with the release of 3.0 later this year and only `/api` will be supported.**
=> refactor(core-api): register /api/v2 as a transition period fallback

__tests__/integration/core-webhooks/server.test.ts, __tests__/unit/core-database/database-service.test.ts, __tests__/unit/core-forger/manager.test.ts, packages/core-blockchain/package.json, packages/core-blockchain/src/blockchain.ts, packages/core-database/src/database-service.ts, packages/core-forger/package.json, packages/core-forger/src/manager.ts, packages/core-p2p/package.json, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/peer-processors.ts, packages/core-transaction-pool/package.json, packages/core-transaction-pool/src/connection.ts, packages/core-transactions/package.json, packages/core-transactions/src/handlers/delegate-registration.ts, packages/core-transactions/src/handlers/delegate-resignation.ts
Use ApplicationEvents enum instead of strings.
=> refactor: use ApplicationEvents enum instead of string

packages/core-p2p/src/peer-communicator.ts
Don't throw an error and cause a suspension if a plugin is unresponsive.
=> fix(core-p2p): don't cause suspensions for unresponsive plugins

__tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts, __tests__/unit/core-blockchain/state-machine.test.ts, packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/processor/handlers/unchained-handler.ts, packages/core-blockchain/src/state-machine.ts
Divide blocks into smaller chunks (based on number of transactions and number of blocks) before batch processing them.
This will avoid blocking the whole application while processing the blocks.
=> fix: divide blocks into smaller chunks for batch processing

__tests__/unit/core-p2p/peer-guard.test.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-guard.ts, packages/core-p2p/src/peer-processors.ts, packages/core-p2p/src/peer.ts
Remove the timeout ban as it can cause issues when the network is in bad shape.
=> refactor(core-p2p): remove timeout banning

.circleci/config.yml, packages/core-explorer/.gitattributes, packages/core-explorer/README.md, packages/core-explorer/package.json, packages/core-explorer/src/defaults.ts, packages/core-explorer/src/index.ts, packages/core-explorer/tsconfig.json, yarn.lock
Starts Explorer together with Core as requested by @alexbarnsley.
=> feat(core-explorer): initial implementation

packages/core-forger/src/client.ts, packages/core-forger/src/manager.ts, packages/core-p2p/src/peer-processors.ts
By default the timeout between reconnects increases with each attempt up to a maximum of 60 seconds. Now the forger tries to reconnect every second.
=> fix(core-forger): use a static reconnect timeout

__tests__/unit/core-utils/transform-plugins.test.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-utils/src/transform-plugins.ts, packages/core-wallet-api/src/server/handlers.ts
Return packages with name and port instead of using some trimmed down alias.
=> fix(core-wallet-api): return plugins with package names

__tests__/integration/core-api/handlers/blocks.test.ts, __tests__/integration/core-api/handlers/transactions.test.ts, packages/core-api/src/handlers/blocks/methods.ts, packages/core-api/src/handlers/blocks/schema.ts, packages/core-api/src/handlers/blocks/transformer.ts, packages/core-api/src/handlers/delegates/methods.ts, packages/core-api/src/handlers/delegates/schema.ts, packages/core-api/src/handlers/peers/schema.ts, packages/core-api/src/handlers/rounds/schema.ts, packages/core-api/src/handlers/shared/controller.ts, packages/core-api/src/handlers/shared/schemas/block-id.ts, packages/core-api/src/handlers/shared/schemas/pagination.ts, packages/core-api/src/handlers/transactions/controller.ts, packages/core-api/src/handlers/transactions/methods.ts, packages/core-api/src/handlers/transactions/schema.ts, packages/core-api/src/handlers/transactions/transformer.ts, packages/core-api/src/handlers/utils.ts, packages/core-api/src/handlers/votes/methods.ts, packages/core-api/src/handlers/votes/schema.ts, packages/core-api/src/handlers/wallets/methods.ts, packages/core-api/src/handlers/wallets/schema.ts, packages/core-api/src/services/transformer.ts
Allow retrieval of blocks and transactions in the same format as `@arkecosystem/crypto` uses them via `?transform=false`.
This is enabled on all endpoints that serve blocks or transactions.
=> feat(core-api): allow retrieval of raw blocks and transactions

__tests__/integration/core-api/handlers/transactions.test.ts, packages/core-api/src/handlers/transactions/schema.ts, packages/core-database-postgres/src/models/transaction.ts, packages/core-database/src/repositories/utils/search-parameter-converter.ts, packages/core-interfaces/src/core-database/search/search-parameters.ts
The `/transactions/search` endpoint now accepts an `asset` object.
Internally it uses the `@>` (contains) operator for comparing the payload against the `jsonb` column.
For example this payload:
```
{"asset": {} }
```
returns all transactions with an asset.
Whereas this one:
```
{"asset": {"delegate": {} } }
```
only returns type 2 transactions. 
And lastly this
```
{"asset": {"delegate": { "username": "boldninja" } } }
```
returns one matching transaction.
Note: Due to how `@>` works it is not possible to e.g. search for all assets with a username starting with "b" or with a number greater or equal something. Another limiting factor is our used sql query builder which makes it difficult to impossible to express more sophisticated statements.
=> feat(core-api): search transactions by asset

__tests__/integration/core-blockchain/blockchain.test.ts, __tests__/unit/core-p2p/mocks/blockchain.ts, __tests__/unit/core-p2p/mocks/core-container.ts, __tests__/unit/core-p2p/mocks/transaction-pool.ts, __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts, __tests__/unit/core-transaction-pool/__stubs__/connection.ts, __tests__/unit/core-transaction-pool/connection.test.ts, __tests__/utils/config/testnet/plugins.js, __tests__/utils/config/unitnet/plugins.js, packages/core-api/src/versions/2/node/controller.ts, packages/core-blockchain/src/blockchain.ts, packages/core-forger/src/manager.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-interfaces/src/core-transaction-pool/connection.ts, packages/core-p2p/src/socket-server/versions/internal.ts, packages/core-transaction-pool/src/connection.ts, packages/core-transaction-pool/src/defaults.ts, packages/core-transaction-pool/src/memory.ts, packages/core-transaction-pool/src/storage.ts, packages/crypto/src/blocks/deserializer.ts, packages/crypto/src/transactions/deserializer.ts, packages/crypto/src/transactions/factory.ts, yarn.lock
Currently the assumption is that all data that is in the transaction pool is valid as it otherwise could not enter, which is obviously not true. In order to resolve that issue a few things have been changed.
- When the node loads all transactions from the the pool on boot every transaction that fails to deserialised or results in an unexpected id gets removed.
- Deserialise transactions before they leave the pool and apply the same rules as during boot
- The forger now calls `fromBytesUnsafe` instead of `fromBytes` because the relay will ensure that all data it sends out is valid
=> refactor(core-transaction-pool): deserialize transactions before they leave the pool

packages/core-blockchain/src/replay/replay-blockchain.ts
Fixes `TypeError: Cannot assign to read only property 'drain' of object '#<Object>'` which is apparently readonly in [async 3.0](https://github.com/caolan/async/releases/tag/v3.0.0) which got released a few days ago.
=> fix(core-blockchain): chain replay stopped working after dependency update

packages/core-container/src/config/index.ts
This allows for those using the ARK Deployer to use pubKeyHash 0.
=> refactor(core-container): require a minimum of 0 as pubKeyHash

packages/core-p2p/src/network-monitor.ts
Under certain circumstances `curr` can be undefined which then results in `TypeError: curr is not iterable`.
=> fix(core-p2p): handle undefined `curr` during block download

CHANGELOG.md
Add the latest changes to the unreleased changelog of 2.4.0.
=> chore(changelog): add latest changes for 2.4.0

__tests__/integration/core-api/handlers/blocks.test.ts, packages/core-api/src/handlers/blocks/controller.ts, packages/core-api/src/handlers/blocks/routes.ts, packages/core-api/src/handlers/blocks/schema.ts, packages/core-api/src/handlers/blocks/transformer.ts
Often times you just want the last forged block or the genesis block to check something. This adds 2 endpoints to the block resource that retrieves those from in-memory instead of hitting the database.
=> feat(core-api): allow easy retrieval of first and last block

packages/core-api/src/versions/2/transactions/transformer.ts
It is my understanding that forged transactions must have a positive confirmation count. If that is indeed the case, there is an off-by-one error in the transaction count. This manifests itself by looking at transactions forged in the most recent block, which will show zero confirmations.
=> fix(core-api): off by one error in transaction confirmations

__tests__/helpers/peers.ts, __tests__/integration/core-api/v1/handlers/peers.test.ts, __tests__/integration/core-api/v2/handlers/peers.test.ts, __tests__/integration/core-p2p/network-monitor.test.ts, packages/core-api/src/versions/1/peers/transformer.ts, packages/core-api/src/versions/2/peers/transformer.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/peer.ts
Removes the redundant `p2p` entry from `ports`:
=> refactor(core-p2p): remove redundant p2p port from broadcast

packages/core-forger/src/manager.ts, packages/core-p2p/src/socket-server/index.ts
This PR removes misleading output like this:
```
7|ark-relay  | [2019-06-03 23:50:17.705] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.712] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.730] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.737] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.740] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.767] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.771] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 23:50:17.803] WARN : The payload contains invalid transaction.
7|ark-relay  | [2019-06-03 …
```
=> refactor(core-p2p): improve logging

packages/core/src/commands/config/cli.ts, packages/core/src/helpers/config.ts, packages/core/src/hooks/init/config.ts
If the `next` release is installed via `yarn global add @arkecosystem/core@next` instead of using the `ark config:cli --channel=next` flag the `channel` will default to `latest`.
This PR adds a check on start to switch the channel in the configuration so that `ark update` can be used.
=> fix(core): set the correct channel if core was directly installed with @next

packages/core-api/src/repositories/transactions.ts
=> fix(core-api): invalid orderBy causes internal server error

deprecated/core-json-rpc/src/server/index.ts, packages/core-api/src/server.ts, packages/core-http-utils/src/plugins/whitelist.ts, packages/core-p2p/src/utils/is-whitelisted.ts, packages/core-webhooks/src/server/index.ts
With the addition of pinging peers to see which plugins are available on which port the log only causes noise.
=> refactor(core-http-utils): remove whitelist access log

packages/core-p2p/src/socket-server/worker.ts
We already fixed this with 2.3, but it somehow regressed with the switch to websockets. Blocking on `acceptNewPeer` causes issues for nodes running behind a firewall, since they don't respond to pings and therefore trigger a timeout.
=> fix(core-p2p): perform `acceptNewPeer` non-blocking

packages/core-snapshots/src/db/index.ts, packages/core-snapshots/src/db/queries/index.ts, packages/core-snapshots/src/db/queries/rounds/latest.sql, packages/core-snapshots/src/manager.ts, packages/core-snapshots/src/transport/index.ts, packages/core-snapshots/src/transport/verification.ts
Follow the logic of INSERTing into blocks and transactions also for
rounds: only INSERT a row during snapshot restore if its identifier
is higher than the highest in the database (ie a sloppy check whether
a row is in the database).
=> fix(core-snapshots): avoid trying to INSERT duplicates in rounds

packages/core-blockchain/src/plugin.ts, packages/core-container/src/registrars/plugin.ts, packages/core-database-postgres/src/plugin.ts, packages/core-event-emitter/src/index.ts, packages/core-interfaces/src/core-container/container.ts, packages/core-logger-pino/src/plugin.ts, packages/core-p2p/src/plugin.ts, packages/core-state/src/plugin.ts, packages/core-transaction-pool/src/plugin.ts
Introduces the concept of `required` and `optional` plugins. When a required plugin throws an error during boot, Core will shutdown like before. But if an optional plugin cannot be loaded it will no longer shutdown and print a nice warning with the error instead.
Unless explicitely marked required, all plugins are considered optional.
The required plugins are:
```
@arkecosystem/core-event-emitter
@arkecosystem/core-logger-pino
@arkecosystem/core-state
@arkecosystem/core-database-postgres
@arkecosystem/core-transaction-pool
@arkecosystem/core-p2p
@arkecosystem/core-blockchain
```
=> fix(core-container): handle failing optional plugins gracefully

packages/core-transaction-pool/src/connection.ts
Transactions have to be known to the pool, before they can be purged from the storage. Therefore we have to first `remember` the transactions from disk and then filter them.
=> fix(core-transaction-pool): correctly purge invalid transactions from disk on start

packages/core-snapshots/src/db/index.ts, packages/core-snapshots/src/db/queries/rounds/round-range.sql, packages/core-snapshots/src/manager.ts, packages/core-snapshots/src/utils.ts
When appending to an existent snapshot, only append rows with higher id
than already in the (old) snapshot. Otherwise the snapshot would contain
rows with duplciate rounds.id values and would not be importable.
This patch assumes no gaps in rounds.id and monotonically increasing
rounds.id when new rounds are being added.
=> fix(core-snapshots): don't append duplicate rounds rows to a snapshot

__tests__/unit/core-transaction-pool/connection.forging.test.ts, __tests__/unit/core-transaction-pool/connection.test.ts, packages/core-transaction-pool/package.json, packages/core-transaction-pool/src/connection.ts
Calling only `canBeApplied` is not sufficient when transactions affect the sender/recipient of a following transaction. It is necessary keep track of the state changes by creating temporary wallets.
See also added tests.
=> fix(core-transaction-pool): use temporary wallets for transaction validation

__tests__/unit/core-transaction-pool/connection.forging.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, __tests__/unit/crypto/crypto/bip38.test.ts, packages/core-api/package.json, packages/core-api/src/formats.ts, packages/core-transaction-pool/package.json, packages/core-transactions/package.json, packages/core-transactions/src/utils.ts, packages/crypto/package.json, packages/crypto/src/crypto/bip38.ts, packages/crypto/src/identities/address.ts, packages/crypto/src/transactions/serializer.ts, packages/crypto/src/transactions/types/ipfs.ts, packages/crypto/src/transactions/types/multi-payment.ts, packages/crypto/src/transactions/types/timelock-transfer.ts, packages/crypto/src/transactions/types/transfer.ts, yarn.lock
Replaces `bs58check` which is a pure JS implementation with `bstring` which ships a native `base58` implemenation.
It is about twice as fast:
```
✓  bstring.base58.decode x 439,740 ops/sec ±1.76% (83 runs sampled)
✓  bs58check.decode x 223,122 ops/sec ±1.42% (82 runs sampled)
✓  bstring.base58.encode x 315,189 ops/sec ±1.10% (88 runs sampled)
✓  bs58check.encode x 162,822 ops/sec ±1.63% (92 runs sampled)
```
=> perf(crypto): replace bs58check with bstring

packages/core-api/src/versions/2/blocks/transformer.ts
Only the v1 endpoint displayed them.
=> fix(core-api): missing block confirmations on v2 endpoint

__tests__/unit/core-transaction-pool/connection.forging.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, __tests__/unit/crypto/crypto/bip38.test.ts, __tests__/unit/crypto/utils/base58.test.ts, packages/core-api/src/formats.ts, packages/core-transactions/src/utils.ts, packages/crypto/src/crypto/bip38.ts, packages/crypto/src/identities/address.ts, packages/crypto/src/transactions/serializer.ts, packages/crypto/src/transactions/types/multi-payment.ts, packages/crypto/src/transactions/types/timelock-transfer.ts, packages/crypto/src/transactions/types/transfer.ts, packages/crypto/src/utils/base58.ts, packages/crypto/src/utils/index.ts
Move the `base58` specific code out of the address identity because identities shouldn't expose anything besides methods to generate/validate the type of identity it is.
=> refactor(crypto): move base58 functions to utils

__tests__/unit/core-forger/delegate.test.ts, __tests__/unit/core-transaction-pool/connection.test.ts, packages/core-forger/src/delegate.ts, packages/core-transaction-pool/src/connection.ts
A few fixes related to nonces :
- (core-forger) do not sort transactions when forging (we already get sorted transactions from relay)
- (core-transaction-pool) update purgeByBlock to manage reverting transactions with higher nonces
=> fix: do not sort transactions in forger / update purgeByBlock logic for handling nonces

docker/production/mainnet/mainnet.env
=> chore(docker): add CORE_LOG_LEVEL for mainnet

__tests__/unit/core-forger/manager.test.ts, packages/core-forger/src/manager.ts
Keep forging even if overheight block is detected.
=> fix(core-forger): ignore overheight block

CHANGELOG.md
=> docs: 2.4.0 changelog

packages/core/src/shared/start.ts
Set `NODE_ENV` to `production` as many npm packages determine the current environment and optimize their code for production.
=> refactor(core): start process in production env

__tests__/unit/core-blockchain/blockchain.test.ts, __tests__/unit/core-blockchain/state-machine.test.ts, __tests__/unit/core-blockchain/stubs/state-storage.ts, __tests__/unit/core-database/__fixtures__/state-storage-stub.ts, __tests__/unit/core-state/__fixtures__/state-storage-stub.ts, packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/processor/handlers/accept-block-handler.ts, packages/core-blockchain/src/state-machine.ts, packages/core-interfaces/src/core-blockchain/blockchain.ts, packages/core-interfaces/src/core-state/state-store.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-state/src/stores/state.ts, packages/crypto/src/blocks/block.ts, packages/crypto/src/errors.ts
It's necessary to chunk the blocks around milestones so the queued blocks do not erroneously fail validation.
Without this the mainnet sync gets stuck at height `8128038` - which is the first block containing a vendor field longer than 64 bytes.
=> fix(core-blockchain): take milestones into account when downloading blocks in parallel

packages/core-p2p/src/defaults.ts
Forgot to add the 2.5 version constraints to the p2p config.
=> fix(core-p2p): add 2.5 to minimum versions

__tests__/unit/core-p2p/utils/is-valid-version.test.ts, packages/core-p2p/src/defaults.ts
For a smooth 2.5 migration the 2.4 nodes need to allow 2.5 nodes.
=> chore(core-p2p): allow 2.4 and 2.5 nodes

packages/core-p2p/src/event-listener.ts, packages/core-p2p/src/peer-communicator.ts
Do not disconnect from a peer for plain errors. Also forget a peer if we disconnect from it.
=> fix(core-p2p): forget peer when socket is disconnected

__tests__/integration/core-p2p/mocks/core-container.ts, packages/core-p2p/src/peer-verifier.ts
Since #2686 the claimed peer block header is checked, but it is really expensive:
```
265   16.3%    v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*)
170   64.2%      LazyCompile: ~verify /home/supaiku/git/ark-core/node_modules/bcrypto/lib/native/secp256k1.js:540:35
170  100.0%        LazyCompile: ~verifyECDSA /home/supaiku/git/ark-core/packages/crypto/dist/crypto/hash.js:8:23
161   94.7%          LazyCompile: ~verifyHash /home/supaiku/git/ark-core/packages/crypto/dist/transactions/verifier.js:32:22
161  100.0%            LazyCompile: ~verify /home/supaiku/git/ark-core/packages/crypto/dist/transactions/verifier.js:10:18
9    5.3%          LazyCompile: ~verifySignature /home/supaiku/git/ark-core/packages/crypto/dist/blocks/block.js:79:20
6   66.7% …
```
=> perf(core-p2p): improve peer block header check

__tests__/unit/core-blockchain/stubs/state-storage.ts, __tests__/unit/core-database/__fixtures__/state-storage-stub.ts, __tests__/unit/core-p2p/network-monitor.test.ts, __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts, __tests__/unit/core-state/__fixtures__/state-storage-stub.ts, __tests__/unit/core-state/stores/state.test.ts, packages/core-database/src/database-service.ts, packages/core-interfaces/src/core-database/database-service.ts, packages/core-interfaces/src/core-p2p/peer-communicator.ts, packages/core-interfaces/src/core-state/state-store.ts, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer-verifier.ts, packages/core-p2p/src/schemas.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-state/src/stores/state.ts
The peer verifier only needs block headers.
=> refactor(core-p2p): only fetch block headers when verifying peers

__tests__/helpers/peers.ts, __tests__/unit/core-blockchain/mocks/p2p/network-monitor.ts, __tests__/unit/core-p2p/network-monitor.test.ts, packages/core-blockchain/src/state-machine.ts, packages/core-interfaces/src/core-p2p/network-monitor.ts, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/plugin.ts, packages/core-p2p/src/schemas.ts
This PR delays the peer discovery until after the state initialization is done to solve several issues where a relay could end up without peers.
=> refactor(core-p2p): delay peer discovery until after state initialization is done

docker/production/devnet/devnet.env, docker/production/devnet/docker-compose-build.yml, docker/production/devnet/docker-compose.yml, docker/production/mainnet/docker-compose-build.yml, docker/production/mainnet/docker-compose.yml
Add Wallets API, remove PostgreSQL container port default mapping to localhost to avoid potential conflicts if the port is already occupied. Containers internal communication remains intact. User just losses the ability to access the database from the host.
-
[x] No
=> chore(docker): Add Wallets API, remove PostgreSQL container port default mapping to localhost

packages/core-database-postgres/src/postgres-connection.ts
Core doesn't really recover on it's own when the database throws an error (i.e. try a db restart while Core is running). It pretty much rekts Core. While it would be nice to handle it more gracefully, this PR enables Core to at least to recover from it by exiting the process so pm2 can restart it.
=> refactor(core-database-postgres): exit on unexpected error

__tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts, packages/core-p2p/src/enums.ts, packages/core-p2p/src/socket-server/rate-limiter.ts, packages/core-p2p/src/socket-server/versions/internal.ts, packages/core-p2p/src/socket-server/versions/peer.ts, packages/core-p2p/src/socket-server/worker.ts, packages/crypto/package.json
When a node exceeds the global rate limit it is now blocked for 60 seconds and the connection is closed.
=> refactor(core-p2p): block when rate limit exceeded

packages/core-blockchain/src/blockchain.ts, packages/core-blockchain/src/state-machine.ts
When a node is restarted and the last block is less than `blockTime * 3` old it thinks it is already synced and thus won't download new blocks and often miss the "train". It will take at least a minute until the wake up happens to sync and catch up to height to start receiving blocks.
=> fix(core-blockchain): always attempt to download blocks after start

__tests__/unit/core-database/database-service.test.ts, __tests__/unit/core-state/wallets/temp-wallet-manager.test.ts, packages/core-blockchain/src/state-machine.ts, packages/core-database/src/database-service.ts, packages/core-interfaces/src/core-state/wallets.ts, packages/core-state/src/wallets/index.ts, packages/core-state/src/wallets/temp-wallet-manager.ts, packages/core-state/src/wallets/wallet-manager.ts
The function `calcPreviousActiveDelegates` that is called on node start and after a rollback is using a
temporary wallet manager to restore the vote balances from the beginning of the current round. Then based on these numbers the active delegate order is derived.
Now, there is one problem that manifests when the blocks that are reverted affect the vote balances in a way that the ranking changes and it is not caused by a delegate but a voter other than a delegate. In other words the temporary wallet manager only knows about the delegate wallets and thus can't revert the vote balances accurately when other non-delegate wallets are in play as their actual balances are unknown.
This PR fixes this by giving the temporary wallet manager access to all wallets.
If yes, please describe the impact …
=> fix: previous round order calculation

__tests__/integration/core-database-postgres/connection.test.ts, __tests__/unit/core-blockchain/blockchain.test.ts, __tests__/unit/core-blockchain/mocks/database.ts, packages/core-blockchain/src/blockchain.ts, packages/core-database-postgres/src/postgres-connection.ts
When `saveBlocks` fails, we have to revert the accepted blocks. It would also pretty much loop indefinitely and keep trying to process the same blocks over and over again. Instead of removing the top blocks, now all accepted blocks are reverted, all queued blocks dropped and the state machine gets to decide when to process blocks again.
=> fix(core-blockchain): revert accepted blocks when saveBlocks fails

packages/core-snapshots/src/transport/index.ts, packages/core-snapshots/src/transport/verification.ts
For some reason the hardcoded id of the genesis block in
packages/crypto/src/networks/*/genesisBlock.json is different than the
one that would be calculated by the crypto package (block
serialize/deserialize).
Because the id as in genesisBlock.json is already in previous_block of
the subsequent block (at height 2), we must use the hardcoded id instead
of the one derived by the crypto package.
=> fix(core-snapshots): do not restore genesis block with wrong id

packages/core-p2p/src/peer-communicator.ts
If peerBlocks is falsy, then "for (const block of peerBlocks) {"
would throw an exception that peerBlocks is not iterable.
=> fix(core-p2p): avoid iterating on non-iterable peerBlocks

packages/core-database-postgres/src/repositories/repository.ts
For example, if the request is contains offset=100, limit=10 and we
get 3 rows from the database, then we know that the total rows matching
the query are 103: 100 (skipped due to offset) + 3 (returned rows).
=> fix(core-database-postgres): correct estimate if less than limit rows

__tests__/unit/core-transaction-pool/connection.forging.test.ts, packages/core-transaction-pool/src/connection.ts
Before this patch we would take the top "size" transactions, filter away
some of them and return the result, possibly returning less than the
requested "size" even if there could be legit transactions in the pool
that could be returned, up to "size".
Change the code to keep iterating until we have collected "size" valid
transactions, or the end of the pool is reached.
=> fix: try harder to return the requested number of transactions

__tests__/integration/core-p2p/network-monitor.test.ts, __tests__/unit/core-p2p/network-monitor.test.ts, packages/core-interfaces/src/core-p2p/network-monitor.ts, packages/core-p2p/src/network-monitor.ts
At the moment we only discover new peers when `hasMinimumPeers()` returns false. This is generally too low. This PR changes `discoverPeers` to also look for new peers when the own peer count is significantly lower than the peer count of other peers.
=> refactor(core-p2p): discover new peers sooner

packages/core-database-postgres/src/migrations/20190626000000-enforce-chained-blocks.sql
@adrian69 was experiencing some issues with PG9.5 that didn't occur on PG10.5 so changed the drop command to also take the function specific arguments into account.
=> fix(core-database-postgres): drop check_previous_block with arguments

__tests__/unit/core-utils/is-whitelisted.test.ts, packages/core-api/src/defaults.ts, packages/core-container/src/registrars/plugin.ts, packages/core-database-postgres/src/repositories/transactions.ts, packages/core-http-utils/src/plugins/whitelist.ts, packages/core-interfaces/src/core-container/container.ts, packages/core-utils/package.json, packages/core-utils/src/index.ts, packages/core-utils/src/is-whitelisted.ts, packages/core-wallet-api/package.json, packages/core-wallet-api/src/plugin.ts, packages/core-wallet-api/src/server/index.ts, packages/core/bin/config/devnet/plugins.js, packages/core/bin/config/mainnet/plugins.js, packages/core/bin/config/testnet/plugins.js, yarn.lock
Backports a fix for `core-wallet-api` which behaved incorrectly when loaded before `core-api` and a crash in the `/node/fees` endpoint when there are no transactions. 
=> backport: some fixes for the deployer

packages/core/package.json, packages/core/src/shared/start.ts
Potatos (<=2GB RAM) tend to run OOM during sync from 0 because Node.js tries to use up to 1.5GB before the GC kicks in by default.
By lowering the `max_old_space_size` to `500` on nodes with little RAM they actually manage to sync without running OOM. 
=> refactor(core): run GC earlier on potatos

packages/core-http-utils/src/plugins/content-type.ts
=> refactor(core-http-utils): always enforce `application/json` as content-type

__tests__/unit/core-forger/manager.test.ts, packages/core-forger/src/client.ts, packages/core-forger/src/manager.ts
Increase request timeout and prevent blocks from getting forged when the current slot has less than 2 seconds left.
=> refactor(core-forger): increase timeout, check time left in slot

__tests__/integration/core-p2p/peer-communicator.test.ts, packages/core-api/src/server.ts, packages/core-database-postgres/src/state-builder.ts, packages/core-interfaces/src/core-p2p/peer-communicator.ts, packages/core-interfaces/src/core-p2p/peer.ts, packages/core-p2p/src/network-monitor.ts, packages/core-p2p/src/peer-communicator.ts, packages/core-p2p/src/peer.ts, yarn.lock
We used to do it only once and cache the result for the entire lifetime of a peer.
=> refactor(core-p2p): refresh peer ports

install.sh, scripts/publish/alpha.sh, scripts/publish/beta.sh, scripts/publish/latest.sh, scripts/publish/next.sh, scripts/publish/rc.sh
=> feat(install): let the user choose if they want to use @next release

__tests__/unit/core-forger/manager.test.ts, packages/core-forger/src/manager.ts
=> fix(core-forger): also check if still in same slot

packages/core-api/src/handlers/peers/controller.ts, packages/core-api/src/handlers/peers/schema.ts
The peer api currently returns the total count of all peers, instead of the count of the filtered peers, thus messing with the pagination.
It's worth noting that the schema for index currently accepts `ip`, `status`, and `port` as query params, yet filtering based on those values is not implemented.
=> fix(core-api): return count of filtered peers

packages/core-database-postgres/src/migrations/20190718000000-check_previous_block-add-schema.sql, packages/core-database-postgres/src/migrations/index.ts
Without "public." prefix, accessing the table just by name - "blocks"
causes pg_dump dumps to fail during load with:
pg_restore: [archiver (db)] COPY failed for table "blocks": ERROR:  relation "blocks" does not exist
=> fix(core-database-postgres): prefix table names with schema

packages/core-api/src/handlers/utils.ts
If the cache is disabled the `respondWithCache` will run into issues because it assumes the data it received is a cache object that was created by hapi. Return early if the cache is disabled to avoid this behaviour.
```
Debug: internal, implementation, error
TypeError: Cannot read property 'isBoom' of undefined
at Object.exports.respondWithCache (/Users/dev/Code/core/packages/core-api/dist/handlers/utils.js:35:15)
at WalletsController.respondWithCache (/Users/dev/Code/core/packages/core-api/dist/handlers/shared/controller.js:18:24)
at WalletsController.transactions (/Users/dev/Code/core/packages/core-api/dist/handlers/wallets/controller.js:23:22)
```
If adding a **new …
=> fix(core-api): return data directly if cache is disabled

packages/core-p2p/package.json, packages/core-p2p/src/socket-server/payload-processor.ts
=> fix(core-p2p): ensure payload database exists

__tests__/unit/core-state/wallets/wallet-manager.test.ts, packages/core-interfaces/src/core-state/wallets.ts, packages/core-state/src/wallets/wallet-manager.ts
=> refactor(core-state): expose current block for transaction handlers

__tests__/unit/core-transaction-pool/connection.forging.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, packages/core-database-postgres/src/state-builder.ts, packages/core-transactions/src/errors.ts, packages/core-transactions/src/handlers/delegate-registration.ts, packages/core-transactions/src/handlers/delegate-resignation.ts, packages/core-transactions/src/handlers/handler-registry.ts, packages/core-transactions/src/handlers/htlc-claim.ts, packages/core-transactions/src/handlers/htlc-lock.ts, packages/core-transactions/src/handlers/htlc-refund.ts, packages/core-transactions/src/handlers/ipfs.ts, packages/core-transactions/src/handlers/multi-payment.ts, packages/core-transactions/src/handlers/multi-signature.ts, packages/core-transactions/src/handlers/second-signature.ts, packages/core-transactions/src/handlers/transaction.ts, packages/core-transactions/src/handlers/transfer.ts, packages/core-transactions/src/handlers/vote.ts, packages/core-transactions/src/interfaces.ts, packages/crypto/src/transactions/registry.ts, packages/crypto/src/transactions/types/factory.ts
Allows transaction types to depend on other transaction types which are automatically resolved by the transaction registry. This is especially useful for plugins since they no longer need to worry that their transaction types are registered in the correct order as long as the dependencies are correct.
Also cleans everything a bit up and adds more test coverage needed for an upcoming PR.
=> refactor: transaction registry

__tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts, __tests__/unit/core-state/wallets/wallet-manager.test.ts, __tests__/unit/core-transactions/handler-registry.test.ts, packages/core-state/src/wallets/wallet.ts, packages/core-transactions/src/handlers/delegate-registration.ts, packages/core-transactions/src/handlers/delegate-resignation.ts, packages/core-transactions/src/handlers/handler-registry.ts, packages/core-transactions/src/handlers/htlc-claim.ts, packages/core-transactions/src/handlers/htlc-lock.ts, packages/core-transactions/src/handlers/htlc-refund.ts, packages/core-transactions/src/handlers/ipfs.ts, packages/core-transactions/src/handlers/multi-payment.ts, packages/core-transactions/src/handlers/multi-signature.ts, packages/core-transactions/src/handlers/second-signature.ts, packages/core-transactions/src/handlers/transaction.ts, packages/core-transactions/src/handlers/transfer.ts, packages/core-transactions/src/handlers/vote.ts, packages/core-transactions/src/interfaces.ts
Transaction types now have to register attributes before they can access them. Trying to read/write an unknown attribute at runtime will cause an error now.
=> feat(core-transactions): register wallet attributes before accessing them

__tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts, __tests__/integration/core-p2p/mocks/core-container.ts, __tests__/integration/core-p2p/peer-processor.test.ts, __tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/unit/core-p2p/mocks/event-emitter.ts, packages/core-p2p/src/peer-processor.ts, packages/core-p2p/src/utils/is-valid-version.ts
Allows changing the accepted minimum versions via milestone.
For example this would cause all peers below `3.0` to be dropped once reaching the milestone:
```
{
"height": 10000000,
"p2p": {
"minimumVersions": ["^3.0"]
}
}
```
=> feat(core-p2p): change minimum version via milestone

__tests__/integration/core-p2p/peer-communicator.test.ts, __tests__/integration/core-p2p/socket-server/peer.test.ts, __tests__/unit/core-p2p/mocks/core-container.ts, __tests__/unit/core-p2p/socket-server/utils/validate.test.ts, packages/core-p2p/src/schemas.ts, packages/core-p2p/src/socket-server/worker.ts
Make the peer reply schemas more strict and disconnect on invalid request instead of returning an error.
=> fix(core-p2p): stricter schema on peer replies, disconnect on invalid requests

__tests__/unit/crypto/transactions/deserializer.test.ts, packages/crypto/src/transactions/deserializer.ts, packages/crypto/src/transactions/signer.ts, packages/crypto/src/transactions/types/delegate-resignation.ts, packages/crypto/src/transactions/types/htlc-claim.ts, packages/crypto/src/transactions/types/htlc-lock.ts, packages/crypto/src/transactions/types/htlc-refund.ts, packages/crypto/src/transactions/types/ipfs.ts, packages/crypto/src/transactions/types/multi-payment.ts, packages/crypto/src/transactions/types/multi-signature.ts, packages/crypto/src/transactions/verifier.ts
Ensures that a V2 transaction that uses ECDSA can still be properly deserialized.
=> refactor(crypto): signature deserialization
